### ISSUE TITLE
PaddleOCR onnx runtime 部署出错

### ISSUE THREAD

**Issue by 203chenjing** [PaddlePaddle/Paddle2ONNX#1005]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
部署Paddle OCR 报参数错误

**报错截图**
![image](https://user-images.githubusercontent.com/101111227/210594855-9c2c29ee-3975-4879-8fa7-6b39cb6ea234.png)

**其他信息**

**Comment by jiangjiajun** [comment]
原因在于模型要求的维度，与你输入的实际数据维度不符。

**Comment by 203chenjing** [comment]
> 原因在于模型要求的维度，与你输入的实际数据维度不符。
    @jiangjiajun 想问这个问题要怎么解决呀?是要修改下输入图片shape，让它跟训练模型时输入的shape一样吗？ 谢谢！

**Comment by jiangjiajun** [comment]
参考这个工具 https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle
