### ISSUE TITLE
关于paddle2onnx转换报错的求助

### ISSUE THREAD

**Issue by LimBoom** [PaddlePaddle/Paddle2ONNX#1006]
**问题描述**
于win10使用paddle2onnx1.0.5尝试将PaddleOCR文本方向分类模型ch_ppocr_mobile_slim_v2.0_cls的部署模型向量化时出现报错:

[Paddle2ONNX] Oops, there are some operators not supported yet, including 
fake_channel_wise_quantize_dequantize_abs_max,
fake_quantize_dequantize_moving_average_abs_max,
[ERROR] Due to the unsupported operators, the conversion is aborted.

查询Issues发现该报错于20221130已有反馈 (https://github.com/PaddlePaddle/Paddle2ONNX/issues/975#issue-1469413313) 但未寻得解决方法，想请教下转onnx的方法

**具体信息如下**
paddle2onnx  --model_dir E:\paddleModel\cls_model\ch_ppocr_mobile_v2.0_cls_slim_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --opset_version 11 --save_file E:\paddleModel\cls_model\ch_ppocr_mobile_v2.0_cls_slim_infer\inference.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: E:\paddleModel\cls_model\ch_ppocr_mobile_v2.0_cls_slim_infer\inference.pdmodel
[Paddle2ONNX] Paramters file path: E:\paddleModel\cls_model\ch_ppocr_mobile_v2.0_cls_slim_infer\inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model.
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by yeliang2258** [comment]
导出的模型是一个量化模型，请参考这个文档：https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/quantize.md
