### ISSUE TITLE
"ernie-1.0" requires paddle dependency running with paddle2onnx converted ONNX model

### ISSUE THREAD

**Issue by neso613** [PaddlePaddle/Paddle2ONNX#1007]
嘿

我有一个标点符号模型并使用 paddle2onnx 转换为 ONNX，但它的预处理步骤有这个 'ernie-1.0' dependecny。
这需要安装桨叶，这在树莓派上是不可能的。
为此需要帮助。

**Comment by jiangjiajun** [comment]
安装paddle2onnx不依赖paddle， 在树莓派上转换Paddle到ONNX模型也无需依赖Paddle，直接编译安装即可。

- 由于Paddle2ONNX没有发布树莓派linux aarch64上的pypi包，注意需自行参考这个文档编译安装 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md
