### ISSUE TITLE
Cannot export deeplabv3p_xception65_humanseg to ONNX: Cannot found attribute padding_algorithm in op: conv2d

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/Paddle2ONNX#1008]
System
=====´
Windows 10
Python 3.10.4
paddle2onnx        1.0.5
paddlefsl          1.1.0
paddlehub          2.3.1
paddlenlp          2.4.9
paddlepaddle       2.4.1
paddleseg          2.7.0     d:\local\devel\python\paddleseg_2.7.0

Prepare
=====
```
hub install deeplabv3p_xception65_
humanseg
Download https://bj.bcebos.com/paddlehub/paddlehub_dev/deeplabv3p_xception65_hum
anseg_1_2_0.zip
[##################################################] 100.00%
Decompress C:\Users\ukoehler\.paddlehub\tmp\tmptznv48kc\deeplabv3p_xception65_hu
manseg_1_2_0.zip
[##################################################] 100.00%
[2023-01-10 12:09:39,796] [    INFO] - Successfully installed deeplabv3p_xceptio
n65_humanseg-1.2.0
```

Export
====
```
(.venv) D:\Local\devel\Python\PaddleSeg_2.7.0>paddle2onnx --model_dir C:\Users\u
koehler\.paddlehub\modules\deeplabv3p_xception65_humanseg\deeplabv3p_xception65_
humanseg_model  --model_filename model.pdmodel --params_filename model.pdiparams
 --save_file deeplabv3p_xception65_humanseg\deeplabv3p_xception65_humanseg.onnx
--opset_version 11 --enable_onnx_checker True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: C:\Users\ukoehler\.paddlehub\modules\deeplabv3p_x
ception65_humanseg\deeplabv3p_xception65_humanseg_model\model.pdmodel
[Paddle2ONNX] Paramters file path: C:\Users\ukoehler\.paddlehub\modules\deeplabv
3p_xception65_humanseg\deeplabv3p_xception65_humanseg_model\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute padding_algorithm in op: conv2d
```

Files
===
https://drive.google.com/file/d/1NKmH2MDedriomeKgEIHEvQBCEh72xiez/view?usp=sharing
https://drive.google.com/file/d/1KyaAXdfo-d0mM7-nik95e99Y9-RAutDK/view?usp=sharing

**Comment by yeliang2258** [comment]
您好，目前Paddle2ONNX支持Paddle2.0之后的模型导出为ONNX

**Comment by ukoehler** [comment]
Sorry, I do not speak Chinese. Do you mean that the model is not in Paddle 2 format? According to the documentation, a combination of model/parameter file is supported. How can I convert to Paddle 2.0 format?

**Comment by yeliang2258** [comment]
Hello, currently Paddle2ONNX supports the export of Paddle models after Paddle 2.0 to ONNX. You can ask paddlehub to provide a Paddle model exported from Paddle2.0, and then convert it to ONNX
