### ISSUE TITLE
How to export the op not supported to onnx when I transfrom paddle model to onnx?

### ISSUE THREAD

**Issue by liuxubit** [PaddlePaddle/Paddle2ONNX#1009]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：to onnx to trt
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone): liuxubit@163.com

Hello,
How to export the op not supported to onnx when I transfrom paddle model to onnx?
for example，I have a model with msda。The onnx doesn't has the op。 When I use torch, the op can be taken place by a fake op like this:
![image](https://user-images.githubusercontent.com/39891612/211707244-39450ea3-cbe9-4475-82a2-14ec8f11cd1f.png)
Then，I can export it to onnx like this:
![image](https://user-images.githubusercontent.com/39891612/211707306-f37b1933-7342-45c5-8173-a83044e85dbf.png)
And it can be used to generate a trt engine。
So if I use paddle model like rtformer，how can I reproduce the process like what I did in torch? Do you have the same function?

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/1058

**Comment by yeliang2258** [comment]
Hi, this PR is available for testing and conversion
