### ISSUE TITLE
模型转换时缺少中间节点的shape信息

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle2ONNX#1011]
## 设备信息

System: Linux x86
Paddle2ONNX Version: 1.0.5

## bash

```bash
# Down
wget https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar
tar -xvf ch_PP-OCRv3_det_infer.tar

## export to onnx
paddle2onnx --model_dir ch_PP-OCRv3_det_infer \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.onnx \
            --enable_dev_version True
```

## error node
node name: p2o.Add.84
node picture:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/58363586/212242840-4ca9231c-2c49-41f9-ba29-30635ed65fa5.png">

**Comment by jiangjiajun** [comment]
通过此方式处理模型后，可以得到各个节点的Shape信息

python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"

**Comment by Zheng-Bicheng** [comment]
## 使用ONNX 模型优化工具推理中间shape
使用`Paddle2ONNX/tree/develop/tools/onnx/onnx_infer_shape.py`推理中间shape
将上述导出的onnx模型拷贝至Paddle2ONNX/tree/develop/tools/onnx目录并执行以下代码:
```bash
python onnx_infer_shape.py --input ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.onnx --output ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.onnx 
```

报错
```
Traceback (most recent call last):
  File "onnx_infer_shape.py", line 2435, in <module>
    args.guess_output_rank, args.verbose)
  File "onnx_infer_shape.py", line 2393, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "onnx_infer_shape.py", line 2189, in _infer_impl
    out_rank = len(get_shape_from_type_proto(vi.type))
  File "onnx_infer_shape.py", line 37, in get_shape_from_type_proto
    assert not is_sequence(type_proto)
  File "onnx_infer_shape.py", line 32, in is_sequence
    assert cls_type in ['tensor_type', 'sequence_type']
```

**Comment by Zheng-Bicheng** [comment]
> 通过此方式处理模型后，可以得到各个节点的Shape信息
> 
> python -m paddle2onnx.optimize --input_model model.onnx --output_model new_model.onnx --input_shape_dict "{'x':[1,3,224,224]}"

图中的模型已经固定了shape，可以看到下图圈出来的两个节点是有shape信息的
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/58363586/212243370-12196e52-f0aa-4f73-8a27-d2860a1df75d.png">

**Comment by jiangjiajun** [comment]
这个模型已经执行过上面的命令了吗
python -m paddle2onnx.optimize --input_model model.onnx --output_model new_model.onnx --input_shape_dict "{'x':[1,3,224,224]}"

**Comment by Zheng-Bicheng** [comment]
> 这个模型已经执行过上面的命令了吗
> python -m paddle2onnx.optimize --input_model model.onnx --output_model new_model.onnx --input_shape_dict "{'x':[1,3,224,224]}"

执行过了
