### ISSUE TITLE
paddleocr_kie_ser模型转onnx报错

### ISSUE THREAD

**Issue by LJY6356** [PaddlePaddle/Paddle2ONNX#1013]
kie_algorithm=LayoutXLM
paddle2onnx==0.9.1

转onnx命令行：
paddle2onnx --model_dir ./inference/ser_vi_layoutxlm_bank --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/ser_onnx/model.onnx --opset_version 11  --enable_onnx_checker True

报错
 

脚本/ppstructure/kiepredict_kie_token_ser.py  是否支持onnx推理

**Comment by yeliang2258** [comment]
请问一下，报错信息是？

**Comment by LJY6356** [comment]
> 请问一下，报错信息是？

![1](https://user-images.githubusercontent.com/67177370/212835883-efcc22fb-9623-4beb-993c-1f2a5b674cf0.jpg)
追问：ser模型onnx推理  脚本/ppstructure/kiepredict_kie_token_ser.py 是否支持onnx推理

**Comment by yeliang2258** [comment]
麻烦升级一下最新的Paddle2ONNX再转换试试。
如果是PaddleOCR的部署咨询问题，可以直接去PaddleOCR的Repo下提issue咨询哦
