### ISSUE TITLE
solov2导出模型转换为onnx出现不支持的算子

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle2ONNX#1016]
您好，我使用paddle2onnx工具转换PaddleDetection算法中的Solov2导出模型出现了不支持的算子。
paddle2onnx版本：1.0.5    paddle2paddle版本：2.3.0 
导出指令：
paddle2onnx --model_dir tube/ --model_filename model.pdmodel --params_filename model.pdiparams --save_file tube/test_tube.onnx --enable_onnx_checker True --enable_dev_version False --opset_version 16
下边是报错信息：
NotImplementedError:
There's 3 ops are not supported yet
=========== select_input ===========
=========== conditional_block ===========
=========== tril_triu ===========

Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: tube/model.pdmodel
[Paddle2ONNX] Paramters file path: tube/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,tril_triu,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by yeliang2258** [comment]
你好，目前还不支持将带有控制流的Paddle模型转换为ONNX

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
