### ISSUE TITLE
如何将转换的onnx模型format ONNX v8转换为v7

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/Paddle2ONNX#1019]
![image](https://user-images.githubusercontent.com/36955510/216269457-5fd5a789-4dfc-4a83-8c7b-ff35d48423d9.png)

使用paddle2onnx转换的onnx模型默认format是onnx v8，我现在需要v7 format的onnx模型，我应该如何设置。

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/FAQ.md 参考这个文档的最后一个问题
