### ISSUE TITLE
floating point exception both in macOS and linux

### ISSUE THREAD

**Issue by andreybondarb** [PaddlePaddle/Paddle2ONNX#1024]
"Floating point exception" error both in linux and macOS when trying to load converted SVTR-Tiny text recognition model. SVTR-Large model which is converted to .onnx  works just fine.

Code:

```
from onnxruntime import InferenceSession, SessionOptions
options = SessionOptions()
session = InferenceSession('./inference/svtr_tiny.onnx', options, providers=["CPUExecutionProvider"])
```
Opset version is 16. Paddle2ONNX Version latest.

**Comment by yeliang2258** [comment]
Hello, please provide the Paddle model to me to confirm the problem.

**Comment by andreybondarb** [comment]
Hi, here are models and .yml files used to train models. Thanks

[https://drive.google.com/drive/folders/19nuzBqiO-BZGUa4gXcUUy4vzCznz8Of_?usp=share_link](url)

**Comment by yeliang2258** [comment]
Please provide me the paddle model, I can directly convert and verify, thank you

**Comment by andreybondarb** [comment]
It seems like I have solved the problem. Just took the working config of SVTR-Large and filled all params for the SVTR-Tiny from the original paper. Also I noticed that there is some param in original SVTR-Tiny provided by PaddleOCR - which is
`"last_stage: True"`
in my SVTR-Large there wasn't such param. I also left unchanged some params
, just filled that were provided by original parer.

Last picture with working params for conversion of SVTR-Tiny to .onnx. Thank you.

<img width="939" alt="svtr_tiny_paddle_ocr 11 27 41" src="https://user-images.githubusercontent.com/53795493/218041667-566fe820-fd0c-4bb2-9df9-9d7d6f7439eb.png">
<img width="943" alt="svtr_tiny_form_large" src="https://user-images.githubusercontent.com/53795493/218041675-6afa92a2-032d-433e-8f62-93d214546b6d.png">

**Comment by andreybondarb** [comment]
Now I tested with "last_stage: True" and it is ok. So the problem was not because of "last_stage" param, but because some inconsistent shapes in model params. The error was because of Backbone.img_size: [32, 100] and Transform.tps_outputsize: [32, 100]. So I have changed it to [48, 160] as it was in SVTR-Large
