### ISSUE TITLE
自己用Paddle2ONNX转中英文超轻量PP-OCRv2模型到onnx，与官方转好的onnx模型，输入和输出存在区别

### ISSUE THREAD

**Issue by cdycdycdy** [PaddlePaddle/Paddle2ONNX#1026]
自己用Paddle2ONNX转中英文超轻量PP-OCRv2模型到onnx，与官方转好的onnx模型，输入和输出存在区别。官方的onnx可以动态输入，自己转的不行，例如文本检测模型DB输入必须为[1, 3, 960，960]

![image](https://user-images.githubusercontent.com/46981976/218052133-0902b4b0-0efc-42fc-b0c4-9150035e9c0e.png)
上图上面为官方转的onnx，下图自己转的onnx。

python infer.py --det_model_dir=./ch_PP-OCRv2_det_infer.onnx --rec_model_dir=./ch_PP-OCRv2_rec_infer.onnx --cls_model_dir=./ch_ppocr_mobile_v2.0_cls_infer.onnx --image_path=./images/lite_demo.png  执行报错：

Traceback (most recent call last):
  File "H:/PaddleOcr/Paddle2ONNX-develop/model_zoo/ocr/infer.py", line 143, in <module>
    dt_boxes = text_detector(img)
  File "H:\PaddleOcr\Paddle2ONNX-develop\model_zoo\ocr\utils\predict_det.py", line 332, in __call__
    outputs = self.predictor.run(None, input_dict)
  File "H:\Anaconda3\envs\paddle_env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: x for the following indices
 index: 2 Got: 288 Expected: 960
 index: 3 Got: 448 Expected: 960
 Please fix either the inputs or the model.

请问怎样用paddle2ONNX转换ocr模型跟官方的一样，能实现动态输入大小？

**Comment by yeliang2258** [comment]
先用这个工具修改一下Paddle模型的输入，然后再导出ONNX试试：
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle#2-%E4%BF%AE%E6%94%B9-paddle-%E6%A8%A1%E5%9E%8B%E8%BE%93%E5%85%A5-shape

**Comment by cdycdycdy** [comment]
> 先用这个工具修改一下Paddle模型的输入，然后再导出ONNX试试： https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle#2-%E4%BF%AE%E6%94%B9-paddle-%E6%A8%A1%E5%9E%8B%E8%BE%93%E5%85%A5-shape

谢谢，转换后就可以了。
