### ISSUE TITLE
能否paddle2onnx支技data_formate=NHWC的模型转换成onnx

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle2ONNX#1027]
在有paddleocr自己训练一个rostta模理，正常的默认是 NCHW格式。具体流程是image(NCHW)-》CNN(NCHW,H=1)-》Reshape(NCW)-》Transpose(NWC)-》FC.遇到的问题是要在特定的芯片上部署，不支持Transpose算子。改成image(NHWC)-》CNN(NHWC,H=1)-》Reshape(NWC)-》FC，这样，把transpose做到了预处理当中，就不存在与模型中。paddle的动静态模型都是能保存成功的，但是转onnx时报错，提示：Conv2d:convwd_39.tmp_0 cannot support input with nhwc..ERROR Due to the operatorL conv2d,this model cannot be export ed to onnx.

**Comment by yeliang2258** [comment]
由于ONNX支持的是NCHW格式的，就算Paddle2ONNX里面要支持NHWC，也要配合Transpose才可以，所以还是绕不开这个问题，Transpose算子是一个比较基础的算子，建议给硬件厂商提需求，新增Transpose算子

**Comment by DLlearn** [comment]
> 

@yeliang2258 好的，谢谢了。
