### ISSUE TITLE
Rtformer的onnx文件无法利用openvino转为.bin和.xml文件

### ISSUE THREAD

**Issue by zzyy520** [PaddlePaddle/Paddle2ONNX#1030]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
 Cannot infer shapes or values for node "p2o.MaxPool.0".
Stride can not be zero in node p2o.MaxPool.0
之前是有些算子不支持，现在升级了paddle2onnx，能够转onnx文件，但是不能将onnx文件转成其他文件类型。

**更多信息 :**
 - 用于部署的推理引擎:openvino
 - 为什么需要转换为ONNX格式：支持openvino推理
 - Paddle2ONNX版本:1.0.5
 - 你的联系方式(Email/Wechat/Phone):2317677054@qq.com

**报错截图**

![image](https://user-images.githubusercontent.com/82746353/219259979-bd77b0b1-2c03-45de-b01d-5835d3913165.png)

**其他信息**

**Comment by yeliang2258** [comment]
您好，麻烦先用ONNXRuntime推理这个ONNX模型，试一下是否能正常推理，如果可以正常推理，那么应该就是openvino不支持

**Comment by zzyy520** [comment]
您好，我们利用ONNXRuntime推理Rtformer-Slim模型训练的ONNX文件，不能正常的推理。为了防止测试代码问题，对比了其他ONNX模型，均可正常推理。

**Comment by yeliang2258** [comment]
那麻烦提供一下Paddle的模型，我这边来定位一下问题。可以通过网盘提供Paddle2ONNX可以直接转换的Paddle模型给我

**Comment by zzyy520** [comment]
链接：https://pan.baidu.com/s/1ql7TRYs3l1RE4nMWMrauZg?pwd=zycc 
提取码：zycc

百度网盘提供了paddle模型，中间文件和ONNX文件。
