### ISSUE TITLE
cannot convert PP-HumanSegV1-Lite to onnx - ValueError: basic_string::resize

### ISSUE THREAD

**Issue by labeeb-7z** [PaddlePaddle/Paddle2ONNX#1033]
while trying to convert the [PP-HumanSegV1-Lite](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/contrib/PP-HumanSeg#42-general-human-segmentation-models) (checkpoint) to onnx Im getting the following error : 

```
Traceback (most recent call last):
  File "/home/labeeb/miniconda3/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/labeeb/miniconda3/lib/python3.9/site-packages/paddle2onnx/command.py", line 233, in main
    c_paddle_to_onnx(
  File "/home/labeeb/miniconda3/lib/python3.9/site-packages/paddle2onnx/command.py", line 143, in c_paddle_to_onnx
    onnx_model_str = c_p2o.export(
ValueError: basic_string::resize
```

![image](https://user-images.githubusercontent.com/94868003/219573671-88e381b6-beda-42a1-a36a-64d01db91b9e.png)

What can I do differently to convert the model in onnx form? Thanks

System : pop-os (ubuntu based) 22.04
paddle2onnx version : 1.0.5

**Comment by yeliang2258** [comment]
Hello, the Paddle model must be a static graph model, the model file ends with pdmodel, and the parameter file ends with pdiparams.

**Comment by vvwomen** [comment]
放了动态图还是有相同的报错，请问楼主有解决吗？有的话，解决方法是什么呢？
