### ISSUE TITLE
PaddleOCR v3 文本识别onnx模型在ort-gpu加载失败

### ISSUE THREAD

**Issue by lzj9072** [PaddlePaddle/Paddle2ONNX#1034]
**问题描述**
使用onnxruntime(1.10.0)可正常加载；在onnxruntime-gpu(1.4.0)无法加载，如下图。机器是2080ti，cuda 10.2，paddle2onnx版本为1.0.5
![image](https://user-images.githubusercontent.com/26057369/219607709-75446dbf-4d3e-48d9-a47b-75b95bcbbee1.png)

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/FAQ.md  参考这个文档中第3个问题处理方式

**Comment by lzj9072** [comment]
可以了，感谢
