### ISSUE TITLE
在使用ssdlite_mobilenet_v1_300_coco模型转为onnx遇到算子不支持

### ISSUE THREAD

**Issue by impossible5657** [PaddlePaddle/Paddle2ONNX#1037]
你好我使用python tools/export_model.py -c configs/ssd/ssdlite_mobilenet_v1_300_coco.yml --output_dir=./inference_model -o weights=output/ssdlite_mobilenet_v1_300_coco/best命令导出模型并且转到onnx时遇到如下问题
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/ssdlite_mobilenet_v1_300_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/ssdlite_mobilenet_v1_300_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including prior_box,
[ERROR] Due to the unsupported operators, the conversion is aborted.
已放弃 (核心已转储)

请问应该如何解决？

**Comment by yeliang2258** [comment]
导出时，设置 --enable_dev_version Fasle试试
