### ISSUE TITLE
 converting pp-liteseg model to onnx format for C++ deployment

### ISSUE THREAD

**Issue by EudicL** [PaddlePaddle/Paddle2ONNX#1041]
When I convert the a model to onnx format for C++ deployment, an error is reported that I don't get the names of the inputs and outputs

 When I check the converted onnx, it says check is none

The pytorch model  can be converted with the following functions:

with torch.no_grad():
    torch.onnx.export(
        model, dummy_input,
        output_file,
        input_names=['input'],
        output_names=['output'],
        export_params=True,
        keep_initializers_as_inputs=False,
        opset_version=11,
        dynamic_axes=dynamic_axes)

I would like to know how input_names and output_names are specified in paddle

**更多信息 :**
 - 用于部署的推理引擎: onnxruntime
 - 为什么需要转换为ONNX格式：for C++ deployment
 - Paddle2ONNX版本: 
 - 你的联系方式(Email/Wechat/Phone): 

**报错截图**

inline char* Session::GetInputName(size_t index, OrtAllocator* allocator) const {
  char* out;
  ThrowOnError(GetApi().SessionGetInputName(p_, index, allocator, &out));
  return out;
}

**其他信息**

**Comment by Zheng-Bicheng** [comment]
Please report this issue in PaddlePaddle Repo
