### ISSUE TITLE
[Feature Request] 建议新增 bitwise_and、bitwise_not、conditional_block、empty、select_input 算子

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle2ONNX#1043]
## update 2023.03.23
移除了 elementwise_floordiv 算子：
https://paddlespeech.bj.bcebos.com/demos/paddle_work/vits_csmsc_ckpt_1.4.0_6.zip
可能存在的问题，可能有算子输出的 0D Tensor shape 为 [] 
用的是 2023.03.12 的 paddle develop 导出的静态模型，已经有些算子支持了 0D Tensor
<img width="645" alt="38e6964798caf29940f3d6a5e35f6751" src="https://user-images.githubusercontent.com/24568452/227108891-aafe2a35-7f8d-4ebd-b027-ccde00982c8b.png">

## update 2023.03.15

Lite 同学反馈某个 elemul 的输入类型是 bool，但是 lite 不支持，于是提前 cast 成 int64 了：

https://paddlespeech.bj.bcebos.com/demos/paddle_work/vits_csmsc_ckpt_1.4.0_5.zip
## update 2023.03.14
Lite 同学反馈最后一个 expand_v2 算子 expand shape 的 dtype 不一致，修改组网代码后重新导出模型如下：

https://paddlespeech.bj.bcebos.com/demos/paddle_work/vits_csmsc_ckpt_1.4.0_4.zip

## update 2023.03.13

Lite 同学反馈 reduce_sum 算子输入和输出类型不一致，输入为 bool 输出为 int64 ，修改组网代码重新导出模型如下：

https://paddlespeech.bj.bcebos.com/demos/paddle_work/vits_csmsc_ckpt_1.4.0_3.zip

## update
lite 反馈 pad 算子加起来比较复杂，我把 F.pad 转成了 nn.Pad1D 和 nn.Pad2D 成功移除了 pad 算子（变成了已有的 pad3d 算子），因此不再需要实现的 pad 算子了

目前的报错：
![image](https://user-images.githubusercontent.com/24568452/223414921-3e87341c-558b-4d19-81cb-23f12513ae2f.png)

去掉 pad 算子的模型：https://paddlespeech.bj.bcebos.com/demos/paddle_work/vits_csmsc_ckpt_1.4.0_2.zip

----

PaddleSpeech VITS 模型使用 Paddle2ONNX 缺少上述算子，了解到 conditional_block 算子加起来比较复杂，故这些算子新增不是强需求，提个 Feature Request 占下坑，后续如果有对 conditional_block 的新增计划，可以用 VITS 模型做测试
![image](https://user-images.githubusercontent.com/24568452/221859756-e176a7df-8511-4383-b298-a2d010a48bdd.png)

**Comment by Zheng-Bicheng** [comment]
bitwise_and、bitwise_not

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1321

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
