### ISSUE TITLE
some operators not supported yet

### ISSUE THREAD

**Issue by Whatsetsthisend** [PaddlePaddle/Paddle2ONNX#1046]
[Paddle2ONNX] Oops, there are some operators not supported yet, including mv,
mv算子还未支持对我来说很重要
![1677723912799](https://user-images.githubusercontent.com/44335783/222314865-46cdae68-7700-44e7-8bef-a525e3a89e6f.png)

**Comment by yeliang2258** [comment]
您好，请问是什么模型？这个模型转到ONNX是用什么推理引擎部署呢？

**Comment by Whatsetsthisend** [comment]
> 您好，请问是什么模型？这个模型转到ONNX是用什么推理引擎部署呢？

这是一个提取小区域内文本区域的模型主干应该是unet，推理部署采用onnxruntime在c++上运行，我已经绕过了这个问题，但是问题依旧是没有解决，我在转换为推理模型是修改paddle.mv为paddle,matmul，已经是成功转换了但是我觉得还是支持以下最好
![image](https://user-images.githubusercontent.com/44335783/222341216-b0360dea-b7f7-49ce-afb5-e941a47a68f5.png)

**Comment by Whatsetsthisend** [comment]
而且我有点不理解的是明明在推理的时候这些孤立的节点是不需要的，但是转换为推理模型后依然存在，我修改为matmul之后进行onnx转换出的onnx模型它就自动删除了这些孤立的分支

**Comment by yeliang2258** [comment]
因为这些节点都存在了Paddle的模型中，Paddle2ONNX都需要转换的，保持和原图一样的结构。

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/1047

**Comment by Whatsetsthisend** [comment]
> #1047

十分感谢
