### ISSUE TITLE
Hit Error: module paddle has no attibute ‘enable'

### ISSUE THREAD

**Issue by supercatking** [PaddlePaddle/Paddle2ONNX#1049]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
使用工具paddle_infer_shape.py修改模型输入参数出现报错：paddle has no attibute ‘enable'

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![image](https://user-images.githubusercontent.com/87652697/223068338-3fa5fe1c-1e2c-47dc-94d8-6df83ee56ac0.png)

**其他信息**
paddle.__version__ = 1.0.2

**Comment by yeliang2258** [comment]
请升级paddle为最新版本
