### ISSUE TITLE
多batch推理

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle2ONNX#1051]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

ppyoloe支持onnx batch>1推理么，如果不支持，具体是为什么呢？
**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
由于multiclass_nms3 op的原因，目前只支持batch size为1

**Comment by bixiaopeng0** [comment]
如果去掉后处理，是支持的哈

**Comment by yeliang2258** [comment]
是的，去掉后处理，将nms放到外面做，就可以支持多batch
