### ISSUE TITLE
pp-yoloe-r导出onnx如何固定输入

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/Paddle2ONNX#1053]
默认方式导出的onnx为多batch状态，我想导出一个输入为1*3*640*640的onnx，按照[教程](https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle)修改输入后，只改了输入image，还有个scale参数没有修改，而且导致输出也是之前的奇怪状态：
![Screenshot from 2023-03-10 14-18-33](https://user-images.githubusercontent.com/18437178/224239910-038ff296-25f1-40d6-b734-723a0e2eb7f6.png)

修改输入的命令:
python paddle_infer_shape.py --model_dir ../../PaddleDetection/output_inference/ppyoloe_r_crn_m_3x_dota/ --model_filename model.pdmodel --params_filename model.pdiparams --save_dir renamed.onnx --input_shape_dict="{'image':[1,3,640,640]}"

所以想问一下怎么固定pp-yoloe-r的输入尺寸？

**Comment by yeliang2258** [comment]
两个输入都固定，再导出看看

**Comment by LLsmile** [comment]
![1](https://user-images.githubusercontent.com/18437178/224258887-f8d1957e-3f01-478b-80c7-dd36e5169314.jpg)
不知道是不是中间有特殊处理，输出的还是不固定，scale_factor不知道是什么参数，我先固定成[1,2]

**Comment by LLsmile** [comment]
我用PaddleDetection的推理脚本测试了一下，虽然outputs可视化结果是不固定的，但是推理的结果都是固定的1*8400*8和1*1*8400，不知道该怎么改成输出也固定的？
