### ISSUE TITLE
mobilenetv2文档描述和实际的网络不一致

### ISSUE THREAD

**Issue by supercatking** [PaddlePaddle/Paddle2ONNX#1059]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
文档介绍的页面描述的是mobilenetV2，但实际网络是mobileV3。我想知道mobilenetV2在哪里下载。

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![image](https://user-images.githubusercontent.com/87652697/226786982-dcbe0d6d-8a30-4e74-a0b3-5ed3c85e0390.png)

**其他信息**

**Comment by yeliang2258** [comment]
可以去下载一个MobileNetV2的paddle模型，然后用Paddle2ONNX来转。
FastDeploy里面可以下载：https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/classification/paddleclas
