### ISSUE TITLE
转换ONNX模型时出现量化参数不匹配的问题

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle2ONNX#1070]
在使用Paddle2ONNX转换模型时出现量化参数不对齐的问题

模型链接: [PPOCRV3_rec_QAT.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/11117836/PPOCRV3_rec_QAT.zip)

**Comment by Zheng-Bicheng** [comment]
@yeliang2258

**Comment by Zheng-Bicheng** [comment]
具体可以见`p2o.Add.98`节点，存在2个量化参数

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/58363586/229014769-0d520232-f707-4444-a6bf-eba105399d35.png">

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/1071
