### ISSUE TITLE
尝试将transformer模型转为onnx时报错，目前ppadle是否支持换transformer模型

### ISSUE THREAD

**Issue by sparkssjj** [PaddlePaddle/Paddle2ONNX#1072]
目前尝试将papdlenlp中uie-m-large模型转换为onnx报错，转换命令如下：

paddle2onnx --model_dir ./ \
            --model_filename sentencepiece.bpe.model \
            --params_filename model_state.pdparams \
            --save_file uie_m_large.onnx \
            --enable_dev_version False

<img width="784" alt="7241af36db4580b776981bfbe31c188f" src="https://user-images.githubusercontent.com/65718907/229459319-80e9f69a-125c-47e9-bf5d-40665e4f9ecf.png">

目前paddle转换是否支持transformer

**Comment by yeliang2258** [comment]
看起来是模型解析就报错了，安装的是那个版本的Paddle呢？另外，升级一下Paddle2ONNX为最新版本，设置--enable_dev_version True

**Comment by sparkssjj** [comment]
paddle==2.4.2, paddlenlp==2.5.2, paddle2onnx==1.0.6， enable_dev_vision True也是同样错误

**Comment by yeliang2258** [comment]
我才注意到，你的模型是预训练模型，不是部署模型，部署模型应该是.pdmodel和pdiparams结尾的文件

**Comment by sparkssjj** [comment]
import paddle
from paddlenlp import Taskflow

schema = ['时间', '选手', '赛事名称']
ie = Taskflow('information_extraction', schema=schema, model="uie-m-large")
paddle.save(ie, "./npl_model/uie_m_large.pdmodel")

用这样的方式保存报错：
File "/usr/local/lib/python3.8/dist-packages/paddle/framework/io.py", line 348, in _pickle_save
    pickler.dump(obj)

TypeError: cannot pickle 'paddle.fluid.libpaddle.AnalysisConfig' object

请问nlp模型怎么正确保存为部署模型。

**Comment by chestnut111** [comment]
同问 ; 
请问nlp模型怎么正确保存为部署模型。
