### ISSUE TITLE
[pool2d: pool2d_4.tmp_0]

### ISSUE THREAD

**Issue by Cccccc-c** [PaddlePaddle/Paddle2ONNX#1076]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
转换模型的时候报了下面的错误，pool2d 

**Informations (please complete the following information):**
 - Inference engine for deployment:  NPU
 - Why convert to onnx：因为我们的推理框架只支持onnx的输入，测试一下paddlepaddle的模型
 - Paddle2ONNX Version:2023-04-07 16:57:54 [INFO]      paddle2onnx-1.0.6 with python>=3.6, paddlepaddle>=2.0.0  
 - Email/Wechat/Phone:

**Screenshots**
```shell
paddle2onnx --model_dir . --model_filename model.pdmodel  --params_filename model.pdiparams --opset_version 11 --save_file output.onnx                                                             
[Paddle2ONNX] Start to parse PaddlePaddle model...                                                                                
[Paddle2ONNX] Model file path: ./model.pdmodel                                                                                    
[Paddle2ONNX] Paramters file path: ./model.pdiparams                                                                              
[Paddle2ONNX] Start to parsing Paddle model...                                                                                    
[ERROR][Paddle2ONNX] [pool2d: pool2d_4.tmp_0] Adaptive only support static input shape.                                           
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.                                                 
[ERROR][Paddle2ONNX] [pool2d: pool2d_5.tmp_0] Adaptive only support static input shape.                                           
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.                                                 
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.                   
Aborted (core dumped)
```

**Additional context**

模型来源：wget https://paddleseg.bj.bcebos.com/inference/pp_liteseg_infer_models/pp_liteseg_stdc1_cityscapes_1024x512_scale1.0_160k_inference_model.zip

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle#2-%E4%BF%AE%E6%94%B9-paddle-%E6%A8%A1%E5%9E%8B%E8%BE%93%E5%85%A5-shape
先用这个工具将Paddle模型的输入shape固定，再转ONNX

**Comment by yeliang2258** [comment]
推荐使用FastDeploy进行部署，可以不用固定shape进行部署，https://github.com/PaddlePaddle/FastDeploy/tree/develop/examples/vision/segmentation/paddleseg

**Comment by Cccccc-c** [comment]
Good !!!
