### ISSUE TITLE
PaddleSeg提供的HarDNet模型，导出成ONNX模型后精度严重下降

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/Paddle2ONNX#1078]
具体情况描述在下方链接，但是还没有工作人员回复
https://github.com/PaddlePaddle/PaddleSeg/issues/3137

**Comment by yeliang2258** [comment]
麻烦提供一下Paddle的部署模型，我这边看看。可以放到网盘里，然后给我网盘链接

**Comment by censhallwe** [comment]
> 麻烦提供一下Paddle的部署模型，我这边看看。可以放到网盘里，然后给我网盘链接

谢谢您的回复，我用的模型是PaddleSeg里的HarDNet模型，官方链接https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.7/configs/hardnet
现在问题已经解决了，是原模型的训练轮次不够。但有一点很奇怪，就是原模型预测效果还行（预测的时候用的也是训练集里的图像），但是转成ONNX模型后，精度就下来了，必须让原模型训练的轮次足够大才行，只要轮次够多，转成ONNX之后就没问题。我试了几次，都是这样的情况。不知道您有没有遇到过这种现象，如果有的话，您知道是什么原因导致的吗？麻烦您告知我，辛苦您了，感谢❤

**Comment by Louis-YanKang** [comment]
您好，我也遇到了相似得问题，请问您前后得训练轮次调得是多少呢？感谢

**Comment by wangkd0** [comment]
> 您好，我也遇到了相似得问题，请问您前后得训练轮次调得是多少呢？感谢

+1

**Comment by censhallwe** [comment]
> > 您好，我也遇到了相似得问题，请问您前后得训练轮次调得是多少呢？感谢
> 
> +1

我印象中设的蛮大的，原本只有1000，后来设成了100000

**Comment by wangkd0** [comment]
只是增加训练轮次吗，其他参数没有调整吗
