### ISSUE TITLE
转yolov3  paddle1.5.1

### ISSUE THREAD

**Issue by zengxianyugithub** [PaddlePaddle/Paddle2ONNX#108]
aistudio@jupyter-83877-140942:~$ paddle2onnx --fluid_model freeze_model/  --onnx_model onnxyolov3.onnx/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
-----------  Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: freeze_model/
fluid_model_name: 
fluid_params_name: 
image_path: 
name_prefix: 
onnx_model: onnxyolov3.onnx
return_variable: False
to_print_model: False
------------------------------------------------
load the model parameter done.
The operator sets to run test case.
{'nearest_interp', 'yolo_box', 'shape', 'batch_norm', 'multiclass_nms', 'conv2d', 'transpose2', 'cast', 'concat', 'fill_constant', 'leaky_relu', 'slice', 'elementwise_mul', 'scale', 'elementwise_add'}
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 194, in convert
    checker.check_model(onnx_model)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 2 not in range [min=3, max=4].

==> Context: Bad node spec: input: "leaky_relu_58.tmp_0" input: "nearest_interp_0.tmp_0@scales" output: "nearest_interp_0.tmp_0" op_type: "Resize" attribute { name: "mode" s: "nearest" type: STRING }

**Comment by zengxianyugithub** [comment]
Python版本
Python 3.7
框架版本
PaddlePaddle 1.5.1
darnet yolov3  训练的模型
notebook           5.7.8          
numpy              1.16.4         
onnx               1.6.0          
opencv-python      4.1.1.26       
paddle2onnx        0.2            
paddlehub          1.2.0          
paddlepaddle       1.5.1 

训练参数和模型：https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/configs/yolov3_darknet_voc.yml

使用转换命令：paddle2onnx --fluid_model mj_yolov3_darknet/  --fluid_model_name mj_yolov3_darknet/__model__ --fluid_params_name mj_yolov3_darknet/__params__ --onnx_model mjy3
得到的结果
>>/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
-----------  Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: mj_yolov3_darknet/
fluid_model_name: mj_yolov3_darknet/__model__
fluid_params_name: mj_yolov3_darknet/__params__
image_path: 
name_prefix: 
onnx_model: mjy3
return_variable: False
to_print_model: False
------------------------------------------------
load the model parameter done.
The operator sets to run test case.
{'concat', 'multiclass_nms', 'scale', 'conv2d', 'leaky_relu', 'batch_norm', 'yolo_box', 'nearest_interp', 'elementwise_add', 'transpose2'}
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 194, in convert
    checker.check_model(onnx_model)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 0 not in range [min=1, max=1].

==> Context: Bad node spec: output: "nearest_interp_0.tmp_0@out_size_f" op_type: "Cast" attribute { name: "to" i: 1 type: INT }

**Comment by cjt222** [comment]
可以尝试使用models下的PaddleDetection1.5版本的yolov3模型进行转换，目前paddle2onnx还未适配最新版本的模型转换

**Comment by aixier** [comment]
> 可以尝试使用models下的PaddleDetection1.5版本的yolov3模型进行转换，目前paddle2onnx还未适配最新版本的模型转换

意思是换成paddle1.5训练么？我马上训练一个

**Comment by aixier** [comment]
> 可以尝试使用models下的PaddleDetection1.5版本的yolov3模型进行转换，目前paddle2onnx还未适配最新版本的模型转换
![image](https://user-images.githubusercontent.com/7700464/74040522-d575a800-49fe-11ea-9b1e-d65161cc208c.png)

感觉在好为难，Detection有只支持1.6以上，模型这里又要求1.5
@reyoung

**Comment by zengxianyugithub** [comment]
> 可以尝试使用models下的PaddleDetection1.5版本的yolov3模型进行转换，目前paddle2onnx还未适配最新版本的模型转换

我的模型就是在paddle1.5.1上訓練的

**Comment by aixier** [comment]
@cjt222

**Comment by cjt222** [comment]
> > 可以尝试使用models下的PaddleDetection1.5版本的yolov3模型进行转换，目前paddle2onnx还未适配最新版本的模型转换
> 
> 我的模型就是在paddle1.5.1上訓練的

我的意思是models库 1.5版本，不是Paddle版本

**Comment by cjt222** [comment]
问题在最新代码中已修复，可以更新下代码，使用最新的PaddleDetection的模型进行转换
