### ISSUE TITLE
paddle2onnx 导出onnx模型

### ISSUE THREAD

**Issue by sc199505** [PaddlePaddle/Paddle2ONNX#1084]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
paddle2onnx 导出QAT量化后模型失败 fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max  not support 不支持
**更多信息 :**
 - 用于部署的推理引擎:onnx
 - 为什么需要转换为ONNX格式：需要比较在onnx上原始模型和QAT量化模型性能
 - Paddle2ONNX版本:1.0.6
 - 你的联系方式(Email/Wechat/Phone):1848621099@qq.com

**报错截图**
fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max  not support
**其他信息**
paddle-slim 2.4.0

**Comment by sc199505** [comment]
是需要paddle2onnx特定版本么？

**Comment by sc199505** [comment]
找到原因了

**Comment by sc199505** [comment]
导出静态图模型的时候quant_config onnx_format设置为true，不会再出现fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max op，量化模型可以正常推理，但是在paddle2onnx 出现段错误。

**Comment by sc199505** [comment]
![Screenshot from 2023-04-17 17-02-37](https://user-images.githubusercontent.com/45219151/232446129-4e612281-7403-49ad-87d6-9cd5d660e39e.png)
![Screenshot from 2023-04-17 17-03-34](https://user-images.githubusercontent.com/45219151/232446140-8dba8ae1-ae8d-4b0a-90b3-9dd748154844.png)
![Screenshot from 2023-04-17 17-04-12](https://user-images.githubusercontent.com/45219151/232446145-7f92b62d-792c-4a5f-a354-8a4593b8b22c.png)
![Screenshot from 2023-04-17 17-04-42](https://user-images.githubusercontent.com/45219151/232446151-3cdb5fc3-6eb1-4137-82c4-4b18076b8df1.png)

**Comment by sc199505** [comment]
[exported_model.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/11248620/exported_model.zip)

**Comment by sc199505** [comment]
[dd3d_quant.zip.001.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/11248654/dd3d_quant.zip.001.zip)
[dd3d_quant.zip.002.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/11248655/dd3d_quant.zip.002.zip)
[dd3d_quant.zip.003.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/11248656/dd3d_quant.zip.003.zip)

**Comment by sc199505** [comment]
develop 版本可解决

**Comment by yangy996** [comment]
> develop 版本可解决

我试过了 还是会报错

**Comment by Daipuwei** [comment]
> 导出静态图模型的时候quant_config onnx_format设置为true，不会再出现fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max op，量化模型可以正常推理，但是在paddle2onnx 出现段错误。

请问是需要下载paddle2onnx的develop分支源码进行编译然后再转onnx就能成功吗

**Comment by Daipuwei** [comment]
> develop 版本可解决

方便加个微信交流下这个问题吗？我的微信是：daipuweiai

**Comment by 1314520gu** [comment]
请问解决了吗
