### ISSUE TITLE
one_hot算子不支持转换，如何解决

### ISSUE THREAD

**Issue by 471417367** [PaddlePaddle/Paddle2ONNX#1085]
paddlenlp 2.5.2
paddlepaddle 2.4.2
onnx 1.13.1
paddle2onnx 1.0.6

文件结构：docprompt/inference.pdmodel docprompt/inference.pdiparams
使用命令：
paddle2onnx --model_dir docprompt --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file docprompt.onnx --enable_onnx_checker True
报错：
[Paddle2ONNX] Oops, there are some operators not supported yet, including one_hot,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
请问这如何解决呢？

**Comment by yeliang2258** [comment]
可以参考这个文档自己新增OP：https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/Paddle2ONNX_Development_Guide.md

**Comment by Lingchen99** [comment]
请问解决了吗
