### ISSUE TITLE
ppseg2.8 MaskFormer转onnx，roll/einsum/bitwise_not算子不支持

### ISSUE THREAD

**Issue by trarynight** [PaddlePaddle/Paddle2ONNX#1087]
**问题描述**
ppseg2.8 MaskFormer转onnx时，roll/einsum/bitwise_not算子不支持。
指令：paddle2onnx --model_dir output/huaxian_mformer_230421/export/ --params_filename model.pdiparams --model_filename model.pdmodel --save_file output/huaxian_mformer_230421/export/model.onnx --enable_onnx_checker True --opset_version 16
版本信息：
![image](https://user-images.githubusercontent.com/26101192/233895228-64b8e24a-dcfc-4a39-baf1-49c88c7d38be.png)

**更多信息 :**
 - 用于部署的推理引擎:triton-tensorrt或paddlelite backend
 - 为什么需要转换为ONNX格式：模型太大，需要trt加速。
 - Paddle2ONNX版本:1.0.6
 - 你的联系方式(Email/Wechat/Phone): 18217585139

**报错截图**
![image](https://user-images.githubusercontent.com/26101192/233894997-01884011-2fb0-40c7-a216-c23e868e4ac8.png)

**其他信息**

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1321

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1314

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1228
