### ISSUE TITLE
paddle转onnx出错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/Paddle2ONNX#109]
Python：Python 3.7
转换框架版本：PaddlePaddle 1.5.1
paddledetecton0.1:  darnet yolov3  训练的模型
paddle2onnx： 0.2
****训练参数和模型***：*https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/configs/yolov3_darknet_voc.yml

**使用转换命令**：paddle2onnx --fluid_model mj_yolov3_darknet/ --fluid_model_name mj_yolov3_darknet/model --fluid_params_name mj_yolov3_darknet/params --onnx_model mjy3
**得到的结果,出错信息**

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
----------- Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: mj_yolov3_darknet/
fluid_model_name: mj_yolov3_darknet/model
fluid_params_name: mj_yolov3_darknet/params
image_path:
name_prefix:
onnx_model: mjy3
return_variable: False
to_print_model: False

load the model parameter done.
The operator sets to run test case.
{'concat', 'multiclass_nms', 'scale', 'conv2d', 'leaky_relu', 'batch_norm', 'yolo_box', 'nearest_interp', 'elementwise_add', 'transpose2'}
Traceback (most recent call last):
File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 10, in 
sys.exit(main())
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
convert(args)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 194, in convert
checker.check_model(onnx_model)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 0 not in range [min=1, max=1].

==> Context: Bad node spec: output: "nearest_interp_0.tmp_0@out_size_f" op_type: "Cast" attribute { name: "to" i: 1 type: INT }
@cjt222

**Comment by aixier** [comment]
用paddle1.5.1训练了一个一样的问题

**Comment by aixier** [comment]
这个模块没有人维护了么@cjt222

**Comment by cjt222** [comment]
可以尝试使用models1.5下的PaddleDetection训练yolov3，由于PaddleDetection做了一些更新，造成了一些OP的不适配

**Comment by leeburt** [comment]
能说的具体一点吗？models1.5是指？ PaddleDetection的版本不需要指定版本吗？

**Comment by cjt222** [comment]
现在代码中已修复，你可以更新下代码，下载最新的PaddleDetection的模型进行转换

**Comment by leeburt** [comment]
> 现在代码中已修复，你可以更新下代码，下载最新的PaddleDetection的模型进行转换

我用的是paddlepaddle1.6.2版本，onnx是1.6.0版本。PaddleDetection和PaddleONNX都是最新的版本。但是报错如下，模型是mobilenet yolov3
`load the model parameter done.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx-0.1-py3.7.egg/fluid_onnx/detection_ops.py:845: UserWarning: The parameter normalized of multiclass_nms OP of Paddle is False, which has diff with ONNX.                          Please set normalized=True in multiclass_nms of Paddle
The operator sets to run test case.
{'depthwise_conv2d', 'transpose2', 'concat', 'elementwise_add', 'scale', 'multiclass_nms', 'batch_norm', 'nearest_interp', 'yolo_box', 'leaky_relu', 'conv2d', 'relu'}
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 11, in <module>
    load_entry_point('paddle2onnx==0.1', 'console_scripts', 'paddle2onnx')()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx-0.1-py3.7.egg/fluid_onnx/fluid_to_onnx.py", line 230, in main
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx-0.1-py3.7.egg/fluid_onnx/fluid_to_onnx.py", line 194, in convert
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 2 not in range [min=3, max=4].

==> Context: Bad node spec: input: "leaky_relu_6.tmp_0" input: "nearest_interp_0.tmp_0@scales" output: "nearest_interp_0.tmp_0" op_type: "Resize" attribute { name: "mode" s: "nearest" type: STRING }`

**Comment by cjt222** [comment]
测试时使用的onnx 1.5.0版本，onnx1.6版本有些OP做过改动，之后会更新升级。可以先使用onnx 1.5.0进行转换试一下
