### ISSUE TITLE
Make version changes to paddle2onnx to support conversion

### ISSUE THREAD

**Issue by ss756** [PaddlePaddle/Paddle2ONNX#1091]
The current version of paddle2onnx has bugs and does not support inference of the model converted to onnx format as the input shape is stored as a object (p2.Dynamic). Downgrading to a earlier version of paddle2onnx fixes this issue. Would it be possible to add the functionality to the current version of paddle2onnx

**Comment by yeliang2258** [comment]
pip install paddle2onnx==x.x.x
