### ISSUE TITLE
ppmodel convert onnx ，paddleocr run to fail

### ISSUE THREAD

**Issue by jian-kuang** [PaddlePaddle/Paddle2ONNX#1092]
paddle2onnx --model_dir ./inference/det --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/det_onnx/model.onnx --opset_version 11 --enable_onnx_checker True

paddle2onnx --model_dir ./inference/rec --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/rec_onnx/model.onnx --opset_version 11 --enable_onnx_checker True

paddle2onnx --model_dir ./inference/cls --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./inference/cls_onnx/model.onnx --opset_version 11 --enable_onnx_checker True

run erro info：
`Traceback (most recent call last):
  File "H:\Develop\paddleOCR\test.py", line 10, in <module>
    ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_onnx=True,
  File "H:\Develop\paddleOCR\paddleocr.py", line 502, in __init__
    super().__init__(params)
  File "H:\Develop\paddleOCR\tools\infer\predict_system.py", line 46, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "H:\Develop\paddleOCR\tools\infer\predict_det.py", line 146, in __init__
    if img_h is not None and img_w is not None and img_h > 0 and img_w > 0:
TypeError: '>' not supported between instances of 'str' and 'int'`

model view, why x value is float32[p2o.DynamicDimension.0,3,p2o.DynamicDimension.1,p2o.DynamicDimension.2 ?

**Comment by 2018-Summer** [comment]
没个人回复一下吗？？？

**Comment by hoangph3** [comment]
You should use `paddle2onnx==0.9.0`. It's working!
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/54660554/03510708-fef8-4bba-ac4d-38f5e8b5e9db)
