### ISSUE TITLE
det 模型转onnx后怎样用python代码使用得到的模型？

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/Paddle2ONNX#1093]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by MianMianMeow** [comment]
看看这个呢
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/paddle2onnx/readme.md
可以根据下面这些文件写
python3.7 tools/infer/predict_system.py --use_gpu=False --use_onnx=True \
--det_model_dir=./inference/det_onnx/model.onnx  \
--rec_model_dir=./inference/rec_onnx/model.onnx  \
--cls_model_dir=./inference/cls_onnx/model.onnx  \
--image_dir=doc/imgs_en/img_12.jpg \
--rec_char_dict_path=ppocr/utils/en_dict.txt

**Comment by nissansz** [comment]
你会改paddle源代码吗？
ch_PP-OCRv3_rec_distillation.yml  将其改为resnet34 backbone
不能直接训练，需要改源代码，不知道怎么改
