### ISSUE TITLE
grid_sample算子导致paddle2onnx强制使用opset_version 16

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/Paddle2ONNX#1102]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
RT，我在尝试使用PaddleDetection的rt-detr模型转换onnx，但是在paddle2onnx时会因为存在grid_sample算子导致工具强制走opset_version 16。

然而我们后面对onnx模型的使用强以来与opset_version 11。有什么办法可以帮忙绕过该算子吗？

转换方式：[rtdetr](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rtdetr)

**更多信息 :**
 - 用于部署的推理引擎: 厂家自定的引擎
 - 为什么需要转换为ONNX格式：推理引擎依赖onnx parser
 - Paddle2ONNX版本: 1.0.5
 - 你的联系方式(Email/Wechat/Phone): 

**报错截图**
[参考log](https://github.com/PaddlePaddle/PaddleDetection/issues/8114#issuecomment-1552818223)

**其他信息**

**Comment by jiangjiajun** [comment]
因为这个算子只有opset 16有，所以需要强制到16

**Comment by cqlp1314** [comment]
> 因为这个算子只有opset 16有，所以需要强制到16

我也遇到了这种情况,我需要opset_version 12,请问大佬有什么办法可以解决吗,可以帮忙提出一个理论上能解决的方式吗?

**Comment by Sujie1528** [comment]
把使用grid_sample的地方全部替换为mmcv版本的grid_sample，其中使用view()函数的地方替换为reshape().
