### ISSUE TITLE
Paddle2onnx转出来的onnx模型都会带有两个domain吗？

### ISSUE THREAD

**Issue by RebornARX** [PaddlePaddle/Paddle2ONNX#1112]
我使用Paddle2onnx转出onnx模型文件：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58839824/cb5a0302-8d1b-49fe-a2ad-57576154f8d7)
但是当我用netron将转好的onnx文件打开时发现该文件有两个domain
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58839824/5233061e-8790-48ed-81fc-65f643b6554a)
这是我不希望看到的，我希望转出的onnx文件中domain信息只包含ai:onnx v13不要Paddle v1

**Comment by yeliang2258** [comment]
使用最新的版本，应该就没这问题了
