### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle2onnx.paddle2onnx_cpp2py_export'

### ISSUE THREAD

**Issue by Curry-Christopher** [PaddlePaddle/Paddle2ONNX#1113]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
进行paddle模型转onnx时报错：
xxx/Paddle2ONNX/paddle2onnx/command.py", line 155, in c_paddle_to_onnx               
    import paddle2onnx.paddle2onnx_cpp2py_export as c_p2o
ModuleNotFoundError: No module named 'paddle2onnx.paddle2onnx_cpp2py_export'

**更多信息 :**
 - 用于部署的推理引擎: 
 - 为什么需要转换为ONNX格式：转tensorrt
 - Paddle2ONNX版本: develop版本
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
没有正确安装Paddle2ONNX，可以直接使用pip安装
