### ISSUE TITLE
var linear_0.w_0 not in this block

### ISSUE THREAD

**Issue by TgrotCn** [PaddlePaddle/Paddle2ONNX#1114]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
python ./prune_paddle_model.py --model_dir  /workspace/jia/test/orgin/infer_model/ \
                             --model_filename text.pdmodel \
                             --params_filename text.pdiparams \
                             --output_names linear_0.w_0 \
                             --save_dir ../new_model/
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58065607/5c41fd65-2eb3-4a1b-b935-1aa80701ce68)

显示var not in this block ，请问这个output_names是Onnx图里面的算子名称吗还是什么。
**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

![Snipaste_2023-05-30_12-31-43](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58065607/9a414098-2589-4020-87e5-0c5c5a362664)

**其他信息**

**Comment by yeliang2258** [comment]
用最新版本的Paddle2ONNX，不指定output_names再试试
