### ISSUE TITLE
PP-MobileSeg通过paddl2onnx转换报错，op问题 conditional_block

### ISSUE THREAD

**Issue by Yang507** [PaddlePaddle/Paddle2ONNX#1125]
转换命令： 
    paddle2onnx --model_dir=./models --model_filename=model.pdmodel --params_filename=model.pdiparams -- 
     save_file=./models/inference.onnx --opset_version=11 --enable_onnx_checker=True  --enable_dev_version True

    版本：
    paddlepaddle-gpu: 2.4.2.post112
    paddle2onnx:           1.0.6

   ```
   报错：
    [Paddle2ONNX] Start to parse PaddlePaddle model...
    [Paddle2ONNX] Model file path: ./models/model.pdmodel
    [Paddle2ONNX] Paramters file path: ./models/model.pdiparams
    [Paddle2ONNX] Start to parsing Paddle model...
    [Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,
    [ERROR] Due to the unsupported operators, the conversion is aborted.
    Aborted (core dumped)
```

**Comment by Zheng-Bicheng** [comment]
* * https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
