### ISSUE TITLE
Paddle2Onnx新版本为什么没提供预编译库？

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle2ONNX#1127]
注意到Paddle2Onnx老版本<=1.0.5都提供了预编译库：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/1317141/d2c842e0-9da5-4b4d-bd7b-0a2c5b0c89c1)

想了解一下为什么Paddle2Onnx新版本>1.0.5都未提供预编译库：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/1317141/33e3adb9-d785-465b-b059-dc300e62a0d1)

想了解一下为什么不提供了？windows/linux/osx的编译总归是个麻烦的事，提供预编译库能减轻很多工作，建议提供。

**Comment by Zheng-Bicheng** [comment]
自行编译，dist目录下会出现编译库
