### ISSUE TITLE
There are some operators not supported yet

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [PaddlePaddle/Paddle2ONNX#1128]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
I'm trying to convert **faster_rcnn_r50_fpn_1x_coco** to onnx format. But some operators in '**faster_rcnn_r50_fpn_1x_coco**' are not supported by PADDLE2ONNX like this operator used for generating region proposals -> **generate_proposals_v2**

The error message :
start->

[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.
./3_export_rcnn_model_to_onnx: line 4: 18905 Aborted                 (core dumped) paddle2onnx --model_dir inference_model/faster_rcnn_r50_fpn_1x_coco --model_filename model.pdmodel --params_filename model.pdiparams --save_file faster_rcnn_r50_fpn_1x_coco.onnx

end <-

**My paddle packages installed version:**
paddle2onnx              1.0.6
paddledet                   2.6.0
paddlepaddle             2.4.2
paddlepaddle-gpu      2.4.2.post117

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by hl-gl** [comment]
请问解决了吗

**Comment by seejah** [comment]
遇到了一模一样的问题，导出模型时已去控制流（export_onnx=True），转换时按isuses里的答案设置了-enable_dev_version False，出现的提示居然是： ModuleNotFoundError: No module named 'onnx'，连onnx都不认识了.......

**Comment by zhjian831129** [comment]
> 遇到了一模一样的问题，导出模型时已去控制流（export_onnx=True），转换时按isuses里的答案设置了-enable_dev_version False，出现的提示居然是： ModuleNotFoundError: No module named 'onnx'，连onnx都不认识了.......

我跟你一样的操作，碰到也是你这样的问题， 请问 你解决了吗

**Comment by seejah** [comment]
@zhjian831129 
解决了。
1、paddle版本2.4
2、onnx版本1.10
在上述环境下，onnx导出成功。
之前版本高点、低点都不行，也不知咋回事。

**Comment by zhjian831129** [comment]
> @zhjian831129 解决了。 1、paddle版本2.4 2、onnx版本1.10 在上述环境下，onnx导出成功。 之前版本高点、低点都不行，也不知咋回事。

你是用paddledetection 吗？ 你现在可以转onnx 了吗？  能加个好友吗？  我的QQ：33138135

**Comment by zhjian831129** [comment]
> **请将下面信息填写完整，便于我们快速解决问题，谢谢！**
> 
> **问题描述** I'm trying to convert **faster_rcnn_r50_fpn_1x_coco** to onnx format. But some operators in '**faster_rcnn_r50_fpn_1x_coco**' are not supported by PADDLE2ONNX like this operator used for generating region proposals -> **generate_proposals_v2**
> 
> The error message : start->
> 
> [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdmodel [Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r50_fpn_1x_coco/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2, [ERROR] Due to the unsupported operators, the conversion is aborted. ./3_export_rcnn_model_to_onnx: line 4: 18905 Aborted (core dumped) paddle2onnx --model_dir inference_model/faster_rcnn_r50_fpn_1x_coco --model_filename model.pdmodel --params_filename model.pdiparams --save_file faster_rcnn_r50_fpn_1x_coco.onnx
> 
> end <-
> 
> **My paddle packages installed version:** paddle2onnx 1.0.6 paddledet 2.6.0 paddlepaddle 2.4.2 paddlepaddle-gpu 2.4.2.post117
> 
> **更多信息 :**
> 
> * 用于部署的推理引擎:
> * 为什么需要转换为ONNX格式：
> * Paddle2ONNX版本:
> * 你的联系方式(Email/Wechat/Phone):
> 
> **报错截图**
> 
> **其他信息**

楼主，我和你问题一模一样，请问你解决了吗

**Comment by seejah** [comment]
@zhjian831129 
很久不用qq了，加我微信吧w7670028
