### ISSUE TITLE
为什么paddle2onnx还不提供python3.11的 wheel 安装包

### ISSUE THREAD

**Issue by 526872163** [PaddlePaddle/Paddle2ONNX#1132]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
我需要在python3.11的环境中使用paddle2onnx，请尽快提供python3.11的pip 安装包 ，如果要使用是否要手动编译？

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):526872163@qq.com

**报错截图**

**其他信息**

**Comment by 526872163** [comment]
我需要在paddlenlp项目中使用

**Comment by jiangjiajun** [comment]
会尽快发布。 当前你可以参考这个文档自行编译 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md
