### ISSUE TITLE
p2o.DynamicDimension.0

### ISSUE THREAD

**Issue by banhongjun** [PaddlePaddle/Paddle2ONNX#1137]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/99791142/5aa848ad-dc00-4c98-ba78-dfbd5ee32830)

onnx文件的输出batch为p2o.DynamicDimension.0，怎样改为-1。如：[-1,300,5]

**Comment by jiangjiajun** [comment]
使用老版本Paddle2ONNX可以，例发1.0.0
