### ISSUE TITLE
自己训练paddleseg中的模型转onnx报错

### ISSUE THREAD

**Issue by KKWY0909** [PaddlePaddle/Paddle2ONNX#1139]
采用自己的数据集训练paddleseg中pp_liteseg_stdc2模型，已经转换成推理模型，转onnx出现报错：

**更多信息 :**
 - 用于部署的推理引擎: 
 - 为什么需要转换为ONNX格式：标注软件X-Anylabeling需要
 - Paddle2ONNX版本: paddle2onnx-1.0.6
 - 你的联系方式(Email/Wechat/Phone): 2240316863@qq.com

**报错截图**
![捕获](https://github.com/PaddlePaddle/Paddle2ONNX/assets/54742276/89fccb40-5d1c-46c0-8ae5-150211141831)

**其他信息**

**Comment by hl-gl** [comment]
请问解决了吗

**Comment by Zheng-Bicheng** [comment]
@KKWY0909 @liuhuan-gl 这个报错已经很明确了，请先固定用于转换的paddle模型的输入shape，再使用paddle2onnx进行转换。
