### ISSUE TITLE
如何用opset12导出rtdetr

### ISSUE THREAD

**Issue by Sujie1528** [PaddlePaddle/Paddle2ONNX#1142]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
使用opset=12导出rt-detr模型时，grid_sample算子要求opset=16。但是项目后续部分要求使用opset=12。如何使用opset=12导出rt-detr？

**更多信息 :**
 - 用于部署的推理引擎: rknpu
 - 为什么需要转换为ONNX格式：部署模型到rk3588开发板
 - Paddle2ONNX版本:  1.0.5
 - 你的联系方式(Email/Wechat/Phone): fangsujie2001@gmail.com

**报错截图**
![K8hVfI4cSk](https://github.com/PaddlePaddle/Paddle2ONNX/assets/63102146/9c2b7b03-3028-4183-9e59-a3864e06e21f)
其中PaddleDetection是这个git repo：https://github.com/PaddlePaddle/PaddleDetection

**其他信息**

**Comment by Zheng-Bicheng** [comment]
联系RK那边解决哈，这个我们没办法处理，ONNX算子就是这么要求的
