### ISSUE TITLE
AttributeError: module 'paddle.fluid.layers' has no attribute 'multiclass_nms'

### ISSUE THREAD

**Issue by mahesh11T** [PaddlePaddle/Paddle2ONNX#1147]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Informations (please complete the following information):**
 - Paddle2ONNX Version:latest

**Screenshots**

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/107621428/2ef25c66-20fd-45cd-84a3-764d57ff4b6b)

**Additional context**

**Comment by seejah** [comment]
我也遇到了这个问题，当转换模型为onnx时，出现了这个错误信息：

> AttributeError: module 'paddle.fluid.layers' has no attribute 'multiclass_nms'

**Comment by jiangjiajun** [comment]
将paddle包降级到2.4.2

**Comment by seejah** [comment]
@jiangjiajun 是的是的！ paddle降到2.4.2后 可以导出onnx了！
我在这里也做了说明：https://github.com/PaddlePaddle/Paddle2ONNX/issues/924#issuecomment-1751667471
