### ISSUE TITLE
Oops, there are some operators not supported yet, including roll

### ISSUE THREAD

**Issue by jeiva2000** [PaddlePaddle/Paddle2ONNX#1152]
cannot export model rtdetr swin

**Comment by jeiva2000** [comment]
I was checking, and it seems to me that you need to create and add the roll.h and roll.cc files

**Comment by taroshi** [comment]
got same problem : [Paddle2ONNX] Oops, there are some operators not supported yet, including roll,

**Comment by taroshi** [comment]
@taroshi  try to add params  --enable_dev_version False --opset_version=12, it works for me

**Comment by tartesia** [comment]
I have tried but now I get this: 
NotImplementedError: 
There's 1 ops are not supported yet
=========== pad ===========

**Comment by jeiva2000** [comment]
I have tried but now I get this:
NotImplementedError:
There's 1 ops are not supported yet
=========== pad ===========

**Comment by jeiva2000** [comment]
@jiangjiajun

**Comment by YeXinZ** [comment]
NotImplementedError: 
There's 2 ops are not supported yet

**Comment by Zheng-Bicheng** [comment]
@YeXinZ @jeiva2000 @taroshi I'm not sure if you still need to convert Paddle models with the Roll operator. This PR will provide support for the Roll operator.

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1228
