### ISSUE TITLE
python 版本是 3.9.13. pypi 上能看到 paddle2onnx = 1.0.9 为什么 pip 安装是提示最新的是 1.0.6 , pip 已经更新过了.

### ISSUE THREAD

**Issue by falling-ts** [PaddlePaddle/Paddle2ONNX#1158]
**问题描述**
python 版本是 3.9.13. pypi 上能看到 paddle2onnx = 1.0.9 为什么 pip 安装是提示最新的是 1.0.6 , pip 已经更新过了.

**报错截图**
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/41218920/9569b718-ecdc-4ff8-aff3-67d6d58f1632)
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/41218920/1c805bbb-b055-47c7-b360-a8303ef3eb6b)

**Comment by jiangjiajun** [comment]
Windows平台没有更新到最新。 有需要的话，可以自行参考这篇文档编译安装最新的代码https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md
