### ISSUE TITLE
Paddledetection 中的yolov5导出为onnx

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle2ONNX#1160]
球球了，大佬，导出v5为onnx的时候如何设置batch 为1 现在导出的模型要么在paddle2onnx=1.0.0版本下为-1 要么为p2o.DynamicDimension.0，怎么设置为1？

**Comment by jiangjiajun** [comment]
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"  使用这个命令来改
