### ISSUE TITLE
Picodet模型导出Onnx出错

### ISSUE THREAD

**Issue by ff-stone** [PaddlePaddle/Paddle2ONNX#1163]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
paddlex需用Picodet模型训练，导出inference_model文件夹（包含model.pdiparams，model.pdiparams.info，model.pdmodel，model.yml，pipeline.yml）
新建导出python文件：
from paddle2onnx import export
model = r'H:/paddlex_workspace/P0025-T0128_export_model/inference_model/inference_model/model.pdmodel'
params_file= r'H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdiparams'
save_file= r'H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\picodet.onnx'
# export the model to ONNX format
export(model, params_file, save_file)

请在此处详细的描述报错信息
运行后报如下错误：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: H:/paddlex_workspace/P0025-T0128_export_model/inference_model/inference_model/model.pdmodel
[Paddle2ONNX] Paramters file path: H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] LodTensorArray is not supported.
[ERROR] Due to the unsupported operators, the conversion is aborted.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,lod_array_length,select_input,tensor_array_to_tensor,while,write_to_array,

Process finished with exit code -1073740791 (0xC0000409)

**更多信息 :**
 - 用于部署的推理引擎:  rknn
 - 为什么需要转换为ONNX格式：转换为rknn
 - Paddle2ONNX版本: 
paddle2onnx               1.0.6                    pypi_0    pypi
paddlepaddle-gpu          2.2.2.post112            pypi_0    pypi
paddleslim                2.2.1                    pypi_0    pypi
paddlex                   2.1.0                    pypi_0    pypi
 - 你的联系方式(Email/Wechat/Phone):
ff-stone@163.com
**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
RKNN不支持NMS，需要你把Picodet的输出裁剪到NMS之前

**Comment by ff-stone** [comment]
我是 paddle2onnx 时出错，不是onnx转rknn时出错
![Uploading 屏幕截图 2024-03-05 135015.png…]()

**Comment by ff-stone** [comment]
(my_paddlex210_onnx) C:\Users\lenovo>paddle2onnx --model_dir H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model   --model_filename H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdmodel --params_filename H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdiparams  --save_file H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\picodet.onnx  --enable_dev_version True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdmodel
[Paddle2ONNX] Paramters file path: H:\paddlex_workspace\P0025-T0128_export_model\inference_model\inference_model\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] LodTensorArray is not supported.
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,lod_array_length,select_input,tensor_array_to_tensor,while,write_to_array,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by Zheng-Bicheng** [comment]
* 1 PaddleDetection导出模型时设置nms=true
* 2 固定Picodet模型的输入shape测试一下
* 3 详细查看[FastDeploy PaddleDetection RKNPU2模型转换教程](https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/rknpu2/README_CN.md)

**Comment by ff-stone** [comment]
您好！可是我是 paddle2onnx 时出错，不是onnx转rknn时出错










在 2024-02-29 11:58:34，"Zheng-Bicheng" ***@***.***> 写道：

RKNN不支持NMS，需要你把Picodet的输出裁剪到NMS之前

**Comment by Zheng-Bicheng** [comment]
> 您好！可是我是 paddle2onnx 时出错，不是onnx转rknn时出错 

这是很简单的道理：如果你的模型转换的终点是RKNN模型，那么在RKNN不支持NMS的情况下，你的ONNX模型即使带了NMS有什么意义呢？最简单的办法就是直接在Paddle模型层面裁剪掉NMS及其后面的算子，降低出错的概率。其次，我不明白你这边为什么有这么多不支持的算子，因为我之前测试过PaddleDetetcion2.5是可以直接导出的，即使带了NMS，是不是PaddleDetection版本太低了？

**Comment by ff-stone** [comment]
我不是用PaddleDetection中的Picodet，是PaddleX2.1.0  GUI  中用Picodet网络训练导出的模型，我想导出onnx后再裁剪










在 2024-03-05 14:04:04，"Zheng-Bicheng" ***@***.***> 写道：

您好！可是我是 paddle2onnx 时出错，不是onnx转rknn时出错

这是很简单的道理：如果你的模型转换的终点是RKNN模型，那么在RKNN不支持NMS的情况下，你的ONNX模型时即使带了NMS有什么意义呢？最简单的办法就是直接在Paddle模型层面裁剪掉NMS及其后面的算子，降低出错的概率。其次，我不明白你这边为什么有这么多不支持的算子，因为我之前测试过PaddleDetetcion2.5是可以直接导出的，即使带了NMS，是不是PaddleDetection版本太低了？

**Comment by Zheng-Bicheng** [comment]
那这个需要你问一下PaddleX那边为啥用旧版本的PaddleDetection了，现在Paddle2ONNX应该没有人力来适配旧版本的算子了。

**Comment by ff-stone** [comment]
好的，谢谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年03月05日 14:11 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle2ONNX] Picodet模型导出Onnx出错 (Issue #1163) |

那这个需要你问一下PaddleX那边为啥用旧版本的PaddleDetection了，现在Paddle2ONNX应该没有人力来适配旧版本的算子了。
