### ISSUE TITLE
导出onnx可以设置输入输出的名称吗？例如输入的名称为“input”，输出为“output”

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/Paddle2ONNX#1164]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
如下图，onnx的输入和输出名字修改，可以做到吗？

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/39027951/94a6179b-49f4-4a11-ae66-d67a77692486)

**其他信息**

**Comment by jiangjiajun** [comment]
不可以，但是你可以通过这个工具来修改onnx中模型输出名 https://github.com/jiangjiajun/PaddleUtils/tree/main/onnx

**Comment by Zheng-Bicheng** [comment]
可以使用[Paddle2ONNX的ONNX工具脚本](https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/onnx)来实现
