### ISSUE TITLE
需要将Paddle模型转换为onnx，报错：[ERROR] Cannot found attribute beta in op: swish

### ISSUE THREAD

**Issue by HW-WF** [PaddlePaddle/Paddle2ONNX#1167]
paddle2onnx               1.0.6                    
paddlepaddle              2.6.0

我使用的命令为：paddle2onnx --model_dir export_model --model_filename model.pdmodel --params_filename model.pdiparams --input_shape_dict "{'image':[1,3,640,640]}" --opset_version 11 --save_file ppyoloe_crn_s_80.onnx

以下是输出信息：
[WARNING] [Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle [0m
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: export_model\model.pdmodel
[Paddle2ONNX] Paramters file path: export_model\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish

请问大佬们这个如何解决

**Comment by jiangjiajun** [comment]
安装最新的Paddle，然后重新导出模型。然后再导出paddle2onnx

**Comment by JuliusQv** [comment]
同样的问题，

paddle2onnx           1.0.9
paddlepaddle-gpu      0.0.0.post112

已经是开发版的paddle了，还会碰到这个问题。
求大佬解答

**Comment by laugh12321** [comment]
Windows10
- paddlepaddle-gpu-2.6.0
- paddle2onnx 1.0.6

模型转onnx报错[ERROR] Cannot found attribute beta in op: swish

**解决办法：**
paddlepaddle-gpu 回退为2.5.2，重新导出模型，再转onnx正常。仅供参考

**Comment by HW-WF** [comment]
> Windows10
> - paddlepaddle-gpu-2.6.0
> - paddle2onnx 1.0.6
> 
> 模型转onnx报错[ERROR] Cannot found attribute beta in op: swish
> 
> **解决办法：**
> paddlepaddle-gpu 回退为2.5.2，重新导出模型，再转onnx正常。仅供参考
> 

次方法可行，非常感谢😆

**Comment by Zheng-Bicheng** [comment]
目前已经针对PaddlePaddle2.6修复了这个Bug（通过移除对beta参数的获取操作），考虑到部分用户可能仍然在使用paddlepaddle-2.5，后期会通过HasAttr("threshold")操作来添加对低版本Paddle的支持。

PR链接：

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1190

**Comment by m00nLi** [comment]
> 目前已经针对PaddlePaddle2.6修复了这个Bug（通过移除对beta参数的获取操作），考虑到部分用户可能仍然在使用paddlepaddle-2.5，后期会通过HasAttr("threshold")操作来添加对低版本Paddle的支持。
> 
> PR链接：
> 
> * [[Bug][CI] Fix the error caused by swish no longer having a beta parameter #1190](https://github.com/PaddlePaddle/Paddle2ONNX/pull/1190)


2.6修复， 2.7再引进？真的烦

**Comment by yuanzhibin** [comment]
Cannot found attribute threshold in op: relu6
有没有大佬遇到这个问题的

**Comment by Zheng-Bicheng** [comment]
> Cannot found attribute threshold in op: relu6 有没有大佬遇到这个问题的

已经修复这个问题了，从源码编译下哈，近期会做自动发包机制

**Comment by Zheng-Bicheng** [comment]
@yuanzhibin 可以看一下 [Paddle2ONNX 源码编译方式](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md)

**Comment by yuanzhibin** [comment]
好的好的 看起来有点子复杂 我研究一下 感谢指导

**Comment by yuanzhibin** [comment]
请问新版本的 Paddle2ONNX 支持prior_box算子的转换吗，谢谢大佬@Zheng-Bicheng

**Comment by Zheng-Bicheng** [comment]
> 请问新版本的 Paddle2ONNX 支持prior_box算子的转换吗，谢谢大佬@Zheng-Bicheng

这个具体要你这边尝试一下呢。如果确实不支持的话，请提一个Issues。我们计划在这次黑客松比赛，把一部分的算子放到上面让社区来帮忙完成。

**Comment by ksdyxx** [comment]
> Windows10
> 
> * paddlepaddle-gpu-2.6.0
> * paddle2onnx 1.0.6
> 
> 模型转onnx报错[ERROR] Cannot found attribute beta in op: swish
> 
> **解决办法：** paddlepaddle-gpu 回退为2.5.2，重新导出模型，再转onnx正常。仅供参考

thank you!

**Comment by unicasad** [comment]
将 paddlepaddle-gpu 回退为2.5.2，重新导出模型，还是报错；可能是什么原因，
Windows11
paddlepaddle-gpu-2.5.2
paddle2onnx 1.0.6

**Comment by Zheng-Bicheng** [comment]
> 将 paddlepaddle-gpu 回退为2.5.2，重新导出模型，还是报错；可能是什么原因， Windows11 paddlepaddle-gpu-2.5.2 paddle2onnx 1.0.6

切换到linux吧，linux的最新版本没有这个问题了。

**Comment by YiAnXS** [comment]
> > 将 paddlepaddle-gpu 回退为2.5.2，重新导出模型，还是报错；可能是什么原因， Windows11 paddlepaddle-gpu-2.5.2 paddle2onnx 1.0.6
> 
> 切换到linux吧，linux的最新版本没有这个问题了。

您好 我在paddlepaddle 2.6.1-gpu版本中发现还是有这个问题 如何解决呀

**Comment by Zheng-Bicheng** [comment]
> 您好 我在paddlepaddle 2.6.1-gpu版本中发现还是有这个问题 如何解决呀

Paddle2ONNX升级了吗？
```bash
pip uninstall paddle2onnx
pip install paddle2onnx
```
