### ISSUE TITLE
paddleSeg模型转换支持

### ISSUE THREAD

**Issue by Magsun** [PaddlePaddle/Paddle2ONNX#117]
您好，请问paddle图像分割模型目前是否支持paddle2onnx转换？

目前使用的模型是FAST_SCNN和DEEPLABV3+.

**Comment by jiangjiajun** [comment]
目前暂不支持

**Comment by InternetMaster1** [comment]
@jiangjiajun 

Any plans to support this in the near future? 

I am trying to run the humanseg_mobile model (based on HRNet) on PaddleLite.

I am [not getting any success](https://github.com/PaddlePaddle/PaddleSeg/issues/279). So I thought I will try to convert & run in tensorflow lite.

**Comment by jiangjiajun** [comment]
> @jiangjiajun
> 
> Any plans to support this in the near future?
> 
> I am trying to run the humanseg_mobile model (based on HRNet) on PaddleLite.
> 
> I am [not getting any success](https://github.com/PaddlePaddle/PaddleSeg/issues/279). So I thought I will try to convert & run in tensorflow lite.

Human Seg Mobile now is supported, please use x2paddle to convert your model to onnx https://github.com/PaddlePaddle/X2Paddle

**Comment by maingene** [comment]
> > @jiangjiajun
> > Any plans to support this in the near future?
> > I am trying to run the humanseg_mobile model (based on HRNet) on PaddleLite.
> > I am [not getting any success](https://github.com/PaddlePaddle/PaddleSeg/issues/279). So I thought I will try to convert & run in tensorflow lite.
> 
> Human Seg Mobile now is supported, please use x2paddle to convert your model to onnx https://github.com/PaddlePaddle/X2Paddle

X2Paddle tested not support convert humanseg_mobile to onnx yet

**Comment by jiangjiajun** [comment]
> > > @jiangjiajun
> > > Any plans to support this in the near future?
> > > I am trying to run the humanseg_mobile model (based on HRNet) on PaddleLite.
> > > I am [not getting any success](https://github.com/PaddlePaddle/PaddleSeg/issues/279). So I thought I will try to convert & run in tensorflow lite.
> > 
> > 
> > Human Seg Mobile now is supported, please use x2paddle to convert your model to onnx https://github.com/PaddlePaddle/X2Paddle
> 
> X2Paddle tested not support convert humanseg_mobile to onnx yet

Humanseg mobile is supported converting to onnx with opset version 11.

```
pip install paddle2onnx==0.3.2
paddle2onnx --model humanseg_mobile_infer --save_dir onnx_model --opset 11
```
