### ISSUE TITLE
paddle2onnx转化相关问题

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/Paddle2ONNX#1172]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**
我这几天使用paddle2onnx，想把自己使用paddlepaddle框架训练的模型转成onnx模型并调用，但是有的算子不支持，有的转换成功了也不知道怎么搭建网络并调用，有自己训练模型转换成onnx模型并推理的教程吗。感觉支持的框架不多
**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：使用了多个框架来训练模型，想把几个框架的模型都转成onnx格式的模型并推理
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
能具体一点吗？具体哪个算子碰到问题了呢？
