### ISSUE TITLE
paddle2onnx 新版本 --input_shape_dict 参数提示信息

### ISSUE THREAD

**Issue by weirman** [PaddlePaddle/Paddle2ONNX#1173]
使用1.x.x版本paddle2onnx时，--input_shape_dict 字段以及被弃用，但是会提示转到

```
2024-01-22 23:21:54 [WARNING]	[Deprecated] The flag `--input_shape_dict` is deprecated, if you need to modify the input shape of PaddlePaddle model, please refer to this tool https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle
```

官方提供了解决方案，所以这个log输出应该需要更改一下。
```
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"
```

**Comment by HawkingRadiation42** [comment]
facing the same issue, has anyone here solved it?

**Comment by weirman** [comment]
You can find the solution [here](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/README_en.md). 
```bash
python -m paddle2onnx.optimize --input_model model.onnx \
                                --output_model new_model.onnx \
                                --input_shape_dict "{'x':[1,3,224,224]}"
```

**Comment by HawkingRadiation42** [comment]
#1183
can you look into this as well? did you face this error? and if not then what versions are you using right now

**Comment by weirman** [comment]
We are not experiencing the same problem, you can try upgrading paddle2onnx.
It looks like paddle2onnx doesn't support deformable_conv.

**Comment by HawkingRadiation42** [comment]
yeah tried that as well, thank you

**Comment by Zheng-Bicheng** [comment]
已经移除了这个无用提示:

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1200
