### ISSUE TITLE
No module named 'paddle2onnx.paddle2onnx_cpp2py_export'

### ISSUE THREAD

**Issue by ilbash** [PaddlePaddle/Paddle2ONNX#1174]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**
While compiling paddle2onnx, I cannot run it. How to solve it ?

```bash
# cmake installation
wget https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-Linux-x86_64.sh && \
chmod +x cmake-3.28.1-Linux-x86_64.sh && \
./cmake-3.28.1-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license && \
rm ./cmake-3.28.1-Linux-x86_64.sh && \
sudo ln -s /usr/local/bin/cmake /usr/bin/cmake

# protobuf installation
git clone https://github.com/protocolbuffers/protobuf.git
cd protobuf
git checkout v3.16.0
git submodule update --init --recursive
./autogen.sh
./configure
make -j$(nproc)
make check
make install
ldconfig

# paddle2onnx installation
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
git submodule init
git submodule update
python setup.py install
```

**Comment by jiangjiajun** [comment]
It will throw this error, if there's a directory or file named 'paddle2onnx' in your current directory

**Comment by Zheng-Bicheng** [comment]
Hey @Ilyabasharov, I'm sorry for the delayed response. We've updated the English version of the [Paddle2ONNX compilation documentation](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/en/compile_local.md). I hope this helps you (although you might not need Paddle2ONNX anymore).
