### ISSUE TITLE
您好导出onnx,有没有办法导出旧的算子

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/Paddle2ONNX#1176]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58769772/25f42c56-cfff-4ddf-b85f-c10b156f7553)
像这种旧的方式导出，有什么办法是可以的嘛谢谢

**Comment by Zheng-Bicheng** [comment]
能具体一点吗？什么叫旧的算子

**Comment by chen-del** [comment]
@Zheng-Bicheng   类似于这样，logit_list = [
                F.interpolate(
                    x, x_hw, mode='nearest')，转化onnx的算子的时候，能否导出opst=v9系列的算子，比如Upsample; 而不是使用opst=12导出resize，我看版本已经迭代很新了，最低支持都到了opst=12，转化不出来。

**Comment by Zheng-Bicheng** [comment]
这个是有什么需求吗？我看了下Paddle研发同学的代码实现，针对你给的这个Paddle OP，默认就是直接使用opset 11支持的。

**Comment by Zheng-Bicheng** [comment]
代码逻辑可以看一下: [interpolate.cc](https://github.com/PaddlePaddle/Paddle2ONNX/blob/0386ba5ab8ec5f44ac1acc0e43a8c6c286e6b5dd/paddle2onnx/mapper/nn/interpolate.cc#L117C3-L124C4)

**Comment by chen-del** [comment]
@Zheng-Bicheng ，看了逻辑里面是使用的resize方式作为onnx算子，我想知道的是，有没有办法导出的时候是Upsample,上采样的算子
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58769772/de967fa2-bbb4-4807-9fb5-f554f380aebe)，他的版本追溯大概是这个
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/58769772/f7b0a06d-888c-4a6f-8935-0d0901d2faf5)
我想导出10之前的版本也就是paddle2onnx --model_dir ${SVAE_DIR} \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --opset_version 9 \
            --save_file ${SVAE_DIR}/${NAME}，这样子出来上面的那个算子nearest属性

**Comment by Zheng-Bicheng** [comment]
你方便把PaddleInference模型打包提供一下吗？

**Comment by chen-del** [comment]
@Zheng-Bicheng ，可以的方便下面就是打包的
[weights.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/14415042/weights.zip)

**Comment by Zheng-Bicheng** [comment]
@chen-del 你的onnxruntime版本用的是多少呀，我这边看Upsample这个算子已经在最新的onnxruntime里面被废弃了，为什么会需要这个算子呢？

**Comment by Zheng-Bicheng** [comment]
其次我在CI中测试了一下这个算子，Paddle的Upsample和interpolate应该对应的都是现在ONNX的Resize，只有极少数的案例可以被导出为Upsample，因此目前的实现应该是没有问题的。

**Comment by chen-del** [comment]
@Zheng-Bicheng ，部署的时候要用到，在nvidia的设备上，因为版本原因里面的tensorrt都是0.6，cuda用的是10.0,所支持的onnx算子变为了Upsample才可以被使用

**Comment by Zheng-Bicheng** [comment]
nvidia设备的cuda版本没办法升级吗？这个有点尴尬，因为如果我给你适配了这个Upsample，我的单测是会挂的

**Comment by Zheng-Bicheng** [comment]
其次，你有试过低版本的P2O吗？我的理解上低版本的P2O应该是能够解决这个问题的？

**Comment by chen-del** [comment]
试过但是没有成功，导出失败我好像看到介绍说最低支持到opst=9，但是大部分情况都是说要11才可以

**Comment by Zheng-Bicheng** [comment]
这个估计需要你升级设备了，因为没办法做兼容性的修改

**Comment by chen-del** [comment]
@Zheng-Bicheng ，谢谢，我只是看看paddle有没有适配这个，看样子很麻烦不太好转出，我这边直接采用torch了，torch可以这样可以导出，板子内核是改了的，不然我就升级了，谢谢。
