### ISSUE TITLE
bash: paddle2onnx: command not found => How to fix it?

### ISSUE THREAD

**Issue by PeterKim1** [PaddlePaddle/Paddle2ONNX#1182]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

First, install paddle2onnx.

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/57930520/b073508c-9864-4ab0-8483-fd7cd81bc12a)

After that, I try to use paddle2onnx, then command not found error occur.

How can I fix it?

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/57930520/95fe793d-1a8a-410e-bdb3-f96bafb63ae7)

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：Need to convert TensorRT.
 - Paddle2ONNX Version: 1.1.0
 - Email/Wechat/Phone:

**Screenshots**

**Additional context**

**Comment by GreatV** [comment]
Hi @PeterKim1, please check if paddle2onnx is in your environment variables, it is recommended to use paddle2onnx in a virtual environment.

**Comment by jzhang533** [comment]
as a workaround, please try: `python -mpaddle2onnx.command`, paddle2onnx command is kind of shortcut for this module. 

BTW: I am confused by the versioning of this package, we have package with version greater than 1.0.7 on pip, see: https://pypi.org/project/paddle2onnx/#history, but the latest tag in the code repository is 1.0.7, anyone knows the reason?
