### ISSUE TITLE
onnx转rknn报错

### ISSUE THREAD

**Issue by Nankee-Lee** [PaddlePaddle/Paddle2ONNX#1186]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
系统平台：linux x64 Ubuntu 18.04
onnxruntime：1.10.0
一开始用的rknn的工具是rknn_toolkit2-1.5.0+1fa95b5cl报错如下图1
后来换了rknn_toolkit2-1.6.1b0+9379f5f7，报错如下图2

**更多信息 :**
我的联系方式是505582357@qq.com，期待您的来信，谢谢！

**报错截图**
![J%9S6%W}1~$L_LVQW Z6M8](https://github.com/PaddlePaddle/Paddle2ONNX/assets/143511511/f8a0994a-d2a3-40ee-956d-d41902d4312d)
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/143511511/c3b7c900-11ec-4486-bec1-df0a2d8ef681)

**其他信息**

**Comment by Zheng-Bicheng** [comment]
具体是哪一个模型呢？

**Comment by Nankee-Lee** [comment]
paddleOCR



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 中午1:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle2ONNX] onnx转rknn报错 (Issue #1186)




 
具体是哪一个模型呢？

**Comment by Zheng-Bicheng** [comment]
更新到最新的 rknn-toolkit2
