### ISSUE TITLE
fluid_params_name 问题

### ISSUE THREAD

**Issue by komejisatori** [PaddlePaddle/Paddle2ONNX#119]
在使用paddle2onnx时，导出模型只包含__model__和__params__，于是我指定
`--fluid_params_name $PATH_TO_MODELDIR$/__params__`
但仍会提示
`Cannot open file $PATH_TO_MODELDIR$/conv6_depthwise_bn_offset for load op at (/paddle/paddle/fluid/operators/load_op.h:38)
`

**Comment by JerryDeepl** [comment]
> 在使用paddle2onnx时，导出模型只包含__model__和__params__，于是我指定
> `--fluid_params_name $PATH_TO_MODELDIR$/__params__`
> 但仍会提示
> `Cannot open file $PATH_TO_MODELDIR$/conv6_depthwise_bn_offset for load op at (/paddle/paddle/fluid/operators/load_op.h:38) `
碰过类似问题，指定格式应该是这样子的
     --fluid_model_name __model__  --fluid_params_name __params__

**Comment by komejisatori** [comment]
@JerryDeepl 感谢！
