### ISSUE TITLE
导出后的onnx模型依然存在动态维度的问题

### ISSUE THREAD

**Issue by AntyRia** [PaddlePaddle/Paddle2ONNX#1195]
操作的模型：
[https://aistudio.baidu.com/modelsdetail/10/intro](url)
按照以下代码进行导出：
`paddle2onnx --model_dir picodet_v2_s_320_pedestrian/ --model_filename model.pdmodel --params_filename model.pdiparams --save_file picodet_v2_s_320_pedestrian.onnx --opset_version 12 --enable_onnx_checker True`
`python -m paddle2onnx.optimize --input_model picodet_v2_s_320_pedestrian.onnx --output_model picodet_v2_s_320_pedestrian_static.onnx --input_shape_dict "{'image':[1,3,320,320]}"`
此时从模型角度来看输入的确变成了静态图：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/75578545/fc30f5f0-daa2-4d06-9e60-07f66ed9f6e7)
但是在转为rknn模型时：
这一层报错，说这一层存在动态维度：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/75578545/f8140fb0-ceb2-45e7-b4b8-d16153034116)
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/75578545/c4e91e67-db1d-41c1-bdeb-0a26b639bfc0)
针对错误文档的说法和报错信息，想问问可能的原因以及解决办法
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/75578545/5123b688-b82a-4140-8834-6aebeb8d8723)

**Comment by AntyRia** [comment]
补充说明，上述操作都是在linux x86容器进行的

**Comment by Zheng-Bicheng** [comment]
NMS操作在RK平台上是支持的吗，据我了解应该是不支持这个算子，建议将模型裁剪到NMS的两个输入OP？

**Comment by AntyRia** [comment]
感谢回复！
