### ISSUE TITLE
ch_ppstructure_mobile_v2.0_SLANet表格识别模型转rknn模型报错

### ISSUE THREAD

**Issue by cty-ai** [PaddlePaddle/Paddle2ONNX#1205]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
模型：ch_ppstructure_mobile_v2.0_SLANet
**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：硬件是rk3588
 - Paddle2ONNX Version:1.1.0
 - Email/Wechat/Phone:c-t-y@qq.com

**Screenshots**
![LR5)SJ_7@@C($WCAA6_ _5E](https://github.com/PaddlePaddle/Paddle2ONNX/assets/55014745/380162cf-c926-4277-b80a-371596b3c6a7)

**Additional context**
rknn_toolkit2-1.5.3b21+11d8562a-cp38-cp38-linux_x86_64.whl
rknn_toolkit2-1.6.0+81f21f4d-cp38-cp38-linux_x86_64.whl
rknn_toolkit2-1.6.1b16+e3c0774a-cp38-cp38-linux_x86_64.whl
rknn_toolkit2-1.6.2b3+eeda9fd5-cp38-cp38-linux_x86_64.whl
这几个toolkit都试过报一样的错误，转onnx没报错，再转rknn报错如截图

**Comment by Zheng-Bicheng** [comment]
这个已经很明显了呀，你需要固定一下Shape再进行转换，RKNN只支持固定的shape,这和Paddle2ONNX无关。
