### ISSUE TITLE
An error while attempting to convert a PaddlePaddle model to ONNX format

### ISSUE THREAD

**Issue by PattaWapee** [PaddlePaddle/Paddle2ONNX#1206]
I encountered an error while attempting to convert a PaddlePaddle model to ONNX format using paddle2onnx. Below are the details of the error. I run the following command line 
>> paddle2onnx --model_dir ./models/v1/infer_weights --model_filename inference.pdmodel --params_filename inference.pdiparams --export_fp16_model True --save_file models/v1/model.onnx --opset_version 15 --enable_onnx_checker True >/dev/null

and I got this error 

>>[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./models/v1/infer_weights/inference.pdmodel
[Paddle2ONNX] Paramters file path: ./models/v1/infer_weights/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Cannot found attribute beta in op: swish
Aborted (core dumped)

My environment
Python 3.8.10
paddle2onnx==1.1.0
paddleocr==2.7.0.3
paddlepaddle==2.6.0
paddlepaddle-gpu==2.6.0
Please let me know how to solve this.

**Comment by 89080322** [comment]
同样的问题

**Comment by Zheng-Bicheng** [comment]
@89080322 @PattaWapee Please recompile Paddle2ONNX from the source code

**Comment by Zheng-Bicheng** [comment]
[Github source installation method](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md)
