### ISSUE TITLE
Cannot found attribute threshold in op: relu6

### ISSUE THREAD

**Issue by xaclincoln** [PaddlePaddle/Paddle2ONNX#1208]
**Describe the bug**
将PLSC的人脸识别模型导出为ONNX格式，报错Cannot found attribute threshold in op: relu6

**Informations (please complete the following information):**
 - Inference engine for deployment: openvino
 - Why convert to onnx：use openvino for inference
 - Paddle2ONNX Version: 1.0.6 
 - PaddlePaddle version: 2.6.0, CUDA 11.8

**Comment by Jiang-Jia-Jun** [comment]
降低Paddle版本到2.3.2，再重新导出模型试下。 

@Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

**Comment by Zheng-Bicheng** [comment]
> 降低Paddle版本到2.3.2，再重新导出模型试下。
> 
> @Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

Get

**Comment by wangkd0** [comment]
降低版本可以解决吗

**Comment by Zheng-Bicheng** [comment]
两位(@wangkd0 @xaclincoln )好，其实现在develop分支已经修复了这个问题:

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1189

但是现在P2O的发包机制还在搭建中，方便自行编译安装一下P2O吗？

**Comment by LijialinHub** [comment]
> 降低Paddle版本到2.3.2，再重新导出模型试下。
> 
> @Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

我降低到您说的版本了 还是没用

**Comment by Zheng-Bicheng** [comment]
> > 降低Paddle版本到2.3.2，再重新导出模型试下。
> > @Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？
> 
> 我降低到您说的版本了 还是没用

Hello 最新的 Paddle2ONNX 已经修复这个问题了，安装 v1.2.10 使用哈

**Comment by LijialinHub** [comment]
主要是 PIP 的方式下载的并不是最新的，我用源码编译又频频保存，大佬From iPhone 在 2024年10月22日，17:30，Zheng-Bicheng ***@***.***> 写道：﻿


降低Paddle版本到2.3.2，再重新导出模型试下。
@Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

我降低到您说的版本了 还是没用

Hello 最新的 Paddle2ONNX 已经修复这个问题了，安装 v1.2.10 使用哈

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1189
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1198

**Comment by Zheng-Bicheng** [comment]
> 主要是 PIP 的方式下载的并不是最新的，我用源码编译又频频保存

目前 Paddle2ONNX 支持的是 Linux，Mac/Windows 需要自行编译

**Comment by LijialinHub** [comment]
我看见了您的 csdn 博客 上边有改代码解决的方式，但是我不知道改哪里，请明示From iPhone 在 2024年10月22日，17:30，Zheng-Bicheng ***@***.***> 写道：﻿


降低Paddle版本到2.3.2，再重新导出模型试下。
@Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

我降低到您说的版本了 还是没用

Hello 最新的 Paddle2ONNX 已经修复这个问题了，安装 v1.2.10 使用哈

**Comment by Zheng-Bicheng** [comment]
> 我看见了您的 csdn 博客 上边有改代码解决的方式，但是我不知道改哪里

已经修改合入到主仓库里了，不需要你修改了，直接 git clone Paddle2ONNX 编译就好了。

**Comment by LijialinHub** [comment]
请问您可以提供一个 whl 嘛 windows 版本的 ，我讲感激不尽☺️From iPhone 在 2024年10月22日，17:30，Zheng-Bicheng ***@***.***> 写道：﻿


降低Paddle版本到2.3.2，再重新导出模型试下。
@Zheng-Bicheng 这个我们是否可以更新下Relu算子，增加对threshold不存在的兼容呢？

我降低到您说的版本了 还是没用

Hello 最新的 Paddle2ONNX 已经修复这个问题了，安装 v1.2.10 使用哈
