### ISSUE TITLE
模型转换出错

### ISSUE THREAD

**Issue by lgcy** [PaddlePaddle/Paddle2ONNX#122]
tensor version 1904018048 in not supported, only version 0 is supported

**Comment by zky001** [comment]
I also meet this error

**Comment by Channingss** [comment]
@zky001 which framework to Paddle?

**Comment by Channingss** [comment]
@zky001 now we migrate paddle2onnx to https://github.com/PaddlePaddle/X2Paddle，you can try x2paddle.

**Comment by trikim** [comment]
@lgcy Have you solved this problem?
