### ISSUE TITLE
[Discussion] 迁移Paddle2ONNX构建方式到Python 新规范(pyproject.toml)

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle2ONNX#1220]
简介
由Paddle2ONNX PMC讨论，Paddle2ONNX将要将项目构建方式从目前的使用 setup.py + requirement.txt的方式转向使用 setup.py + pyproject.toml的方式。

实施过程
由于Paddle2ONNX使用了pybind实现c++代码在python上的调用，因此计划使用pybind给出的例程作为Demo来实现这个过程，PMC的各位成员如果有建议可以畅所欲言。

**Comment by Zheng-Bicheng** [comment]
@Zheng-Bicheng @Jiang-Jia-Jun @Aurelius84 @GreatV

**Comment by GreatV** [comment]
使用 `pyproject.toml` 是不是不需要`setup.py`了

**Comment by Zheng-Bicheng** [comment]
> 使用 `pyproject.toml` 应该不需要`setup.py`了

这个我判断下来是这样的，对于普通工程来说， `pyproject.toml`就足够了。但是对于Paddle2ONNX来说`setup.py`这个脚本会用于CMake编译，目前没找到能在`pyproject.toml`中执行类似操作的办法。可以参考下[cmake_example](https://github.com/pybind/cmake_example)

**Comment by Zheng-Bicheng** [comment]
考虑到[Python 3.11最新标准](https://docs.python.org/zh-cn/3.11/whatsnew/3.11.html)中已经废弃了[整个 distutils 包](https://docs.python.org/zh-cn/3.11/whatsnew/3.10.html#distutils-deprecated)，setup.py需要进行重新的改写。

**Comment by Jiang-Jia-Jun** [comment]
可以参考下 https://github.com/onnx/onnx ， 我看里面也已经有pyproject.toml了

**Comment by jzhang533** [comment]
> 使用 `pyproject.toml` 是不是不需要`setup.py`了

可能还是必要的。只是，不要再直接在命令行调用 setup.py 就可以了。
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

**Comment by Zheng-Bicheng** [comment]
已经基本实现该需求，见:

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1221
