### ISSUE TITLE
paddle模型本来是不固定输入输出的，但是使用Paddle2ONNX转换必须指定input_size,不然会报Due to the operator: pool2d, this model cannot be exported to ONNX错

### ISSUE THREAD

**Issue by wangkd0** [PaddlePaddle/Paddle2ONNX#1229]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
paddle模型本来是不固定输入输出的，但是使用Paddle2ONNX转换必须指定input_size,不然会报Due to the operator: pool2d, this model cannot be exported to ONNX错误

python tools/export.py --config configs/quick_start/ppmattingv2-stdc1-human_512.yml --model_path pretrained_models/ppmattingv2-stdc1-human_512.pdparams --save_dir output/inference_model_end
使用上面这个命令不指定input_size, 导出时就会报错，我不想指定size需要怎么处理

模型使用的ppmattingv2-stdc1-human_512.yml

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - 使用onnxruntime运行
 - 
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
这个需要固定一下输入shape哈

**Comment by Zheng-Bicheng** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle

**Comment by zhanglaplace** [comment]
> https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle

你们paddle能搞的在复杂点吗？本来一个paddleSeg的项目，需要安装paddle，转化模型用paddle2onnx,出了问题也不能再paddl2onnx的使用doc看到，非得查issue,这么难吗？

**Comment by Zheng-Bicheng** [comment]
> > https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle
> 
> 你们paddle能搞的在复杂点吗？本来一个paddleSeg的项目，需要安装paddle，转化模型用paddle2onnx,出了问题也不能再paddl2onnx的使用doc看到，非得查issue,这么难吗？

第一，我不是Paddle的工程师，只是普通开发者，不要对着我diss paddle，没有意义。第二，用开源的东西，你觉得不好可以自己提PR修正，diss改变不了什么。

**Comment by zhanglaplace** [comment]
> > > https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle
> > 
> > 
> > 你们paddle能搞的在复杂点吗？本来一个paddleSeg的项目，需要安装paddle，转化模型用paddle2onnx,出了问题也不能再paddl2onnx的使用doc看到，非得查issue,这么难吗？
> 
> 第一，我不是Paddle的工程师，只是普通开发者，不要对着我diss paddle，没有意义。第二，用开源的东西，你觉得不好可以自己提PR修正，diss改变不了什么。

sorry, 单纯吐槽，主要只是为了调研体验，其他的模型都还挺顺利的，这边就各种doc文档和版本的不一致，再次抱歉；

**Comment by surprise335** [comment]
> 这个需要固定一下输入shape哈

我想问一下现在paddle2onnx已经不支持固定字段了 --input_shape_dict="{'x':[-1,3,-1,-1]}" 是版本问题吗

**Comment by Zheng-Bicheng** [comment]
> > 这个需要固定一下输入shape哈
> 
> 我想问一下现在paddle2onnx已经不支持固定字段了 --input_shape_dict="{'x':[-1,3,-1,-1]}" 是版本问题吗

是的，移除这个东西了。
