### ISSUE TITLE
paddle2onnx 在尝试将 PaddlePaddle 模型转换为 ONNX 格式时遇到了不支持的算子（operators）：distribute_fpn_proposals 和 generate_proposals_v2。由于这些算子在 ONNX 规范中没有直接的等价实现或者paddle2onnx转换工具中尚未实现对这些算子的支持，转换过程被中止了

### ISSUE THREAD

**Issue by jinjin4318** [PaddlePaddle/Paddle2ONNX#1230]
paddle2onnx 在尝试将 PaddlePaddle 模型转换为 ONNX 格式时遇到了不支持的算子（operators）：distribute_fpn_proposals 和 generate_proposals_v2。由于这些算子在 ONNX 规范中没有直接的等价实现或者paddle2onnx转换工具中尚未实现对这些算子的支持，转换过程被中止了

(Detection) E:\PaddleDetection>paddle2onnx --model_dir=output/output1/inference_model/jjs_rcnn --model_filename=model.pdmodel  --params_filename=model.pdiparams --opset_version=16  --save_file=jjs_rcnn.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: output/output1/inference_model/jjs_rcnn\model.pdmodel
[Paddle2ONNX] Paramters file path: output/output1/inference_model/jjs_rcnn\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.

-用于部署的推理引擎：PaddlePaddle
-为什么转换为onnx：
-Paddle2ONNX版本：1.0.6

![屏幕截图 2024-04-19 190949](https://github.com/PaddlePaddle/Paddle2ONNX/assets/166143077/de00f08d-358c-4dc2-a0ae-0726b76d3362)

**Comment by Jiang-Jia-Jun** [comment]
maskrcnn不支持
