### ISSUE TITLE
Matting模型转换为ONNX时报错 [pool2d: pool2d_10.tmp_0] While Attribute(ksize)'s type is Tensor, it's not supported. 

### ISSUE THREAD

**Issue by gunh4mmer** [PaddlePaddle/Paddle2ONNX#1231]
版本：paddle2onnx -1.2.1
模型：paddleseg中Matting中的ppmattingv2模型
具体报错信息如下图：
![Dingtalk_20240422113727](https://github.com/PaddlePaddle/Paddle2ONNX/assets/73456895/fd73e32f-da3f-4103-8584-f54fe077947a)

流程：对训练模型首先使用export.py转为预测模型，然后使用infer_paddle_model_shape.py对预测模型进行固定输入，如上图，固定为:[-1,3,1374,918]，最后对固定输入后的模型进行paddle2onnx，最后一步的文件夹文件列表如下
![Dingtalk_20240422114025](https://github.com/PaddlePaddle/Paddle2ONNX/assets/73456895/78646742-2740-421e-be15-e6a8c70ed488)

奇怪的是固定输入后模型在netron查看时显示没有输出（固定前查看输入输出均为动态），如下图
![Dingtalk_20240422132225](https://github.com/PaddlePaddle/Paddle2ONNX/assets/73456895/e4962af7-1e3d-4b45-a5b2-afda30a7e107)

请问是Matting的模型仍未支持转换为ONNX，还是以上操作流程存在问题

**Comment by Zheng-Bicheng** [comment]
能把Paddle模型上传一下嘛？我这边看一下

**Comment by gunh4mmer** [comment]
> 能把Paddle模型上传一下嘛？我香料看一下

问题已经解决，我在 [https://github.com/PaddlePaddle/PaddleSeg/issues/3688](url)中发现，export.py已经支持固定模型的输入大小，而我之前使用的是paddle2onnx中裁剪工具中的infer_paddle_model_shape.py，也许该工具目前存在一定的适配问题？因为我之前使用该工具对其他的seg模型进行固定时并没有出现问题，对于上面issue中提到的onnx模型存在精度问题还没有进行验证
