### ISSUE TITLE
【开源之夏】飞桨PaddlePaddle-PIR适配Paddle2ONNX推理转换

### ISSUE THREAD

**Issue by 0x45f** [PaddlePaddle/Paddle2ONNX#1233]
# 项目描述
ONNX是一种开放的深度学习模型交换格式，可让模型在不同平台和框架间无缝转换与部署，Paddle2ONNX开源仓库支持将飞桨的推理模型表示转换到ONNX算子协议以实现对接ONNX生态。飞桨在3.0Beta发布了新一代的中间表示（即Paddle IR），并升级了所有的算子定义形式，取代了2.x版本基于protobuf的中间表示。因此我们期望能够基于飞桨新一代Paddle IR的算子定义，升级Paddle2ONNX中的转换规则，支持Paddle IR 协议下的ONNX模型转换。

飞桨PaddlePaddle：以百度多年的深度学习技术研究和业务应用为基础，是中国首个自主研发、功能完备、开源开放的产业级深度学习平台，集深度学习核心训练和推理框架、基础模型库、端到端开发套件和丰富的工具组件于一体。

如果有任何疑问，可发邮件给导师同时抄送 ext_paddle_oss@baidu.com 。

# 项目产出要求
1. 研读Paddle2ONNX源码，给出Paddle新一代IR下算子到ONNX转换的技术思路 
2. 完成20个典型算子，和2个控制流算子（if和while）的2ONNX转换支持 
3. 代码合入 https://github.com/PaddlePaddle/paddle2ONNX

# 项目技术要求
熟悉 C++ 2. 熟悉 Python

# 项目成果仓库
https://github.com/PaddlePaddle/paddle2ONNX

# 参考文档
- [Paddle2ONNX 开发指南](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/Paddle2ONNX_Development_Guide.md)
- [PIR设计指南](https://github.com/PaddlePaddle/community/blob/master/pfcc/paddle-code-reading/IR_Dialect/README.md)
- PIR下save后的program的文件可以执行Paddle仓库中的test/ir/pir/test_ir_save_load.py单测后查看test_save_program2.json文件

**Comment by qzylalala** [comment]
你好，这个项目目前已经还可以申请吗

**Comment by luotao1** [comment]
@qzylalala 可以报名，请到 https://summer-ospp.ac.cn/ 开源之夏官网入口报名
