### ISSUE TITLE
[Discussion] 请求提供 Paddle2ONNX 开发者培训计划

### ISSUE THREAD

**Issue by marlin688** [PaddlePaddle/Paddle2ONNX#1234]
**问题描述**
最近我对 Paddle2ONNX 项目产生了浓厚的兴趣，并希望能够贡献我的力量。然而，我发现我对于如何添加新的操作（OP）以及整个开发流程并不了解。

鉴于此，我想提出一个请求，希望社区能够组织一次线上培训活动，涵盖从 OP 添加流程到整个开发流程的内容。这样的培训计划将帮助像我这样的新手开发者更好地融入 Paddle2ONNX 的开发团队，并且促进项目的成长和发展。

培训内容建议：

OP 添加流程： 详细介绍如何在 Paddle2ONNX 中添加新的操作，包括必要的步骤、文件结构以及相关的文档要求。
开发环境设置： 提供设置开发环境所需的必要工具和依赖项，以及如何构建和测试代码的说明。
代码贡献流程： 解释代码贡献的基本流程，包括如何提交 Pull Request、代码审查流程等。

我相信通过这样的培训计划，不仅能够吸引更多的开发者加入 Paddle2ONNX 的开发团队，也将为项目的发展注入新的活力和动力。感谢您的关注和支持！

**Comment by Zheng-Bicheng** [comment]
大佬我明天给你整理一份文档

**Comment by Zheng-Bicheng** [comment]
@chris-magic @jzhang533 两位大佬看看 [Paddle2ONNX_Development_Guide](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/Paddle2ONNX_Development_Guide.md) 能不能满足两位的需求？

**Comment by Zheng-Bicheng** [comment]
我已经重构了一下开发文档

**Comment by marlin688** [comment]
高效，我们先看下

**Comment by marlin688** [comment]
非常详细，还有个问题想请教下，我们现在在paddle2onnx时候，还有一些op是paddle.fluid下面的，这个我们有什么建议吗

**Comment by Zheng-Bicheng** [comment]
> 非常详细，还有个问题想请教下，我们现在在paddle2onnx时候，还有一些op是paddle.fluid下面的，这个我们有什么建议吗

指的是控制流相关的op嘛？具体是哪些呢？一般也都是通过多个已有的ONNX OP构造一个Paddle OP的方式实现。

**Comment by marlin688** [comment]
控制流的已经在让算法在改了，
[Paddle2ONNX] Oops, there are some operators not supported yet, including gru,im2sequence,  我们最近在加的是这两个op，但在写im2sequence 单测的时候卡住了。

**Comment by Zheng-Bicheng** [comment]
> 控制流的已经在让算法在改了， [Paddle2ONNX] Oops, there are some operators not supported yet, including gru,im2sequence, 我们最近在加的是这两个op，但在写im2sequence 单测的时候卡住了。

大佬，我添加了哈，您的私人信息我帮您删除掉了，怕你收到骚扰信息。
