### ISSUE TITLE
转换paddlespeech的KWS部署模型出现了问题

### ISSUE THREAD

**Issue by lingyuwangwang** [PaddlePaddle/Paddle2ONNX#1236]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
你好，我在转换paddlespeech的KWS模型出现了问题。我已经事先转换了.pdparsms文件为.pdparsms和.pdmodel文件
报错信息如下：
Oops, there are some operators not supported yet, including conditional_block,lod_array_length,while,write_to_array,

**更多信息 :**
 - 用于部署的推理引擎: 语音唤醒模型KWS
 - Paddle2ONNX版本:#  paddle2onnx 版本：1.2.0 
 - 你的联系方式(Email/Wechat/Phone): wanglingyu1114@gmail.com

**报错截图**
![325143670-a2b266b3-08d2-41eb-a2a6-650778f31a3f](https://github.com/PaddlePaddle/Paddle2ONNX/assets/145318741/13f4bec5-5a5d-4f55-8404-401c33cdc86d)

**其他信息**

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324

**Comment by eli-zheng-ubtech** [comment]
.pdparsms文件转为.pdparsms和.pdmodel文件，你是怎么转的？我转了会失败
![image](https://github.com/user-attachments/assets/aa790a24-943c-449b-aa62-d22923717e8e)

**Comment by Zheng-Bicheng** [comment]
暂时不支持这几种控制流
