### ISSUE TITLE
无法通过pip install paddle2onnx安装，同时也无法通过编译安装

### ISSUE THREAD

**Issue by XianlinYao** [PaddlePaddle/Paddle2ONNX#1237]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
使用官方提供的所有方式均无法安装paddle2onnx

**Environment**
Win11 23H2
python 3.11.7 & 3.12.3

**Screenshots**
![34f84f7c5481501d13e313e10d1499d](https://github.com/PaddlePaddle/Paddle2ONNX/assets/55677914/71bea2ed-7a38-4b73-b88c-cf39491e8f20)
![55cf5c6683a46f5d9e516518b656aff](https://github.com/PaddlePaddle/Paddle2ONNX/assets/55677914/ca40a056-2b07-4aeb-aee3-eab0f2299a55)
第一张是通过pip安装，第二张是通过编译安装

**Additional context**

**Comment by Zheng-Bicheng** [comment]
看报错是Python环境缺少包了，先执行以下代码，再编译试试？

```
pip install setuptools wheel auditwheel auditwheel-symbols build
```

**Comment by XianlinYao** [comment]
> 看报错是Python环境缺少包了，先执行以下代码，再编译试试？
> 
> ```
> pip install setuptools wheel auditwheel auditwheel-symbols build
> ```

安装了这个包再使用VS去编译吗

**Comment by Zheng-Bicheng** [comment]
> 安装了这个包再使用VS去编译吗

@XianlinYao 是的

**Comment by XianlinYao** [comment]
> > 安装了这个包再使用VS去编译吗
> 
> @XianlinYao 是的

还是一样的问题
![屏幕截图 2024-04-25 184916](https://github.com/PaddlePaddle/Paddle2ONNX/assets/55677914/e4f70ee6-5b58-477a-a482-0e497224d073)

**Comment by gutenye** [comment]
通过python 3.8安装pip install paddle2onnx 成功

**Comment by XianlinYao** [comment]
> 通过python 3.8安装pip install paddle2onnx 成功

3.8是没问题，就是很奇怪为什么照着教程没法在3.11，3.12安装
