### ISSUE TITLE
paddleseg模型和onnx模型的推理结果不一致，精度差距较大

### ISSUE THREAD

**Issue by LS1030** [PaddlePaddle/Paddle2ONNX#1238]
使用paddleseg的seaformer模型，发现paddleseg模型和使用paddle2onnx转换出来的onnx模型的推理结果不一致，精度差距较大。

具体问题描述和复现工程：https://github.com/PaddlePaddle/PaddleSeg/issues/3682

paddleseg回复说这说明paddle2onnx或者onnxruntime存在精度误差，麻烦排查一下是什么问题。

**Comment by Zheng-Bicheng** [comment]
您好，有办法测试下在相同输入的情况下，Paddle Inference和ONNXRuntime的结果差距有多大嘛？

**Comment by Zheng-Bicheng** [comment]
可以参考我之间测试TVM时候的测试方法:

* https://github.com/apache/tvm/pull/16651
