### ISSUE TITLE
将apollo-model-centerpoint训练的模型转onnx时，报算子不支持的问题

### ISSUE THREAD

**Issue by TheGreatGalaxy** [PaddlePaddle/Paddle2ONNX#1244]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
将apollo-model-centerpoint训练的模型转onnx时，报算子不支持的问题， 如果解决这个问题。
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/43978497/331af493-4111-4c53-bdde-0e0ebf3d0f0e)

**更多信息 :**
 - 用于部署的推理引擎: tensorrt
 - 为什么需要转换为ONNX格式：因为支持更友好些
 - Paddle2ONNX版本:1.2.1
 - 你的联系方式(Email/Wechat/Phone):1319361380@qq.com

**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
Paddle2ONNX暂时不支持这些算子的转换
