### ISSUE TITLE
custom_ops映射使用问题

### ISSUE THREAD

**Issue by FrankyTang** [PaddlePaddle/Paddle2ONNX#1245]
我在使用命令行进行put_along_axis映射，使用了custom_ops，但是onnx的输入和输出发现对不上
这个是我使用的命令行：paddle2onnx --model_dir . --model_filename paddle_put_along_axis.pdmodel --opset_version 16 --save_file put_along_axis.onnx --custom_ops '{"put_along_axis":"ScatterElements"}'

下面的图片可以看到输入的名称和变量都对不上，可能是我使用的不对，能否提供一个正确的使用教程

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/32587916/f434cae3-9250-4ad7-8570-a186b9f3719a)

**Comment by Jiang-Jia-Jun** [comment]
哪里没对上

**Comment by Zheng-Bicheng** [comment]
@Jiang-Jia-Jun 这个参数还有在使用吗？

**Comment by Zheng-Bicheng** [comment]
这个好像没错呀，你这个输入变量名称原本应该是什么呢？

**Comment by Zheng-Bicheng** [comment]
custom_ops映射我们移除了，这个确实有问题，请问是在哪个地方需要使用到这个东西呢？

**Comment by Zheng-Bicheng** [comment]
现在的Runtime都是和ONNX的标准对齐的，理论上用不到这个功能了

**Comment by FrankyTang** [comment]
我的场景是paddle->onnx->trt。然后模型涉及到自定义算子，我就需要使用custom_ops完成paddle->onnx的转换。

**Comment by Zheng-Bicheng** [comment]
@FrankyTang 您是自己使用trt实现了算子是吗？所以需要用CustomOps？

**Comment by FrankyTang** [comment]
@Zheng-Bicheng 是的，我有自定义的trt算子。
