### ISSUE TITLE
unsupported ops: conditional_block,select_input,tril_triu

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/Paddle2ONNX#1246]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

PaddleOCR 表格识别算法 无法导出onnx

https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/algorithm_overview.md#3-%E8%A1%A8%E6%A0%BC%E8%AF%86%E5%88%AB%E7%AE%97%E6%B3%95

**Informations (please complete the following information):**
 - Inference engine for deployment: onnx
 - Why convert to onnx：
 - Paddle2ONNX Version: 
 - Email/Wechat/Phone:

**Screenshots**
```shell
paddle2onnx --model_dir inference/table_structure_tablemaster_infer --params_filename inference.pdiparams --model_filename inference.pdmodel  --save_file inference/table_structure_tablemaster_infer/best.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference/table_structure_tablemaster_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path: inference/table_structure_tablemaster_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,tril_triu,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)
```
**Additional context**

**Comment by Zheng-Bicheng** [comment]
这些控制流太多了，不太好做支持，大部分算子在Paddle2.6都删除了
