### ISSUE TITLE
量化paddle模型后通过Paddle2Onnx导出onnx存在的问题

### ISSUE THREAD

**Issue by God-song** [PaddlePaddle/Paddle2ONNX#1247]
现在使用paddledetection中的slim配置文件，进行了QAT量化训练，已经设置了onnx_format=True
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/a3a69dac-7607-4aec-81e5-1e2c27a46caa)

量化训练后，得到结果
进行导出
，通过文档正常导出
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/d6959ba6-c4ec-4afa-b4c8-9e4fc52c4245)
得到paddle infer模型
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/1a00e657-56d7-4c4a-a968-0575c3c586c8)

接下来通过paddle2onnx,将该结果导出量化后的 onnx
用这个命令可以导出
cmd = ['paddle2onnx', '--model_dir', str(output_dir), '--model_filename', 'model.pdmodel',
           '--params_filename', 'model.pdiparams', '--save_file', model_onnx,
           '--opset_version', '13', '--deploy_backend', 'tensorrt','--enable_onnx_checker', 'True',
           '--enable_dev_version', 'True']

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/95737b30-11a3-4a78-9503-bfa13c98d194)
但是没有量化配置文件（calibration_table.txt），calibration.cache 
,根本没有这个文件。

环境如下
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/9f791e93-d995-40b0-be67-ed6977602f8a)

如果使用 --save_calibration_file 指定保存路径。会直接报错，显示没有该参数，paddle提供的量化模型文档的步骤，根本无法正常的让我导出量化的模型，请告知如何正常导出，并使用

**Comment by God-song** [comment]
将paddle2onnx升级到1.2.1版本后会出现以下错误
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/10d2677f-9d77-4d4f-85e5-1fc9e034ced5)

**Comment by Zheng-Bicheng** [comment]
您这个是哪个模型呀

**Comment by God-song** [comment]
@Zheng-Bicheng PP-yoloe-L 模型，目标侦测

**Comment by Zheng-Bicheng** [comment]
我看了下，这应该是Windows的Paddle2ONNX版本过低导致的问题，请在amd64 Linux下使用哈，否则需要自行编译Paddle2ONNX

**Comment by God-song** [comment]
这就是linux

**Comment by God-song** [comment]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/a06a7136-6966-42e3-98a0-5fa67fe0eda5)

**Comment by Zheng-Bicheng** [comment]
我看你这张Log图片ONNX应该是正常导出了呀，量化配置文件（calibration_table.txt）是什么东西呢？Paddle2ONNX的哪个文档有提到这个文件吗？

**Comment by Zheng-Bicheng** [comment]
然后一个是您用Email回复的话，Github回复格式是有问题的，麻烦您到Github回复

**Comment by God-song** [comment]
@Zheng-Bicheng https://github.com/PaddlePaddle/Paddle2ONNX/blob/v1.0.7/docs/zh/quantize.md，这个官方提示了
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/47f41dee-96dd-499a-8306-7bcb42679fef)

**Comment by God-song** [comment]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/4e1b7423-4b14-48a5-976b-62e89e514956)
但是dao导出会出现这些问题，我现在期望是训练pp-yoloe-L模型目标侦测模型，训练完成后，期望感知量化训练，得到int8模型，然后再导出onnx

**Comment by Zheng-Bicheng** [comment]
这个是早期的导出方式了，新的导出方式是没有这个量化配置文件的

**Comment by Zheng-Bicheng** [comment]
你把你的模型压缩成zip上传一下把，我看一下

**Comment by God-song** [comment]
好的，最主要
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/38659788/39662ded-2fe6-463c-805f-c74b23c37377)
hai'you还有这个错误

**Comment by God-song** [comment]
@Zheng-Bicheng 能给个联系方式吗，正在上传

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 能给个联系方式吗，正在上传

在Issues回复就行了哈

**Comment by God-song** [comment]
已发送给你

**Comment by Zheng-Bicheng** [comment]
你这个模型怎么1.5个G呀

**Comment by God-song** [comment]
里面

**Comment by Zheng-Bicheng** [comment]
我的意思是，PPYOLOE模型训练出来会这么大吗？达到1.5个G

**Comment by God-song** [comment]
没有一个模型200m，我给你发了好几个阶段的

**Comment by Zheng-Bicheng** [comment]
只需要把你需要的量化模型发过来就行哈，我这边1.5个G要下好久。还有，不要用邮箱回复Github信息，你现在的消息已经出现一堆乱码了。

**Comment by God-song** [comment]
@Zheng-Bicheng 分享文件：test_ppyoloe_slim.zip
链接：https://pan.xunlei.com/s/VNy3aLEzkefLeE2Bt_FXKGs_A1?pwd=73gr#
复制这段内容后打开手机迅雷App，查看更方便

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 分享文件：test_ppyoloe_slim.zip 链接：https://pan.xunlei.com/s/VNy3aLEzkefLeE2Bt_FXKGs_A1?pwd=73gr# 复制这段内容后打开手机迅雷App，查看更方便

迅雷网盘我没办法下载呀，这玩意要下载客户端，Github上传不了你的模型吗？

**Comment by Zheng-Bicheng** [comment]
可以直接把压缩包拖到回复框里的，会自动上传

**Comment by God-song** [comment]
不行，超过25M了

**Comment by Zheng-Bicheng** [comment]
我这边没有复现这个问题，是可以正常转换的，你看一下Paddle2ONNX是不是最新版本，最新版本应该是1.2.x

**Comment by God-song** [comment]
版本paddle2onnx1.2开头的，文档我看依赖是基于paddle2.6版本的，目前我的所有开发环境都是paddle2.4.2

**Comment by Zheng-Bicheng** [comment]
新建一个环境，PaddlePaddle升级到2.6，Paddle2ONNX升级到1.2.x再进行转换哈，不再对以往的环境做支持。然后重复一下，请您在Github网页端回复！！！！！你的每一个评论都有乱码，这样是不方便后续的用户浏览这个Issues的，我现在需要一个一个的删除你的乱码，给我增加工作量了。

**Comment by Zheng-Bicheng** [comment]
或者使用PaddleDetection 2.7 + PaddlePaddle2.6 + Paddle2ONNX 1.2.x
