### ISSUE TITLE
能否指定 IR representation的版本

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle2ONNX#1248]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/12130348/47950cf2-0b04-41ac-ba71-23ad613b9079)
如图，能否指定format 版本呢？在转模型时，针对特定onnx工具，对于高版本的 不支持，报错， IR representation should smaller v8

**Comment by Zheng-Bicheng** [comment]
暂时没办法指定哦

**Comment by DLlearn** [comment]
> 暂时没办法指定哦

那有工具可以降么？把转好的onnx从v8给降一下。

**Comment by Zheng-Bicheng** [comment]
这个还真没办法，但是你这图上不是v7吗？哪里看出来是v8呢？

**Comment by DLlearn** [comment]
> 这个还真没办法，但是你这图上不是v7吗？哪里看出来是v8呢？

我用0.9 版的paddle2onnx了，不能再高，才弄成v7.paddlepaddle版本用的2.6倒也兼容。如果默认pip install paddle2onnx就是v8

**Comment by DLlearn** [comment]
> 这个还真没办法，但是你这图上不是v7吗？哪里看出来是v8呢？

pytorch 我试了下，用2.3 导出的onnx 也是V6，

**Comment by Zheng-Bicheng** [comment]
这个有点尴尬，因为我们不可能专门的再去适配低版本的ONNX了

**Comment by Zheng-Bicheng** [comment]
@Jiang-Jia-Jun 大佬，IR representation是通过什么来控制的呢？

**Comment by DLlearn** [comment]
> 这个有点尴尬，因为我们不可能专门的再去适配低版本的ONNX了

我是不太懂，paddle2onnx随着版本的升级，IR representation 也在改变升级，但pytorch一直升级却可以做到一直V6，所以看起来这个IR 版本不升也是没问题的。

**Comment by DLlearn** [comment]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/12130348/97b31ce9-71e1-46a1-a614-c27bdfb86692)
试了下pytorch2.2.2,两层FC

**Comment by Zheng-Bicheng** [comment]
@DLlearn 我会尝试一下修复这个问题哈，找到问题在哪里了，但是有个问题，就是IR版本好像和ONNX版本是强绑定了，我得研究下确保不会出现问题。

**Comment by DLlearn** [comment]
> @DLlearn 我会尝试一下修复这个问题哈，找到问题在哪里了，但是有个问题，就是IR版本好像和ONNX版本是强绑定了，我得研究下确保不会出现问题。

赞！

**Comment by Zheng-Bicheng** [comment]
麻烦把你的模型提供一下哈，我这边测试一下

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1261

**Comment by DLlearn** [comment]
> 麻烦把你的模型提供一下哈，我这边测试一下

[litev1_192.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/15454849/litev1_192.zip)
命令就是：paddle2onnx --model_dir litev1_192 --model_filename model.pdmodel --params_filename model.pdiparams --save_file litev1_192/litev1_192.onnx --opset 11  ，优化用onnxsim:python -m onnxsim litev1_192.onnx litev1_192_sim.onnx

**Comment by Zheng-Bicheng** [comment]
<img width="1512" alt="image" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/58363586/fd5c5eac-4f3e-42e4-8bcb-f12653e46d84">

**Comment by Zheng-Bicheng** [comment]
@DLlearn 用除了python3.11以外的版本下载一下最新的P2O，应该支持你的需求了，我导出来是v6了

**Comment by DLlearn** [comment]
> @DLlearn 用除了python3.11以外的版本下载一下最新的P2O，应该支持你的需求了，我导出来是v6了
OK,三个想法想和您了解 1：与paddlepaddle 版本有关吗？改变paddle版本会影响吗？2：与onnx版本有关吗？改变onnx版本会影响吗3：v6,v7,v8 及未来的这种，影响onnx的精度，推理速度，还是支持算子数，还是没啥用，就是随意这么一指定。

**Comment by Zheng-Bicheng** [comment]
看一下这里哈，这个功能已经实现了，如果后续有问题可以另起一个Issues来提问哈:

* https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions

**Comment by YiAnXS** [comment]
> [@DLlearn](https://github.com/DLlearn) 用除了python3.11以外的版本下载一下最新的P2O，应该支持你的需求了，我导出来是v6了

你好 谢谢作者的修改 但是我发现新版的paddle2onnx2.0.2rc3 这个ir更新好像丢了？opset_version修改后 ir版本不会相应的修改 请问可以告知再代码哪里可以修改吗？或者是否还有新版更新计划 谢谢
