### ISSUE TITLE
使用paddlehub下载的module finetune之后，如何转化为onnx模型呢？

### ISSUE THREAD

**Issue by libingbingdev** [PaddlePaddle/Paddle2ONNX#125]
使用paddlehub下载的module ('shufflenet_v2_imagenet') finetune之后，如何转化为onnx模型呢？
想要用intel 神经棒做边缘计算，需要将paddle模型转为onnx，onnx再转为IR

**Comment by jiangjiajun** [comment]
参考此文档说明 https://github.com/PaddlePaddle/paddle2onnx/blob/develop/README.md

**Comment by juzuo** [comment]
@libingbingdev 你好，使用paddlehub下载的module怎么进行finetune呢？缺少训练过程中的一些文件啊。

**Comment by jiangjiajun** [comment]
> @libingbingdev 你好，使用paddlehub下载的module怎么进行finetune呢？缺少训练过程中的一些文件啊。

可以在PaddleHub的Github Repo下提issue，会有相关的同学快速解答你的疑问哦 @juzuo  https://github.com/PaddlePaddle/PaddleHub
