### ISSUE TITLE
编译Paddle2ONNX出现报错

### ISSUE THREAD

**Issue by xiaoyewww** [PaddlePaddle/Paddle2ONNX#1252]
**Describe the bug**
按照https://github.com/xiaoyewww/Paddle2ONNX/blob/develop/docs/zh/compile_local.md进行编译，编译develop分支出现问题。

**Env**

cmake=3.18.0
g++==12.1.0
protobuf==3.16.0

**Screenshots**
<img width="1526" alt="image" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/50870160/8363cee4-a5af-4649-82d8-8852e3c5c798">

<img width="1522" alt="image" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/50870160/c37c4967-6e15-45d9-8789-1c18e250fcb1">

**Comment by Zheng-Bicheng** [comment]
在以下PR中我们尝试对这个Bug进行了修复，请您重新测试一下是否还存在这个问题:

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1253

**Comment by xiaoyewww** [comment]
> 在以下PR中我们尝试对这个Bug进行了修复，请您重新测试一下是否还存在这个问题:
> 
> * [[CI] Add test for bitwise_and op #1253](https://github.com/PaddlePaddle/Paddle2ONNX/pull/1253)

谢谢，解决了。

另外我忘了补充这个docker拉的是paddle官网上的12.0：
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6
