### ISSUE TITLE
请问如何将onnx的输入的batch size 固定为1，现在是动态输入的batch size

### ISSUE THREAD

**Issue by muuda** [PaddlePaddle/Paddle2ONNX#1254]
![Uploading dynamic.png…](https://img2.imgtp.com/2024/05/21/SOY8bDoI.png)

即将`p2o.DynamicDimension.0`转为1。尝试如下命令后仍然不行：
![Uploading dynamic.png…](https://img2.imgtp.com/2024/05/21/i0ZHULnO.png)

**Comment by Zheng-Bicheng** [comment]
请使用 [Paddle 模型优化工具](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/tools/paddle/README.md) 固定Paddle模型后再使用Paddle2ONNX导出模型
