### ISSUE TITLE
转换成onnx后使用netron可视化尺寸不是-1而是p2o.DynamicDimension.0-5

### ISSUE THREAD

**Issue by gaowq2017** [PaddlePaddle/Paddle2ONNX#1265]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
使用命令行转换paddle模型到onnx，具体命令行为：paddle2onnx --model_dir E:\PaddleOCR\checkpoint\inference_new --model_filename inference_new.pdmodel --params_filename inference_new.pdiparams --save_file E:\PaddleOCR\checkpoint\inference_new/model.onnx --opset_version 11 --input_shape_dict="{'x':[-1,3,-1,-1]}"
查看paddle2onnx没有input_shape_dict这个参数？还是我使用不对？

 - Paddle2ONNX版本:1.0.6
 -可视化截图如下：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/29697367/582891cd-3cc3-4513-92aa-6d2f69cc431e)
谢谢！

**Comment by Zheng-Bicheng** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle

**Comment by Zheng-Bicheng** [comment]
修改一下输入shape再使用Paddle2ONNX导出哈
