### ISSUE TITLE
depthwise_conv2d, this model cannot be exported to ONNX.

### ISSUE THREAD

**Issue by MichaelZsl** [PaddlePaddle/Paddle2ONNX#1276]
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: export/food_det_both_416x128_eps_v0/model.pdmodel
[Paddle2ONNX] Parameters file path: export/food_det_both_416x128_eps_v0/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_1.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_2.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_3.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[Paddle2ONNX] Detected there's control flow 'while' op in your model, this requires the minimal opset version of 13.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_5.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_6.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_7.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[Paddle2ONNX] Detected there's control flow 'while' op in your model, this requires the minimal opset version of 13.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_9.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_10.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_11.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_13.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_14.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_15.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_17.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_18.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_19.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_21.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_22.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_23.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[Paddle2ONNX] Detected there's control flow 'while' op in your model, this requires the minimal opset version of 13.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_26.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_27.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_30.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_31.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_34.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_35.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_38.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_39.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_42.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_43.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_46.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_47.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_50.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_51.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_54.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX] [depthwise_conv2d: depthwise_conv2d_55.tmp_0] While dilations != 1, cannot support padding = 'SAME'.
[Paddle2ONNX] Due to the operator: depthwise_conv2d, this model cannot be exported to ONNX.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1717583184 (unix time) try "date -d @1717583184" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3eb000019ab) received by PID 6571 (TID 0x7f5103486440) from PID 6571 ***]

Aborted (core dumped)

**Comment by MichaelZsl** [comment]
麻烦看下这个是BUG吗，目前有没有快速解决的办法？

**Comment by MichaelZsl** [comment]
应该是nn.Conv2D中dilation!= 1时设置的padding=‘same’卷积核不支持转换

**Comment by Zheng-Bicheng** [comment]
这个具体是哪个套件的模型呢？

**Comment by MichaelZsl** [comment]
> 这个具体是哪个套件的模型呢？

是PaddleSeg下的ESPNet（ESPNetV2），麻烦看下，谢谢！
