### ISSUE TITLE
paddleocr    DBnet  转成onnx  后  reshape2 丢了

### ISSUE THREAD

**Issue by StarShang** [PaddlePaddle/Paddle2ONNX#1278]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**
这是export的inferrence.pdmodel  输出部分
<img width="1246" alt="image" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/51013149/546786fa-1480-40cb-b1ab-b5bc6742ed37">
这是paddle2onnx 后的onnx 的输出部分
<img width="964" alt="image" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/51013149/885ef07e-3880-4cee-9c06-0f73a97c4d2e">

发现reshape2丢了？？？？

**Describe the bug**

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version:
 - Email/Wechat/Phone:

**Screenshots**

**Additional context**

**Comment by Jiang-Jia-Jun** [comment]
模型精度有差别吗？

- reshape2不是丢掉了，而是被优化掉了。 在原模型中，reshape2的输入是一个constant常量，因此Paddle2ONNX在转换过程中，通过**常量折叠**优化，直接消除了这个算子
