### ISSUE TITLE
UIE多输入转onnx后输入结构与原模型不符

### ISSUE THREAD

**Issue by XiHenSuper** [PaddlePaddle/Paddle2ONNX#1282]
**问题描述**
UIE原始模型的输入有三个: input_ids、position_ids以及常量fill constant
通过paddle2onnx.command.c_paddle_to_onnx函数转onnx后输入结构发生大的变动。

**更多信息 :**
 - 用于部署的推理引擎: onnx
 - 为什么需要转换为ONNX格式：需要适配国产化系统
 - Paddle2ONNX版本: 1.1.0
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
UIE原始输入模型结构：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/35356847/77e73073-7211-458d-b6cb-9212f967f90c)

转onnx后的输入模型结构：
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/35356847/ab02d22f-ace1-4e4f-9ad2-4bd491c6bdaa)

**其他信息**

**Comment by Jiang-Jia-Jun** [comment]
与原模型哪里不符？
