### ISSUE TITLE
pip install failed!

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/Paddle2ONNX#1293]
win11

```bash
conda create -n paddle_onnx python=3.11
conda activate paddle_onnx
pip install paddle2onnx
```

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/44420757/b7f7ddc3-c14f-4d8e-a4c7-e591a9cc0007)

**Comment by Zheng-Bicheng** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile_local.md
