### ISSUE TITLE
安装paddle2onnx会强制修改numpy版本

### ISSUE THREAD

**Issue by tianshuo78520a** [PaddlePaddle/Paddle2ONNX#1303]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
如果我的numpy==2.0.0 再安装paddle2onnx>=0.9.6 就会强制把numpy修改成1.26.4
在代码库中也没有看到requirements.txt文件，不太清楚依赖版本

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
    pip3.9 install paddle2onnx>=0.9.6
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![a71b0bdd0a3673f3b50c681ae2667b7f](https://github.com/PaddlePaddle/Paddle2ONNX/assets/29832297/d006deca-5493-4b35-b044-ecf5d0da91f5)

**其他信息**

**Comment by jzhang533** [comment]
应该是 paddle2onnx 依赖的 onnxruntime 引起的。

https://github.com/microsoft/onnxruntime/issues/21063

现在需要安装 onnxruntime nightly build 才可以。

**Comment by Zheng-Bicheng** [comment]
这个PR中做处理

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1306
