### ISSUE TITLE
[讨论]关于mapper_registery.h.in 里REGISTER_MAPPER宏的new 操作的疑问

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle2ONNX#1307]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
最近在看`mapper_registery.h.in` 里的代码，对如下REGISTER_MAPPER的实现有一个疑问：

https://github.com/PaddlePaddle/Paddle2ONNX/blob/4d27011092854bcc5e3d9785b7ca529227512b50/paddle2onnx/mapper/register_mapper.h#L34

上述代码中是在`Create` 接口中调用了new 操作符，在heap上创建的对象，但是并没有找到对应的 delete操作，是否有内存泄露的风险?

比如每次`MapperHelper::CreateMapper()` 都会触发一次new，然后返回 heap 上的 Mapper 指针，但是没有找到delete资源的操作；
https://github.com/PaddlePaddle/Paddle2ONNX/blob/4d27011092854bcc5e3d9785b7ca529227512b50/paddle2onnx/mapper/register_mapper.h#L106
**更多信息 :**
在飞桨Paddle 框架里也存在对于算子或者Kernel的注册管理，也是单例形式，但采用了static 全局静态变量的方式，对资源管理更加友好：
```cpp
// op_registry.h
#define REGISTER_OPERATOR(op_type, op_class, ...)                        \
  STATIC_ASSERT_GLOBAL_NAMESPACE(                                        \
      __reg_op__##op_type,                                               \
      "REGISTER_OPERATOR must be called in global namespace");           \
  static ::paddle::framework::OperatorRegistrar<op_class, ##__VA_ARGS__> \
      __op_registrar_##op_type##__(#op_type);                            \
  int TouchOpRegistrar_##op_type() {                                     \
    __op_registrar_##op_type##__.Touch();                                \
    return 0;                                                            \
  }


template <typename... ARGS>
struct OperatorRegistrar : public Registrar {
  explicit OperatorRegistrar(const char* op_type) {
    PADDLE_ENFORCE_EQ(
        OpInfoMap::Instance().Has(op_type),
        false,
        platform::errors::AlreadyExists(
            "Operator '%s' is registered more than once.", op_type));
    static_assert(sizeof...(ARGS) != 0,
                  "OperatorRegistrar should be invoked at least by OpClass");
    OpInfo info;    //  并没有使用 new 操作符
    details::OperatorRegistrarRecursive<0, false, ARGS...>(op_type, &info);
    OpInfoMap::Instance().Insert(op_type, info);   // 全局单例
  }
};
```

**报错截图**

**其他信息**
还有一种方式，就是不直接返回Mapper*，再抽象一层接口wrapper下。其持有这个heap上的对象指针，然后实现一个析构函数，在里面调用delete

**Comment by jzhang533** [comment]
我理解是，反正进程结束后，内存都没了，代码就写的没考虑那么多。

**Comment by Aurelius84** [comment]
进程结束后确实会被操作系统给统一回收。风险点在于进程没有退出时，且用户的机器内存受限时，可能有在转换过程挂掉，只是这种风险可能小一些而已，与算子的数量（而非种类）线性相关。

假设每个Mapper对象大小16B，64个算子才1KB，看起来风险极小。
