### ISSUE TITLE
在转换模型时遇到了如下错误： Can't parse message of type "paddle2onnx.framework.proto.ProgramDesc" because it is missing required fields: blocks[0].ops[27].attrs[7].type, blocks[3].ops[12].attrs[7].type

### ISSUE THREAD

**Issue by JiaXinLI98** [PaddlePaddle/Paddle2ONNX#1308]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
转换模型时遇到错误：

[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference2/model.pdmodel
[Paddle2ONNX] Paramters file path: ./inference2/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[libprotobuf ERROR /workspace/Paddle2ONNX/protobuf/src/google/protobuf/message_lite.cc:133] Can't parse message of type "paddle2onnx.framework.proto.ProgramDesc" because it is missing required fields: blocks[0].ops[27].attrs[7].type, blocks[3].ops[12].attrs[7].type
[Paddle2ONNX] Failed to parse paddlepaddle model from read content.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version: 1.2.5
 - Email/Wechat/Phone:  

**Screenshots**
<img width="852" alt="截屏2024-07-09 19 47 26" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/41884632/83386259-f53b-4450-9bcd-562197ada018">

**Additional context**
启动命令：
paddle2onnx --model_dir ./inference2 \
            --model_filename model.pdmodel \
            --params_filename model.pdiparams \
            --save_file onnx_model/model.onnx
模型：baichuan13b

**Comment by Aurelius84** [comment]
通过提供的模型和参数文件验证，是模型中包含了一些控制流等算子未支持，已单独建立需求类issue跟进，感谢您的反馈，我们会尽快支持。
<img width="897" alt="6dc88e03ae39d5fef6cfd1259df8181b" src="https://github.com/PaddlePaddle/Paddle2ONNX/assets/9301846/c6179a96-b3b6-410d-a92e-ad44aa6e9e8b">
