### ISSUE TITLE
使用X2Paddle将ONNX模型转Paddle时报错

### ISSUE THREAD

**Issue by hezhihao10** [PaddlePaddle/Paddle2ONNX#1309]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**
在尝试将ernie+自定义操作的基于pytorch框架的模型转onnx后再转为paddle模型。在gather算子这里转换脚本报错

以下为x2paddle自动转换的代码
 在ernie里gather embedding时出错
```
x2paddle__bert_embeddings_position_embeddings_Gather_output_0 = paddle.gather(x=x2paddle_bert_embeddings_position_embeddings_weight, index=x2paddle__bert_embeddings_Constant_output_0, axis=0)
 x2paddle__bert_embeddings_task_type_embeddings_Gather_output_0 = paddle.gather(x=x2paddle_bert_embeddings_task_type_embeddings_weight, index=x2paddle__bert_embeddings_Constant_1_output_0, axis=0)
```
对应的index为：
```
self.x2paddle__bert_embeddings_Constant_output_0 = self.create_parameter(shape=[1, 32], attr='x2paddle__bert_embeddings_Constant_output_0', dtype='int64', default_initializer=paddle.nn.initializer.Constant(value=0.0))
self.x2paddle__bert_embeddings_Constant_1_output_0 = self.create_parameter(shape=[1, 32], attr='x2paddle__bert_embeddings_Constant_1_output_0', dtype='int64', default_initializer=paddle.nn.initializer.Constant(value=0.0))
```
其中32为max_seqence_length

**问题描述**
请在此处详细的描述报错信息

下面为详细报错
> In transformed code:
> 
>     File "/Users/zhihao02.he/Codes/intent_detect_model_pytorch/data/model/ernie_mini_trained/pd_model_dynamic/x2paddle_code.py", line 225, in forward
>         x2paddle__bert_ConstantOfShape_output_0 = paddle.full(shape=x2paddle__bert_Constant_3_output_0, dtype='int64', fill_value=1)
>         x2paddle__bert_Unsqueeze_output_0 = paddle.unsqueeze(x=x2paddle_attention_mask, axis=x2paddle__bert_Constant_5_output_0)
>         x2paddle__bert_embeddings_position_embeddings_Gather_output_0 = paddle.gather(x=x2paddle_bert_embeddings_position_embeddings_weight, index=x2paddle__bert_embeddings_Constant_output_0, axis=0)
>         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>         x2paddle__bert_embeddings_task_type_embeddings_Gather_output_0 = paddle.gather(x=x2paddle_bert_embeddings_task_type_embeddings_weight, index=x2paddle__bert_embeddings_Constant_1_output_0, axis=0)
>         x2paddle__ConstantOfShape_output_0 = paddle.full(shape=x2paddle__Constant_1_output_0, dtype='int64', fill_value=1)
> 
>     File "/opt/anaconda3/envs/onnx_tf/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3019, in gather
>         helper.append_op(
>     File "/opt/anaconda3/envs/onnx_tf/lib/python3.8/site-packages/paddle/base/layer_helper.py", line 44, in append_op
>         return self.main_program.current_block().append_op(*args, **kwargs)
>     File "/opt/anaconda3/envs/onnx_tf/lib/python3.8/site-packages/paddle/base/framework.py", line 4467, in append_op
>         op = Operator(
>     File "/opt/anaconda3/envs/onnx_tf/lib/python3.8/site-packages/paddle/base/framework.py", line 3214, in __init__
>         self.desc.infer_shape(self.block.desc)
> 
>     ValueError: (InvalidArgument) The last dim of index should be 1 when it is 2D, but we get 32
>   [Hint: Expected index_dims[1] == 1, but received index_dims[1]:32 != 1:1.] (at /Users/paddle/xly/workspace/6b5f2c56-ddc3-4da3-aa89-e4f3a21369ae/Paddle/paddle/phi/infermeta/binary.cc:1541)
>   [operator < gather > error]

**更多信息 :**
 - 用于部署的推理引擎:   
 环境
Macos
python                     3.8.19  
x2paddle                  1.4.1 
onnx                      1.15.0  
paddlepaddle              2.6.0          

 - 你的联系方式(Email/Wechat/Phone):
wechat : 13714857390
**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
这个 Repo 是 Paddle2ONNX 不是 X2Paddle
