### ISSUE TITLE
【🚀需求🚀】支持控制流conditional_block + select_input 系列算子的支持

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle2ONNX#1310]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
记录一个算子转换需求的问题：控制流 if 下涉及的 conditional_block + select_input 算子转ONNX

**更多信息 :**
 - 用于部署的推理引擎: 待更新
 - 为什么需要转换为ONNX格式：业务需求
 - Paddle2ONNX版本: 1.2.5 
 - 你的联系方式(Email/Wechat/Phone): Aurelius84

**报错截图**

**其他信息**

**Comment by Aurelius84** [comment]
从 onnx 的 [if 官方文档](https://onnx.ai/onnx/operators/onnx__If.html#l-onnx-doc-if) 来看，其功能定义似乎比飞桨的控制流算子更为严格，评估可能类似while_loop算子一样是有限场景的转ONNX。

TODO：待确认ONNX对于控制流嵌套支持度如何？

**Comment by jiuyuedeyu156** [comment]
![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/151344256/c2d5604b-7014-4c87-a313-759614a2fc6e)
Paddle2ONNX 支持Graph数据结构吗？

**Comment by Aurelius84** [comment]
应该可以构造，ModelProto 里可以mutable一个新的Graph?

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
