### ISSUE TITLE
【🚀需求🚀】支持飞桨 top_p_sampling 算子转ONNX

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle2ONNX#1312]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
记录一个待支持转ONNX的算子需求：top_p_sampling 算子。且去ONNX官网看了下，没有直接对应的算子，需要用ONNX算子组合实现

**更多信息 :**
 - 用于部署的推理引擎: 待更新
 - 为什么需要转换为ONNX格式： 业务方
 - Paddle2ONNX版本: 1.2.5
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by Zheng-Bicheng** [comment]
@Aurelius84 大佬，这个方便让业务大佬过来说一下，这个 top_p_sampling 作用是什么吗？我有点没看明白搜到的资料
