### ISSUE TITLE
paddle2onnx 编译python wheel 包问题

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/Paddle2ONNX#1315]
**问题描述**
在编译paddle2onnx的过程中发现了两个问题：
1. 执行`python -m build `命令后即使编译过一次，进行些许改动后（甚至不改任何东西）重新执行`python -m build` 也会对整个项目进行重新编译，编译很慢很耗时。
2. 在编译完成后，安装paddle2onnx的whl包，包里面把c++源码全部打包进去了。

请问一下这俩问题该怎么优化一下吗？尤其是问题1，电脑不行编译就会很耗时。

**Comment by Zheng-Bicheng** [comment]
用 `pip install -e .`  来编译试试？

**Comment by Aurelius84** [comment]
提了一个优化PR，移除了wheel里的cpp类似的文件：https://github.com/PaddlePaddle/Paddle2ONNX/pull/1316

**Comment by ChaoII** [comment]
感谢两位大佬，在需要频繁编辑的情况下，确实应该用`pip install e .` 如果用`python -m build` 一直都是重新编译

**Comment by Zheng-Bicheng** [comment]
@ChaoII PR已经合入啦，现在不会再把 CPP 文件打包进去了

* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1316

感谢 @Aurelius84 大佬的帮助

**Comment by 154775258** [comment]
大佬 打包不成功可以分享一下 打包后的文件
