### ISSUE TITLE
Hello, with the help of Paddle2onNx, can the mobilenet_v2_VOC format data set model trained by myself be converted to ONNX?

### ISSUE THREAD

**Issue by dongyangli-del** [PaddlePaddle/Paddle2ONNX#132]

**Comment by dongyangli-del** [comment]
Has anyone ever tried to convert their trained model to onNX format?I am currently deploying the edge AI hardware platform with paddle models in conjunction with NCS2, can anyone who is doing similar work give some good advice?

**Comment by Channingss** [comment]
@dongyangli-del  this page is about how to deploy paddle model on OpenVINO(NCS2) traind by PaddleX, which may help you. 
https://paddlex.readthedocs.io/zh_CN/develop/deploy/openvino/index.html

**Comment by dongyangli-del** [comment]
> @dongyangli-del this page is about how to deploy paddle model on OpenVINO(NCS2) traind by PaddleX, which may help you.
> https://paddlex.readthedocs.io/zh_CN/develop/deploy/openvino/index.html

Thank you ! This has been very helpful in my recent work！！
