### ISSUE TITLE
paddle ocr 转onnx之后精度损失

### ISSUE THREAD

**Issue by gzgc** [PaddlePaddle/Paddle2ONNX#1328]
在使用paddle的模型测试时，测试集准确率是100% ，转为onnx模型测试，同样的测试集，准确率变成了88%。出现了大量的错误。

**Comment by Zheng-Bicheng** [comment]
具体是哪个模型呢？

**Comment by gzgc** [comment]
[pocr.zip](https://github.com/user-attachments/files/16230959/pocr.zip)
我在原始模型上进行微调过，这里是训练好的模型，压缩包中有我测试的图片，没有转为onnx时测试都是对的。转为onnx之后都识别错误了

**Comment by gzgc** [comment]
[pocr.zip](https://github.com/user-attachments/files/16231117/pocr.zip)
这是我微调过的模型，压缩包里有测试的数据，我选了一些paddle模型识别正确，转为onnx之后就识别错的。

**Comment by jiuyuedeyu156** [comment]
当遇到paddle和ONNX精度异常问题时，我通常会使用裁剪工具，从下到上逐步裁剪paddle模型，然后检查裁剪后的paddle模型和对应ONNX模型的精度，直到找到异常算子。paddle裁剪工具：https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle

**Comment by Zheng-Bicheng** [comment]
@gzgc OCR是三个模型联合推理的，您方便排查一下，这三个模型哪一个模型出问题了吗？

**Comment by gzgc** [comment]
我只微调了识别模型，其他的两个模型没有使用。

**Comment by Zheng-Bicheng** [comment]
你是固定了Shape转的吗，还是动态shape

**Comment by gzgc** [comment]
我看文档说会默认启用动态shape，我并没有填写什么参数控制，而且看paddle2onnx 的readme文档也没有控制的参数

**Comment by GreatV** [comment]
动态shape精度应该是一样的，你得检查一下配置参数是不是一致的。

**Comment by Zheng-Bicheng** [comment]
@gzgc 我测试了几张，也没啥问题呀，你可以把你输入到模型中的数据给我一下吗？

**Comment by gzgc** [comment]
数据就是我在压缩包里发的那些，你是说你的结果是正确的，我可以看下你转onnx的命令吗还有onnx模型推理的命令
