### ISSUE TITLE
SLANet-LCNetV2 转onnx模型报错

### ISSUE THREAD

**Issue by milely** [PaddlePaddle/Paddle2ONNX#1331]
#### 问题描述 / Problem Description
新SLANet-LCNetV2 通过paddle2onnx转onnx模型时报错

#### 运行环境 / Runtime Environment
- OS: centos
- Paddle:  2.6.1
- PaddleOCR:

#### 完整报错 / Complete Error Message
![image](https://github.com/user-attachments/assets/33f69309-abfb-4cbb-a93a-0c149aafdea8)

**Comment by GreatV** [comment]
`while` 算子还不支持

**Comment by milely** [comment]
也就是没办法通过onnx推理嘛，之前看到SLAnet是可以解决的  https://github.com/PaddlePaddle/PaddleOCR/pull/7485

**Comment by Zheng-Bicheng** [comment]
@milely 暂时移除了，后续会更新

**Comment by milely** [comment]
> @milely 暂时移除了，后续会更新

好的，我使用1.0.7的版本配合opset 13转换成功了，原来的版本是会有掉精度的风险吗

**Comment by Zheng-Bicheng** [comment]
> > @milely 暂时移除了，后续会更新
> 
> 好的，我使用1.0.7的版本配合opset 13转换成功了，原来的版本是会有掉精度的风险吗

建议换到1.2.5

**Comment by milely** [comment]
好的，1.2.5也转换成功了，谢谢～

**Comment by squallliu** [comment]
> > > @milely 暂时移除了，后续会更新
> > 
> > 
> > 好的，我使用1.0.7的版本配合opset 13转换成功了，原来的版本是会有掉精度的风险吗
> 
> 建议换到1.2.5

1.2.5不支持conditional_block select_input

**Comment by Zheng-Bicheng** [comment]
> 1.2.5不支持conditional_block select_input

1.2.6为了添加对 `conditional_block select_input` 的支持，因此大面积重构了代码。代码和while的逻辑冲突了，所以暂时取消了对while的支持，我们后续会更新的。

**Comment by PeiyuLau** [comment]
while支持，现在有更新么？

**Comment by Zheng-Bicheng** [comment]
> while支持，现在有更新么？

换到1.2.5吧，暂时没人力支持，需要等一段时间

**Comment by Zheng-Bicheng** [comment]
已经更新支持 while 算子，等待 CI 结束后 安装 Paddle2ONNX v1.2.10 使用:

* https://github.com/PaddlePaddle/Paddle2ONNX/actions/runs/11362622694

**Comment by Zheng-Bicheng** [comment]
先关闭这个Issues，有问题请再打开并 @Zheng-Bicheng
