### ISSUE TITLE
无法在set_value算子中找到fp32_values属性

### ISSUE THREAD

**Issue by jiuyuedeyu156** [PaddlePaddle/Paddle2ONNX#1332]
## paddle模型代码
```python
import paddle
class Net(paddle.nn.Layer):
    def __init__(self):
        super(Net, self).__init__()
    def forward(self, inputs):
        inputs[1,1] = 1
        return inputs
net = Net()
inputs = paddle.to_tensor([[1,2,3], [4,5,6]], dtype=paddle.float32)
y = net(inputs)
paddle.jit.save(net, 'model', input_spec=[inputs])
```
## pdmodel文件
![image](https://github.com/user-attachments/assets/e4198903-4bcd-4e67-887a-490205b36393)
![image](https://github.com/user-attachments/assets/f99a2d55-d1fb-490e-aa22-cafe786b84e9)

**Comment by jiuyuedeyu156** [comment]
找不到inputs[1,1] = 1的有效信息，无论是属性还是输入

**Comment by jiuyuedeyu156** [comment]
通过解析pdmodel的方法已经找到有效信息values，然后我将fp32values属性改为values，发现paddle2onnx不支持axis rank > 1的情况
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/914af6e0-7548-491e-8917-90645c363788">

**Comment by Zheng-Bicheng** [comment]
> 通过解析pdmodel的方法已经找到有效信息values，然后我将fp32values属性改为values，发现paddle2onnx不支持axis rank > 1的情况

这个应该是你自己这边做的限制？Paddle2ONNX有这方面的限制吗？

**Comment by jiuyuedeyu156** [comment]
> > 通过解析pdmodel的方法已经找到有效信息values，然后我将fp32values属性改为values，发现paddle2onnx不支持axis rank > 1的情况
> 
> 这个应该是你自己这边做的限制？Paddle2ONNX有这方面的限制吗？

Paddle2ONNX只支持input[5]=2或者input[1:5]=2这种零维、一维索引赋值，但不支持input[1, 3]=2或者input[1:2, 3:4]=2这种多维度索引赋值

**Comment by jiuyuedeyu156** [comment]
当在神经网络中调用input[1, 2]=2时，属性是axes=[0, 1], values=2, dtype=int64, starts=[1, 2], ends=[2,3], 输入是input

**Comment by Zheng-Bicheng** [comment]
> 当在神经网络中调用input[1, 2]=2时，属性是axes=[0, 1], values=2, dtype=int64, starts=[1, 2], ends=[2,3], 输入是input

那是不是可以考虑做有限的支持呢？我有点没理解这里是ONNX的限制还是Paddle2ONNX代码的限制

**Comment by jiuyuedeyu156** [comment]
我想copy一下torch的代码，但看不懂函数的参数。paddle set_value对应torch input_put这个函数。https://github.com/pytorch/pytorch/blob/499621e7bbd30f9c7600f26a5fba0cf065faad5e/torch/onnx/symbolic_opset11.py#L207
