### ISSUE TITLE
windwos下安装，版本是旧版本

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle2ONNX#1334]
环境:
1) window11
2) paddlepaddle-gpu  2.6.1
3) onnxruntime-gpu 1.17
在直接安装或者升级paddle2onnx的时候，一直安装的都是1.0.6的版本，我去pypi上看到最新的和github上发布的版本一样，是不是因为最新版本目前还不支持windows，目前看离线安装编译的都是linux版本的

**Comment by zzz-zyq** [comment]
同疑惑。
在清华源搜了win关键字，发现最高版本确实只到1.0.6。
https://pypi.tuna.tsinghua.edu.cn/simple/paddle2onnx/

**Comment by yjyz1011** [comment]
1.0.6之后，没有windows编译包，只有linux，小编懒啊。

**Comment by GreatV** [comment]
windows 得自己编译

**Comment by LijialinHub** [comment]
有人编译过了嘛 麻烦分享下呗，谢谢 鄙人实在是编译不过

**Comment by LijialinHub** [comment]
> 环境:
> 
> 1. window11
> 2. paddlepaddle-gpu  2.6.1
> 3. onnxruntime-gpu 1.17
>    在直接安装或者升级paddle2onnx的时候，一直安装的都是1.0.6的版本，我去pypi上看到最新的和github上发布的版本一样，是不是因为最新版本目前还不支持windows，目前看离线安装编译的都是linux版本的

请问您解决了嘛 求分享whl文件。

**Comment by zzz-zyq** [comment]
个人用的1.2.5版本，是在Linux系统上用pip安装的。
因为清华源里高于1.0.6版的都只能支持mac和linux了。
![image](https://github.com/user-attachments/assets/8e681b07-1130-4ee2-9cb8-ea11a3ebf681)

**Comment by LijialinHub** [comment]
> 个人用的1.2.5版本，是在Linux系统上用pip安装的。 因为清华源里高于1.0.6版的都只能支持mac和linux了。 ![image](https://private-user-images.githubusercontent.com/80569086/379517045-8e681b07-1130-4ee2-9cb8-ea11a3ebf681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MzYwNzksIm5iZiI6MTcyOTczNTc3OSwicGF0aCI6Ii84MDU2OTA4Ni8zNzk1MTcwNDUtOGU2ODFiMDctMTEzMC00ZWUyLTljYjgtZWExMWEzZWJmNjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDAyMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFiMzcxMTY1YmZlYWY3MGE2OTkzZmRlZGYzNGRlZmNhNjA2NzcxZmEwZDg5ZDFhNzY0ZmVjMmVjY2RmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uwgs7jW8uri9YG3tTec8jOGLDtu-IN-uaqBnzq3Oyv4)

这个我也知道的哈哈，工作环境需要嘛 一体化流程，要在win上搞😂
