### ISSUE TITLE
无法在assign_value算子中找到fp32_values和int64_values属性

### ISSUE THREAD

**Issue by wangna11BD** [PaddlePaddle/Paddle2ONNX#1338]
DETR模型导出后转onnx报错无法在assign_value算子中找到fp32_values和int64_values属性
转onnx命令：paddle2onnx --model_dir=./output_inference/detr_r50_1x_coco/ \
    --model_filename=model.pdmodel \
    --params_filename=model.pdiparams \
    --save_file=./output_inference/detr_r50_1x_coco/model.onnx \
    --enable_onnx_checker=True \
    --opset_version 16
报错截图：
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/0cd90286-f821-41ef-98e0-23b4b2b0c5c7">
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/61746520-c1b9-470a-a784-2af95d90bf49">

**Comment by jiuyuedeyu156** [comment]
不要使用paddlepaddle3导出静态图，建议使用paddlepaddle2.6.1

**Comment by wangna11BD** [comment]
已解决，感谢～
