### ISSUE TITLE
ppdet 导出的rtdetr模型转onnx报错

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/Paddle2ONNX#1357]
导出命令：
 python tools/export_model.py -c configs/rtdetr/rtdetr_hgnetv2_l_6x_coco.yml -o weights=output/rtdetr_hgnetv2_l_6x_coco/model_final.pdparams trt=True

转换命令：
 paddle2onnx --model_dir=./output_inference/rtdetr_hgnetv2_l_6x_coco/  --model_filename model.pdmodel --params_filename model.pdiparams --enable_onnx_checker True --enable_dev_version False --opset_version 16
--save_file rtdetr_hgnetv2_6x_coco.onnx

版本：
![3 (2)](https://github.com/user-attachments/assets/818717cf-0d8b-4bd6-9c2a-350c14d64081)

报错信息:
![2 (2)](https://github.com/user-attachments/assets/5d8ad85e-4721-4990-9a9c-3c1b7cdd06d7)

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version:
 - Email/Wechat/Phone:510628461@qq.com

**Screenshots**

**Additional context**

**Comment by Zheng-Bicheng** [comment]
P2O版本太低了，用Linux下载最新的Paddle2ONNX来转
