### ISSUE TITLE
[ERROR] Cannot found attribute beta in op: swish

### ISSUE THREAD

**Issue by Hakstar** [PaddlePaddle/Paddle2ONNX#1358]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
运行https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/tools/paddle/README.md中的剪枝操作之后，对pd模型转换为onnx，出现报错

paddle2onnx        1.0.9
paddlepaddle       3.0.0b1
(尝试过paddle2.6，2.5都报相同的错误，其中2.5.2在运行剪枝时找不到paddle.base这个包)

**更多信息 :**
 - 用于部署的推理引擎: 
 - 为什么需要转换为ONNX格式：后续转om
 - Paddle2ONNX版本: 1.0.9
 - 你的联系方式(Email/Wechat/Phone): dbw46784086@icloud.com

**报错截图**
<img width="1232" alt="Snipaste_2024-08-22_11-55-18" src="https://github.com/user-attachments/assets/dc5469ec-4d2a-4b5d-824f-ae7117d33177">

**其他信息**

**Comment by SWHL** [comment]
我遇到了同样的问题，你这是解决了吗？

**Comment by Hakstar** [comment]
> 我遇到了同样的问题，你这是解决了吗？

我换了个方法，先将模型转为onnx格式，再通过项目内的脚本对onnx进行裁剪，这样是可行的
