### ISSUE TITLE
尝试将ssdlite_mobilenet_v3_small转成onnx格式，成功了但是onnx推理报错

### ISSUE THREAD

**Issue by ruyijidan** [PaddlePaddle/Paddle2ONNX#136]
报错如下：
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node () Op (Mul) [ShapeInferenceError] Incompatible dimensions`
说的应该是Mul在推理时的维度不匹配。
查看了一下转换后的模型结构，这里的INPUTS A和B是不是运算顺序反了，导致计算维度不匹配？

**Comment by ruyijidan** [comment]
![Uploading image.png…]()

**Comment by ruyijidan** [comment]
![image](https://user-images.githubusercontent.com/40780469/97099862-b754f280-16c8-11eb-8935-df3a2005c9f4.png)

**Comment by ruyijidan** [comment]
![image](https://user-images.githubusercontent.com/40780469/97099870-d2bffd80-16c8-11eb-8c6c-c99f4466b4d5.png)

**Comment by Channingss** [comment]
@ruyijidan 能否提供模型给到我们测试一下，chenlingchi@baidu.com或者chen_lingchi@163.com

**Comment by ruyijidan** [comment]
已经发了。模型其实就是套件里的https://paddlemodels.bj.bcebos.com/object_detection/mobile_models/lite/ssdlite_mobilenet_v3_small.tar

**Comment by Channingss** [comment]
@ruyijidan 好的，这边尽快定位问题并回复。
