### ISSUE TITLE
为什么model_zoo没有了呢？？？

### ISSUE THREAD

**Issue by mjz0110** [PaddlePaddle/Paddle2ONNX#1372]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**
为什么model_zoo没有了呢？？？
**问题描述**
请在此处详细的描述报错信息
为什么model_zoo没有了呢？？？

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
为什么model_zoo没有了呢？？？

**其他信息**
为什么model_zoo没有了呢？？？

**Comment by Zheng-Bicheng** [comment]
model_zoo都是老的Paddle模型，不保证能用，所以删除了。请前往Paddle套件下载最新的模型并使用P2O来转换。
