### ISSUE TITLE
pamodel

### ISSUE THREAD

**Issue by ouyangpingbu** [PaddlePaddle/Paddle2ONNX#139]
How Can convert my model to onnx, when my model files are model.pdmodel  model.pdopt  model.pdparams

**Comment by Channingss** [comment]
@ouyangpingbu you can change their names:  `model.pdmodel ` to `__model__` and  `model.pdparams` to `__params__`.

**Comment by Channingss** [comment]
@ouyangpingbu Sorry, the previously provided method cannot solve this problem. You need to call the interface [save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/save_inference_model_cn.html#save-inference-model) after loading the model.
