### ISSUE TITLE
SLANetv2 转 onnx 不支持while，什么时候解决呢？或者有没有其他方式可以导出onnx呢？

### ISSUE THREAD

**Issue by yoliax** [PaddlePaddle/Paddle2ONNX#1391]
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /workspace/models/ch_ppstructure_openatom_SLANetv2_infer/inference.pdmodel
[Paddle2ONNX] Parameters file path: /workspace/models/ch_ppstructure_openatom_SLANetv2_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including while,
[ERROR] Due to the unsupported operators, the conversion is aborted.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1726811834 (unix time) try "date -d @1726811834" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x33cb51) received by PID 3394385 (TID 0x7ff2b5302740) from PID 3394385 ***]

**Comment by Zheng-Bicheng** [comment]
回退到 Paddle2ONNX 1.2.5

**Comment by yoliax** [comment]
@Zheng-Bicheng 
> 回退到 Paddle2ONNX 1.2.5


已经回退到paddle2onnx=1.2.5, paddlepaddle=2.6.0 ,命令如下
paddle2onnx --model_dir /workspace/models/**ch_ppstructure_openatom_SLANetv2_infe**r \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --opset_version 16 \
            --save_file /workspace/models/ch_ppstructure_openatom_SLANetv2_infer/model.onnx
            

还有报错
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /workspace/models/ch_ppstructure_openatom_SLANetv2_infer/inference.pdmodel
[Paddle2ONNX] Parameters file path: /workspace/models/ch_ppstructure_openatom_SLANetv2_infer/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,
[ERROR] Due to the unsupported operators, the conversion is aborted.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1728465566 (unix time) try "date -d @1728465566" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x9258f) received by PID 599439 (TID 0x7fcb346cd740) from PID 599439 ***]

Aborted (core dumped)

如何解决呢？ch_ppstructure_openatom_SLANetv2_infe 这个模型

**Comment by yoliax** [comment]
@Zheng-Bicheng 可否提供一个转换成功的 ch_ppstructure_openatom_SLANetv2_infer onnx模型呢？

**Comment by Zheng-Bicheng** [comment]
已经支持while算子，请更新到 1.2.10 使用

**Comment by Zheng-Bicheng** [comment]
先关闭这个Issues，有问题请再打开并 @Zheng-Bicheng
