### ISSUE TITLE
请教大家一个问题，我在使用paddlespeech的kws时，想把模型转为静态图或者onnx，均出现以下报错，要怎么解决才能导出模型？

### ISSUE THREAD

**Issue by eli-zheng-ubtech** [PaddlePaddle/Paddle2ONNX#1398]
请教大家一个问题，我在使用paddlespeech的kws时，想把模型转为静态图或者onnx，均出现以下报错，要怎么解决才能导出模型？
![image](https://github.com/user-attachments/assets/ec4857f8-59f1-494f-a1a8-a876932913c1)

**Comment by Zheng-Bicheng** [comment]
这个看上去是框架部分的问题，问一下 Paddle 框架的工程师呢？

**Comment by Zheng-Bicheng** [comment]
去 Paddle Issues 提问下
