### ISSUE TITLE
SLANet_plus表格模型无法转换

### ISSUE THREAD

**Issue by Joker1212** [PaddlePaddle/Paddle2ONNX#1405]
在转换paddlex中的SLANet_plus表格模型，无法转换为onnx，提示常量算子好像不支持
![image](https://github.com/user-attachments/assets/6fa13968-461e-4713-b5ee-8b524a9a924d)

aistudio@jupyter-11515527-8327948:~$ paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./table.onnx --opset_version 16 --enable_onnx_checker True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Parameters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including while,
[ERROR] Due to the unsupported operators, the conversion is aborted.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

**Comment by Joker1212** [comment]
按照其他issue切换到版本1.2.5，也还是不行，看解释好像是这个模型两种冲突的算子都有，导致不管怎么样都无法转换
aistudio@jupyter-11515527-8327948:~$ paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ./table.onnx --opset_version 14 --enable_onnx_checker True
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Parameters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including conditional_block,select_input,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by Zheng-Bicheng** [comment]
已经更新支持 while 算子，等待 CI 结束后 安装 Paddle2ONNX v1.2.10 使用:

* https://github.com/PaddlePaddle/Paddle2ONNX/actions/runs/11362622694

**Comment by Zheng-Bicheng** [comment]
先关闭这个Issues，有问题请再打开并 @Zheng-Bicheng
