### ISSUE TITLE
导出一直报错IndexError: Input undefined_var_1 is undefined!，不管用什么linux系统，确认了没有少参数

### ISSUE THREAD

**Issue by Joker1212** [PaddlePaddle/Paddle2ONNX#1411]
[models.zip](https://github.com/user-attachments/files/17397516/models.zip)

开始使用
paddlepaddle==3.0.0b1
paddle2onnx==2.1.10
![image](https://github.com/user-attachments/assets/5821001d-23e4-49ec-ba52-944089a8aad4)
将paddle2onnx换1.2.9，同样的命令就没有这个报错，还是之前的while算子问题
![image](https://github.com/user-attachments/assets/4fac33e2-8355-4eb6-b691-6263ac358941)

模型是paddlex的slanet_plus https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/table_structure_recognition.md

**Comment by Zheng-Bicheng** [comment]
Paddle2ONNX目前支持的依赖库版本如下：

* PaddlePaddle == 2.6.0
* onnxruntime >= 1.10.0

PaddlePaddle3.0在支持中，需要等待

**Comment by Zheng-Bicheng** [comment]
有东西可以验证这个模型是否正确嘛？

**Comment by Joker1212** [comment]
> 有东西可以验证这个模型是否正确嘛？

使用paddle2.6.0会有其他的报错
<img width="752" alt="image" src="https://github.com/user-attachments/assets/a7e78449-944f-4d8f-ac30-76a1df550f95">
<img width="1062" alt="image" src="https://github.com/user-attachments/assets/f5301736-5b70-400e-a020-64279d2188fd">

模型是从PaddleX的表格识别SLA产线下载的，内部结构我不太懂, 按paddleX的示例，执行时会自动下载模型，https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/table_structure_recognition.md

**Comment by Zheng-Bicheng** [comment]
AIStudio下你不能简单粗暴的 `pip install paddlepaddle==2.6.0` ，要切换项目版本到 paddle2.6.0

麻烦测试下以下模型是否正确

[inference.zip](https://github.com/user-attachments/files/17405407/inference.zip)

**Comment by Zheng-Bicheng** [comment]
@Joker1212

**Comment by Zheng-Bicheng** [comment]
@Joker1212 Hello 模型可以用的话回复我一下哦，我合入到主分支内，这样你就能在星河社区上用啦

**Comment by Joker1212** [comment]
> @Joker1212 Hello 模型可以用的话回复我一下哦，我合入到主分支内，这样你就能在星河社区上用啦

模型完全没有问题，非常感谢哈，但是我自己在启动环境的时候就算选择2.6.2的paddle环境，还是会有这个报错，emmm,是内部有修代码吗？
