### ISSUE TITLE
how to convert model using python code

### ISSUE THREAD

**Issue by tvone** [PaddlePaddle/Paddle2ONNX#1414]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
I don't want to use paddle2onnx command line, How to use it using python code, thank you

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by jzhang533** [comment]
```python
import paddle2onnx

paddle2onnx.export(
        model_file='./demo.pdmodel',
        params_file='./demo.pdiparams',
        save_file='./demo.onnx'
        )
```
