### ISSUE TITLE
自己微调的模型转换为onnx报错Oops, there are some operators not supported yet, including isnan_v2,[ERROR] Due to the unsupported operators, the conversion is aborted.

### ISSUE THREAD

**Issue by RicardaY** [PaddlePaddle/Paddle2ONNX#1415]
**问题描述**
[Paddle2ONNX] Oops, there are some operators not supported yet, including isnan_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by Billybeast2003** [comment]
I had the same issue
paddle2onnx==1.2.11
paddlepaddle-gpu==2.5.2
"paddleocr>=2.0.1"

**Comment by RicardaY** [comment]
> I had the same issue
> paddle2onnx==1.2.11
> paddlepaddle-gpu==2.5.2
> "paddleocr>=2.0.1"
请问你解决了吗，我到现在也没找到解决办法

**Comment by GreatV** [comment]
更新一下PaddleOCR，重新训练一下，之前引入了isnan op

**Comment by RicardaY** [comment]
> 更新一下PaddleOCR，重新训练一下，直接引入了isnan op

还真是，解决了，感谢
