### ISSUE TITLE
[ERROR] Cannot found attribute threshold in op: relu6

### ISSUE THREAD

**Issue by LijialinHub** [PaddlePaddle/Paddle2ONNX#1417]
在使用paddle2onnx过程中报错 [ERROR] Cannot found attribute threshold in op: relu6，我的paddle版本2.6.1 paddle2onnx版本为paddle2onnx     1.0.6， 我看到现在最新版本是1.2.11版本的，并且在lssues区看见在新版中该bug已经修复，但是我用源码编译安装频频出错，用pip的方式安装最高能安装到1.0.6的版本，求解，求大神指导 谢谢！ 最好可以提供一个whl也可以 我是python3.8

**Comment by LijialinHub** [comment]
> 在使用paddle2onnx过程中报错 [ERROR] Cannot found attribute threshold in op: relu6，我的paddle版本2.6.1 paddle2onnx版本为paddle2onnx 1.0.6， 我看到现在最新版本是1.2.11版本的，并且在lssues区看见在新版中该bug已经修复，但是我用源码编译安装频频出错，用pip的方式安装最高能安装到1.0.6的版本，求解，求大神指导 谢谢！ 最好可以提供一个whl也可以 我是python3.8

这是我在将pp mobileSeg的推理模型转为onnx模型过程中遇到的问题。

**Comment by Zheng-Bicheng** [comment]
@CvBokchoy 请下载最新的 Paddle2ONNX 使用，已经支持 Windows 平台

**Comment by LijialinHub** [comment]
> @CvBokchoy 请下载最新的 Paddle2ONNX 使用，已经支持 Windows 平台

thank you very
