### ISSUE TITLE
什么时候pip可以下载最新版的paddle2onnx python库呢，现在最新是1.0.6

### ISSUE THREAD

**Issue by LijialinHub** [PaddlePaddle/Paddle2ONNX#1418]

**Comment by 188080501** [comment]
同问，希望能直接安装最新版本

现在我自己编译源码报错：
LINK : fatal error LNK1104: 无法打开文件“python310.lib” [C:\Users\Jason\AppData\Local\Temp\build-via-sdist-nmcq4q1z\paddle2onnx-1.2.11\.setuptools-cmake-build\paddle2onnx_cpp2py_export.vc

不知道如何解决，电脑已经安装了310版本，并且正确设置了PATH，始终解决不了。如果可以直接pip安装最新版本的话会方便很多

**Comment by LijialinHub** [comment]
对对对，我也是卡在这里了，环境变量都加了 还不行，还在解决中，如果咱俩哪个人解决了记得留言哈哈From iPhone 在 2024年10月23日，17:58，Jason ***@***.***> 写道：﻿
同问，希望能直接安装最新版本
现在我自己编译源码报错：
LINK : fatal error LNK1104: 无法打开文件“python310.lib” [C:\Users\Jason\AppData\Local\Temp\build-via-sdist-nmcq4q1z\paddle2onnx-1.2.11.setuptools-cmake-build\paddle2onnx_cpp2py_export.vc
不知道如何解决，电脑已经安装了310版本，并且正确设置了PATH，始终解决不了。如果可以直接pip安装最新版本的话会方便很多

**Comment by 188080501** [comment]
我把我找到的方法全部都试了，都不行。。放弃了，等过段时间吧，我搜索了没人提issuse，可能是一个暂时的bug，等官方更新pip的版本直接安装或者等过几个版本再尝试源码编译下

**Comment by LijialinHub** [comment]
够呛会出 Windows 版本的了，你去看 pipy 官网，1.0.6 后边就没再提供 Windows 版本了，到现在 1.2.11 已经很多个版本没有提供了😂From iPhone 在 2024年10月23日，18:02，Jason ***@***.***> 写道：﻿
我把我找到的方法全部都试了，都不行。。放弃了，等过段时间吧，我搜索了没人提issuse，可能是一个暂时的bug，等官方更新pip的版本直接安装或者等过几个版本再尝试源码编译下

**Comment by Zheng-Bicheng** [comment]
暂时没人力适配 Windows 版本，Windows 的使用者太少了，现在发包都是发 Linux 的包，Windows 需要等一段时间了。

**Comment by longer95** [comment]
有大佬解决了吗

**Comment by 188080501** [comment]
> 有大佬解决了吗

找一台Linux电脑
我现在就是在Windows训练和开发，然后要导出ONNX的时候，就把模型scp到Linux系统里导出下

**Comment by Zheng-Bicheng** [comment]
请下载最新的 Paddle2ONNX 使用，已经支持 Windows 平台

**Comment by Zheng-Bicheng** [comment]
@188080501 @CvBokchoy @longer95
