### ISSUE TITLE
请问Paddle2ONNX可以配合哪一个PaddleDetection模型使用？

### ISSUE THREAD

**Issue by 188080501** [PaddlePaddle/Paddle2ONNX#1423]
我尝试了 PP-YOLOE_plus-L和YOLOX-L模型，可以正常导出ONNX，但是加载运行时报错
Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1"

尝试多个方法都无法解决这个问题，也有其他人提了同个issuse，如下：
https://github.com/PaddlePaddle/Paddle2ONNX/issues/1375

然后我尝试了FasterRCNN-ResNet101模型，但是转换时报错，无法正常得到onnx文件
LodTensorArray is not supported.

Paddle2ONNX已经使用了最新版本1.2.11
PaddleX训练的模型，使用的是3.0-beta1

所以请教一下，如果我想ONNX做目标检测，我应该使用哪个模型？或者说是我参数错误导致？

**Comment by 188080501** [comment]
语义分割 Deeplabv3_Plus-R50 模型
实例分割 Mask-RT-DETR-X 模型
我都已经跑通，得到ONNX模型并且正常推理，现在想找一个目标检测模型用

**Comment by 188080501** [comment]
我又尝试了DETR-R50模型，结果训练出来mAP全部是0，也无法正常使用
关联的issuse：https://github.com/PaddlePaddle/PaddleDetection/issues/8918

不过这个和Paddle2ONNX没关系，Paddle2ONNX在这个模型上是正常转换，且ONNX可以推理，但是无法得到正常结果

**Comment by Zheng-Bicheng** [comment]
PPYOLOE应该没问题啊，是可以正常导出的

**Comment by Zheng-Bicheng** [comment]
PaddleDetection官方提供的预训练模型也不可以导出了吗？

**Comment by 188080501** [comment]
终于搞定了，换了PicoDet-L模型，一切正常了，可以在ONNX推理

**Comment by Zheng-Bicheng** [comment]
Picodet、PPYOLOE、和主流的Yolo系列模型应该都是可以的，后期更新的旋转框检测有些问题，没来得及适配。

**Comment by 188080501** [comment]
> PPYOLOE应该没问题啊，是可以正常导出的

我是自己训练的，可以导出，但是ONNX加载报错，也有其他人遇到了同样的问题

报错内容：Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1"

**Comment by Zheng-Bicheng** [comment]
@188080501 方便把模型上传下嘛

**Comment by 188080501** [comment]
这个是我基于YOLOX-T训练的模型
[inference.zip](https://github.com/user-attachments/files/17744124/inference.zip)
[model.onnx.zip](https://github.com/user-attachments/files/17744126/model.onnx.zip)

我的环境是：
PaddleX 3.0-beta1
paddlepaddle-gpu 3.0.0b2
Windows10 ltsc 2019
Python 3.10
CUDA 11.8

训练的参数是：
python main.py -c paddlex/configs/object_detection/YOLOX-T.yaml -o Global.mode=train -o Global.dataset_dir=./dataset/Examples/det_coco_examples -o Train.num_classes=4 -o Global.device=gpu:0

训练中eval log:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.175
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.394
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.109
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.104
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.274
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.067
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.209
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.317
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.368
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.164
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.462
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.413
[11/14 14:31:58] ppdet.engine.callbacks INFO: Total sample number: 176, average FPS: 31.10683324456071

训练好后，我把模型拷贝到了一台Linux电脑中，再调用Paddle2ONNX，Paddle2ONNX的版本是:
paddle2onnx-1.2.11 with python>=3.8, paddlepaddle>=2.0.0

Paddle2ONNX命令和log：
 paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams  --save_file model.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Parameters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [strided_slice: image_strided_slice_0] While has strides, Requires the minimal opset version of 10.
[Paddle2ONNX] [strided_slice: image_strided_slice_1] While has strides, Requires the minimal opset version of 10.
[Paddle2ONNX] [strided_slice: image_strided_slice_2] While has strides, Requires the minimal opset version of 10.
[Paddle2ONNX] [strided_slice: image_strided_slice_3] While has strides, Requires the minimal opset version of 10.
[Paddle2ONNX] [range: range_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_2.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_3.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_4.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [range: range_5.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] Requires the minimal opset version of 10.
[Paddle2ONNX] Due to the operator: nearest_interp_v2, requires opset_version >= 11.
[Paddle2ONNX] Due to the operator: strided_slice, requires opset_version >= 10.
[Paddle2ONNX] Opset version will change to 11 from 9
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[WARN][Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] [WARNING] Due to the operator multiclass_nms3, the exported ONNX model will only supports inference with input batch_size == 1.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.

最后，我在ONNX中使用这个导出的模型，报错信息如下：
Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1

**Comment by Zheng-Bicheng** [comment]
这里看上去是因为NMS输出结果出问题的了导致的，具体我再排查下

**Comment by Zheng-Bicheng** [comment]
临时解决方案是导出模型时将 PaddlePaddle 版本设置为 2.6.0

**Comment by Zheng-Bicheng** [comment]
我在 Mac 下推理没有复现这个问题

**Comment by Zheng-Bicheng** [comment]
onnxruntime版本是1.20.0吗

**Comment by 188080501** [comment]
我这里onnxruntime用的是1.18.1

**Comment by Zheng-Bicheng** [comment]
> 我这里onnxruntime用的是1.18.1

升级一下试试呗，我这验证出来没问题的呀

**Comment by Zheng-Bicheng** [comment]
@188080501 另外 Windows 的 Paddle2ONNX 可以用了，不需要再用 Linux 了

**Comment by 188080501** [comment]
> @188080501 另外 Windows 的 Paddle2ONNX 可以用了，不需要再用 Linux 了

感谢升级，我去试下

**Comment by 188080501** [comment]
> > 我这里onnxruntime用的是1.18.1
> 
> 升级一下试试呗，我这验证出来没问题的呀

我把Paddle2ONNX升级1.3.0版本了，还是同样的报错。我现在直接用python脚本加载的，也会报错，python如下：

```
import onnx
print(onnx.__version__)
if __name__ == '__main__':
    model = onnx.load_model( "model.onnx" )
    onnx.checker.check_model(model, full_check=True)
```

报错信息:
```
 python3.8 test.py
1.17.0
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    onnx.checker.check_model(model, full_check=True)
  File "/home/jason/.local/lib/python3.8/site-packages/onnx/checker.py", line 179, in check_model
    C.check_model(
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] Inference error(s): (op_type:Gather, node name: Gather.8): [ShapeInferenceError] data tensor must have rank >= 1
(op_type:Gather, node name: Gather.10): [ShapeInferenceError] data tensor must have rank >= 1
(op_type:Reshape, node name: Reshape.32): [TypeInferenceError] Input 0 expected to have type but instead is null
```

这个是我在Linux系统下跑的，是1.17.0。Windows下我用的是1.18.0。都有相同的报错，无论C++还是Python
看起来这个是ONNX的版本问题？ 我先想办法升级下ONNX版本然后再测试下

**Comment by tsrdsy** [comment]
兄弟，同问，解决了吗，我在将mot_ppyoloe_l_36e_pipeline转为onnx也是这个报错，在
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: mobilenetv3\mot_ppyoloe_l_36e_pipeline/model.pdmodel
[Paddle2ONNX] Parameters file path: mobilenetv3\mot_ppyoloe_l_36e_pipeline/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [reduce_mean: mean_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [reduce_mean: mean_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [reduce_mean: mean_2.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [reduce_mean: mean_3.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] Requires the minimal opset version of 10.
[Paddle2ONNX] Use opset_version = 11 for ONNX export.
[WARN][Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] [WARNING] Due to the operator multiclass_nms3, the exported ONNX model will only supports inference with input batch_size == 1.
[Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.

在验证的时候同时也是
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from mot_ppyoloe_l_36e_pipeline.onnx failed:Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1

**Comment by 188080501** [comment]
> 兄弟，同问，解决了吗，我在将mot_ppyoloe_l_36e_pipeline转为onnx也是这个报错，在 [Paddle2ONNX] Start to parse PaddlePaddle model... [Paddle2ONNX] Model file path: mobilenetv3\mot_ppyoloe_l_36e_pipeline/model.pdmodel [Paddle2ONNX] Parameters file path: mobilenetv3\mot_ppyoloe_l_36e_pipeline/model.pdiparams [Paddle2ONNX] Start to parsing Paddle model... [Paddle2ONNX] [reduce_mean: mean_0.tmp_0] Requires the minimal opset version of 11. [Paddle2ONNX] [reduce_mean: mean_1.tmp_0] Requires the minimal opset version of 11. [Paddle2ONNX] [reduce_mean: mean_2.tmp_0] Requires the minimal opset version of 11. [Paddle2ONNX] [reduce_mean: mean_3.tmp_0] Requires the minimal opset version of 11. [Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] Requires the minimal opset version of 10. [Paddle2ONNX] Use opset_version = 11 for ONNX export. [WARN][Paddle2ONNX] [multiclass_nms3: multiclass_nms3_0.tmp_1] [WARNING] Due to the operator multiclass_nms3, the exported ONNX model will only supports inference with input batch_size == 1. [Paddle2ONNX] PaddlePaddle model is exported as ONNX format now.
> 
> 在验证的时候同时也是 onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from mot_ppyoloe_l_36e_pipeline.onnx failed:Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1

没有解决，我现在是paddlex3.0b2，配合onnx 1.20，一样的报错没有区别，不是ONNX版本问题，是其他东西导致的，暂时不知道是什么原因

要用目标检测的话，你可以看下PicoDet或者RT-DETR，这是可以的。PP-YOLOE不行

**Comment by yikoudamifan** [comment]
请问这一块有解决方案了吗？，我尝试了yolo3，pp-yolo，pp-yoloe都有这样的问题

**Comment by 188080501** [comment]
> 请问这一块有解决方案了吗？，我尝试了yolo3，pp-yolo，pp-yoloe都有这样的问题

如果一定要用pp-yoloe的话好像是有解决方法，翻一下其他issues，好像要写代码改什么地方
我自己没继续研究了，换了PicoDet，等下个版本再回来看下

**Comment by yikoudamifan** [comment]
> > 请问这一块有解决方案了吗？，我尝试了yolo3，pp-yolo，pp-yoloe都有这样的问题
> 
> 如果一定要用pp-yoloe的话好像是有解决方法，翻一下其他issues，好像要写代码改什么地方 我自己没继续研究了，换了PicoDet，等下个版本再回来看下

好的，谢谢

**Comment by moliwei2019** [comment]
> 实例分割 Mask-RT-DETR-X 模型

你好，请问你能将Mask-RT-DETR-X的onnx模型成功导出为trt模型吗，我在这一步使用trtexec导出trt模型的时候遇到了报错

![Image](https://github.com/user-attachments/assets/e4bb90f2-9171-45c6-b307-527475d60eb9)

另外，我在测试Mask-RT-DETR-X onnx模型的时候遇到了报错

![Image](https://github.com/user-attachments/assets/f53644f0-ad9e-48ce-b5b8-e27bc423723e)

希望能够得到您的回复以及建议

**Comment by tsrdsy** [comment]
首先我先声明一下，我没有尝试训练或推理过实例分割 Mask-RT-DETR-X 模型，以下内容是根据图片报错进行回答
第一张图片的问题
"
Error[10]: Could not find any implementation for node {ForeignNode[(Unnamed Layer* 1897) [Shuffle]...Reshape.259]}Error[10]: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[(Unnamed Layer* 1897) [Shuffle]...Reshape.259]}.)
"
可以使用Netron这个网站去查看以下onnx模型中是否真的存在Layer* 1897，确认这一层的参数，或许在模型定义时或者训练时，出现的网络层数的相关问题所导致的

第二张图片的问题
"
ValueError: Unsupported arch: DETR
"
问题在于配置文件，可能是infer_cfg.yml之类的文件中的arch被设置成DETR，但是推理文件中仅支持expect {'DeepSORT', ...}如果一定要使用DETR的话，要将
supported_archs = {'DeepSORT', 'StrongBaseline', 'S2ANet'}
修改成
supported_archs = {'DETR', 'DeepSORT', 'StrongBaseline', 'S2ANet'}
然后就是添加加载DETR的相关加载模型

以上就是我对你本次问题的回答，希望对你有所帮助
祝你实验顺利


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle2ONNX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年2月13日(星期四) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle2ONNX] 请问Paddle2ONNX可以配合哪一个PaddleDetection模型使用？ (Issue #1423)





  
实例分割 Mask-RT-DETR-X 模型
  
你好，请问你能将Mask-RT-DETR-X的onnx模型成功导出为trt模型吗，我在这一步使用trtexec导出trt模型的时候遇到了报错
 
image.png (view on web)
 
另外，我在测试Mask-RT-DETR-X onnx模型的时候遇到了报错
 
image.png (view on web)
 
希望能够得到您的回复以及建议

**Comment by moliwei2019** [comment]
> 以上就是我对你本次问题的回答，希望对你有所帮助

十分感谢您的回复！

对于第一个问题我已经解决，是因为没有固定ONNX模型中im_shape和scale_factor这两个参数导致的，最后参考官方文档完成了转换。

**Comment by 188080501** [comment]
我把paddlepaddle和paddlex都升级到了rc0的版本，使用PP-YOLOE_plus-M模型，这个问题还是存在
Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1

**Comment by yikoudamifan** [comment]
> 我把paddlepaddle和paddlex都升级到了rc0的版本，使用PP-YOLOE_plus-M模型，这个问题还是存在 Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1

更改一下onneruntime版本

**Comment by 188080501** [comment]
> > 我把paddlepaddle和paddlex都升级到了rc0的版本，使用PP-YOLOE_plus-M模型，这个问题还是存在 Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1
> 
> 更改一下onneruntime版本

我的onnxruntime版本是 1.20.0

https://github.com/microsoft/onnxruntime/releases/tag/v1.20.0

这个版本已经足够了吧，或者说确实是版本问题?

**Comment by yikoudamifan** [comment]
> must



> > > 我把paddlepaddle和paddlex都升级到了rc0的版本，使用PP-YOLOE_plus-M模型，这个问题还是存在 Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1
> > 
> > 
> > 更改一下onneruntime版本
> 
> 我的onnxruntime版本是 1.20.0
> 
> https://github.com/microsoft/onnxruntime/releases/tag/v1.20.0
> 
> 这个版本已经足够了吧，或者说确实是版本问题?

版本太高了，改成1.10.0试一下

**Comment by 188080501** [comment]
> > must
> 
> > > > 我把paddlepaddle和paddlex都升级到了rc0的版本，使用PP-YOLOE_plus-M模型，这个问题还是存在 Node (Gather.8) Op (Gather) [ShapeInferenceError] data tensor must have rank >= 1
> > > 
> > > 
> > > 更改一下onneruntime版本
> > 
> > 
> > 我的onnxruntime版本是 1.20.0
> > https://github.com/microsoft/onnxruntime/releases/tag/v1.20.0
> > 这个版本已经足够了吧，或者说确实是版本问题?
> 
> 版本太高了，改成1.10.0试一下

降版本又有其他问题   T.T   

我还是等等看，看官方能不能修复，或者有没有其他解决方案

**Comment by Hold-on-li** [comment]
> 终于搞定了，换了PicoDet-L模型，一切正常了，可以在ONNX推理

您好，请教一下 我自己训练的picodet-L模型转onnx后推理发现精度差异跟原paddle模型差异很大，Inputs里有两个一个是image,另外一个是scale_factor，差异比较大的情况是正常的吗？并且我想转openvino模型时发现报错

**Comment by Hold-on-li** [comment]
> > 以上就是我对你本次问题的回答，希望对你有所帮助
> 
> 十分感谢您的回复！
> 
> 对于第一个问题我已经解决，是因为没有固定ONNX模型中im_shape和scale_factor这两个参数导致的，最后参考官方文档完成了转换。

您好，官网文档相关的地址能否方便发一下呢，非常感谢了

**Comment by 188080501** [comment]
> > 终于搞定了，换了PicoDet-L模型，一切正常了，可以在ONNX推理
> 
> 您好，请教一下 我自己训练的picodet-L模型转onnx后推理发现精度差异跟原paddle模型差异很大，Inputs里有两个一个是image,另外一个是scale_factor，差异比较大的情况是正常的吗？并且我想转openvino模型时发现报错

有另外2个im_shape和scale_factor正常，onnx推理的时候带上就可以了，给你一个代码参考:

```
    std::vector< float >   imShapeData_;
    std::vector< int64_t > imShapeDims_;
    std::vector< float >   scaleFactorData_;
    std::vector< int64_t > scaleFactorDims_;

    imShapeDims_ = { 1, 2 };
    imShapeData_ = { static_cast< float >( size_.width() ), static_cast< float >( size_.height() ) };

    scaleFactorDims_ = { 1, 2 };
    scaleFactorData_ = { 1.f, 1.f };

        if ( const QString name = inputNames_[ index ]; name == "im_shape" )
        {
            values->emplace_back(
                Ort::Value::CreateTensor< float >(
                    memoryInfo_,
                    imShapeData_.data(),
                    imShapeData_.size(),
                    imShapeDims_.data(),
                    imShapeDims_.size() ) );
        }
        else if ( name == "scale_factor" )
        {
            values->emplace_back(
                Ort::Value::CreateTensor< float >(
                    memoryInfo_,
                    scaleFactorData_.data(),
                    scaleFactorData_.size(),
                    scaleFactorDims_.data(),
                    scaleFactorDims_.size() ) );
        }
```

然后给onnx的Ort::Value会有3个东西，分别是图像和这2个附加的参数

当然你也可以在onnx模型本身上修改，直接把这2个写死，但是这样导出的模型就要多一步处理，我是直接做到推理那边了，这样对模型的兼容要好一些

**Comment by Hold-on-li** [comment]
> > > 终于搞定了，换了PicoDet-L模型，一切正常了，可以在ONNX推理
> > 
> > 
> > 您好，请教一下 我自己训练的picodet-L模型转onnx后推理发现精度差异跟原paddle模型差异很大，Inputs里有两个一个是image,另外一个是scale_factor，差异比较大的情况是正常的吗？并且我想转openvino模型时发现报错
> 
> 有另外2个im_shape和scale_factor正常，onnx推理的时候带上就可以了，给你一个代码参考:
> 
> ```
>     std::vector< float >   imShapeData_;
>     std::vector< int64_t > imShapeDims_;
>     std::vector< float >   scaleFactorData_;
>     std::vector< int64_t > scaleFactorDims_;
> 
>     imShapeDims_ = { 1, 2 };
>     imShapeData_ = { static_cast< float >( size_.width() ), static_cast< float >( size_.height() ) };
> 
>     scaleFactorDims_ = { 1, 2 };
>     scaleFactorData_ = { 1.f, 1.f };
> 
>         if ( const QString name = inputNames_[ index ]; name == "im_shape" )
>         {
>             values->emplace_back(
>                 Ort::Value::CreateTensor< float >(
>                     memoryInfo_,
>                     imShapeData_.data(),
>                     imShapeData_.size(),
>                     imShapeDims_.data(),
>                     imShapeDims_.size() ) );
>         }
>         else if ( name == "scale_factor" )
>         {
>             values->emplace_back(
>                 Ort::Value::CreateTensor< float >(
>                     memoryInfo_,
>                     scaleFactorData_.data(),
>                     scaleFactorData_.size(),
>                     scaleFactorDims_.data(),
>                     scaleFactorDims_.size() ) );
>         }
> ```
> 
> 然后给onnx的Ort::Value会有3个东西，分别是图像和这2个附加的参数
> 
> 当然你也可以在onnx模型本身上修改，直接把这2个写死，但是这样导出的模型就要多一步处理，我是直接做到推理那边了，这样对模型的兼容要好一些

好的 我试试看 非常感谢

**Comment by chiawei2002** [comment]
Mask-RT-DETR

> 语义分割 Deeplabv3_Plus-R50 模型 实例分割 Mask-RT-DETR-X 模型 我都已经跑通，得到ONNX模型并且正常推理，现在想找一个目标检测模型用

看到你的成功跑通，想請教一下
Mask-RT-DETR-M方式輸出的onnx 出來結果與infer差異很大是有哪個環節需要修改嗎?

Name: onnxruntime
Version: 1.22.1

Name: paddle2onnx
Version: 2.0.2rc3

轉乘onnx
paddle2onnx.export(model_filename="output/inference_model/mask_rtdetr_test/model.pdmodel",
                   params_filename="output/inference_model/mask_rtdetr_test/model.pdiparams",
                   save_file="output/onnx/mask_rtdetr.onnx",
                   opset_version=19)

前置作業
    # resize
    frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) 
    img_resized = cv2.resize(frame, target_size,interpolation=cv2.INTER_LINEAR)
    scale = 1.0 / 255.0
    img_resized *= scale   
    img_resized = img_resized.transpose(2, 0, 1)[np.newaxis, :]
    im_shape = np.array([[target_size[1], target_size[0]]], dtype=np.float32)
    scale_factor = np.array([[target_size[1] / target_size[1], target_size[0] / orig_w]], dtype=np.float32)

呼叫onnxruntime
 sess = onnxruntime.InferenceSession(onnx_path, providers=['CUDAExecutionProvider'])
outputs = sess.run(output_names, input_feed)

主要outputs 在score上分數差太多，是有什麼地方需要修改的?

再麻煩你指導，感謝你!!

**Comment by 188080501** [comment]
> Mask-RT-DETR
> 
> > 语义分割 Deeplabv3_Plus-R50 模型 实例分割 Mask-RT-DETR-X 模型 我都已经跑通，得到ONNX模型并且正常推理，现在想找一个目标检测模型用
> 
> 看到你的成功跑通，想請教一下 Mask-RT-DETR-M方式輸出的onnx 出來結果與infer差異很大是有哪個環節需要修改嗎?
> 
> Name: onnxruntime Version: 1.22.1
> 
> Name: paddle2onnx Version: 2.0.2rc3
> 
> 轉乘onnx paddle2onnx.export(model_filename="output/inference_model/mask_rtdetr_test/model.pdmodel", params_filename="output/inference_model/mask_rtdetr_test/model.pdiparams", save_file="output/onnx/mask_rtdetr.onnx", opset_version=19)
> 
> 前置作業 # resize frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) img_resized = cv2.resize(frame, target_size,interpolation=cv2.INTER_LINEAR) scale = 1.0 / 255.0 img_resized *= scale img_resized = img_resized.transpose(2, 0, 1)[np.newaxis, :] im_shape = np.array([[target_size[1], target_size[0]]], dtype=np.float32) scale_factor = np.array([[target_size[1] / target_size[1], target_size[0] / orig_w]], dtype=np.float32)
> 
> 呼叫onnxruntime sess = onnxruntime.InferenceSession(onnx_path, providers=['CUDAExecutionProvider']) outputs = sess.run(output_names, input_feed)
> 
> 主要outputs 在score上分數差太多，是有什麼地方需要修改的?
> 
> 再麻煩你指導，感謝你!!

你训练的时候mean和std改了没，和你onnx里能对齐不

**Comment by chiawei2002** [comment]
> > Mask-RT-DETR
> > > 语义分割 Deeplabv3_Plus-R50 模型 实例分割 Mask-RT-DETR-X 模型 我都已经跑通，得到ONNX模型并且正常推理，现在想找一个目标检测模型用
> > 
> > 
> > 看到你的成功跑通，想請教一下 Mask-RT-DETR-M方式輸出的onnx 出來結果與infer差異很大是有哪個環節需要修改嗎?
> > Name: onnxruntime Version: 1.22.1
> > Name: paddle2onnx Version: 2.0.2rc3
> > 轉乘onnx paddle2onnx.export(model_filename="output/inference_model/mask_rtdetr_test/model.pdmodel", params_filename="output/inference_model/mask_rtdetr_test/model.pdiparams", save_file="output/onnx/mask_rtdetr.onnx", opset_version=19)
> > 前置作業 # resize frame = cv2.cvtColor(img, cv2.COLOR_BGR2RGB).astype(np.float32) img_resized = cv2.resize(frame, target_size,interpolation=cv2.INTER_LINEAR) scale = 1.0 / 255.0 img_resized *= scale img_resized = img_resized.transpose(2, 0, 1)[np.newaxis, :] im_shape = np.array([[target_size[1], target_size[0]]], dtype=np.float32) scale_factor = np.array([[target_size[1] / target_size[1], target_size[0] / orig_w]], dtype=np.float32)
> > 呼叫onnxruntime sess = onnxruntime.InferenceSession(onnx_path, providers=['CUDAExecutionProvider']) outputs = sess.run(output_names, input_feed)
> > 主要outputs 在score上分數差太多，是有什麼地方需要修改的?
> > 再麻煩你指導，感謝你!!
> 
> 你训练的时候mean和std改了没，和你onnx里能对齐不


感謝提醒，順利解決!
主要在TestReader 裡面的image_shape 與 preprocess Resize順序定義我誤會!
感謝!
