### ISSUE TITLE
时序分类模块（TimesNet_cls），缺少算子转换失败

### ISSUE THREAD

**Issue by 188080501** [PaddlePaddle/Paddle2ONNX#1440]
我的Paddle2ONNX版本是：paddle2onnx-1.2.11 with python>=3.8, paddlepaddle>=2.0.0

转换命令和log如下：
 paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams  --save_file model.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: ./inference.pdmodel
[Paddle2ONNX] Parameters file path: ./inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including fft_r2c,
[ERROR] Due to the unsupported operators, the conversion is aborted.

C++ Traceback (most recent call last):
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

Error Message Summary:
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1732086981 (unix time) try "date -d @1732086981" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000033b9) received by PID 13241 (TID 0x7fd443546740) from PID 13241 ***]

Aborted (core dumped)

请问后续有这个支持计划吗？支持这个模型或者说支持这个算子

**Comment by 188080501** [comment]
模型文件如下：
[inference.zip](https://github.com/user-attachments/files/17827387/inference.zip)

**Comment by Zheng-Bicheng** [comment]
@188080501 不是我们不添加， ONNX 好像不支持 FFT 这个算子吧。

**Comment by Zheng-Bicheng** [comment]
* https://onnx.ai/onnx/operators/

**Comment by 188080501** [comment]
> @188080501 不是我们不添加， ONNX 好像不支持 FFT 这个算子吧。

好吧。。这个我不太了解。如果ONNX不支持的话只能等ONNX那边先更新了
