### ISSUE TITLE
pip install Paddle2ONNX发生错误

### ISSUE THREAD

**Issue by IceSugarLemon** [PaddlePaddle/Paddle2ONNX#1447]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
pip install paddle2onnx 发生错误

电脑：M1 pro MacbookPro
conda环境：
Python 3.12 
paddlepaddle==2.6.2
onnxruntime==1.20.1

**报错截图**
<img width="2025" alt="image" src="https://github.com/user-attachments/assets/b8741d02-9cf4-4e93-aa10-9983ff9312c6">

**其他信息**

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1445

**Comment by Zheng-Bicheng** [comment]
今晚发布

**Comment by Zheng-Bicheng** [comment]
可以了，重新 pip install 试试？

**Comment by IceSugarLemon** [comment]
感谢
