### ISSUE TITLE
windows环境下使用subprocess来对paddle模型文件进行转换报错subprocess.CalledProcessError

### ISSUE THREAD

**Issue by sensenforever** [PaddlePaddle/Paddle2ONNX#1461]
**问题描述**
在cmd.exe中执行命令paddle2onnx --model_dir ./save/paddle/ --model_filename model.pdmodel --params_filename model.pdiparams --save_file ./save/paddle/paddle_model.onnx --opset_version 11'可以很顺利地转换为onnx文件，这说明环境依赖以及命令输入都是没有问题的。
但是在编写.py文件时，使用subprocess就会报错subprocess.CalledProcessError

源码如下：
subprocess.run([
            "cmd", "/c",
            "paddle2onnx",
            "--model_dir", "./save/paddle/",
            "--model_filename", "model.pdmodel",
            "--params_filename", "model.pdiparams",
            "--save_file", "./save/paddle/paddle.onnx",
            "--opset_version", str(opset_version),
            "--full_graph=True"
        ], check=True)
![微信图片_20241219161059](https://github.com/user-attachments/assets/41d24b77-58b6-4545-9957-bf34e8d2541e)

报错信息：
C:\Users\zly\.conda\envs\python310\lib\site-packages\paddle\jit\dy2static\program_translator.py:712: UserWarning: full_graph=False don't support input_spec arguments. It will not produce any effect.
You can set full_graph=True, then you can assign input spec.

  warnings.warn(
I1219 16:10:03.694989 29176 program_interpreter.cc:212] New Executor is Running.
'paddle2onnx' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "E:\workProject\onnx_convert-main\convert_paddle.py", line 115, in <module>
    export_model_to_onnx(None, None, paddle_model_path, paddle_onnx_path, framework='paddlepaddle')
  File "E:\workProject\onnx_convert-main\convert_paddle.py", line 53, in export_model_to_onnx
    subprocess.run([
  File "C:\Users\zly\.conda\envs\python310\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmd', '/c', 'paddle2onnx', '--model_dir', './save/paddle/', '--model_filename', 'model.pdmodel', '--params_filename', 'model.pdiparams', '--save_file', './save/paddle/paddle.onnx', '--opset_version', '11', '--full_graph=True']' returned non-zero exit status 1.

Process finished with exit code 1
![image](https://github.com/user-attachments/assets/27597def-da10-4f39-80fa-385704c9f963)

**Comment by Zheng-Bicheng** [comment]
这个不太清楚诶，看上去像是开发环境的问题，不是 Paddle2ONNX 本身的问题哈。
