### ISSUE TITLE
ppocr 转onnx

### ISSUE THREAD

**Issue by PureHing** [PaddlePaddle/Paddle2ONNX#148]
@Channingss 你好，尝试使用这个工具paddle2onnx将mbv3-db ocr检测部分转为onnx，出现了如下的错误
`~$　paddle2onnx --model_dir ./Desktop/ch_det_mv3_db_infer/ch_det_mv3_db/ -s ./output --opset_version 11`

* model

![截图录屏_选择区域_20201112003556](https://user-images.githubusercontent.com/62579216/98838498-5165ba80-247f-11eb-959a-186df4dc338c.png)

```sh

----------------------
Error Message Summary:
----------------------
UnavailableError: Load operator fail to open file Desktop/ch_det_mv3_db_infer/ch_det_mv3_db/conv3_expand_bn_variance, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] at (/paddle/paddle/fluid/operators/load_op.h:41)
  [operator < load > error]
```
看issue里有人用x2paddle转成过mbv3-db的文本检测，我使用x2paddle，推荐使用这个paddle2onnx的repo，所以请问下我这里出了什么问题

**Comment by Channingss** [comment]
@PureHing 请参考[参数说明](https://github.com/PaddlePaddle/paddle2onnx#%E5%8F%82%E6%95%B0%E9%80%89%E9%A1%B9)，您的paddle模型属于'参数被保存在一个单独的二进制文件中（combined）'，执行指令的时候指定一下 --model_filename=\_\_model\_\_ 和 --params_filename=\_\_params\_\_

**Comment by PureHing** [comment]
thanks!
