### ISSUE TITLE
关于转换paddleocr中的文字检测模型出现的问题

### ISSUE THREAD

**Issue by ZHR1997** [PaddlePaddle/Paddle2ONNX#154]
![image](https://user-images.githubusercontent.com/33384210/99962889-e5af1600-2dcb-11eb-8b27-bc4277865a56.png)
用的是这三个文字检测模型
三个模型的报错的op都是一样的：
paddle2onnx --model_dir ./ --model_filename 'model' --params_filename 'params' --save_file ch_mobile_v1.1 --opset_version 10 --enable_onnx_checker True
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/python2.7.15/bin/paddle2onnx", line 11, in <module>
    load_entry_point('paddle2onnx==0.4', 'console_scripts', 'paddle2onnx')()
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 139, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 111, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 30, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 162, in build
    status = OpMapper.mapping(onnx_graph, node)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 96, in mapping
    format(node.layer_name, node.type, node.inputs, node.outputs))
Exception: Error happened when mapping node ['nearest_interp@0'] to onnx, which op_type is 'nearest_interp' with inputs: {u'OutSize': [], u'X': [u'conv2d_32.tmp_0'], u'SizeTensor': [], u'Scale': []} and outputs: {u'Out': [u'nearest_interp_0.tmp_0']}

这个要怎么去修改 才能转换成功？

**Comment by Channingss** [comment]
@ZHR1997 请问是图中哪一个模型

**Comment by ZHR1997** [comment]
> @ZHR1997 请问是图中哪一个模型

三个我都测试了   三个模型报错都是这个nearest_interp ...   我paddlepaddle版本1.8   onnx版本1.7   paddle2onnx 0.4版本的

**Comment by Channingss** [comment]
@ZHR1997 使用[第二种安装方式](https://github.com/PaddlePaddle/paddle2onnx#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F2)，手动clone后安装最新的代码，我刚刚转了第一个模型是可以的。

**Comment by ZHR1997** [comment]
> @ZHR1997 使用[第二种安装方式](https://github.com/PaddlePaddle/paddle2onnx#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F2)，手动clone后安装最新的代码，我刚刚转了第一个模型是可以的。
好的 谢谢   我再去试试看

**Comment by ZHR1997** [comment]
> @ZHR1997 使用[第二种安装方式](https://github.com/PaddlePaddle/paddle2onnx#%E5%AE%89%E8%A3%85%E6%96%B9%E5%BC%8F2)，手动clone后安装最新的代码，我刚刚转了第一个模型是可以的。

①我首先git clone https://github.com/PaddlePaddle/paddle2onnx.git，然后python setup.py install，安装最后输出了 Finished processing dependencies for paddle2onnx==0.4，应该是安装成功了。
②我然后进入下载的模型目录，执行paddle2onnx --model_dir ./ --model_filename model --params_filename params --save_file ch_mobile_1.1 --opset_version 10 --enable_onnx_checker True，还是会报错：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/python2.7.15/bin/paddle2onnx", line 11, in <module>
    load_entry_point('paddle2onnx==0.4', 'console_scripts', 'paddle2onnx')()
  File "build/bdist.linux-x86_64/egg/paddle2onnx/command.py", line 139, in main
  File "build/bdist.linux-x86_64/egg/paddle2onnx/command.py", line 111, in program2onnx
  File "build/bdist.linux-x86_64/egg/paddle2onnx/convert.py", line 74, in program2onnx
  File "build/bdist.linux-x86_64/egg/paddle2onnx/convert.py", line 30, in export_onnx
  File "build/bdist.linux-x86_64/egg/paddle2onnx/graph/onnx_graph.py", line 162, in build
  File "build/bdist.linux-x86_64/egg/paddle2onnx/op_mapper/op_mapper.py", line 96, in mapping
Exception: Error happened when mapping node ['nearest_interp@0'] to onnx, which op_type is 'nearest_interp' with inputs: {u'OutSize': [], u'X': [u'conv2d_32.tmp_0'], u'SizeTensor': [], u'Scale': []} and outputs: {u'Out': [u'nearest_interp_0.tmp_0']}


会不会是我们两之间哪里的环境出现了问题，能知道你是配置了什么版本的环境吗？

**Comment by Channingss** [comment]
@ZHR1997 你先pip uninstall  paddle2onnx，然后再重新python setup.py install。试试

**Comment by ZHR1997** [comment]
> @ZHR1997 你先pip uninstall paddle2onnx，然后再重新python setup.py install。试试

我刚刚就是先pip uninstall paddle2onnx  然后再删掉原来的paddl2onnx的代码  重新git的

**Comment by Channingss** [comment]
@ZHR1997 那你换到python3的环境试一下吧。我看了一下代码，看上去是nearest_interp的转换过程中做了字符串的判断，不兼容python2。

**Comment by ZHR1997** [comment]
> @ZHR1997 那你换到python3的环境试一下吧。我看了一下代码，看上去是nearest_interp的转换过程中做了字符串的判断，不兼容python2。

好的  我刚刚确实是用的python2.7

**Comment by ZHR1997** [comment]
> @ZHR1997 那你换到python3的环境试一下吧。我看了一下代码，看上去是nearest_interp的转换过程中做了字符串的判断，不兼容python2。

很奇怪 我这边用python3.5的环境还是有问题..... 先是用--opset_version 10进行转换的出现以下错误：
![image](https://user-images.githubusercontent.com/33384210/100056680-0d03f280-2e61-11eb-8613-fd4e1b43612f.png)

然后我改成--opset_version 11，还是有错误：
![image](https://user-images.githubusercontent.com/33384210/100056761-2efd7500-2e61-11eb-8a9a-b0d6e899f83e.png)

我感觉还是环境的问题....

**Comment by Channingss** [comment]
> > @ZHR1997 那你换到python3的环境试一下吧。我看了一下代码，看上去是nearest_interp的转换过程中做了字符串的判断，不兼容python2。
> 
> 很奇怪 我这边用python3.5的环境还是有问题..... 先是用--opset_version 10进行转换的出现以下错误：
> ![image](https://user-images.githubusercontent.com/33384210/100056680-0d03f280-2e61-11eb-8613-fd4e1b43612f.png)
> 
> 然后我改成--opset_version 11，还是有错误：
> ![image](https://user-images.githubusercontent.com/33384210/100056761-2efd7500-2e61-11eb-8a9a-b0d6e899f83e.png)
> 
> 我感觉还是环境的问题....


--enable_onnx_checker True的时候需要安装onnx

**Comment by ZHR1997** [comment]
> > > @ZHR1997 那你换到python3的环境试一下吧。我看了一下代码，看上去是nearest_interp的转换过程中做了字符串的判断，不兼容python2。
> > 
> > 
> > 很奇怪 我这边用python3.5的环境还是有问题..... 先是用--opset_version 10进行转换的出现以下错误：
> > ![image](https://user-images.githubusercontent.com/33384210/100056680-0d03f280-2e61-11eb-8613-fd4e1b43612f.png)
> > 然后我改成--opset_version 11，还是有错误：
> > ![image](https://user-images.githubusercontent.com/33384210/100056761-2efd7500-2e61-11eb-8a9a-b0d6e899f83e.png)
> > 我感觉还是环境的问题....
> 
> --enable_onnx_checker True的时候需要安装onnx

我安装的了   pip3 install onnx==1.7.0

**Comment by Channingss** [comment]
@ZHR1997 应该是pip3 install onnx==1.7.0的时候，没安装在/usr/local/python3.5.1下面，你可以自己在python的命令行里面import onnx看有安装成功么。试试pip install onnx==1.7.0，不需要特意指定pip3。

**Comment by ZHR1997** [comment]
> @ZHR1997 应该是pip3 install onnx==1.7.0的时候，没安装在/usr/local/python3.5.1下面，你可以自己在python的命令行里面import onnx看有安装成功么。试试pip install onnx==1.7.0，不需要特意指定pip3。

我把--enable_onnx_checker设置为false     onnx的model是能转出来的。
我pip安装的onnx是安装在/usr/local/python3.5.1  安装的时候说的是安装成功了，我python3进去import onnx的时候报错：ImportError: /usr/local/python3.5.1/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet 

enable_onnx_checker设置为false 对最后的结果输出应该没有影响吧？

**Comment by Channingss** [comment]
@ZHR1997 那看样子是onnx安装失败了，不影响结果，就是帮助check模型正确性的。

**Comment by ZHR1997** [comment]
> @ZHR1997 那看样子是onnx安装失败了，不影响结果，就是帮助check模型正确性的。

好的  谢谢你一下午帮我纠错了！！！

**Comment by Channingss** [comment]
@ZHR1997 客气了

**Comment by zrl4836** [comment]
opset_version=10 设置下这个参数就好了，默认是9
