### ISSUE TITLE
PaddleOCR 识别模型转换问题

### ISSUE THREAD

**Issue by LucySha** [PaddlePaddle/Paddle2ONNX#155]
采用官方给出的模型rec_crnn进行转换，三种算子不支持转换：lstm, ctc_align, top_k，请问这些算子后续可以添加吗？或者自己怎么定义这些算子的转换？谢谢~

**Comment by Channingss** [comment]
@LucySha 目前只支持转换PaddleOCR的检测模型到ONNX，两者LSTM存在比较大的差别。Paddle正在重新设计LSTM的接口，未来会考虑支持PaddleOCR，自定义算子的转换也会推出教程。
