### ISSUE TITLE
剪枝后的模型如何转onnx

### ISSUE THREAD

**Issue by JerryDeepl** [PaddlePaddle/Paddle2ONNX#158]
请问，paddlesim剪枝后保存模型 __shapes__和__params__，怎么转到onnx？谢谢

**Comment by Channingss** [comment]
@JerryDeepl 是不是您在[save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#save-inference-model) 的时候自定了model_filename=‘ shapes__’, params_filename=‘ __params’吗？
可以参考一下[教程](https://github.com/PaddlePaddle/paddle2onnx/blob/develop/examples/tutorial.ipynb)

**Comment by JerryDeepl** [comment]
按照教程，报错如下：
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.Traceback (most recent call last):
  File "/home/codeadmin/.conda/envs/paddle_env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle2onnx/command.py", line 139, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle2onnx/command.py", line 105, in program2onnx
    params_filename=params_filename)
  File "<decorator-gen-74>", line 2, in load_inference_model
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 215, in __impl__
    return func(*args, **kwargs)
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1498, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "/home/codeadmin/.conda/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4744, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::ProgramDesc::ProgramDesc(std::string const&)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:104)
使用命令
# 剪枝onnx
paddle2onnx --model_dir ${test_model} \
    --model_filename '__shapes__' \
    --params_filename '__params__' \
    --save_file ${onnx_path} \
    --opset_version 11

paddleslim使用如下保存shape https://github.com/PaddlePaddle/PaddleSlim/blob/3d2a5924fc957195c336b3aaf4a9bf95ea16a74b/paddleslim/prune/prune_io.py#L15

`_PARAMS_FILE = "__params__"
_SHAPES_FILE = "__shapes__"


def save_model(exe, graph, dirname):
    """
    Save weights of model and information of shapes into filesystem.

    Args:
        exe(paddle.fluid.Executor): The executor used to save model.
        graph(Program|Graph): The graph to be saved.
        dirname(str): The directory that the model saved into.
    """
    assert graph is not None and dirname is not None
    graph = GraphWrapper(graph) if isinstance(graph, Program) else graph

    fluid.io.save_params(
        executor=exe,
        dirname=dirname,
        main_program=graph.program,
        filename=_PARAMS_FILE)
    weights_file = os.path.join(dirname, _PARAMS_FILE)
    _logger.info("Save model weights into {}".format(weights_file))
    shapes = {}
    for var in graph.all_parameters():
        shapes[var.name()] = var.shape()
    SHAPES_FILE = os.path.join(dirname, _SHAPES_FILE)
    with open(SHAPES_FILE, "w") as f:
        json.dump(shapes, f)
        _logger.info("Save shapes of weights into {}".format(SHAPES_FILE))`


这个保存下来的__shapes__和fluid.io.save_inference_model 的__model__不一样，不知道要怎么转onnx

**Comment by Channingss** [comment]
@JerryDeepl  这边找slim的工作人员来看一下。

**Comment by Shixiaowei02** [comment]
```
InvalidArgumentError: Failed to parse program_desc from binary string.
[Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:104)
```

您好，这个报错的原因是二进制格式的错误。如果您确定输入文件路径是正确的（不是输入了一个错误格式的无关文件），请联系生成模型的逻辑的开发者，确认没有问题。谢谢！

**Comment by JerryDeepl** [comment]
> ```
> InvalidArgumentError: Failed to parse program_desc from binary string.
> [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:104)
> ```
> 
> 您好，这个报错的原因是二进制格式的错误。如果您确定输入文件路径是正确的（不是输入了一个错误格式的无关文件），请联系生成模型的逻辑的开发者，确认没有问题。谢谢！

您好，文件路径无误，模型来自paddleseg官方https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.7.0/slim/prune/README.md
自己训练出来的剪枝模型也是同样的错误

**Comment by Shixiaowei02** [comment]
请先使用官网提供的常规模型尝试是否可以正常加载，如果可以的话，确认是转换逻辑的问题还是加载时。谢谢

**Comment by JerryDeepl** [comment]
> 请先使用官网提供的常规模型尝试是否可以正常加载，如果可以的话，确认是转换逻辑的问题还是加载时。谢谢

您好：
1. 官方提供的非剪枝模型是可以正常转onnx的；
2. 模型转onnx都是参考paddle2onnx的教程来进行
3. 麻烦确认下paddleslim保存的__shape__文件 和 fluid.io.save_inference_model 保存的__model__有何不同， fluid.io.save_inference_model 保存的模型都是可以正常转的，但paddleslim save_model保存的模型，没有正常转换过

谢谢~

**Comment by Shixiaowei02** [comment]
嗯嗯，请保证 load_inference_model 的输入必须是 save_inference_model 的产出。其它文件是否与 load_inference_model 格式相同，取决于 save_inference_model 接口的外层封装是否做了保证

**Comment by Channingss** [comment]
@JerryDeepl 我看了一下slim应该没有save_inference_model的接口，请取回接口https://paddlepaddle.github.io/PaddleSlim/api_cn/prune_api.html#paddleslim.prune.Pruner.prune 返回的Program，然后调用
[save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/save_inference_model_cn.html#save-inference-model)接口，指定参数`main_program`为prune接口返回的program保存模型，再使用paddle2onnx即可。

**Comment by Shixiaowei02** [comment]
> @JerryDeepl 我看了一下slim应该没有save_inference_model的接口，请取回接口https://paddlepaddle.github.io/PaddleSlim/api_cn/prune_api.html#paddleslim.prune.Pruner.prune 返回的Program，然后调用
> [save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/save_inference_model_cn.html#save-inference-model)接口，指定参数`main_program`为prune接口返回的program保存模型，再使用paddle2onnx即可。

感谢回复
