### ISSUE TITLE
paddleseg中的shufflenetv2模型转onnx,batch_size不定项

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/Paddle2ONNX#176]
paddleseg中的shufflenetv2模型转onnx,batch_size不默认==1

**Comment by wsy1991** [comment]
此模型用的Paddleseg中humanseg下的humanseg_lite_inference模型(shufflenetv2),基于paddle=1.8.5得到

**Comment by Channingss** [comment]
> paddleseg中的shufflenetv2模型转onnx,batch_size不默认==1

因为这个模型你导出来的时候batch_size==-1，所以导出为onnx的模型也是batch_size==-1呢？是想要固定模型的batch_size=1吗
