### ISSUE TITLE
ppocr模型怎么设置输入维度可变

### ISSUE THREAD

**Issue by MachineVision123** [PaddlePaddle/Paddle2ONNX#194]
请问怎么将模型的输入维度设置为可变？
我使用paddleocr提供的dbnet推理模型进行转化，获得的onnx模型输入维度固定为[-1，3，640，640]。请问这个宽高维度怎么设为不固定的？
我转化的命令如下：
paddle2onnx -m ch_ppocr_mobile_v2.0_det_infer/ --model_filename inference.pdmodel --params_filename inference.pdiparams -s onnx/det_db/ppocr_dbnet.onnx --opset_version 11
模型地址：
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar

**Comment by Channingss** [comment]
@MachineVision123 
参考另外一个issue: 
https://github.com/PaddlePaddle/Paddle2ONNX/issues/191#issuecomment-780999059
