### ISSUE TITLE
弱弱的问一句： “手把手教你使用ONNXRunTime部署PP-OCR实现”   里面代码位于onnx_inference/目录下面

### ISSUE THREAD

**Issue by HongChow** [PaddlePaddle/Paddle2ONNX#203]
抱歉。onnx_inference文件夹在哪里，我怎么找不到。。。

**Comment by Channingss** [comment]
@HongChow 需要运行项目才会导出onnx的模型，并放置在onnx_inference目录下面

**Comment by HongChow** [comment]
> @HongChow 需要运行项目才会导出onnx的模型，并放置在onnx_inference目录下面

感谢回答，onnx模型已经导好了，很奇怪，我并没有onnx_inference的目录，还是自己建？（主要是预测调用onnx的python代码是不是paddle提供的？）

**Comment by Channingss** [comment]
@HongChow 不好意思搞错了，onnx_inference是模型推理的代码，我看了下文件里面是有onnx_inference目录呢，请问克隆的分支是1.0吗？
![image](https://user-images.githubusercontent.com/12471701/109629576-e996c500-7b7e-11eb-87f6-9e195536927a.png)

**Comment by HongChow** [comment]
原来是在AIStudio上，第一次用。非常感谢~

**Comment by HongChow** [comment]
> @HongChow 不好意思搞错了，onnx_inference是模型推理的代码，我看了下文件里面是有onnx_inference目录呢，请问克隆的分支是1.0吗？
> ![image](https://user-images.githubusercontent.com/12471701/109629576-e996c500-7b7e-11eb-87f6-9e195536927a.png)

谢谢，麻烦请close。

**Comment by HongChow** [comment]
补充问一句，AIStudio上的代码可以怎么拉下来呢？我目前是复制的

**Comment by Channingss** [comment]
鼠标悬停在文件夹上面，右侧会出现下载的按钮：
![image](https://user-images.githubusercontent.com/12471701/109642236-a6901e00-7b8d-11eb-94e8-301cf14f5ecc.png)

**Comment by HongChow** [comment]
> 鼠标悬停在文件夹上面，右侧会出现下载的按钮：
> ![image](https://user-images.githubusercontent.com/12471701/109642236-a6901e00-7b8d-11eb-94e8-301cf14f5ecc.png)
谢谢，但是我这边好像悬停还是不能出现下载按钮，不知道为啥。在Ubuntu和windows上都试过。

**Comment by HongChow** [comment]
@Channingss  您好， 我现在一个个py文件拷来拷去实在是麻烦，您可以帮忙下载好打包发给我吗？ 
给个邮箱： chinamos@sjtu.edu.cn
如果文件太大，麻烦您提供个网盘下载地址？非常感谢

**Comment by Channingss** [comment]
@HongChow 换个浏览器或者让同学帮忙试一下，不行明天我打包发一下。

**Comment by HongChow** [comment]
> @HongChow 换个浏览器或者让同学帮忙试一下，不行明天我打包发一下。
已经找了三个小伙伴，还是不行；浏览器试过两个（firefox / Chrome），我IE的不知道为啥打不开（我再试试）
B.T.W其实已经工作了，不行 明天 真要麻烦您了。

**Comment by HongChow** [comment]
> @HongChow 换个浏览器或者让同学帮忙试一下，不行明天我打包发一下。
抱歉，还是不能下载。求帮忙打包~

**Comment by HongChow** [comment]
@Channingss 您好 paddleOCR的ONNX 已经打通验证OK
请问官方有提供OpenVINO的paddleOCR的教程么？

**Comment by Channingss** [comment]
你是不是并没有fork并运行这个项目，直接在项目的主页上面看的话，是不能下载的，点击右边的fork，然后启动该项目。

**Comment by Channingss** [comment]
> @Channingss 您好 paddleOCR的ONNX 已经打通验证OK
> 请问官方有提供OpenVINO的paddleOCR的教程么？

OpenVINO的支持，目前遇到小小的阻碍，再和OpenVINO的同学一起解决。

**Comment by HongChow** [comment]
> 你是不是并没有fork并运行这个项目，直接在项目的主页上面看的话，是不能下载的，点击右边的fork，然后启动该项目。

的确没有fork
另外，观察到好像paddle/onnx版 在检测（detection）预测前的预处理都没有resize到某个固定尺寸
所以训练数据集在训练时也是各种分辨率分布的么？

**Comment by HongChow** [comment]
> > @Channingss 您好 paddleOCR的ONNX 已经打通验证OK
> > 请问官方有提供OpenVINO的paddleOCR的教程么？
> 
> OpenVINO的支持，目前遇到小小的阻碍，再和OpenVINO的同学一起解决。

非常感谢，如有进展请让我们知晓。
