### ISSUE TITLE
YOLOv3 ResNet50_vd DCN DropBlock IoULoss 检测模型转onnx提示错误

### ISSUE THREAD

**Issue by peace-zy** [PaddlePaddle/Paddle2ONNX#206]
paddle: 1.8.5
Exception: Error happened when mapping node ['deformable_conv@0'] to onnx, which op_type is 'deformable_conv' with inputs: {'Filter': ['res5a_branch2b_weights'], 'Input': ['bn5a_branch2a.output.1.tmp_3'], 'Mask': ['sigmoid_0.tmp_0'], 'Offset': ['split_0.tmp_0']} and outputs: {'Output': ['res5a_branch2b.conv2d.output.1.tmp_0']}, specific error: module 'paddle' has no attribute 'static'

**Comment by Channingss** [comment]
@peace-zy 请安装paddle: 2.0
