### ISSUE TITLE
转换完的onnx格式 paddleOCR 识别模型(rec)无法加载，报scatterND 错误

### ISSUE THREAD

**Issue by znsoftm** [PaddlePaddle/Paddle2ONNX#212]
在onnxruntime 1.6中正常的模型，在onnxruntime 1.7中无法加载，报无法加载scatterND 算子
这个问题应该已经知道了，提个issue,备忘。

onnxruntime 1.７能提速４０％以上，实在是值得升级使用。

**Comment by znsoftm** [comment]
``

**Comment by PhilCuriosity** [comment]
你好，请问你解决了吗？

**Comment by PhilCuriosity** [comment]
> 在onnxruntime 1.6中正常的模型，在onnxruntime 1.7中无法加载，报无法加载scatterND 算子
> 这个问题应该已经知道了，提个issue,备忘。
> 
> onnxruntime 1.７能提速４０％以上，实在是值得升级使用。

你好，请问你解决了吗？我是在onnx2trt遇到的这个问题

**Comment by znsoftm** [comment]
这个需要paddle2onnx 的大佬们修改才行，具体原因应该说了一些，无奈自己改不动。

**Comment by znsoftm** [comment]
已经更新，暂时没有合并。

我们手工合并了一个非官方的版本，经测试可用： https://github.com/znsoftm/paddle2onnx-wild

**Comment by znsoftm** [comment]
此版本作者 @Channingss ，我们只是搬运合并和测试。

**Comment by jiangjiajun** [comment]
已在最新的代码中修复此问题，将会随Paddle2ONNX的v0.6发版

**Comment by znsoftm** [comment]
感谢：）@jiangjiajun

**Comment by williamlzw** [comment]
onnxruntime1.7.0运行paddle2.0.2转换的paddleocr rec模型报错。ScatterND算子 
Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

**Comment by williamlzw** [comment]
> 已在最新的代码中修复此问题，将会随Paddle2ONNX的v0.6发版

onnxruntime1.7.0运行paddle2.0.2转换的paddleocr rec模型报错。ScatterND算子
Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

**Comment by jiangjiajun** [comment]
> > 已在最新的代码中修复此问题，将会随Paddle2ONNX的v0.6发版
> 
> onnxruntime1.7.0运行paddle2.0.2转换的paddleocr rec模型报错。ScatterND算子
> Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

升级到Paddle2ONNX 0.5.1之后，重新转换ocr模型即可

**Comment by williamlzw** [comment]
> > > 已在最新的代码中修复此问题，将会随Paddle2ONNX的v0.6发版
> > 
> > 
> > onnxruntime1.7.0运行paddle2.0.2转换的paddleocr rec模型报错。ScatterND算子
> > Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}
> 
> 升级到Paddle2ONNX 0.5.1之后，重新转换ocr模型即可

我就是安装上面 https://github.com/znsoftm/paddle2onnx-wild的0.6，一样报错

**Comment by znsoftm** [comment]
有点误会了，你要在这儿的仓库中下载： https://github.com/PaddlePaddle/Paddle2ONNX

你发的那个是我以前提前合并，以解决onnxruntime 1.7加载模型时做的野生合并。

**Comment by jiangjiajun** [comment]
直接 pip install paddle2onnx==0.5.1即可

**Comment by williamlzw** [comment]
> 有点误会了，你要在这儿的仓库中下载： https://github.com/PaddlePaddle/Paddle2ONNX
> 
> 你发的那个是我以前提前合并，以解决onnxruntime 1.7加载模型时做的野生合并。

是用paddle2.0内部函数exportonnx导出吗？还是命令行paddle2onnx导出

**Comment by znsoftm** [comment]
这儿有转好的，直接自取吧

https://github.com/RapidOCR/Paddle2OnnxConvertor/releases

**Comment by Dandelion111** [comment]
> 在onnxruntime 1.6中正常的模型，在onnxruntime 1.7中无法加载，报无法加载scatterND 算子
> 这个问题应该已经知道了，提个issue,备忘。
> 
> onnxruntime 1.７能提速４０％以上，实在是值得升级使用。

请问识别模型动态图crnn转换为onnx时，怎么设定输入shape，
