### ISSUE TITLE
slice操作转换问题。

### ISSUE THREAD

**Issue by BBuf** [PaddlePaddle/Paddle2ONNX#219]
你好，我使用实现了这样一个切片操作，然后使用Paddle2ONNX进行转换。
```
class Net(nn.Layer):
        def forward(self, x):
            return x[0, 1:3, :1, 2:]
```

转换出来的ONNX模型是这样的：

![图片](https://user-images.githubusercontent.com/35585791/112405798-f22d8600-8d4d-11eb-96ad-cbcf937c7e94.png)

可以看到ends的最后一维的数值变成了10000000，不是期望的4，希望能修复这个BUG。

如果我显示的指定切片2：4，转换是没有问题的。如下：

```
class Net(nn.Layer):
        def forward(self, x):
            return x[0, 1:3, :1, 2:]
```

![图片](https://user-images.githubusercontent.com/35585791/112405964-459fd400-8d4e-11eb-9c49-5e84ec1dd722.png)

**Comment by jiangjiajun** [comment]
这里你的`slice`是`x[0, 1:3, :1, 2:]`，因此相当于`start`为[0, 1, 0, 2]， `end`为`[1, 3, 1, 最末位]`，由于当前不知道你的x具体shape是多少，所以取了个极值`1000000`，当前在使用转换后的模型，会有什么问题么

**Comment by BBuf** [comment]
emmm，我给了x.shape，是[2,4,3,5]，这个你可以从可视化图中看到。

**Comment by jiangjiajun** [comment]
> 你好，我使用实现了这样一个切片操作，然后使用Paddle2ONNX进行转换。
> 
> ```
> class Net(nn.Layer):
>         def forward(self, x):
>             return x[0, 1:3, :1, 2:]
> ```
> 
> 转换出来的ONNX模型是这样的：
> 
> ![图片](https://user-images.githubusercontent.com/35585791/112405798-f22d8600-8d4d-11eb-96ad-cbcf937c7e94.png)
> 
> 可以看到ends的最后一维的数值变成了10000000，不是期望的4，希望能修复这个BUG。
> 
> 如果我显示的指定切片2：4，转换是没有问题的。如下：
> 
> ```
> class Net(nn.Layer):
>         def forward(self, x):
>             return x[0, 1:3, :1, 2:]
> ```
> 
> ![图片](https://user-images.githubusercontent.com/35585791/112405964-459fd400-8d4e-11eb-9c49-5e84ec1dd722.png)

麻烦给一个完整的导出示例，我看下哈

**Comment by BBuf** [comment]
```
class Net(nn.Layer):
    def forward(self, x):
        return x[0, 1:3, :1, 2:4]
input_size = (2, 4, 3, 5)
pd_module = Net()
paddle.set_device("gpu")
input_names = "x_0"
paddle_model.eval()
input_spec = paddle.static.InputSpec(
    shape=input_size , dtype="float32", name=input_names
)
mode_str = "/tmp/model"

    paddle.onnx.export(
        paddle_model,
        mode_str,
        input_spec=[input_spec],
        opset_version=12,
        enable_onnx_checker=True,
    )
```

然后把model用netron可视化。

**Comment by jiangjiajun** [comment]
我使用如下代码，导出来的onnx模型没有你说的问题哈
```
import paddle

class Net(paddle.nn.Layer):
    def forward(self, x):
        return x[0, 1:3, :1, 2:4]

input_size = (2, 4, 3, 5)
paddle_model = Net()
paddle.set_device("cpu")
input_names = "x_0"
paddle_model.eval()
input_spec = paddle.static.InputSpec(
    shape=input_size , dtype="float32", name=input_names
)
mode_str = "em"

paddle.onnx.export(
    paddle_model,
    mode_str,
    input_spec=[input_spec],
    opset_version=12,
    enable_onnx_checker=True,
)
```
![image](https://user-images.githubusercontent.com/19339784/112453910-1d869400-8d93-11eb-8018-ee64dfd2c233.png)

**Comment by BBuf** [comment]
emmm，可能版本不太对，稍等我截图一下我的paddle和paddle2onnx版本

**Comment by BBuf** [comment]
![图片](https://user-images.githubusercontent.com/35585791/112454466-ad2c4280-8d93-11eb-8167-e800b1a8e6aa.png)

**Comment by BBuf** [comment]
emmm。。好像是没有这个问题，可能问题出在我在后面调用了一次onnx-simplifier，我确认一下再问问大老师，看是不是onnx-simplifier的问题。打扰了。

**Comment by BBuf** [comment]
抱歉，我降智了，代码贴错了。把return x[0, 1:3, :1, 2:4] 改成return x[0, 1:3, :1, 2:] 就可以复现我说的BUG了，不好意思。

**Comment by BBuf** [comment]
import paddle
import onnx

class Net(paddle.nn.Layer):
    def forward(self, x):
        return x[0, 1:3, :1, 2:]

input_size = (2, 4, 3, 5)
paddle_model = Net()
paddle.set_device("cpu")
input_names = "x_0"
paddle_model.eval()
input_spec = paddle.static.InputSpec(
    shape=input_size , dtype="float32", name=input_names
)
mode_str = "em"

paddle.onnx.export(
    paddle_model,
    mode_str,
    input_spec=[input_spec],
    opset_version=12,
    enable_onnx_checker=True,
)

请帮忙看一下

**Comment by jiangjiajun** [comment]
我刚提了个PR https://github.com/PaddlePaddle/Paddle2ONNX/pull/218
你试下重新安装转换试下哈
```
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
git checkout jason
python setup.py install
```

**Comment by BBuf** [comment]
可以的，thanks。方便加个微信吗，以后有paddle onnx的疑惑可以第一时间问你？我的微信bbuf2333。
