### ISSUE TITLE
请问PPOCR官方提供的inference model在转换后只能输入100的宽度，这块如何修改为动态输入呢

### ISSUE THREAD

**Issue by MagicCodess** [PaddlePaddle/Paddle2ONNX#233]
这个链接的model
https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_server_v2.0_rec_infer.tar

**Comment by jiangjiajun** [comment]
当前你贴的这个链接是已经导出来的paddle部署模型，模型的信息已经固化在model.pdmodel文件中，在里面设定的大小就是[-1, 3, 32, 100]，因此转成onnx后，也只能接受100的输入。

如果你需要动态输入，则需使用paddleocr/tools/export_model.py重新导出模型，导出后的rec模型宽度是动态的

**Comment by RyanCCC** [comment]
请问有具体的步骤吗？非常感谢！
