### ISSUE TITLE
AdaptiveMaxPool 和 MaxPool 不支持

### ISSUE THREAD

**Issue by morgan-bc** [PaddlePaddle/Paddle2ONNX#240]
AdaptiveMaxPool3D 和 AdaptiveMaxPool3D 操作不支持
报错信息
```
There's 1 ops are not supported yet
=========== max_pool2d_with_index ===========
```
版本
```
PaddlePaddle-gpu: 2.0.1.post110
Paddle2Onnx: 0.5
onnx: 1.7.0
```

建议把基础的2D和3D操作算子都测一遍，这里面坑也太多了

**Comment by jiangjiajun** [comment]
> AdaptiveMaxPool3D 和 AdaptiveMaxPool3D 操作不支持
> 报错信息
> 
> ```
> There's 1 ops are not supported yet
> =========== max_pool2d_with_index ===========
> ```
> 
> 版本
> 
> ```
> PaddlePaddle-gpu: 2.0.1.post110
> Paddle2Onnx: 0.5
> onnx: 1.7.0
> ```
> 
> 建议把基础的2D和3D操作算子都测一遍，这里面坑也太多了

方便的话，提供一下你的Paddle模型。邮箱jiangjiajun@baidu.com

**Comment by morgan-bc** [comment]
模型中用到了CBAM注意力模块，其中有AdaptiveMaxPool，代码已经发送到您邮箱，帮忙看看问题出在哪

**Comment by jiangjiajun** [comment]
> 模型中用到了CBAM注意力模块，其中有AdaptiveMaxPool，代码已经发送到您邮箱，帮忙看看问题出在哪

你好，由于ONNX目前不支持 Adaptive的Pool方式，因此Paddle2ONNX也不支持网络中存在AdaptiveMaxPool的模型导出

Duplicate of #220

**Comment by morgan-bc** [comment]
ONNX 肯定是支持 AdaptiveMaxPool，参考onnx 文档 [Operators](https://github.com/onnx/onnx/blob/master/docs/Operators.md).
GlobalMaxPool 就是AdaptiveMaxPool，你们找bug能不能认真点。我自己找到一个临时解决方法，在 `paddle2onnx\op_mapper\nn.py` 中做一个改动

```python
# @op_mapper('pool2d')
@op_mapper(['pool2d', 'max_pool2d_with_index'])
class Pool():
    support_opset_verison_range = (1, 12)
    pool_type = {
        'max': ('MaxPool', 'GlobalMaxPool'),
        'avg': ('AveragePool', 'GlobalAveragePool')
    }

```
除此之外还有一个bug是 maxpooling 转成静态图时，不知道什么原因 `node.attr('pooling_type')` 这一项没有了，所以在 `paddle2onnx\graph\paddle_graph.py`  129 行增加

```python
        if 'max_pool' in layer_name:
            attrs.update({'pooling_type': 'max'})
```
` PaddleGraph` 中的`make_node` 就变成

```python

class PaddleGraph(Graph):
    def __init__(self, program, parameters, feed_var_names, fetch_vars):
        super(PaddleGraph, self).__init__()
        self.build_graph(program, parameters, feed_var_names, fetch_vars)

    def make_node(self,
                  op,
                  inputs=None,
                  outputs=None,
                  attrs=None,
                  block=None,
                  layer_name=None,
                  **kw):
        if layer_name is None:
            layer_name = self.generate_node_name(op.type)

        if attrs is None:
            attrs = kw
        attrs.update(kw)

        if inputs is None:
            inputs = {}
        if outputs is None:
            outputs = {'Out': layer_name}

        if 'max_pool' in layer_name:
            attrs.update({'pooling_type': 'max'})

        node = PaddleNode(op, inputs, outputs, attrs, layer_name, block)
        self.insert_node(node)
        return node
```

Bug 都给你们找出来了，希望你们能抽时间改一下

**Comment by jiangjiajun** [comment]
- [Paddle AdaptiveMaxPool2D](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/layer/pooling/AdaptiveMaxPool2D_cn.html#adaptivemaxpool2d) 输入Tensor `X`(n, c, h, w)，参数`output_size`(new_h, new_w)，输出Tensor `Y`(n, c, new_h, new_w)，在pool的过程中kernel size根据输入的shape进行动态变换，确保输出的shape为new_h, new_w
- [ONNX GlobalMaxPool](https://github.com/onnx/onnx/blob/master/docs/Operators.md#globalmaxpool) 输入Tensor `X`(n, c, h, w)，在pool的过程中kernel_size与输入的shape一致`This is equivalent to MaxPool with kernel size equal to the spatial dimension of input tensor.`

**Comment by morgan-bc** [comment]
AdaptiveMaxPool2D 确实不是 GlobalMaxPool ，是我看得不仔细，但是paddle2onnx 代码已经有处理 AdaptivePool 的代码，就是根据 output_size 计算 kernel_size 后在转换为 MaxPool，[代码为](https://github.com/PaddlePaddle/Paddle2ONNX/blob/71c5b1688838b48fa2c227bce511bac08fb919da/paddle2onnx/op_mapper/nn.py#L98)

```python

@op_mapper('pool2d')
class Pool():
    support_opset_verison_range = (1, 12)
    pool_type = {
        'max': ('MaxPool', 'GlobalMaxPool'),
        'avg': ('AveragePool', 'GlobalAveragePool')
    }

 ......

    @classmethod
    def opset_1(cls, graph, node, **kw):
        if node.attr('global_pooling') or (node.attr('adaptive') and
                                           node.attr('ksize') == [1, 1]):
            onnx_node = graph.make_node(
                cls.pool_type[node.attr('pooling_type')][1],
                inputs=node.input('X'),
                outputs=node.output('Out'))
        elif node.attr('adaptive'):
            # if pool is adaptive, check if input shape of pool is fixed.
            mapper_helper.is_static_shape(node.input_shape('X', 0))
            input_h, input_w = node.input_shape('X', 0)[2:]
            output_h, output_w = node.output_shape('Out', 0)[2:]
            stride_h = int(input_h / output_h)
            stride_w = int(input_w / output_w)

            kernel_h = input_h - (output_h - 1) * stride_h
            kernel_w = input_w - (output_w - 1) * stride_w

......

```

MaxPool 转换之所以会出现错误，是因为 `@op_mapper('pool2d')` 中没有 加上 `max_pool2d_with_index ` ，还有就是 `max_pool2d_with_index ` 这个算子在转为换为静态图计算节点后 `node.attr('pooling_type')` 取得的值为 None，所以即使改为 `@op_mapper(['pool2d', 'max_pool2d_with_index'])` 后依然会报错，出现这个 bug 的原因我也没搞清楚，看能不能转达给相关的开发人员
