### ISSUE TITLE
Different behaviors when converting PaddleOCR into Onnx with different opset version.

### ISSUE THREAD

**Issue by JC1DA** [PaddlePaddle/Paddle2ONNX#241]
I tried to convert PaddleOCR text detector model (PP-OCR 2.0 version) into ONNX model. The conversion was successful but the output from ONNX model did not match with the output from the original model (using paddlepaddle).
I also figured out by using different opset from 10-13, I got different results. It seems that using opset 10, I got pretty similar results (not sure if it's 100% similar) compared to the original model but using opset 11 12 and 13, I got completely different results.

Can anyone help check and fix this strange behavior?

Thanks in advance.

**Comment by jiangjiajun** [comment]
> I tried to convert PaddleOCR text detector model (PP-OCR 2.0 version) into ONNX model. The conversion was successful but the output from ONNX model did not match with the output from the original model (using paddlepaddle).
> I also figured out by using different opset from 10-13, I got different results. It seems that using opset 10, I got pretty similar results (not sure if it's 100% similar) compared to the original model but using opset 11 12 and 13, I got completely different results.
> 
> Can anyone help check and fix this strange behavior?
> 
> Thanks in advance.

Hello, there's something I need to confirm
- which inference engine you are using,  and which version

**Comment by JC1DA** [comment]
I'm using paddle 2.0 for this model (https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_det_infer.tar) and onnxruntime to run onnx model.
The script to run paddleocr is here (https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.1/tools/infer/predict_system.py)
