### ISSUE TITLE
psgan model doesn't convert to onnx model

### ISSUE THREAD

**Issue by Igoslow** [PaddlePaddle/Paddle2ONNX#244]
I use this command to convert onnx model:
paddle2onnx --model_filename /home/Paddle2ONNX/model/psgan_weight.pdparams --sa
ve_file save_model --opset_version 10 --enable_onnx_checker True

**Comment by Igoslow** [comment]
please help me, thank you my friens.

**Comment by Igoslow** [comment]
please help me, thank you my friends.

**Comment by jiangjiajun** [comment]
How to convert a PaddlePaddle model to ONNX model, follow 2 steps
- 1. Get a paddlepaddle **inference** model, which means the model is exported to deploy, it contains 2 files include `model.pdmodel` and `model.pdiparams`(filename is defined by user)
- 2. Use command `paddle2onnx --model_dir paddle_model_dirname --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 10 --save_file export_model.onnx`( 3 parameters should be defined, `model_dir`, `model_filename` and `params_filename`)

**Comment by Igoslow** [comment]
I almost understand your meaning, but I don't knowledge which is model_filename or params_filename in psgan's directory.

**Comment by jiangjiajun** [comment]
> I almost understand your meaning, but I don't knowledge which is model_filename or params_filename in psgan's directory.

This relate to the problem of how to export inference model of psgan， you may need to ask for help from psgan

**Comment by Igoslow** [comment]
Thank you very much
