### ISSUE TITLE
Paddle2ONNX V0.6 已经支持PaddleDetection的新版PPYOLOV2和TinyPPYOLO模型

### ISSUE THREAD

**Issue by jiangjiajun** [PaddlePaddle/Paddle2ONNX#245]
正在进行中，如有相关需求，可在此issue下回复『+1』，后续支持后，会在此issue进行更新

**Comment by znsoftm** [comment]
感谢，正好想用这个。

**Comment by duolabmeng6** [comment]
+1

**Comment by DongChenwei2000** [comment]
+1 同时想问下还需要多久，有点急

**Comment by jiangjiajun** [comment]
预计在下一周，即05.10~05.16测试完成发布新版本

**Comment by DongChenwei2000** [comment]
希望这个问题可以得到解决https://github.com/PaddlePaddle/PaddleDetection/issues/2905#issue-880654414

**Comment by dgl547437235** [comment]
+1

**Comment by jiangjiajun** [comment]
ppyolo和ppyolo-tiny已支持，ppyolov2正在进行中，有需求的童鞋可直接安装Paddle2ONNX分支提前使用

## 注意
- ppyolo在转换过程中会最后的后处理matrix_nms改成普通的nms，这会导致结果有不同
- ppyolo-tiny仅支持float模型转换，不支持量化的ppyolo_tiny转换

```
 git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
 cd Paddle2ONNX
 git checkout ppdet2.0
 python setup.py install
```

**Comment by duolabmeng6** [comment]
谢谢

> ppyolo和ppyolo-tiny已支持，ppyolov2正在进行中，有需求的童鞋可直接安装Paddle2ONNX分支提前使用
> 
> ## 注意
> * ppyolo在转换过程中会最后的后处理matrix_nms改成普通的nms，这会导致结果有不同
> * ppyolo-tiny仅支持float模型转换，不支持量化的ppyolo_tiny转换
> 
> ```
>  git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
>  cd Paddle2ONNX
>  git checkout ppdet2.0
>  python setup.py install
> ```

谢谢

**Comment by muzishen** [comment]
> 
> 
> ppyolo和ppyolo-tiny已支持，ppyolov2正在进行中，有需求的童鞋可直接安装Paddle2ONNX分支提前使用
> ## 注意
> 
>     * ppyolo在转换过程中会最后的后处理matrix_nms改成普通的nms，这会导致结果有不同
> 
>     * ppyolo-tiny仅支持float模型转换，不支持量化的ppyolo_tiny转换
> 
> 
> ```
>  git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
>  cd Paddle2ONNX
>  git checkout ppdet2.0
>  python setup.py install
> ```
您好，我发现转ppyolo-tiny出错了，是有些op，不支持么？希望能得到及时解答，谢谢！
我的版本信息： paddle2onnx==0.5.1； python==3.7； paddlepaddle==2.0.2
----------------------------------------报错信息-------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/paddle/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/command.py", line 142, in main
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/command.py", line 114, in program2onnx
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/convert.py", line 77, in program2onnx
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== conditional_block ===========
=========== logical_not ===========
=========== select_input ===========

**Comment by MasonSuWei** [comment]
> > ppyolo和ppyolo-tiny已支持，ppyolov2正在进行中，有需求的童鞋可直接安装Paddle2ONNX分支提前使用
> > ## 注意
> > ```
> > * ppyolo在转换过程中会最后的后处理matrix_nms改成普通的nms，这会导致结果有不同
> > 
> > * ppyolo-tiny仅支持float模型转换，不支持量化的ppyolo_tiny转换
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >  git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
> >  cd Paddle2ONNX
> >  git checkout ppdet2.0
> >  python setup.py install
> > ```
> 
> 您好，我发现转ppyolo-tiny出错了，是有些op，不支持么？希望能得到及时解答，谢谢！
> 我的版本信息： paddle2onnx==0.5.1； python==3.7； paddlepaddle==2.0.2
> ----------------------------------------报错信息-------------------------------------------
> Traceback (most recent call last):
> File "/root/anaconda3/envs/paddle/bin/paddle2onnx", line 33, in
> sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/command.py", line 142, in main
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/command.py", line 114, in program2onnx
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/convert.py", line 77, in program2onnx
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/convert.py", line 32, in export_onnx
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
> File "/root/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx-0.6-py3.7.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
> NotImplementedError:
> There's 3 ops are not supported yet
> =========== conditional_block ===========
> =========== logical_not ===========
> =========== select_input ===========

我也出现了同样的问题

paddle2onnx==0.6； python==3.6.13； paddlepaddle==2.0.2
There's 3 ops are not supported yet
=========== conditional_block ===========
=========== select_input ===========
=========== logical_not ===========

**Comment by jiangjiajun** [comment]
当前(2021.05.16)请注意使用PaddleDetection的Develop分支导出PPYOLO和PPYOLO-tiny模型，注意对应的PaddlePaddle版本也为develop版本

原因在于目前PaddleDetection的release 2.0分支在导出目标检测模型时，会导出控制流相关操作，在develop分支中解决了这个问题

**Comment by francislinker** [comment]
您是指需要切换paddledetection 的 develop 分支还是 paddle2onnx 的develop分支呢

**Comment by jiangjiajun** [comment]
当前(2021.05.16)请注意使用PaddleDetection的Develop分支导出PPYOLO和PPYOLO-tiny模型，注意对应的PaddlePaddle版本也为develop版本

原因在于目前PaddleDetection的release 2.0分支在导出目标检测模型时，会导出控制流相关操作，在develop分支中解决了这个问题

1. PaddleDetection使用develop分支
2. Paddle2ONNX重新安装方式如下
```
 git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
 cd Paddle2ONNX
 git checkout ppdet2.0
 python setup.py install
```

**Comment by jiangjiajun** [comment]
Paddle2ONNX V0.6 已经支持PaddleDetection的新版PPYOLOV2和TinyPPYOLO模型，参考此文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md

**Comment by duolabmeng6** [comment]
> Paddle2ONNX V0.6 已经支持PaddleDetection的新版PPYOLOV2和TinyPPYOLO模型，参考此文档 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/deploy/EXPORT_ONNX_MODEL.md

感谢~

**Comment by printso** [comment]
同样的问题，使用的paddle、paddleDetection、Paddle2ONNX都是develop版
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 142, in main
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 114, in program2onnx
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 77, in program2onnx
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError:
There's 3 ops are not supported yet
**=========== logical_not ===========
=========== conditional_block ===========
=========== select_input ===========**

**Comment by jiangjiajun** [comment]
使用PaddleDetection 2.1分支导出模型

**Comment by printso** [comment]
> 使用PaddleDetection 2.1分支导出模型

使用PaddleDetection 2.1分支还是同样的问题，https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.6/docs/zh/op_list.md
这个列表里面也没有这三个算子

**Comment by jiangjiajun** [comment]
> > 使用PaddleDetection 2.1分支导出模型
> 
> 使用PaddleDetection 2.1分支还是同样的问题，https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.6/docs/zh/op_list.md
> 这个列表里面也没有这三个算子

说明你用的可能仍然在PaddleDetection 2.0分支的代码在导出模型.

检查自己python环境中是否曾安装过PaddleDetection 2.0的代码，例如pip show paddledet

**Comment by printso** [comment]
> > > 使用PaddleDetection 2.1分支导出模型
> > 
> > 
> > 使用PaddleDetection 2.1分支还是同样的问题，https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.6/docs/zh/op_list.md
> > 这个列表里面也没有这三个算子
> 
> 说明你用的可能仍然在PaddleDetection 2.0分支的代码在导出模型.
> 
> 检查自己python环境中是否曾安装过PaddleDetection 2.0的代码，例如pip show paddledet

多谢，是的，问题已解决

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
