### ISSUE TITLE
OCR db server 2.0 如何转动态尺度的onnx?

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/Paddle2ONNX#248]
目前用该工具转换的都是固定w,h的，你们开源的都是推理模型，是不是不支持用paddle.export.onnx重新load，然后转换?

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/issues/233 参考这个

**Comment by daixiangzi** [comment]
> #233 参考这个

恩，我看到过这个，”如果需要动态输入，则需使用paddleocr/tools/export_model.py重新导出模型“  只是我不明白，这个权重是用哪一个，好像2.0只提供了ch_ppocr_server_v2.0_xx 中推理模型文件

**Comment by daixiangzi** [comment]
使用export_model.py 不是应该使用.pdopt 、pdparams这样的文件么，现在关键是你们能不能提供检测部分的ch_ppocr_server_v2.0_xx版本哇

**Comment by daixiangzi** [comment]
是不是你们上面开源的推理模型就是上面标注的训练模型转过来的?

**Comment by jiangjiajun** [comment]
![image](https://user-images.githubusercontent.com/19339784/116575455-3c071e80-a941-11eb-96a4-4ba847ba3c5e.png)
OCR有提供权重文件，可通过export_model.py加载权重后重新导出inference模型

**Comment by daixiangzi** [comment]
> ![image](https://user-images.githubusercontent.com/19339784/116575455-3c071e80-a941-11eb-96a4-4ba847ba3c5e.png)
> OCR有提供权重文件，可通过export_model.py加载权重后重新导出inference模型

谢谢，已经弄好了。

**Comment by RyanCCC** [comment]
你好能不能指导下怎么转换？第一次用paddle的OCR谢谢！
