### ISSUE TITLE
有点问题请教

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/Paddle2ONNX#249]
你们开源的DB检测模型，里面好像没有用变形卷积。虽然说你们现在onnx支持了该算子，下一步会开源相关版本的模型吗

**Comment by jiangjiajun** [comment]
你指的是OCR模型吗，建议在PaddleOCR的REPO反馈相关建议

**Comment by daixiangzi** [comment]
> 你指的是OCR模型吗，建议在PaddleOCR的REPO反馈相关建议

对的
