### ISSUE TITLE
paddle2onnx error

### ISSUE THREAD

**Issue by daixiangzi** [PaddlePaddle/Paddle2ONNX#250]
使用命令转换静态图为onnx:
出现下面错误，不支持lstm 和sequence_pool
There's 2 ops are not supported yet
=========== sequence_pool ===========
=========== lstm ===========

**Comment by daixiangzi** [comment]
但是至少在支持op列表中明显有支持lstm,下面是我的版本信息：
2021-05-08 18:00:56 [INFO]	paddle2onnx-0.5.1 with python>=2.7, paddlepaddle>=1.8.0

**Comment by jiangjiajun** [comment]
1.8版本的lstm不是支持的，目前paddle2onnx支持的是Paddle2.0版本中的lstm。另外你这里在转的是什么模型呢

**Comment by daixiangzi** [comment]
> 1.8版本的lstm不是支持的，目前paddle2onnx支持的是Paddle2.0版本中的lstm。另外你这里在转的是什么模型呢

porn_detection_lstm,文本分类
