### ISSUE TITLE
ppOCR新发布的端到端模型PGNet，是否可以转换成ONNX运行呢

### ISSUE THREAD

**Issue by gaooolianggg** [PaddlePaddle/Paddle2ONNX#251]
我最近在使用ppOCR新增的PGNet，效果很好。我想把模型转换成onnx，然后使用onnx进行部署，请问这个模型可以转换吗

**Comment by jiangjiajun** [comment]
一般情况下没用到特殊的OP算子，是可以支持的，建议自行先转换测试下
