### ISSUE TITLE
paddle转onnx算子不支持assign

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/Paddle2ONNX#256]
onnx模型转的paddle，然后paddle再转onnx报错
There's 1 ops are not supported yet
=========== assign ===========

**Comment by jiangjiajun** [comment]
1. 不建议onnx->paddle->onnx这种操作，这样会导致OP太细，性能变差
2. 你用的是paddle2onnx哪个版本呢，现在最新的是0.6版本，支持assign操作

如果使用0.6仍然出错，麻烦贴下整个报错日志

**Comment by williamlzw** [comment]
0.6转成功了
