### ISSUE TITLE
想转换一个能够处理任意大小的模型

### ISSUE THREAD

**Issue by KKKloveQbh** [PaddlePaddle/Paddle2ONNX#259]
想转换一个能够处理任意大小的模型，设置InputSpec的shape为[1,3,-1,-1]时报错，Only one dimension value of 'shape' in reshape can be -1. But received shape[2] is also -1.请问应该怎么转换呢？原模型是可以处理任意大小的

**Comment by jiangjiajun** [comment]
> 想转换一个能够处理任意大小的模型，设置InputSpec的shape为[1,3,-1,-1]时报错，Only one dimension value of 'shape' in reshape can be -1. But received shape[2] is also -1.请问应该怎么转换呢？原模型是可以处理任意大小的

这里根据提示，应该是由于模型结构不支持处理任意大小的输入

**Comment by KKKloveQbh** [comment]
> 
> 
> > 想转换一个能够处理任意大小的模型，设置InputSpec的shape为[1,3,-1,-1]时报错，Only one dimension value of 'shape' in reshape can be -1. But received shape[2] is also -1.请问应该怎么转换呢？原模型是可以处理任意大小的
> 
> 这里根据提示，应该是由于模型结构不支持处理任意大小的输入

在使用.pdparams模型测试时，是可以任意长度但是要保证宽和高的值相等，就相当于[1,3,X,X],这样该怎么改呢？

**Comment by jiangjiajun** [comment]
这个模型的整个代码是在Github上么，我看下

**Comment by KKKloveQbh** [comment]
> 
> 
> 这个模型的整个代码是在Github上么，我看下

不是的，是自己用paddle写的
`import functools
import paddle
import paddle.nn as nn
import paddle.nn.functional as F



class RG(nn.Layer):

    def __init__(self,channel, reduction, numRCAB):
        super(RG,self).__init__()
        self.RCAB_list = []
        for i in range(numRCAB):
            self.RCAB_list += [self.add_sublayer('RCAB_%d' % i, RCAB(channel, reduction))]
        self.conv = nn.Conv2D(channel,channel,3,padding=1)

    def forward(self, x):
        y = x
        for rcab in self.RCAB_list:
            y = rcab(y)
        y = self.conv(y) 
        return x + y

class RCAB(nn.Layer):

    def __init__(self,channel,reduction):
        super(RCAB, self).__init__()
        self.conv1 = nn.Conv2D(channel,channel,3,padding=1)
        self.conv2 = nn.Conv2D(channel,channel,3,padding=1)
        self.ca = CA(channel, reduction)

    def forward(self,  x):
        y = self.conv1(x)
        y = F.relu(y)
        y = self.conv2(y)
        y = self.ca(y)
        return x + y

class CA(nn.Layer):

    def __init__(self, channel, reduction):
        super(CA, self).__init__()
        self.conv1 = nn.Conv2D(channel,channel//reduction,1)
        self.conv2 = nn.Conv2D(channel//reduction,channel,1)

    def forward(self, x):
        means = P.mean(x, [2,3], True)
        y = self.conv1(means)
        y = F.relu(y)
        y = self.conv2(y)
        y = F.sigmoid(y)
        return x * y




class RCANNet(nn.Layer):

    def __init__(self,channel=64, reduction=16,numRG=5, numRCAB=10, scale=2):
        super(RCANNet,self).__init__()
        self.conv1 = nn.Conv2D(3,channel,3,padding=1)
        self.RG_list = []
        for i in range(numRG):
            self.RG_list += [self.add_sublayer('RG_%d' % i, RG(channel, reduction,numRCAB))]
        self.conv2= nn.Conv2D(channel,channel,3,padding=1)
        self.conv3 = nn.Conv2D(channel,channel*scale**2,3,padding=1)
        self.ps = nn.PixelShuffle(scale)
        self.conv4 = nn.Conv2D(channel,3,3,padding=1)

    def forward(self, x):
        x = self.conv1(x)
        y = x
        for rg in self.RG_list:
            y = rg(y)
        y = self.conv2(y)
        y = x + y
        y = self.conv3(y)
        y = self.ps(y)
        y = self.conv4(y)
        return y
`

**Comment by jiangjiajun** [comment]
```
model = RCANNet()
model.eval()
input = paddle.static.InputSpec(dtype='float32', shape=[1, 3, -1, -1], name='image')
paddle.jit.save(model, 'testxx/xx', [input])
```
我执行如上代码，并没有导出出错

**Comment by KKKloveQbh** [comment]
> 
> 
> ```
> model = RCANNet()
> model.eval()
> input = paddle.static.InputSpec(dtype='float32', shape=[1, 3, -1, -1], name='image')
> paddle.jit.save(model, 'testxx/xx', [input])
> ```
> 
> 我执行如上代码，并没有导出出错

好的，十分感谢！

**Comment by KKKloveQbh** [comment]
> 
> 
> ```
> model = RCANNet()
> model.eval()
> input = paddle.static.InputSpec(dtype='float32', shape=[1, 3, -1, -1], name='image')
> paddle.jit.save(model, 'testxx/xx', [input])
> ```
> 
> 我执行如上代码，并没有导出出错

不好意思，我发现贴错代码了，报错的是这个模型
`import paddle 
import paddle.nn as nn
import paddle.nn.functional as F
from paddle.nn.initializer import Assign




class sa_layer(nn.Layer):
    """Constructs a Channel Spatial Group module.
    Args:
        k_size: Adaptive selection of kernel size
    """

    def __init__(self, channel, groups=4):
        super(sa_layer, self).__init__()
        self.groups = groups
        self.avg_pool = nn.AdaptiveAvgPool2D(1)

        self.cweight = paddle.zeros([1, channel // (2 * groups), 1, 1])
        self.cbias =  paddle.ones([channel // (2 * groups), 1, ])
        self.sweight =  paddle.zeros([1, channel // (2 * groups), 1, 1])
        self.sbias =  paddle.ones([channel // (2 * groups), 1])
        self.conv_c = nn.Conv2D(in_channels=1, out_channels= channel // (2 * groups), kernel_size=[1, 1],
                                weight_attr=paddle.ParamAttr(initializer=Assign(value=self.cweight)),
                                bias_attr= paddle.ParamAttr(initializer=Assign(value=self.cbias))
        )
        self.conv_s = nn.Conv2D(in_channels=1, out_channels= channel // (2 * groups), kernel_size=[1, 1],
                                weight_attr=paddle.ParamAttr(initializer=Assign(value=self.sweight)),
                                bias_attr= paddle.ParamAttr(initializer=Assign(value=self.sbias))
        )

        
        f = channel // (2 * groups)
        self.conv_max = nn.Conv2D(f, f, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2D(f, f, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2D(f, f, kernel_size=3, stride=2, padding=0)
        

        self.sigmoid = nn.Sigmoid()
        
        #self.gn = nn.GroupNorm(channel // (2 * groups), channel // (2 * groups))

    @staticmethod
    def channel_shuffle(x, groups):
        b, c, h, w = x.shape      
        x = x.reshape([b, groups, -1, h, w])     
        x = x.transpose(perm=[0, 2, 1, 3, 4])

        # flatten
        x = x.reshape([b, -1, h, w])

        return x

    def forward(self, x):
        b, c, h, w = x.shape
        
        x = x.reshape([b * self.groups, -1, h, w])
        
        x_0, x_1 = x.chunk(2, axis = 1)       
        # channel attention
        xn = self.avg_pool(x_0)

        xn = self.conv_c(xn)
        xn = F.relu(xn)       
        xn = self.conv_c(xn)

        xn = self.conv_c(xn)
        
        #xn = self.cweight * xn + self.cbias
        xn = x_0 * self.sigmoid(xn)

        # spatial attention
       
        c1 = self.conv2(x_1)
        
        v_max = F.max_pool2d(c1, kernel_size=2, stride=3)
       
        v_range = F.relu(self.conv_max(v_max))
        
        c3 = F.relu(self.conv3(v_range))
       
        c3 = self.conv3(c3)
       
        c3 = F.interpolate(c3, (x_1.shape[2], x_1.shape[3]), mode='bilinear')
       
        xs = self.conv_s(c3+x_1)
       
        xs = self.conv_s(x_1)   
      
        #xs = self.sweight * xs + self.sbias
        xs = x_1 * self.sigmoid(xs)

        # concatenate along channel axis
        out = paddle.concat([xn, xs], axis=1)
        out = out.reshape([b, -1, h, w])

        out = self.channel_shuffle(out, 2)
        return out

class RSAB(nn.Layer):

    def __init__(self,channel,reduction):
        super(RSAB, self).__init__()
        self.conv1 = nn.Conv2D(channel,channel,3,padding=1)
        self.conv2 = nn.Conv2D(channel,channel,3,padding=1)
        self.sa = sa_layer(channel)

    def forward(self,  x):
        y = self.conv1(x)
        y = F.relu(y)
        y = self.conv2(y)
        y = self.sa(y)
        return x + y

class ERG(nn.Layer):

    def __init__(self,channel, reduction, numRCAB):
        super(ERG,self).__init__()
        self.RSAB_list = []
        for i in range(numRCAB):
            self.RSAB_list += [self.add_sublayer('RSAB_%d' % i, RSAB(channel, reduction))]
        self.conv = nn.Conv2D(channel,channel,3,padding=1)

    def forward(self, x):
        y = x
        for rsab in self.RSAB_list:
            y = rsab(y)
        y = self.conv(y) 
        return x + y

class PA(nn.Layer):
    def __init__(self, infeat,outfeat):
        super(PA,self).__init__()
        self.conv_1 = nn.Conv2D(infeat,outfeat,1,1)

    def forward(self,x):
        identity = x
        out = self.conv_1(x)
        out = F.sigmoid(out)
        y = identity*out
        return y


class CRFSAN(nn.Layer):

    def __init__(self,channel=64, reduction=16,numRG=3, numRCAB=6, scale=4):
        super(CRFSAN,self).__init__()
        self.conv1 = nn.Conv2D(3,channel,3,padding=1)
        self.ERG_list = []
        for i in range(numRG):
            self.ERG_list += [self.add_sublayer('ERG_%d' % i, ERG(channel, reduction,numRCAB))]
        self.conv2= nn.Conv2D(channel,channel,3,padding=1)
        self.conv3 = nn.Conv2D(channel,channel*scale**2,3,padding=1)
        self.ps = nn.PixelShuffle(2)
        self.conv4 = nn.Conv2D(channel,3,3,padding=1)

        self.conv_1 = nn.Conv2D(channel,channel*4,3,padding=1)
        self.conv_2 = nn.Conv2D(channel,channel,3,padding=1)
        self.conv_3 = nn.Conv2D(channel,channel*9,3,padding=1)
        self.pa = PA(channel,channel)

    def forward(self, x):
        x = self.conv1(x)
        y = x

        for erg in self.ERG_list:
            y = erg(y)
        y = self.conv2(y)
        y = x + y
        
        #y = self.conv3(y)

        y = self.conv_1(y)
        y = self.ps(y)
        
        y = self.conv_2(y)
        y = self.pa(y)
        y = self.conv_2(y)
        
       
        
        y = self.conv_1(y)
        #y = self.conv_3(y)
        y = self.ps(y)
        
        y = self.conv_2(y)
        y = self.pa(y)
        y = self.conv_2(y)
        

        y = self.conv4(y)
        return y
`

**Comment by jiangjiajun** [comment]
在这个网络中，有好处类似这样的代码
```
    b, c, h, w = x.shape
    
    x = x.reshape([b * self.groups, -1, h, w])
```
或者
```
c3 = F.interpolate(c3, (x_1_h, x_1_w), mode='bilinear')
```
其中的`b`、`c`都是从tensor的attributes中获取，但如若你在定义输入时为`[1, 3, -1, -1]`，那么获取到的attributes中`h`和`w`就是-1，自然就无法满足reshape的需求了

**Comment by KKKloveQbh** [comment]
> 
> 
> 在这个网络中，有好处类似这样的代码
> 
> ```
>     b, c, h, w = x.shape
>     
>     x = x.reshape([b * self.groups, -1, h, w])
> ```
> 
> 或者
> 
> ```
> c3 = F.interpolate(c3, (x_1_h, x_1_w), mode='bilinear')
> ```
> 
> 其中的`b`、`c`都是从tensor的attributes中获取，但如若你在定义输入时为`[1, 3, -1, -1]`，那么获取到的attributes中`h`和`w`就是-1，自然就无法满足reshape的需求了

噢 原来是这样子 难怪转为预测时就不能不指定大小了，非常感谢！！
