### ISSUE TITLE
paddle2onnx能否支持pixel_shuffle ？

### ISSUE THREAD

**Issue by KKKloveQbh** [PaddlePaddle/Paddle2ONNX#260]
进行超分辨率模型的转换时，程序报错There's 1 ops are not supported yet
=========== pixel_shuffle =========== 该怎么解决呢？

**Comment by jiangjiajun** [comment]
> 进行超分辨率模型的转换时，程序报错There's 1 ops are not supported yet
> =========== pixel_shuffle =========== 该怎么解决呢？

你好，方便提供一下你的模型文件吗

**Comment by KKKloveQbh** [comment]
> 
> 
> > 进行超分辨率模型的转换时，程序报错There's 1 ops are not supported yet
> > =========== pixel_shuffle =========== 该怎么解决呢？
> 
> 你好，方便提供一下你的模型文件吗

好的，该怎么给你呢，发邮箱吗？

**Comment by jiangjiajun** [comment]
可以上传百度网盘分享，或者邮件至jiangjiajun@baidu.com

**Comment by jiangjiajun** [comment]
已提PR https://github.com/PaddlePaddle/Paddle2ONNX/pull/261
通过如下方式重新安装Paddle2ONNX即可
```
pip uninstall paddle2onnx
git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
cd Paddle2ONNX
git checkout pixel_shuffle
python setup.py install
```

重新安装后使用如下命令转换即可
```
paddle2onnx --model_dir=. --model_filename=rfsanx4.pdmodel --params_filename=rfsanx4.pdiparams --save_file model.onnx --opset_version=11
```

由于没有测试数据，当前并没有验证模型转换前后的精度是否一致，如您在转换后测试有其它问题，可以随时反馈

**Comment by KKKloveQbh** [comment]
> 
> 
> 已提PR #261
> 通过如下方式重新安装Paddle2ONNX即可
> 
> ```
> pip uninstall paddle2onnx
> git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
> cd Paddle2ONNX
> git checkout develop
> python setup.py install
> ```
> 
> 重新安装后使用如下命令转换即可
> 
> ```
> paddle2onnx --model_dir=. --model_filename=rfsanx4.pdmodel --params_filename=rfsanx4.pdiparams --save_file model.onnx --opset_version=11
> ```
> 
> 由于没有测试数据，当前并没有验证模型转换前后的精度是否一致，如您在转换后测试有其它问题，可以随时反馈

好的，十分感谢您~
