### ISSUE TITLE
paddleseg使用paddle2onnx转换后的onnx模型的输入为什么是type: float32[-1,3,-1,-1]这样？

### ISSUE THREAD

**Issue by Fly-hub** [PaddlePaddle/Paddle2ONNX#269]
请问：paddleseg使用paddle2onnx转换后的onnx模型的输入为什么是type: float32[-1,3,-1,-1]这样？输出是type: float32[-1,2,-1,-1]，为什么只有通道数那个参数是正常的，别的都是-1，而且转换后的onnx模型使用onnxruntime无法有效进行推理部署。我训练的是paddleseg中的unet网络。

**Comment by jiangjiajun** [comment]
- -1表示那一维是动态的，可以随便输入多少大小
- 无法使用onnxruntime进行推理，错误提示是什么呢？

**Comment by Fly-hub** [comment]
是使用onnx的错误，[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:image 是因为输入图像的名字没写对，现在更改完了。但是使用onnxruntime推理的结果类型为什么是list？而不是numpy.ndarray?输入的数据类型明明是numpy.ndarray，是onnxruntime的问题吗？还是我哪里没搞对？

**Comment by jiangjiajun** [comment]
```
sess = onnxruntime.InferenceSession('model.onnx')
data = {'image': np.ndarray}
# 返回的result为list,如果只有一个输出，那result的长度为1，取result[0]即可
result = sess.run(None, data)
```

**Comment by Fly-hub** [comment]
import cv2
import time
import numpy as np
import onnxruntime
import matplotlib.pyplot as plt

sess = onnxruntime.InferenceSession("segonnx/unetmodel.onnx")
img_path = 'PaddleSeg/data/optic_disc_seg/JPEGImages/P0010.jpg'

img0 = cv2.imread(img_path)
img1 = cv2.resize(img0, (512, 512))
ori_image = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
input_image = ori_image.astype(np.float32) / 255.0
input_image = np.transpose(input_image, [2, 0, 1])
img_data = input_image[np.newaxis, :, :, :]

start_time = time.time()
ort_inputs = {sess.get_inputs()[0].name: img_data}
print(type(ort_inputs))
result = sess.run(None, ort_inputs)
end_time = time.time()
print("Time used: ", end_time - start_time, 's')

r_map = result[0]
print("查看result[0]是什么类型",type(r_map))

image=np.asanyarray(conf_map,dtype=np.uint8)
print(type(image))
cv2.imwrite("out.jpg", image)

#没有成功保存为图片
# 结果显示如下：
#<class 'dict'>
#Time used:  3.0770576000213623 s
#查看result[0]是什么类型 <class 'numpy.ndarray'>
#<class 'numpy.ndarray'>
#False

**Comment by jiangjiajun** [comment]
上面的代码调用cv2.imwrite出错，建议查下为何cv2.imwrite执行出错，是否可以这样用，由于这些不属于Paddle2ONNX的范畴，建议在网上找下相关使用方法
