### ISSUE TITLE
ERNIE动态图转ONNX时输入数据类型如何知道？

### ISSUE THREAD

**Issue by bigvine2** [PaddlePaddle/Paddle2ONNX#270]
paddle动态图转ONNX的描述非常简略，能否给出一个详细的例子，例如对现有动态图的预训练模型转换为onnx的过程？
当前例子中输入数据类型是容易知道的，但是预训练模型的输入数据类型并不知道，这使得转onnx无法进行

**Comment by jiangjiajun** [comment]
参考这个回复 https://github.com/PaddlePaddle/Paddle2ONNX/issues/244#issuecomment-825401217

How to convert a PaddlePaddle model to ONNX model, follow 2 steps

- Get a paddlepaddle inference model, which means the model is exported to deploy, it contains 2 files include model.pdmodel and model.pdiparams(filename is defined by user)
- Use command paddle2onnx --model_dir paddle_model_dirname --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 10 --save_file export_model.onnx( 3 parameters should be defined, model_dir, model_filename and params_filename)

**Comment by bigvine2** [comment]
大哥，你这是静态图的转换方式，比较老了，新的文档在这里https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.6/README_zh.md
这里的动态图转换onnx虽然写了，但是太简略，我如何知道预训练模型的input_spec是什么？这是我想问的重点，注意，是动态图！

**Comment by jiangjiajun** [comment]
动态图下支持两种模式
1. 直接使用API导出
2. 使用Paddle接口将模型保存为部署模型后，再进行转换

当前如若你不清楚数据类型如何知道，建议先参考原模型的github上的文档，将模型导出为部署模型，再使用上面那种方式导出模型

**Comment by bigvine2** [comment]
无论是直接导出，或者是保存为部署模型再转，都需要知道先定义输入数据，可是我该怎么知道输入数据类型呢？我看代码里面都是这就调用数据加载函数，并没有模型的input_spec说明

**Comment by jiangjiajun** [comment]
建议先参考原模型的github上的文档，将模型导出为部署模型；如若原Github项目中找不到相关说明，可在相应repo中提issue反馈需求
