### ISSUE TITLE
请教PPYOLOv2转ONNX相关问题

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/Paddle2ONNX#276]
现在通过文档将PPYOLOv2转ONNX是没有问题的。
但是我希望转出来的ONNX是没有NMS这一块的，应该怎么操作呢？
NonMaxSuppression的输入如下，
> boxes
name: Concat_75
scores
name: concat_14.tmp_0
max_output_boxes_per_class
name: Constant_1180
iou_threshold
name: Constant_1179
score_threshold
name: Constant_1178

研究了下模型结构图之后，我希望ONNX的输出由如下算子的输出组成：Concat_73，Concat_74，Concat_75。
请问该如何实现？

**Comment by jiangjiajun** [comment]
有两种方式
- 1. 直接修改转换后的ONNX模型，裁剪掉NMS之后的所有操作，整个模型只要NMS的输入，可以参考下网上的博文，如https://blog.csdn.net/weixin_41521681/article/details/112724867
- 2. 修改PaddleDetection的代码，使它export_model保存的模型不包含NMS

**Comment by raymondchu-z** [comment]
@jiangjiajun 感谢回复。我正在尝试方法1，想要显示每个算子输出的shape。参考代码如下：
> import onnx
from onnx import shape_inference
path = "..."
onnx.save(onnx.shape_inference.infer_shapes(onnx.load(path)), path)

报错如下：
> Traceback (most recent call last):
  File "/home/zlm/9.github/Paddle2ONNX/examples/edit_onnx.py", line 16, in <module>
    onnx.save(onnx.shape_inference.infer_shapes(onnx.load(path)), path.replace(".onnx","_with_shape.onnx"))
  File "/home/zlm/anaconda3/envs/paddle_env/lib/python3.6/site-packages/onnx/shape_inference.py", line 37, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Identity, node name: Identity_5): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)

PPYOLOv2的模型输出为：
<html>
<body>
<!DOCTYPE html>

输出名称 | 说明
-- | --
save_infer_model/scale_0.tmp_1 | NMS的输出，形状为[N, 6], 其中N为预测框的个数，6为[class_id, score, x1, y1, x2, y2]。
save_infer_model/scale_1.tmp_1 | 每张图片对应预测框的个数，例如batch_size为2，输出为[N1, N2], 表示第一张图包含N1个预测框，第二张图包含N2个预测框，并且预测框的总个数和NMS输出的第一维N相同


</body>
</html>

Identity_5这个算子对应的输出就是`scale_1.tmp_1`

**Comment by jiangjiajun** [comment]
上面代码并没有看到是怎么做的
