### ISSUE TITLE
请教如何读取onnx模型里的Constant

### ISSUE THREAD

**Issue by raymondchu-z** [PaddlePaddle/Paddle2ONNX#278]
如题。
例如reshape_4这个算子的shape是
> name: Constant_190
kind: Constant
type: int64[3]
[
    0,
    0,
    -1
]

我该在哪访问到这个`Constant_190`并修改他的值？并不在`graph.node`和`graph.initializer`里。

**Comment by jiangjiajun** [comment]
这个可以去找下ONNX的Python API，模型本质上是一个protobuf文件，你可以找到这个节点的属性进行修改
