### ISSUE TITLE
Help me !!!  生成固定输入大小的ONNX 模型

### ISSUE THREAD

**Issue by WangFengtu1996** [PaddlePaddle/Paddle2ONNX#290]
HI,all
* 在nvidia jetson xvaier nx 上部署 paddlepaddle 提供的预训练模型， 转成ONNX模型，只支持固定输入形状的ONNX模型， 但是我不知道如何生成固定输入大小的ONNX 模型，现在我这边已经可以生成ONNX模型
* 下载paddlepallde 预训练模型 ``http://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_pretrained.tar``
* 转换模型为 ``model``  ``params`` ,通过项目``https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification``
执行下面的脚本
```
python infer.py \
        --model=ResNet50_vd \
        --pretrained_model=${path_to_pretrain_model} \
        --save_inference=True
```
具体内容的话，如下所示
```
    fluid.io.load_persistables(exe, args.pretrained_model)
    if args.save_inference:
        fluid.io.save_inference_model(
            dirname=args.model,
            feeded_var_names=['image'],
            main_program=test_program,
            target_vars=out,
            executor=exe,
            model_filename='model',
            params_filename='params')
        logger.info("model: {0} is already saved".format(args.model))
        exit(0)

```
* 我现在已经可以得到ONNX 模型，但是因为是动态输入，所以在设备上是不支持的，
* 请帮我看下，我这么做是否是一条最优的路径 （使用paddlepaddle 提供的预训练模型， ——》 ONNX， 在设备上部署ONNX TensorRT）
* 针对，固定输入大小，请指导我一下该如何操作（基于我这种方式）

多谢。

**Comment by WangFengtu1996** [comment]
补充一下， 项目中的关于FAQ 中的超链接，已经失效了。

**Comment by WangFengtu1996** [comment]
``https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification`` 这个项目下面，关于paddle2onnx 静态输入大小不会做支持了？

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleCV/image_classification/infer.py#L86 这行代码中，
```
    image = fluid.data(
        name='image', shape=[None] + args.image_shape, dtype='float32')
```
改成具体的shape，例如
```
    image = fluid.data(
        name='image', shape=[1, 3, 224, 224], dtype='float32')
```
然后再重新导出即可
