### ISSUE TITLE
PaddleClas中的商品检测模型Paddle2ONNX转换完后，输入是 -1*3*224*224，这个-1是啥意思？

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle2ONNX#301]
![图片](https://user-images.githubusercontent.com/40679769/129543190-9190d095-7bc8-4da3-99d2-cb41e369020a.png)

**Comment by jiangjiajun** [comment]
-1表示batch size

**Comment by xinsuinizhuan** [comment]
> 
> 
> -1表示batch size

batch size 也不可能是-1啊，都-1了，那还怎么训练

**Comment by jiangjiajun** [comment]
-1表示batch_size是一个可变的值
