### ISSUE TITLE
ernie预训练模型，使用ernie_crf进行信息抽取，转onnx中InputSpec（）里面输出的list是什么，模型有Input_ids,seg_ids,length,我看训练的时候这三个都是tensor

### ISSUE THREAD

**Issue by CocoSkyler** [PaddlePaddle/Paddle2ONNX#305]
不知道paddle支不支持这个模型转换onnx

**Comment by jiangjiajun** [comment]
建议您先通过PaddleNLP将模型导出为inference模型后，再使用Paddle2ONNX进行转换
`paddle2onnx --model_dir mymodel --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx`

另外当前您这边是基于什么原因需要将模型转成ONNX呢

**Comment by CocoSkyler** [comment]
想转成中间模型进行tensorrt加速，后面也方便c++调用部署

**Comment by jiangjiajun** [comment]
PaddleInference支持TensorRT进行部署，同时也可以使用Python或C++进行部署
