### ISSUE TITLE
Paddle模型转mnn失败

### ISSUE THREAD

**Issue by chunfeng9shili** [PaddlePaddle/Paddle2ONNX#308]
我在PaddleDetection中下载PP-YOLO tiny模型,https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.2/configs/ppyolo/README_cn.md
使用以下方式转换成onnx后,再转换成mnn
`paddle2onnx --model_dir ./ppyolo_tiny_quant/ --model_filename '__model__' --params_filename '__params__' --save_file ppyolo_tiny_quant.onnx --opset_version 11
./MNNConvert -f ONNX --modelFile ./ppyolo_tiny_quant.onnx --MNNModel ./ppyolo_tiny_quant.mnn --bizCode biz`
在onnx转mnn时报错:
`Start to Convert Other Model Format To MNN Model...

[21:45:42] ~/MNN-1.1.2/tools/converter/source/onnx/onnxConverter.cpp:31: ONNX Model ir version: 7

Start to Optimize the MNN Net...

Check failed: attrs != nullptr ==> "TopKV's attr is empty"

Error while converting the model! 

Error for onnx convert`

请问有碰到过这种问题吗,麻烦给点提示

**Comment by jiangjiajun** [comment]
这个问题可以咨询下MNN

**Comment by hellosiri** [comment]
请问问题解决了吗，我也碰到这个问题
