### ISSUE TITLE
paddle2onnx, sync_batch_norm不支持

### ISSUE THREAD

**Issue by rourou8023** [PaddlePaddle/Paddle2ONNX#319]
paddle模型转onnx，报下面的错：
There's 1 ops are not supported yet
=========== sync_batch_norm ===========
应该怎么解决呢？

**Comment by jiangjiajun** [comment]
你好，sync_batch_norm不属于应该正常导出来的OP，请联系源REPO，反馈此问题

**Comment by jiangjiajun** [comment]
Duplicate of https://github.com/PaddlePaddle/PaddleSeg/issues/1335
