### ISSUE TITLE
Operator:multiclass_nms only supports input[batch_size] == 1，出现这个警告，

### ISSUE THREAD

**Issue by gyr-kdgc** [PaddlePaddle/Paddle2ONNX#320]
虽然转换成功，但是我在用转换后的onnx去转换openvino格式的时候报错，总是形状不匹配，请问怎么修改模型的输入为1？

**Comment by jiangjiajun** [comment]
转openvino时，由于nms最终会导致输出的结果个数不确定，因此建议在导出模型时，删除NMS，然后再转NMS，具体参考此issue https://github.com/PaddlePaddle/PaddleDetection/issues/3667

**Comment by gyr-kdgc** [comment]
> 转openvino时，由于nms最终会导致输出的结果个数不确定，因此建议在导出模型时，删除NMS，然后再转NMS，具体参考此issue [PaddlePaddle/PaddleDetection#3667](https://github.com/PaddlePaddle/PaddleDetection/issues/3667)

导出时把yml文件中的nms删除之后，还是有这个警告，是不是仍然导出了nms？难道训练的时候也要把nms去掉嘛？

2021-09-13 03:34:48 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-09-13 03:34:51 [INFO]      ONNX model genarated is valid.
2021-09-13 03:34:51 [INFO]      ONNX model saved in /home/chapterix/project/output/onnx_for_acceleration.onnx

**Comment by jiangjiajun** [comment]
> > 转openvino时，由于nms最终会导致输出的结果个数不确定，因此建议在导出模型时，删除NMS，然后再转NMS，具体参考此issue [PaddlePaddle/PaddleDetection#3667](https://github.com/PaddlePaddle/PaddleDetection/issues/3667)
> 
> 导出时把yml文件中的nms删除之后，还是有这个警告，是不是仍然导出了nms？难道训练的时候也要把nms去掉嘛？
> 
> 2021-09-13 03:34:48 [WARNING] Operator:multiclass_nms only supports input[batch_size] == 1.
> 2021-09-13 03:34:51 [INFO] ONNX model genarated is valid.
> 2021-09-13 03:34:51 [INFO] ONNX model saved in /home/chapterix/project/output/onnx_for_acceleration.onnx

1. 删除yml文件中的nms
2. 重新使用PaddleDetection导出模型
3. 再使用paddle2onnx将第2步模型转为ONNX

**Comment by gyr-kdgc** [comment]
终于解决了，只删除yml中的nms没有用，需要在tools/export_model.py中将test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)这一行的exclude_nms设置为True才能不把NMS层导出，这个默认为False，改成默认True就行。
不过有点尴尬的是没了NMS层之后openvino推理出来的结果是很乱的，可能需要再写一个NMS

**Comment by WooXinyi** [comment]
> 终于解决了，只删除yml中的nms没有用，需要在tools/export_model.py中将test_fetches = model.test(feed_vars, exclude_nms=FLAGS.exclude_nms)这一行的exclude_nms设置为True才能不把NMS层导出，这个默认为False，改成默认True就行。 不过有点尴尬的是没了NMS层之后openvino推理出来的结果是很乱的，可能需要再写一个NMS
你好，可以分享下去除NMS层转换后模型的后处理规则吗？谢谢

**Comment by jiangjiajun** [comment]
如果你是openvino部署yolov3，参考此文档即可https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.9/experimental/openvino_ppdet_cn.md

**Comment by WooXinyi** [comment]
> https://github.com/PaddlePaddle/Paddle2ONNX/blob/release/0.9/experimental/openvino_ppdet_cn.md

你好，我不是要用openvino部署，而是要转换为华为om模型，目前还不支持nms，所以得自己实现；但去除掉nms后出来的两个输出shape分别是[-1, 22743, 4]和[-1, 4, 22743]，可以说明一下分别代表的意义吗
