### ISSUE TITLE
paddle2onnx，使用onnxruntime推理，CPU和GPU结果不同

### ISSUE THREAD

**Issue by rourou8023** [PaddlePaddle/Paddle2ONNX#321]
使用paddle2onnx，将paddle动态图模型转为onnx模型，再使用onnxruntime推理时，
使用onnxruntime-cpu,推理结果和paddle模型，结果相近；
但是使用同版本的onnxruntime-gpu，推理结果与paddle结果相差很远，
是什么原因造成的呢？
cpu:
Exported model has been predicted by ONNXRuntime!
ONNXRuntime predict time: 5.0517 s
Paddle predict time: 0.8682 s
The difference of results between ONNXRuntime and Paddle looks good!
relative_diff:  1.0463244e-06
max_abs_diff:  1.1444092e-05

gpu:
Exported model has been predicted by ONNXRuntime!
ONNXRuntime predict time: 1.0025 s
Paddle predict time: 0.9931 s
The difference of results between ONNXRuntime and Paddle looks bad!
relative_diff:  0.29378724
max_abs_diff:  3.240285

**Comment by jiangjiajun** [comment]
你好，当前确认CPU上Paddle与ONNXRuntime结果一致，推测问题在于ONNXRuntime在GPU上推断可能存在问题，模型转换无问题，建议咨询ONNRuntime
