### ISSUE TITLE
paddle.onnx.export return "not_equal "，"fill_zeros_like" op not support

### ISSUE THREAD

**Issue by kevinfu1717** [PaddlePaddle/Paddle2ONNX#323]
When I transform the "ernie_gen_acrostic_poetry" model in PaddleHub to ONNX. I got the error below:

NotImplementedError: 
There's 2 ops are not supported yet
=========== not_equal ===========
=========== fill_zeros_like ===========

my script is "paddle.onnx.export(net, 'erine', input_spec=[q_ids], opset_version=12, enable_onnx_checker=True)"

And I found the op:
equal | 1~12 |  
fill_constant | 1~12 |  
fill_constant_batch_size_like | 9~12 |  
fill_any_like | 9~12

were support in paddle2ONNX.

how can I go on my transform for "ernie_gen_acrostic_poetry "

**Comment by kevinfu1717** [comment]
whether I can use other op to cross over it? And what are they?

**Comment by yeliang2258** [comment]
You can try to install the develop version to see if the conversion can be successful.

**Comment by yeliang2258** [comment]
What is your usage scenario? Please provide your model.

**Comment by kevinfu1717** [comment]
I want to use ernie_gen_acrostic_poetry from PaddleHub in ONNX or OpenVINO. The model is the  PaddleHub`s model:[https://github.com/PaddlePaddle/PaddleHub/tree/6f8e0ab50140226b111cf16b9b2550736426cbbf/modules/text/text_generation/ernie_gen_acrostic_poetry](https://github.com/PaddlePaddle/PaddleHub/tree/6f8e0ab50140226b111cf16b9b2550736426cbbf/modules/text/text_generation/ernie_gen_acrostic_poetry) 

 **moduleinfo**(
     name="ernie_gen_acrostic_poetry",
     version="1.0.1",
     summary=
     "ERNIE-GEN is a multi-flow language generation framework for both pre-training and fine-tuning. This module has fine-tuned for poetry generation task.",
     author="adaxiadaxi",
     author_email="",
     type="nlp/text_generation",
 )

My script is: [https://aistudio.baidu.com/aistudio/projectdetail/1553121](https://aistudio.baidu.com/aistudio/projectdetail/1553121)
`

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/326
I have added these two ops, please pull this PR to test.

**Comment by kevinfu1717** [comment]
It works. Thx. I think we can close this issue
