### ISSUE TITLE
[issue] Unknown model file format version.

### ISSUE THREAD

**Issue by kaixin-bai** [PaddlePaddle/Paddle2ONNX#327]
```
onnx                              1.10.1
onnxruntime                       1.8.1
```
I tried onnx with both 1.10.1 and 1.7.0 as mentioned in [https://github.com/PaddlePaddle/Paddle2ONNX/issues/317](https://github.com/PaddlePaddle/Paddle2ONNX/issues/317), both versions have the same problem.

with onnx 1.7.0:
```python
>>> import onnx
>>> import onnxruntime
>>> onnx_model = onnx.load("../yolov3obj1.onnx")
>>> onnx.checker.check_model(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.
>>> ort_session = onnxruntime.InferenceSession("../yolov3obj1.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ../yolov3obj1.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.
```

with onnx 1.10.1
```python
>>> import onnx
>>> import onnxruntime
>>> onnx_model = onnx.load("../yolov3obj1.onnx")
>>> onnx.checker.check_model(onnx_model)
>>> ort_session = onnxruntime.InferenceSession("../yolov3obj1.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ../yolov3obj1.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.
```

I used the command below to convert onnx model.
```
paddle2onnx --model_dir inference_model/yolov3_darknet53_270e_obj1_coco/ --model_filename model.pdmodel             --params_filename model.pdiparams             --opset_version 11             --save_file yolov3obj1.onnx
```

**Comment by Goghzki** [comment]
I also face this issue when I convert paddleocr recognition model to onnx.

**Comment by jiangjiajun** [comment]
Hi, @Goghzki @kaixin-bai  Which version of paddle2onnx you are using, use following command to check version information
```
pip show paddle2onnx
```
Also, we just released Paddle2ONNX v0.8.1, please try the newest version, if the problem occurs again, please upload your paddle model(exported as inference model), we'll try to reproduce the problem.

**Comment by Goghzki** [comment]
I got this info after pip show paddle2onnx
`Name: paddle2onnx
Version: 0.8.1
Summary: a toolkit for converting trained model of PaddlePaddle to ONNX.
Home-page: https://github.com/PaddlePaddle/paddle2onnx
Author: dltp-sz
Author-email: dltp-sz@baidu.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: onnx, protobuf, six
Required-by: `

The model I convert is from official model:
`wget https://paddleocr.bj.bcebos.com/PP-OCRv2/chinese/ch_PP-OCRv2_rec_infer.tar`

And the convert command I used is:
`paddle2onnx -m /content/ch_PP-OCRv2_rec_infer/ --model_filename inference.pdmodel --params_filename inference.pdiparams -s rec.onnx --opset_version 11 --enable_onnx_checker True`

**Comment by yeliang2258** [comment]
hello, please install the latest version of paddle and try like this:
`paddle2onnx --model_dir ./ --model_filename inference.pdmodel --params_filename inference.pdiparams -s rec.onnx --opset_version 11 --enable_onnx_checker True`

Name: onnx
Version: 1.7.0

Name: onnxruntime
Version: 1.8.1

**Comment by Goghzki** [comment]
It works! It seems I used wrong onnx version which is 1.10.1. Thinks~
BTW, is there any plan to support distillation model of paddleocr? Error info when I convert them:
There's 2 ops are not supported yet
=========== fake_channel_wise_quantize_dequantize_abs_max ===========
=========== fake_quantize_dequantize_moving_average_abs_max ===========

**Comment by yeliang2258** [comment]
The support of the quantitative model is in our plan list, and it is planned to be supported in the next version V0.9.

**Comment by kaixin-bai** [comment]
```
paddle2onnx                       0.8.1
paddlepaddle-gpu                  2.1.2
onnx                              1.7.0
onnxruntime                       1.8.1
```
yolov3 command:
```bash
paddle2onnx --model_dir ./ --model_filename model.pdmodel --params_filename model.pdiparams -s yolov3_darknet53_270e_obj1_coco.onnx --opset_version 11 --enable_onnx_checker True
```
```python
>>> import onnxruntime
>>> import onnx
>>> onnx_model = onnx.load("yolov3_darknet53_270e_obj1_coco.onnx")
>>> onnx.checker.check_model(onnx_model)
```
For yolov3 everything works fine.

yolov4 command:
```bash
paddle2onnx --model_dir ./ --model_filename __model__ --params_filename __params__ -s yolov4_cspdarknet_synthobj1_coco.onnx --opset_version 11 --enable_onnx_checker True
```
```python
>>> import onnxruntime
>>> import onnx
>>> onnx_model = onnx.load("yolov4_cspdarknet_synthobj1_coco.onnx")
>>> onnx.checker.check_model(onnx_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data-r10/kb/anaconda3/envs/paddle/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: The model does not have an ir_version set properly.
```
For yolov4 I got the error above.

**Comment by yeliang2258** [comment]
Is your model uncombined PaddlePaddle model(parameters saved in different files) or combined PaddlePaddle model(parameters saved in one binary file)? please upload your model.  thanks.

**Comment by kaixin-bai** [comment]
I trained the yolov4 model with paddlepaddle, and export the model with the command:
```
cd static/
python3 tools/export_model.py -c ./configs/yolov4/yolov4_cspdarknet_mpsobj2_coco.yml --output_dir=./inference_model -o weights=output/yolov4_cspdarknet_obj1_coco/model_final.pdparams
```
The config file, model, and parameter file before export: [https://drive.google.com/file/d/1l9bZ4MPPFcsR3Yj7S_eksA214tirfS6k/view?usp=sharing](https://drive.google.com/file/d/1l9bZ4MPPFcsR3Yj7S_eksA214tirfS6k/view?usp=sharing)

**Comment by yeliang2258** [comment]
> I trained the yolov4 model with paddlepaddle, and export the model with the command:
> 
> ```
> cd static/
> python3 tools/export_model.py -c ./configs/yolov4/yolov4_cspdarknet_mpsobj2_coco.yml --output_dir=./inference_model -o weights=output/yolov4_cspdarknet_obj1_coco/model_final.pdparams
> ```
> 
> The config file, model, and parameter file before export: https://drive.google.com/file/d/1l9bZ4MPPFcsR3Yj7S_eksA214tirfS6k/view?usp=sharing

please use this command to convert:
```
paddle2onnx --model_dir ./ --model_filename __model__ --params_filename __params__ -s model.onnx --opset_version 11 --enable_onnx_checker True
```

**Comment by kaixin-bai** [comment]
Thanks! It works.
