### ISSUE TITLE
转换ch_PP-OCRv2_rec_infer模型后，模型运行耗时出现较大增长

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle2ONNX#331]
转换ch_ppocr_mobile_v2.0_det_infer模型为onnx之后，使用python+onnxRuntime+cpu的时候耗时未出现较大波动。
转换ppOCR最近推出的ch_PP-OCRv2_rec_infer模型为onnx之后，python+onnxRuntime+cpu的时候耗时出现翻倍情况。
该模型在paddle上面是相对之前模型更快的，因为两个模型的网络结构改变了，想请教下是Paddle2ONNX或者onnxRuntime对某些新的节点操作并行化优化不太好吗？

**Comment by yeliang2258** [comment]
Hello, paddle2onnx is responsible for the conversion of the model. Please ask the onnxruntime team for model performance issues, thank you.
