### ISSUE TITLE
将BERT转成ONNX是报错，There's 3 ops are not supported yet。

### ISSUE THREAD

**Issue by liucongg** [PaddlePaddle/Paddle2ONNX#333]
详细错误如下：
NotImplementedError: 
There's 3 ops are not supported yet
=========== select_input ===========
=========== logical_not ===========
=========== conditional_block ===========

采用paddlenlp的BERTModel模型，只是在模型内部增加了求解loss和if判断，导致导出onnx报错

**Comment by liucongg** [comment]
我好像发现了，貌似内部不能写if

**Comment by liucongg** [comment]
自己分析，是由于if判断造成的，但是为什么if attention_mask is None，不会报错。但是if len(attention_mask.shape) == 2:会报错呢？

**Comment by yeliang2258** [comment]
Hello, paddle2onnx does not support control flow now.

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
