### ISSUE TITLE
请问动态图和静态图分别代表啥意思

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/Paddle2ONNX#337]
请问动态图和静态图分别代表啥意思

**Comment by jiangjiajun** [comment]
- 动态图指的是PaddlePaddle框架在升级2.0后，采用与PyTorch一样的编程方式，在升级2.0后，我们为框架集成了`paddle.onnx.export`接口，导出ONNX模型可以无需先前模型导出到本地，再使用paddle2onnx进行转换
- 静态图指的是PaddlePaddle框架导出来的模型，这个模型可以是PaddlePaddle 1.x版本保存到本地的模型，也可以是2.0版本通过`paddle.jit.save`保存到本地的模型

**Comment by Dandelion111** [comment]
好的，谢谢，在转换为onnx模型的时候，在实例化模型后是不是要加载一下模型参数再把模型设置为评估状态，我看给的示例中没有这么做

**Comment by Dandelion111** [comment]
> * 动态图指的是PaddlePaddle框架在升级2.0后，采用与PyTorch一样的编程方式，在升级2.0后，我们为框架集成了`paddle.onnx.export`接口，导出ONNX模型可以无需先前模型导出到本地，再使用paddle2onnx进行转换
> * 静态图指的是PaddlePaddle框架导出来的模型，这个模型可以是PaddlePaddle 1.x版本保存到本地的模型，也可以是2.0版本通过`paddle.jit.save`保存到本地的模型

好的，谢谢，在转换为onnx模型的时候，在实例化模型后是不是要加载一下模型参数再把模型设置为评估状态，我看给的示例中没有这么做
