### ISSUE TITLE
ppocr crnn paddle模型转onnx输入格式怎么设置？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/Paddle2ONNX#338]
![image](https://user-images.githubusercontent.com/48303408/134334760-089ba1d0-7de8-46c6-87a9-07c8c3427ea3.png)
请问识别模型ppocr中， crnn paddle模型转onnx输入格式怎么设置？

**Comment by yeliang2258** [comment]
根据模型的输入设置正确的shape和数据类型，具体请咨询：https://github.com/PaddlePaddle/PaddleOCR

**Comment by neverstoplearn** [comment]
> 根据模型的输入设置正确的shape和数据类型，具体请咨询：https://github.com/PaddlePaddle/PaddleOCR

请问设置为None指的是可变的意思吗？
