### ISSUE TITLE
请问有没有ppocr动态图转为onnx的例子

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/Paddle2ONNX#339]

**Comment by jiangjiajun** [comment]
Hi, @Dandelion111 建议你使用如下的步骤完成模型导出

1. https://github.com/PaddlePaddle/PaddleOCR 使用PaddleOCR导出Inference模型， 参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/cpp_infer#21
2. 使用paddle2onnx命令转换模型

另外当前你是出于什么需求才要将模型转成ONNX呢？

**Comment by Dandelion111** [comment]
> Hi, @Dandelion111 建议你使用如下的步骤完成模型导出
> 
> 1. https://github.com/PaddlePaddle/PaddleOCR 使用PaddleOCR导出Inference模型， 参考文档 https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.3/deploy/cpp_infer#21
> 2. 使用paddle2onnx命令转换模型
> 
> 另外当前你是出于什么需求才要将模型转成ONNX呢？

你好，我打算把模型转为onnx，然后再转为openvino模型，我查询到的示例都是静态图的转换，目前没有找到ppocr动态图识别模型如何转换，望指教

**Comment by jiangjiajun** [comment]
动态图也是按照如上流程转换
