### ISSUE TITLE
AIStudio项目如何下载？

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/Paddle2ONNX#350]
![image](https://user-images.githubusercontent.com/48303408/134641859-3d5451fc-e2a6-48e5-85d9-657a51069978.png)
请问AIStudio这样的项目如何下载？

**Comment by jiangjiajun** [comment]
Hi, @Dandelion111 我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s
