### ISSUE TITLE
[bug]paddle2onnx.dygraph2onnx下有bug，非作者原意

### ISSUE THREAD

**Issue by bingo789** [PaddlePaddle/Paddle2ONNX#359]
![onnx_im_bug](https://user-images.githubusercontent.com/40812718/135263990-f4d306eb-6b26-43ea-bab2-abe2cb998ee6.png)
for循环应该减少缩进一个tab

**Comment by jiangjiajun** [comment]
由于目前动转静时，均无需指定`output_specs`，因此此处代码逻辑一直没有被执行过，没有报错。

但不能否定这是个错误的代码，需要修复一下 @yeliang2258
