### ISSUE TITLE
import paddle.fluid as fluid ImportError: No module named fluid

### ISSUE THREAD

**Issue by haifenghan** [PaddlePaddle/Paddle2ONNX#36]
Using `pip install paddlepaddle`, I get the paddlepaddle (0.11.0).
After that I tried `python convert.py --modeldir inception_v1/`, I get the error: `import paddle.fluid as fluid ImportError: No module named fluid`.

Then I tried to change `import paddle.v2.fluid as fluid`, it works.

Rerunning the converter and get the following error:

```Traceback (most recent call last):
  File "/home/haifeng/Synopsys/paddle-onnx/convert.py", line 21, in <module>
    import fluid_onnx.ops as ops
  File "/home/haifeng/Synopsys/paddle-onnx/fluid_onnx/ops.py", line 17, in <module>
    from paddle.fluid.executor import fetch_var
ImportError: No module named fluid.executor
```

It seems the converter use different paddlepaddle version.
Could you look into it?

Thanks

**Comment by kuke** [comment]
@haifenghan The paddle version in `pip` is too old, please reinstall paddlepaddle from the latest source code.
