### ISSUE TITLE
支持pdiparams/pdmodel转成onnx模型吗

### ISSUE THREAD

**Issue by bingo789** [PaddlePaddle/Paddle2ONNX#360]
预训练下已有inference.pdiparams、inference.pdiparams.info、inference.pdmodel，是否可以根据这几个文件直接导出到onnx模型？

**Comment by jiangjiajun** [comment]
支持，直接使用命令即可

**Comment by Hunter-P** [comment]
> 支持，直接使用命令即可

请问要如何转呢，我这边报错
![image](https://user-images.githubusercontent.com/30851628/136951406-d8133df0-7792-4bf3-9fc6-8489bf4e46a0.png)

**Comment by yeliang2258** [comment]
可以使用以下命令行：paddle2onnx --model_dir paddle_model  --save_file onnx_file --opset_version 10 --enable_onnx_checker True

**Comment by jiangjiajun** [comment]
Hi, @Hunter-P 我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s
