### ISSUE TITLE
Support DS2 model

### ISSUE THREAD

**Issue by VictorBebnev** [PaddlePaddle/Paddle2ONNX#37]
Do you plan to support the conversion for [DeepSpeech](https://github.com/PaddlePaddle/DeepSpeech)?

**Comment by kuke** [comment]
@VictorBebnev We don't have a plan yet, because DeepSpeech is in V2 API and the convertor here only supports Fluid API.

**Comment by VictorBebnev** [comment]
[This](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/merge_model.py) isn't converter V2 API to Fluid API?

**Comment by kuke** [comment]
No. It only `Merge the model config and parameters into one file`  for V2 APIs.

**Comment by VictorBebnev** [comment]
Hm, converter V2 API to Fluid API doesn't exist?
In Fluid plan you have [line](https://github.com/PaddlePaddle/Paddle/issues/7145)( 5.1 convert v2 model to fluid model) about it.

**Comment by kuke** [comment]
As far as I know, the conversion from V2 to Fluid is not ready yet, and it has nothing to do with the convertor here.

**Comment by VictorBebnev** [comment]
Tell me please where i can check status of this converter. It is very important for my project.

**Comment by kuke** [comment]
Cannot give a detailed schedule yet. But if you really need Fluid APIs,  you'd better develop your project based  on it from now on. Waiting for the conversion from V2 to Fluid will be full of risks.

**Comment by VictorBebnev** [comment]
To implement the project, I use the pre-trained model for V2, without it I can not implement the project, there is no data on which it was trained.

**Comment by kuke** [comment]
@VictorBebnev Then I suggest you keep using V2 API, and it should be not necessary to convert the V2 model to Fluid.

**Comment by VictorBebnev** [comment]
Ok, thanks.
