### ISSUE TITLE
ch_PP-OCRv2_rec_slim转onnx失败

### ISSUE THREAD

**Issue by Gitlixiangdong** [PaddlePaddle/Paddle2ONNX#376]
使用官方的ch_PP-OCRv2_rec_slim转onnx模型失败，编译命令如下：
paddle2onnx -m ./inference_model/paddlev2_slim/rec_crnn/ --model_file
name inference.pdmodel --params_filename inference.pdiparams -s ./inference_model/onnx_slim/rec_crnn/model.onnx
 --opset_version 11 --enable_onnx_checker True
错误如下：
NotImplementedError:
There's 2 ops are not supported yet
=========== fake_quantize_dequantize_moving_average_abs_max ===========
=========== fake_channel_wise_quantize_dequantize_abs_max ===========
谢谢！

**Comment by yeliang2258** [comment]
你好，请问你的使用场景是？是需要基于什么平台做部署吗？另外请提供一下模型。谢谢

**Comment by Gitlixiangdong** [comment]
> 你好，请问你的使用场景是？是需要基于什么平台做部署吗？另外请提供一下模型。谢谢

你好，我是使用onnx来做ocr推理，模型是paddleocr官方提供的，模型分别为ch_PP-OCRv2_det_slim，ch_PP-OCRv2_rec_slim，ch_ppocr_mobile_slim_v2.0_cls，模型地址为：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md
谢谢

**Comment by yeliang2258** [comment]
> > 你好，请问你的使用场景是？是需要基于什么平台做部署吗？另外请提供一下模型。谢谢
> 
> 你好，我是使用onnx来做ocr推理，模型是paddleocr官方提供的，模型分别为ch_PP-OCRv2_det_slim，ch_PP-OCRv2_rec_slim，ch_ppocr_mobile_slim_v2.0_cls，模型地址为：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md 谢谢

上面的模型是量化模型，你的部署是需要量化后的模型的吗？

**Comment by Gitlixiangdong** [comment]
> > > 你好，请问你的使用场景是？是需要基于什么平台做部署吗？另外请提供一下模型。谢谢
> > 
> > 
> > 你好，我是使用onnx来做ocr推理，模型是paddleocr官方提供的，模型分别为ch_PP-OCRv2_det_slim，ch_PP-OCRv2_rec_slim，ch_ppocr_mobile_slim_v2.0_cls，模型地址为：https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_ch/models_list.md 谢谢
> 
> 上面的模型是量化模型，你的部署是需要量化后的模型的吗？

是的

**Comment by yeliang2258** [comment]
请问你是部署到什么推理框架上呢，应用场景是？

**Comment by Gitlixiangdong** [comment]
> 请问你是部署到什么推理框架上呢，应用场景是？

onnxruntime

**Comment by yeliang2258** [comment]
量化模型我们尚不支持，onnxruntime部署的话，你可以先使用非量化模型，后期支持量化模型的时候你再测试。

**Comment by jiangjiajun** [comment]
Hi, @Gitlixiangdong 
Paddle2ONNX目前还没有支持量化模型的转换，但这个已经在排期当中，相信在这个季度就会给出一个解决方案。欢迎关注我们的项目，以便获取Paddle2ONNX最新的研发进展与更新！

**Comment by Gitlixiangdong** [comment]
> Hi, @Gitlixiangdong Paddle2ONNX目前还没有支持量化模型的转换，但这个已经在排期当中，相信在这个季度就会给出一个解决方案。欢迎关注我们的项目，以便获取Paddle2ONNX最新的研发进展与更新！

好的，谢谢

**Comment by Gitlixiangdong** [comment]
> 量化模型我们尚不支持，onnxruntime部署的话，你可以先使用非量化模型，后期支持量化模型的时候你再测试。

好的，谢谢

**Comment by yeliang2258** [comment]
你好，我们的Paddle2ONNX现在支持量化模型导出为ONNX了，欢迎体验：https://github.com/PaddlePaddle/Paddle2ONNX/pull/399

**Comment by jiangjiajun** [comment]
Hi, @Gitlixiangdong 我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s
