### ISSUE TITLE
Paddle2onnx 按照官方文档转模型报错

### ISSUE THREAD

**Issue by SkipAngel** [PaddlePaddle/Paddle2ONNX#381]
import paddle
from paddle import nn
from paddle.static import InputSpec
import paddle2onnx as p2o

class LinearNet(nn.Layer):
def init(self):
super(LinearNet, self).init()
self._linear = nn.Linear(784, 10)

def forward(self, x):
    return self._linear(x)
export to ONNX
layer = LinearNet()
save_path = './linear_net'
x_spec = InputSpec([None, 784], 'float32', 'x')
layer.eval()
paddle.onnx.export(layer, save_path, input_spec=[x_spec])

报错：
File "/home/xushoukai/anaconda3/envs/baidu/lib/python3.6/site-packages/paddle2onnx-0.8.1-py3.6.egg/paddle2onnx/constant/dtypes.py", line 17, in
File "/home/xushoukai/paddle_test/onnx.py", line 84, in
paddle.onnx.export(layer, save_path, input_spec=[x_spec])
File "/home/xushoukai/anaconda3/envs/baidu/lib/python3.6/site-packages/paddle/onnx/export.py", line 100, in export
p2o.dygraph2onnx(
AttributeError: module 'paddle2onnx' has no attribute 'dygraph2onnx'

**Comment by jiangjiajun** [comment]
Hi, @SkipAngel 
注意到你的paddle2onnx是0.8.1的版本，理论上不应该出现上述问题，请检查下
- 你运行的python代码命名请避免命名为`paddle.py`或`paddle2onnx.py`
- 运行代码的当前目录下是否有`paddle2onnx.py`或者`paddleonxx`命名的文件或文件夹，如若有，请移除

**Comment by jiangjiajun** [comment]
Hi, @SkipAngel  我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s
