### ISSUE TITLE
如何更改ONNX模型输出的名字？

### ISSUE THREAD

**Issue by lucky-xu-1994** [PaddlePaddle/Paddle2ONNX#387]
您好，请问paddle2ONNX可以自己定义输出节点的名字么，如果不能，该如何修改？

**Comment by jiangjiajun** [comment]
出于什么需求要修改名字呢，如果不改会有什么问题？

**Comment by lucky-xu-1994** [comment]
@jiangjiajun 目前已经解决了，谢谢！

**Comment by jiangjiajun** [comment]
Hi, @lucky-xu-1994 我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s

**Comment by WooXinyi** [comment]
> @jiangjiajun 目前已经解决了，谢谢！

请问是怎么修改输出节点名的呢？

**Comment by lucky-xu-1994** [comment]
> > @jiangjiajun 目前已经解决了，谢谢！
> 
> 请问是怎么修改输出节点名的呢？
@WooXinyi 
你可以将模型先转为ONNX，然后直接对ONNX进行操作，修改输出节点。

**Comment by lucky-xu-1994** [comment]
@WooXinyi 
你可以用paddle2onnx将模型转为ONNX之后，直接对ONNX操作，修改输出节点的名字。

**Comment by wuyx517** [comment]
@lucky-xu-1994 请问 ONNX 怎么修改输出节点的名字，我修改后，使用onnx runtime 加载模型失败了

**Comment by jiangjiajun** [comment]
> @lucky-xu-1994 请问 ONNX 怎么修改输出节点的名字，我修改后，使用onnx runtime 加载模型失败了

https://github.com/jiangjiajun/PaddleUtils/tree/main/onnx 使用这个工具脚本吧 @wuyx517
