### ISSUE TITLE
lapstyle

### ISSUE THREAD

**Issue by Chenhait** [PaddlePaddle/Paddle2ONNX#390]
lapstyle模型可以转onnx吗？

**Comment by jiangjiajun** [comment]
Hi，你这里提到的模型开源于哪里，转成onnx的用处是什么呢？ 可以先自行转换测试

**Comment by Chenhait** [comment]
> Hi，你这里提到的模型开源于哪里，转成onnx的用处是什么呢？ 可以先自行转换测试

谢谢您的回复。lapstyle的项目地址是https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/lap_style.md。是否可以直接用Paddle2ONNX转呢？我想转换了用tensorrt部署。谢谢。

**Comment by jiangjiajun** [comment]
如无特殊op，一般都没问题，你可以自行转换

**Comment by Chenhait** [comment]
> 如无特殊op，一般都没问题，你可以自行转换

谢谢您的回复，不过我看lapstyle只给了权重文件，模型文件去哪里找呢？

**Comment by jiangjiajun** [comment]
模型导出的方式可参考PaddlGan文档，或者在其Repo下咨询
