### ISSUE TITLE
operator:matrix_nms only supports input[batch_size]==1

### ISSUE THREAD

**Issue by jiejiangd** [PaddlePaddle/Paddle2ONNX#397]
想问一下两个警告，题目是一个，另一个如下：
Operator:matrix_nms is not supported completely, so we use traditional nms(nms_threshold=0.5) to instead it, which introduce some difference.
在将ppyolov2转化成onnx时出现，因为我后续要转换成rknn模型的时候有关于nms的错误，想知道这个警告会不会有影响，警告的具体意思是什么

**Comment by jiangjiajun** [comment]
- batch_size==1 是指后续在模型推理的时候，每次只支持单张图片输入
- matrix_nms是目标检测模型的一个后处理操作，由于ONNX不支持，所以这个后处理会被替换为普通的NMS，会有一些影响，但影响不大

**Comment by jiangjiajun** [comment]
Hi, @jiejiangd  我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好, 谢谢~ https://iwenjuan.baidu.com/?code=r8hu2s
