### ISSUE TITLE
文档链接失效

### ISSUE THREAD

**Issue by Lingeer** [PaddlePaddle/Paddle2ONNX#401]
Hi, 
链接地址: https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/FAQ.md
在上述文档中提供的`文档导出`失效.

**Comment by yeliang2258** [comment]
文档已经更新，请查阅：https://github.com/PaddlePaddle/Paddle2ONNX/pull/403

**Comment by Lingeer** [comment]
@yeliang2258  Thanks.
