### ISSUE TITLE
ONNX to TensorRT

### ISSUE THREAD

**Issue by Auth0rM0rgan** [PaddlePaddle/Paddle2ONNX#411]
Hello, 

I have trained the PaddelOCR with my own data and I was able to convert the pretrained model to ONNX. My question is how can I convert the onnx file to tensorRT with fp16? is there any documentation that I can follow?

Thanks

**Comment by yeliang2258** [comment]
Thank you for using paddle, you can refer to this link for TensorRT deployment: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#overview
TensorRT has many examples of loading ONNX for deployment, you can refer to them.
In addition, PadldeInference can also deploy the Paddle model efficiently, and you are welcome to use it.

**Comment by yeliang2258** [comment]
Thank you very much for using Paddle. We have prepared a simple survey questionnaire (can be completed in half a minute). If you have time, please help us to complete the survey and help Paddle2ONNX to be better, thank you.
https://iwenjuan.baidu.com/?code=ibd2b1

**Comment by Auth0rM0rgan** [comment]
@yeliang2258, Thanks for the guide! is there any documentation that explained how to use PaddelOCR pretrained model to PaddleInference? and also, do I need to convert the pretrained model to ONNX or TensorRT to use paddleinference?

**Comment by yeliang2258** [comment]
Using PaddleInference deployment does not need to switch to ONNX, you can use the following API interface to deploy.
First, you need to install Paddle with TensorRT, related link: https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html 
then save the PaddleOCR model as an inference paddle model, just like this https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.3/doc/doc_en/inference_en.md
finally use the following API to deploy.
You can refer to the deployment part of the PaddleOCR Repo https://github.com/PaddlePaddle/PaddleOCR
```
from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor
import paddle.inference as paddle_infer

def set_config():
    config = AnalysisConfig('paddle_model/model.pdmodel', 
                            'paddle_model/model.pdiparams')
    config.enable_use_gpu(10000, 0)
    # Enable TensorRT
    config.enable_tensorrt_engine(
        workspace_size=1 << 30,
        max_batch_size=1,
        min_subgraph_size=0,
        precision_mode=paddle_infer.PrecisionType.Half,
        use_static=False,
        use_calib_mode=False)
    config.enable_memory_optim()
    config.gpu_device_id()
    config.switch_use_feed_fetch_ops(False)
    config.switch_specify_input_names(True)
    config.switch_ir_optim(True)
    return config

config = set_config()
predictor = create_paddle_predictor(config)

input_names = predictor.get_input_names()
input_tensor = predictor.get_input_tensor(input_names[0])
input_tensor.reshape([1, 3, 480, 1024])
input_tensor.copy_from_cpu(data)

predictor.zero_copy_run()
output_names = predictor.get_output_names()
output_tensor = predictor.get_output_tensor(output_names[0])
paddleinference_pred = output_tensor.copy_to_cpu()
```

**Comment by Auth0rM0rgan** [comment]
@yeliang2258 Thank you so much for the links and help! Where can I find more information about paddle tensorRT? I searched the deployment part of the PaddleOCR as you mentioned but couldn't find anything related to the tensorRT. 

Thanks!

**Comment by yeliang2258** [comment]
You can download the compiled python version here, then install the corresponding version of tensorrt.:
https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html
![image](https://user-images.githubusercontent.com/30516196/144532618-970ee4b4-4140-4ac8-bce5-ba0b461e00cc.png)

**Comment by Auth0rM0rgan** [comment]
@yeliang2258, I followed the instruction on the website to download and install the PaddleInference. I was able to install everything without any error but Im facing error when I try to run the script you have provide. I searched everywhere and github issues but couldnt find anything so I can solve the error. Here is the error im getting:

```
**You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.**
W1203 15:45:46.118569 36732 analysis_predictor.cc:1183] Deprecated. Please use CreatePredictor instead.
W1203 15:45:46.485334 36732 analysis_predictor.cc:715] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1203 15:45:46.495699 36732 analysis_predictor.cc:549] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1203 15:45:46.527877 36732 graph_pattern_detector.cc:91] ---  detected 24 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
I1203 15:45:46.531420 36732 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
--- Running IR pass [fc_fuse_pass]
I1203 15:45:46.532269 36732 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
--- Running IR pass [conv_elementwise_add_fuse_pass]
I1203 15:45:46.535305 36732 graph_pattern_detector.cc:91] ---  detected 42 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I1203 15:45:46.546943 36732 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 1 nodes
Traceback (most recent call last):
  File "tools/infer/predict_trt.py", line 25, in <module>
    predictor = create_paddle_predictor(config)
**RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
  [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)**


```

My os is Ubuntu 20, TensorRT 7.2 is also installed, Cuda Vesion 11.3

**Comment by mahesh11T** [comment]
@yeliang2258 
```py
config = set_config()
min_input_shape = {"image": [1, 3, 240, 240], "scale_factor": [-1,2], "im_shape": [-1,2]}

config.set_trt_dynamic_shape_info(min_input_shape)
```

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/107621428/f231ec56-f9bf-41fd-abc9-5fd29aac1bbf)
in case of dynamic shapes should we set shapes for all layers or just input layer?, or can we set to static and run, how to solve this?
