### ISSUE TITLE
转onnx模型时模型输出不固定（n,w,h显示为-1）

### ISSUE THREAD

**Issue by lzz773751548** [PaddlePaddle/Paddle2ONNX#421]
感谢您们将如此优秀的框架开源，我在使用Paddle2ONNX出现了一下问题
**问题描述**
我在进行人像分割测试时，在尝试把fcn_hrnetw18_small_v1模型转成onnx。
我希望转换成的onnx模型的输入与输出是固定不可变的，而不是动态的。
我尝试了各种方法，目前只能做到对于模型的输入给予一个固定shape，但模型输出的结果中w与h仍然是-1（可变）

**更多信息 :**
 - 为什么需要转换为ONNX格式：在硬件上测试
 - Paddle2ONNX版本:0.9.0
 - 你的联系方式(Email/Wechat/Phone):lzz773751548@gmail.com

期待您的回复

**Comment by jiangjiajun** [comment]
Hi, @lzz773751548 你好，可使用paddle2onnx 0.9版本进行操作

1. 转换onnx模型时固定输入shape
```
paddle2onnx --model_dir .  \
                       --model_filename model.pdmodel \
                       --params_filename model.pdiparams \
                       --save_file model.onnx \
                       --opset_version 11 \
                       --input_shape_dict="{'x': [1, 3, 512, 512]}"
```
2. 使用onnxruntime来进行优化， onnxruntime在加载模型时，有不同级别的优化，其中当为`ORT_ENABLE_BASIC`时，会删除模型无用节点，进行常量折叠，执行如下代码即可得到优化后的`optimzied_model.onnx`
```
import onnxruntime as ort
option = ort.SessionOptions()
option.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC
option.optimized_model_filepath = "optimized_model.onnx"
sess = ort.InferenceSession("model.onnx", sess_options=option)
```

另外方便的话，麻烦抽半分钟时间填一下此问卷，帮助改进Paddle2ONNX https://wenjuan.baidu-int.com/?code=r8hu2s

**Comment by jiangjiajun** [comment]
Hi, @lzz773751548 

当前如你想从PaddeleSeg转出固定shape的onnx模型，请采用如下步骤修改seg代码后，再重新导出inference模型->onnx模型即可
1. 修改paddle2onnx的export.py代码 https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/export.py#L120
将原代码
```
    new_net = paddle.jit.to_static(
        new_net,
        input_spec=[paddle.static.InputSpec(shape=shape, dtype='float32')])
```
改为例如
```
    new_net = paddle.jit.to_static(
        new_net,
        input_spec=[paddle.static.InputSpec(shape=[1, 3, 512, 512], dtype='float32')])
```
2. 修改paddle2onnx的对应模型代码，如fcn.py https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/paddleseg/models/fcn.py#L81
将原代码
```
    def forward(self, x):
        feat_list = self.backbone(x)
        logit_list = self.head(feat_list)
        return [
            F.interpolate(
                logit,
                paddle.shape(x)[2:],
                mode='bilinear',
                align_corners=self.align_corners) for logit in logit_list
        ]
```
改为
```
    def forward(self, x):
        feat_list = self.backbone(x)
        logit_list = self.head(feat_list)
        return [
            F.interpolate(
                logit,
                [512, 512], # 注意此数值与上面应该相对应
                mode='bilinear',
                align_corners=self.align_corners) for logit in logit_list
        ]
```

另外方便的话，麻烦抽半分钟时间填一下此问卷，帮助改进Paddle2ONNX https://iwenjuan.baidu.com/?code=r8hu2s
