### ISSUE TITLE
官方 Paddle2.0导出ONNX模型和推理 例子运行报错

### ISSUE THREAD

**Issue by xxdm** [PaddlePaddle/Paddle2ONNX#429]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
在官方例子：https://aistudio.baidu.com/aistudio/projectdetail/3243132?forkThirdPart=1  中`ONNX模型验证`
![image](https://user-images.githubusercontent.com/10796263/145942124-1b623570-0346-423f-8880-05e6e7f4f764.png)

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.

**报错截图**
![image](https://user-images.githubusercontent.com/10796263/145942193-85d1b54e-24e8-4826-a312-6fc8bfcf9242.png)

**Comment by yeliang2258** [comment]
用户您好，看起来是ONNXRuntime和ONNX的版本不匹配导致的。
他们的版本匹配关系：https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md
可以尝试安装onnx==1.8.0，onnxruntime==1.10.0
