### ISSUE TITLE
请问“paddle.onnx.export”导出时如何指定outputs节点的名字

### ISSUE THREAD

**Issue by gl94** [PaddlePaddle/Paddle2ONNX#432]
![image](https://user-images.githubusercontent.com/26252750/146330902-5fde32a3-2457-4601-bcaf-545fbc60c770.png)

**Comment by yeliang2258** [comment]
用户你好，请问你是需要只导出模型的一部分吗？

**Comment by gl94** [comment]
> 用户你好，请问你是需要只导出模型的一部分吗？

我需要整个导出 inputs 名字可以改 outputs名字我需要修改因为默认的名字是 
“name: save_infer_model/scale_0.tmp_0” 有一个"."会出问题
![image](https://user-images.githubusercontent.com/26252750/146344938-1fe50bb0-74c6-4bc6-9084-ab145c0c4872.png)

**Comment by jiangjiajun** [comment]
为什么需要改名呢？不改名的话会影响使用吗

**Comment by gl94** [comment]
> 为什么需要改名呢？不改名的话会影响使用吗

没事了 不影响使用 谢谢你

**Comment by yeliang2258** [comment]
方便的话，麻烦抽出半分钟时间帮我们完成一个Paddle2ONNX的调研问卷：https://iwenjuan.baidu.com/?code=r8hu2s 
谢谢！
