### ISSUE TITLE
ppyolov2-转成onnx后，在python上 用opencv调用报错

### ISSUE THREAD

**Issue by xxdm** [PaddlePaddle/Paddle2ONNX#435]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
载入模型报错

**更多信息 :**
 - Paddle2ONNX版本: 最新
 - opencv：4.5
 - python： 3.7

**报错截图**
![image](https://user-images.githubusercontent.com/10796263/146745768-b706b779-ab83-4a58-8090-9461536303a0.png)

**其他信息**
是不是需要修改源码，将切片的方式改掉？

**Comment by yeliang2258** [comment]
看样子是opencv对slice的支持情况有限制，请问你这边为什么需要用opencv进行部署呢？有是那么特殊需求吗？

**Comment by xxdm** [comment]
> 看样子是opencv对slice的支持情况有限制，请问你这边为什么需要用opencv进行部署呢？有是那么特殊需求吗？

这里的编译环境只有vs2015，而且需要用c++调用，除了用opencv 调用 onnx， 找不到其他方法了

**Comment by yeliang2258** [comment]
https://paddleinference.paddlepaddle.org.cn/product_introduction/inference_intro.html
你看看PaddleInference是否可以部署，PaddleInference有c++的接口

**Comment by xxdm** [comment]
> https://paddleinference.paddlepaddle.org.cn/product_introduction/inference_intro.html 你看看PaddleInference是否可以部署，PaddleInference有c++的接口

这个看了，好像不支持vs2015呀，建议vs2019

**Comment by yeliang2258** [comment]
https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html
Paddleinference支持C++调用，好像也支持你说的环境。
![image](https://user-images.githubusercontent.com/30516196/146861317-58359f31-3e89-48de-b288-cc3a4fec23d2.png)

**Comment by xxdm** [comment]
> https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html Paddleinference支持C++调用，好像也支持你说的环境。 ![image](https://user-images.githubusercontent.com/30516196/146861317-58359f31-3e89-48de-b288-cc3a4fec23d2.png)

好的，现在我就试下

**Comment by xxdm** [comment]
> https://paddleinference.paddlepaddle.org.cn/user_guides/source_compile.html Paddleinference支持C++调用，好像也支持你说的环境。 ![image](https://user-images.githubusercontent.com/30516196/146861317-58359f31-3e89-48de-b288-cc3a4fec23d2.png)
![image](https://user-images.githubusercontent.com/10796263/146886179-c9a988ff-3fa7-4a64-998c-7f912209c5db.png)
在编译过程中报错了，这是什么问题呢

**Comment by xxdm** [comment]
> 看样子是opencv对slice的支持情况有限制，请问你这边为什么需要用opencv进行部署呢？有是那么特殊需求吗？

现在编译失败，能否告知如何修改，使opencv 能支持onnx
