### ISSUE TITLE
ppyolov2模型转换为onnx后部分Clip算子没有min和max

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Paddle2ONNX#437]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
ppyolov2_r50vd_dcn_365e_coco模型转换为onnx后Clip_24,Clip_29,Clip_34没有min和max

**更多信息 :**
 - Paddle2ONNX版本:最新
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
![image](https://user-images.githubusercontent.com/31937673/146860631-65e9b704-2891-49a0-a3f0-a2d25accd834.png)

**其他信息**

**Comment by jiangjiajun** [comment]
看起来是转换时使用了默认的min和max，我们来修复一下

另外方便的话，麻烦抽半分钟时间填一下此问卷，帮助改进Paddle2ONNX https://iwenjuan.baidu.com/?code=r8hu2s

**Comment by ChenjieXu** [comment]
已填写

**Comment by ChenjieXu** [comment]
> 看起来是转换时使用了默认的min和max，我们来修复一下
> 
> 另外方便的话，麻烦抽半分钟时间填一下此问卷，帮助改进Paddle2ONNX https://iwenjuan.baidu.com/?code=r8hu2s

我现在看下来其他模型也会有问题，能提供一个转换没有问题的版本、tag或者模型吗？

**Comment by jiangjiajun** [comment]
麻烦上传一下你的原Paddle模型(已经导出为Inference的模型）

另外其他模型指的是什么模型？确认一下，你使用的Paddle2ONNX是0.9版本吗

**Comment by yeliang2258** [comment]
你现在拉最新的develop再测试一下。

**Comment by ChenjieXu** [comment]
可以了，感谢光速支持。<抱拳>
