### ISSUE TITLE
Paddle 模型转换成 ONNX 后使用 onnxruntime 推理出错

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle2ONNX#444]
**问题描述**
使用最新 PaddleDetection 训练了一个 FCOS 模型，然后根据 PaddleDetection 的教程导出为 onnx 格式，期间使用了 onnxsimplifier，转换过程已经完成。

**更多信息 :**
 - 用于部署的推理引擎: onnxruntime
 - 为什么需要转换为ONNX格式：学习使用
 - Paddle2ONNX版本: 0.9.0
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_19' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:479 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 93 by 94

**其他信息**
1. 使用 Paddle 该模型可以推理成功
2. 使用 Netron 查看网络结构，Add_19 算子应该是 FPN 中的一个特征融合结构
2. 已经尝试过降低 onnxruntime 版本，现已尝试过 1.9.0、1.8.0、1.6.0 等
3. 训练模型使用的 PaddleDetection 版本是最新的，且没有改动代码

**Comment by yeliang2258** [comment]
你好，看样子是shape没有对上导致的广播错误，请提供一下你的模型，我们来排查一下

**Comment by yeliang2258** [comment]
方便的话，麻烦抽出半分钟时间帮我们完成一个Paddle2ONNX的调研问卷：https://iwenjuan.baidu.com/?code=r8hu2s
谢谢！

**Comment by ghost** [comment]
> 你好，看样子是shape没有对上导致的广播错误，请提供一下你的模型，我们来排查一下

链接：https://pan.baidu.com/s/1Mh4jR54VEIeUKDV2fw6FDA 
提取码：fcos

好的，问卷已经填写，谢谢。

**Comment by yeliang2258** [comment]
您好，请提供一下Paddle的推理模型。

**Comment by zhangtaoshan** [comment]
> 您好，请提供一下Paddle的推理模型。
这是配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/fcos/fcos_r50_fpn_1x_coco.yml
这是权重文件：链接：https://pan.baidu.com/s/1fXUSqdgL2r19M9HugUJ2yQ 
提取码：fcos

**Comment by ghost** [comment]
> 您好，请提供一下Paddle的推理模型。

这是配置文件：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/fcos/fcos_r50_fpn_1x_coco.yml
这是权重文件：链接：https://pan.baidu.com/s/1fXUSqdgL2r19M9HugUJ2yQ 
提取码：fcos

**Comment by yeliang2258** [comment]
有导出来的模型文件吗.pdmodel和.pdiparams

**Comment by ghost** [comment]
> 有导出来的模型文件吗.pdmodel和.pdiparams

链接：https://pan.baidu.com/s/1qTRCOfP4sGAb4F077wph1w 
提取码：fcos

**Comment by yeliang2258** [comment]
你好，这个模型拉取最新的develop分支进行转换，然后输入设置为[1,3,512,512]和[1,2]时可以正常推理.

**Comment by ghost** [comment]
> 你好，这个模型拉取最新的develop分支进行转换，然后输入设置为[1,3,512,512]和[1,2]时可以正常推理.

好的，谢谢啦，已经成功了。我这边是在转换时将输入固定就可以了，我原来没有固定输入形状。
