### ISSUE TITLE
将paddleDetection的一些模型  转成 onnx格式后，用opencv调用（一些操作如切片opencv不支持）导致报错，如何修改。

### ISSUE THREAD

**Issue by xxdm** [PaddlePaddle/Paddle2ONNX#445]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
将paddleDetection的一些模型  转成 onnx（已经成功转成onnx）格式后，用opencv调用（一些操作如切片opencv不支持）导致报错，如何修改。

**Comment by yeliang2258** [comment]
你好，主要是OpenCV对OP的支持还有问题导致的无法推理，你可以尝试修改Paddle模型，或者换一个推理引擎。
https://github.com/PaddlePaddle/Paddle2ONNX/issues/435

**Comment by yeliang2258** [comment]
你也可以到Paddle框架下面提issue，咨询一下PaddleInference在VS2015下的编译和支持情况。

**Comment by xxdm** [comment]
> 你也可以到Paddle框架下面提issue，咨询一下PaddleInference在VS2015下的编译和支持情况。

去看过了，别人也有类似问题，并没有很好的解决。

**Comment by yeliang2258** [comment]
可以尝试一下OpenCV的Repo下面去提issue，或者尝试修改Paddle模型，如果ONNXRuntime可以正常运行ONNX模型的话，证明ONNX模型导出正确
