### ISSUE TITLE
PaddleOCR的模型转成onnx后的推理结果与原版不一致，精度差很多。

### ISSUE THREAD

**Issue by alatriste-lee** [PaddlePaddle/Paddle2ONNX#451]
按照以下页面的说明，先准备环境，然后转换，接下来测试转换后的onnx推理结果，并对比pdmodel的推理结果。
https://gitee.com/paddlepaddle/Paddle2ONNX#https://gitee.com/link?target=https%3A%2F%2Faistudio.baidu.com%2Faistudio%2Fprojectdetail%2F1461212

第一步，准备conda环境：

用pip安装完成后的：

(ocrv2) ➜  test_onnx pip list | grep paddle

paddle2onnx                       0.9.0
paddleocr                         2.3.0.2
paddlepaddle                      2.2.1

(ocrv2) ➜  test_onnx pip list | grep onnx

onnx                              1.9.0
paddle2onnx                       0.9.0

第二步，转换：
从https://gitee.com/paddlepaddle/PaddleOCR/blob/release/2.4/doc/doc_ch/models_list.md 下载ch_PP-OCRv2_det、rec模型

paddle2onnx --model_dir ch_PP-OCRv2_det_infer  --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_det_infer.onnx --opset_version 10 --enable_onnx_checker True

paddle2onnx --model_dir ch_PP-OCRv2_rec_infer  --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_rec_infer.onnx --opset_version 10 --enable_onnx_checker True

paddle2onnx --model_dir ch_ppocr_mobile_v2.0_cls_infer  --model_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdmodel --params_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdiparams --save_file ppocrv1_cls_infer.onnx --opset_version 10 --enable_onnx_checker True

第三步，推理：
在PaddleOCR目录下，推理./deploy/lite/imgs/lite_demo.png

用onnx推理：

python tools/infer/predict_system.py --use_gpu=False --use_onnx=True --cls_model_dir=ppocrv2_cls_infer_11.onnx --rec_model_dir=ppocrv2_rec_infer_11.onnx --det_model_dir=ppocrv2_det_infer_11.onnx --image_dir=./deploy/lite/imgs/lite_demo.png

用pdmodel推理：

python tools/infer/predict_system.py --use_gpu=False --cls_model_dir=./ch_ppocr_mobile_v2.0_cls_infer --rec_model_dir=./ch_PP-OCRv2_rec_infer --det_model_dir=./ch_PP-OCRv2_det_infer --image_dir=./deploy/lite/imgs/lite_demo.png

现在的问题是，原版pdmodel的推理结果和转成onnx后的推理结果不一致。
转换这一步的opset_version，9、10和11都试过了，用model_zoo页面多个模型排列组合测试过，都是不一致的。

**报错截图**
原版的效果：
![lite_demo_v2](https://user-images.githubusercontent.com/7877379/147378695-bb3faf1f-5ed9-4bf6-b8e6-62b7f9f106d7.png)
onnx后的效果：
![lite_demo_v2_11](https://user-images.githubusercontent.com/7877379/147378774-a4393b75-b775-47a8-914a-1d49de80f872.png)

我在 ocr 14 群。

**Comment by yeliang2258** [comment]
方便的话，麻烦抽出半分钟时间帮我们完成一个Paddle2ONNX的调研问卷：https://iwenjuan.baidu.com/?code=r8hu2s
谢谢！

**Comment by jiangjiajun** [comment]
@alatriste-lee 你的ONNX模型是怎么导出的呢？ 贴一下转换方式（例如文档、代码或命令）

**Comment by neonhuang** [comment]
@alatriste-lee， 您好，paddleocr出现精度差异问题，是因为你转换的onnx模型默认使用了固定输入shape，这样一来，在paddleocr使用onnxruntime进行推理时，需要将图片resize到onnx模型固定的输入大小，但是实际图片可能不是这个大小，这样有可能导致预测的精度下降；
首先，你需要使用如下命令产生onnx模型
paddle2onnx --model_dir ch_PP-OCRv2_det_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_det_infer.onnx --opset_version 10 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True
paddle2onnx --model_dir ch_PP-OCRv2_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file ppocrv2_rec_infer.onnx --opset_version 10 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True

paddle2onnx --model_dir ch_ppocr_mobile_v2.0_cls_infer --model_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdmodel --params_filename ch_ppocr_mobile_v2.0_cls_infer/inference.pdiparams --save_file ppocrv1_cls_infer.onnx --opset_version 10 --input_shape_dict="{'x':[-1,3,-1,-1]}" --enable_onnx_checker True

其次，需要修改paddleocr中的代码:
https://github.com/neonhuang/PaddleOCR/blob/release/2.4/tools/infer/predict_det.py#L104
https://github.com/neonhuang/PaddleOCR/blob/release/2.4/tools/infer/predict_rec.py#L111
具体见修改见PR， https://github.com/PaddlePaddle/PaddleOCR/pull/5095

最后，使用,  python setup.py install 重新安装paddleocr解决

**Comment by alatriste-lee** [comment]
按照新的说明做了重新导出，并按照 [https://github.com/PaddlePaddle/PaddleOCR/pull/5095/files](https://github.com/PaddlePaddle/PaddleOCR/pull/5095/files) 
的指导对文件做了修改，重新预测了一下，哎，这次的结果onnx和导出它的pdmodel是一致的了！！

感谢老师，老师好人一生平安～

**Comment by zxl222** [comment]
您好，我按照最新文档生成的模型出现了效果很差的情况，和上图类似。
![00015504](https://user-images.githubusercontent.com/37622443/148514282-323585e8-0e99-4d66-b579-43305b30c5fa.jpg)

**Comment by jiangjiajun** [comment]
@zxl222 按照上面文档重新导出模型和安装paddleocr后即可解决
