### ISSUE TITLE
ppyolov2模型mul_186两个的输入类型不一致

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Paddle2ONNX#452]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
ppyolov2_r50vd_dcn_365e_coco模型mul_186两个的输入类型不一致，但onnx算子定义要求这两者类型一致才行。导致在转换成其他格式时出错。

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:develop版本
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
用户你好，请提供一下导出的inference model

**Comment by yeliang2258** [comment]
方便的话，麻烦抽出半分钟时间帮我们完成一个Paddle2ONNX的调研问卷：https://iwenjuan.baidu.com/?code=r8hu2s
谢谢！

**Comment by zuocebianpingmao** [comment]
> 用户你好，请提供一下导出的inference model

[Uploading ppyolov2_r50vd_dcn_365e_coco.zip…]()

**Comment by yeliang2258** [comment]
模型上传有问题，无法下载

**Comment by zuocebianpingmao** [comment]
> 模型上传有问题，无法下载

模型一直传不上去，百度网盘可以吗？
链接：https://pan.baidu.com/s/14HP98bW33b1ik2ncK4mbaA 
提取码：jlew

**Comment by yeliang2258** [comment]
用户你好，请安装最新develop版本，最新版本已经解决这个问题

**Comment by ChenjieXu** [comment]
还是无法转换。看了commit之后有两个问题。dtype为什么是Float32和Float64，我报错说是类型是INT32和INT64。还有是opset_version为什么只有[7,9,15]，根据教程我们都是用的11转换的。

**Comment by yeliang2258** [comment]
上面百度网盘里面的模型我验证了develop版本是可以转换而且验证了onnx模型和paddle模型没有计算误差。要不你也提供一下你的model，我这边给你看看。

**Comment by ChenjieXu** [comment]
是没有计算误差，但是输入类型不一致会导致在转换成华为模型的时候会报错。但是根据onnx算子定义要求这两者类型一致才行。
![af951fe3e987c5ae0a7ba63957687ba](https://user-images.githubusercontent.com/31937673/147808907-168e9d35-87e8-4d5a-a4ac-0807aa9bce4c.jpg)

**Comment by ChenjieXu** [comment]
> 上面百度网盘里面的模型我验证了develop版本是可以转换而且验证了onnx模型和paddle模型没有计算误差。要不你也提供一下你的model，我这边给你看看。

哦哦，我们俩用的model是同一个

**Comment by yeliang2258** [comment]
哦哦，明白了，华为这个转换应该是需要int32和int64都严格对应。这个你看看是那个OP，能否自己修改一下？在op_mappe
r中保存了每一个op的转换实现，修改代码之后安装便可。

**Comment by ChenjieXu** [comment]
因为这是ONNX规定是要严格对应的，我的理解是一个通用需求，你看看是否能在你们这边改掉？

**Comment by yeliang2258** [comment]
明白，我们内部会讨论尽快排期支持。



---原始邮件---
发件人: "Chenjie ***@***.***&gt;
发送时间: 2021年12月31日(周五) 下午5:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle2ONNX] ppyolov2模型mul_186两个的输入类型不一致 (Issue #452)




 
因为这是ONNX规定是要严格对应的，我的理解是一个通用需求，你看看是否能在你们这边改掉？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ChenjieXu** [comment]
> 明白，我们内部会讨论尽快排期支持。
> […](#)
> ---原始邮件--- 发件人: "Chenjie ***@***.***&gt; 发送时间: 2021年12月31日(周五) 下午5:15 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle2ONNX] ppyolov2模型mul_186两个的输入类型不一致 (Issue #452) 因为这是ONNX规定是要严格对应的，我的理解是一个通用需求，你看看是否能在你们这边改掉？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

感谢支持，请随时同步<抱拳>

**Comment by jiangjiajun** [comment]
Hi，@ChenjieXu   在这个PR里面我尝试对这个问题进行了修复 https://github.com/PaddlePaddle/Paddle2ONNX/pull/467 麻烦你拉这个代码重新安装paddle2onnx，再进行转换测试，如若可以解决你的问题 或者 仍然存在问题，请麻烦反馈给我们

**Comment by ChenjieXu** [comment]
> Hi，@ChenjieXu 在这个PR里面我尝试对这个问题进行了修复 #467 麻烦你拉这个代码重新安装paddle2onnx，再进行转换测试，如若可以解决你的问题 或者 仍然存在问题，请麻烦反馈给我们

ckass_id 应该为class_id，同时box_id也要加上Cast算子。改了之后测试可用。

**Comment by jiangjiajun** [comment]
@ChenjieXu 太赞了，我重新更新了我的PR，麻烦帮忙确认下是否有问题 https://github.com/PaddlePaddle/Paddle2ONNX/pull/467/files

**Comment by ChenjieXu** [comment]
> @ChenjieXu 太赞了，我重新更新了我的PR，麻烦帮忙确认下是否有问题 https://github.com/PaddlePaddle/Paddle2ONNX/pull/467/files

可以，没有问题。感谢支持。
