### ISSUE TITLE
将yolov3剔除nms后的后处理规则

### ISSUE THREAD

**Issue by WooXinyi** [PaddlePaddle/Paddle2ONNX#490]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
将yolov3剔除nms后，出来的两个输出shape分别是[-1, 22743, 4]和[-1, 4, 22743]，不清楚数据具体意义.以及具体的后处理规则实现

**Comment by lyuwenyu** [comment]
怎么去掉的指的是下边那个
- https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/yolo.py#L96 
- https://github.com/PaddlePaddle/PaddleDetection/blob/635e3e0a80f3d05751cdcfca8af04ee17c601a92/ppdet/modeling/post_process.py#L36

**Comment by WooXinyi** [comment]
> 怎么去掉的指的是下边那个
> 
> * https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/ppdet/modeling/architectures/yolo.py#L96
> * https://github.com/PaddlePaddle/PaddleDetection/blob/635e3e0a80f3d05751cdcfca8af04ee17c601a92/ppdet/modeling/post_process.py#L36

谢谢，但是里面没有nms的具体实现。请问有源码实现了吗

**Comment by WooXinyi** [comment]
已解决，第一个是bboxes，第二个是scores，但需要确定class
