### ISSUE TITLE
Validation for converted models for accuracy

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/Paddle2ONNX#5]
The goal would be to get identical inference results to Paddle models and inference. @kuke has more thoughts. And here is a notebook on the topic: https://github.com/onnx/tutorials/blob/master/tutorials/CorrectnessVerificationAndPerformanceComparison.ipynb.

Q: what runtime would we use for ONNX: TensorRT?

**Comment by kuke** [comment]
A:  I think mainly the server, and TensorRT is only one possible runtime environment.

**Comment by varunarora** [comment]
@kuke The server? Do you mean a Fluid ONNX backend? Because we won't have one for a while - which is why I guess you used Caffe2. Is there a reason you chose Caffe2?

**Comment by kuke** [comment]
Yes, recently many users show interests in converting the models from Fluid to ONNX, then run with other backends on PC or mobile devices. 

I used Caffe2 because the built-in backend in ONNX doesn't work, here is the [issue](https://github.com/onnx/onnx/issues/734).
