### ISSUE TITLE
PaddleDetection模型支持保存为ONNX格式，但很多模型仅支持batch=1推理

### ISSUE THREAD

**Issue by wangyuan111** [PaddlePaddle/Paddle2ONNX#501]
如下图所示 PaddleDetection模型支持保存为ONNX格式，但很多模型仅支持batch=1推理
请问 如果想导出batch=-1或者宽高都是动态尺寸的模型  现在最新版本支持吗？应该需要改哪些地方？

![1642674263(1)](https://user-images.githubusercontent.com/39080886/150320674-5609e327-4eba-414c-aeca-862ae8f43c34.png)

**Comment by jiangjiajun** [comment]
你好，这个是我们计划要解决的事情，当前你对哪些模型有动态batch或动态shape的需求呢，为什么会需要动态shape呢？

另外我们也准备了一份问卷，方便的话请抽出半分钟时间帮完成问卷 https://iwenjuan.baidu.com/?code=r8hu2s 帮助Paddle2ONNX做得更好

**Comment by lofyol** [comment]
我也是想将picodet转成动态batch的onnx

**Comment by pfchai** [comment]
+1  什么时候支持动态batch，paddle 模型部署到生产环境急需这个功能
