### ISSUE TITLE
模型转换成其他格式时NMS算子报错

### ISSUE THREAD

**Issue by ChenjieXu** [PaddlePaddle/Paddle2ONNX#516]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
在转换为华为模型时NMS算子报错，ONNX官方对NMS有官方实现，想请问百度的NMS实现跟这个链接中NMS的官方实现的描述有哪些不一致的地方？谢谢
https://github.com/onnx/onnx/blob/main/docs/Operators.md#NonMaxSuppression

**更多信息 :**
 - 为什么需要转换为ONNX格式：转成华为模型
 - Paddle2ONNX版本:develop

**报错截图**
![3cd77c30bcd5ab028156207cd88fae4](https://user-images.githubusercontent.com/31937673/151090029-a2ee6309-35b0-4921-a5fc-8c098c916fe6.jpg)

**其他信息**
之前相关的问题以及模型下载链接：https://github.com/PaddlePaddle/Paddle2ONNX/issues/452
调查问卷已经填写

**Comment by jiangjiajun** [comment]
Paddle2ONNX转换后已经采用ONNX标准的NMS算子，上面提示需要NMS算子的输出selected_indices申请的buffer size 24192000B已经超过可用。

- selected_indices的shape为`[num_indices, 3]`

这个原因在于PPYOLO在过NMS前，每个类中设定的检测框数量是25200，这样在过NMS后，要输出的selected_indices = 25200 * 80（类别数量）* 3  * 4（每个元素占4个字节）= 24192000B， 如你的日志中所提到，已经超过了可用的buffer 


当前可以考虑降低输入模型的图像大小来解决，根据这里的日志，你的模型输入大小应该是640*640，你可以改为320*320来试下，使用如下脚本重新导出ONNX模型即可
```
import paddle2onnx
import paddle

model_prefix = "/User/XXX/PaddleDetection/inference_model/yolov3_darknet53_270e_coco/model"
model = paddle.jit.load(model_prefix)
input_shape_dict = {
    "image": [1, 3, 320, 320],
    "scale_factor": [1, 2],
    "im_shape": [1, 2]
    }
onnx_model = paddle2onnx.run_convert(model, input_shape_dict=input_shape_dict, opset_version=11)

with open("./yolov3.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())
```

**Comment by WooXinyi** [comment]
我之前转过paddle的yolov3，你把nms去掉就可以转了，nms手动实现很简单，因为去掉后的网络输出已经是解码好的bboxes和scores；即使你把带nms的paddle模型转换成onnx模型也没用，因为nms的输出shape不固定，华为om模型不支持；
此外，如果你是转ppyolov2，不仅需要去掉nms，而且需要将onnx模型中的cast算子从int64类型转为int32类型；然而，按照上述方法转出的模型推理速度极慢，推理一次10s左右，个人猜测是华为对其中的某些算子支持度不够好。

**Comment by jiangjiajun** [comment]
Hi, @WooXinyi 你这里提到的推理一次10s是指单纯华为的硬件上进行推理yolov3就需要10s吗（不考虑NMS和图像前后处理等等），是哪个硬件呢

**Comment by WooXinyi** [comment]
> Hi, @WooXinyi 你这里提到的推理一次10s是指单纯华为的硬件上进行推理yolov3就需要10s吗（不考虑NMS和图像前后处理等等），是哪个硬件呢

是的，在atlas500 pro上面ppyolov2推理一次需要10s，个人觉得就是华为对某些算子支持度不好，还没有用profiling工具分析。

**Comment by jiangjiajun** [comment]
@WooXinyi ppyolov2模型结构比较特殊，里面用到到deformable_convolution, 这个算子目前很多硬件都没有支持。 Paddle2ONNX使用了大量算子来组合实现这个deformable_convolution，这可能是导致他的性能较低的原因。 如果是在华为硬件上，建议使用yolov3

**Comment by WooXinyi** [comment]
> @WooXinyi ppyolov2模型结构比较特殊，里面用到到deformable_convolution, 这个算子目前很多硬件都没有支持。 Paddle2ONNX使用了大量算子来组合实现这个deformable_convolution，这可能是导致他的性能较低的原因。 如果是在华为硬件上，建议使用yolov3

paddle的yolov3是没问题的，剔除nms后推理速度大概在38ms

**Comment by jiangjiajun** [comment]
谢谢 @WooXinyi 的反馈，我想这个信息会有助于Paddle的模型团队在做模型结构设计时，考虑更多外部硬件的兼容性。 

另外我们也计划在Paddle2ONNX添加更多指南文档和代码，帮助大家将飞桨模型部署到不同硬件上，我们预计节后会开始来做这个事情，如若有兴趣成为Paddle2ONNX 开源项目的Contributor，可以提供下联系方式，我会主动联系你哈

**Comment by WooXinyi** [comment]
> 谢谢 @WooXinyi 的反馈，我想这个信息会有助于Paddle的模型团队在做模型结构设计时，考虑更多外部硬件的兼容性。
> 
> 另外我们也计划在Paddle2ONNX添加更多指南文档和代码，帮助大家将飞桨模型部署到不同硬件上，我们预计节后会开始来做这个事情，如若有兴趣成为Paddle2ONNX 开源项目的Contributor，可以提供下联系方式，我会主动联系你哈

谢谢，我很乐意。429360267@qq.com，这是我的邮箱

**Comment by jiangjiajun** [comment]
已回复邮箱，方便的话直接添加邮件中二维码微信即可
