### ISSUE TITLE
Issues using paddle onnx convert models

### ISSUE THREAD

**Issue by baojun-nervana** [PaddlePaddle/Paddle2ONNX#52]
We ran into the following issues and would like to get direction from paddle-onnx dev.

**1.  assertion error : dims.nbDims == 3**

I can convert paddle paddle models to onnx using the fluid_to_onnx.py script, e.g.
 
(venv) root@c33e4b787188:~/paddle-onnx# python fluid_to_onnx.py --fluid_model extras/fit_a_line.inference.model --onnx_model extras/fit_a_line.onnx.inference.model --to_print_model > extras/fit_a_line_onnx.inference.model.out 
(venv) root@c33e4b787188:~/paddle-onnx# cd extras
(venv) root@c33e4b787188:~/paddle-onnx/extras# ls
fit_a_line.inference.model  fit_a_line.onnx.inference.model  fit_a_line_onnx.inference.model.out
 
 
but when I try to validate the resulting onnx model using the validate.py script I get the following error when using the tensorrt backend:
 
(venv) root@c33e4b787188:~/paddle-onnx# deactivate
root@c33e4b787188:~/paddle-onnx# python validate.py --fluid_model extras/fit_a_line.inference.model --onnx_model extras/fit_a_line.onnx.inference.model --backend tensorrt
-----------  Configuration Arguments -----------
a: 0.0
b: 1.0
backend: tensorrt
batch_size: 10
expected_decimal: 5
fluid_model: extras/fit_a_line.inference.model
onnx_model: extras/fit_a_line.onnx.inference.model
------------------------------------------------
Inference results for fluid model:
[array([[15.874767],
       [17.174097],
       [14.951813],
       [14.069194],
       [13.003316],
       [17.782452],
       [16.204231],
       [13.260891],
       [15.537827],
       [13.720056]], dtype=float32)]
 
 
Traceback (most recent call last):
  File "validate.py", line 129, in <module>
    validate(args)
  File "validate.py", line 113, in validate
    rep = backend.prepare(onnx_model, device='CUDA:0')
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 166, in prepare
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 71, in __init__
RuntimeError: While parsing node number 1:
/root/onnx-tensorrt/builtin_op_importers.cpp:539 In function importFlatten:
[8] Assertion failed: dims.nbDims == 3

**2. Issue 2 : dim_value 0**

We see some dim_value of 0 in the generated model. Is this expected and how those should be interpreted. 

When I look at the human readable onnx model, i.e. fit_a_line_onnx.inference.model.out that was generated by the fluid_to_onnx.py script there are nodes with dim_value of 0:
 
(venv) root@c33e4b787188:~/paddle-onnx/extras# cat fit_a_line_onnx.inference.model.out | more
 
-----------  Configuration Arguments -----------
fluid_model: extras/fit_a_line.inference.model
onnx_model: extras/fit_a_line.onnx.inference.model
to_print_model: True
------------------------------------------------
The converted model is:
ir_version: 3
producer_name: "PaddlePaddle"
graph {
  node {
    input: "x"
    output: "x@flatten_0"
    op_type: "Flatten"
    attribute {
      name: "axis"
      i: 1
      type: INT
    }
  }
  node {
    input: "fc_0.w_0"
    output: "fc_0.w_0@flatten_0"
    op_type: "Flatten"
    attribute {
      name: "axis"
      i: 1
      type: INT
    }
  }
  node {
    input: "x@flatten_0"
    input: "fc_0.w_0@flatten_0"
    output: "fc_0.tmp_0@matmul_0"
    op_type: "MatMul"
  }
node {
    output: "fc_0.tmp_0@shape_0"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 2
        data_type: INT64
        int64_data: 0
        int64_data: 1
        name: fc_0.tmp_0@shape_0
      }
      type: TENSOR
    }
  }
  node {
    input: "fc_0.tmp_0@matmul_0"
    input: "fc_0.tmp_0@shape_0"
    output: "fc_0.tmp_0"
    op_type: "Reshape"
  }
  node {
    input: "fc_0.tmp_0"
    input: "fc_0.b_0"
    output: "fc_0.tmp_1"
    op_type: "Add"
    attribute {
      name: "axis"
      i: 1
      type: INT
    }
    attribute {
      name: "broadcast"
      i: 1
      type: INT
    }
  }
  name: "fit_a_line"
  initializer {
    dims: 1
    data_type: FLOAT
    float_data: 19.3055801392
    name: "fc_0.b_0"
  }
  initializer {
    dims: 13
    dims: 1
    data_type: FLOAT
    float_data: -0.235716566443
    float_data: 1.50793659687
    float_data: -1.37839913368
    float_data: 0.587660908699
    float_data: -1.62691628933
    float_data: 1.94002008438
    float_data: -1.5584435463
    float_data: 1.01809895039
    float_data: -2.47688126564
    float_data: -2.48663592339
    float_data: -2.72155380249
    float_data: 1.01887917519
    float_data: -2.73560881615
    name: "fc_0.w_0"
  }
  input {
    name: "x"
    type {
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 0
          }
          dim {
            dim_value: 13
          }
        }
      }
    }
  }
  input {
    name: "fc_0.b_0"
    type {
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "fc_0.w_0"
    type {
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 13
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "fc_0.tmp_1"
    type {
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 0
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
}
opset_import {
  version: 7
}
 
Saved converted model to path: extras/fit_a_line.onnx.inference.model
 
 
I get the same results after converting the recognize_digits_mlp.inference.model from the paddle paddle repo’s /path-to-repo/paddle-paddle/python/paddle/fluid/tests/book directory…

**Comment by baojun-nervana** [comment]
More info:

(venv) root@c33e4b787188:~/paddle-onnx# python validate.py --help
usage: Use dummy data in the interval [a, b] as inputs to verify the conversion.
       [-h] --fluid_model FLUID_MODEL --onnx_model ONNX_MODEL [--a A] [--b B]
       [--batch_size BATCH_SIZE] [--expected_decimal EXPECTED_DECIMAL]
       [--backend {caffe2,tensorrt}]
 
optional arguments:
  -h, --help            show this help message and exit
  --fluid_model FLUID_MODEL
                        The path to PaddlePaddle Fluid model.
  --onnx_model ONNX_MODEL
                        The path to ONNX model.
  --a A                 Left boundary of dummy data. (default: 0.000000)
  --b B                 Right boundary of dummy data. (default: 1.000000)
  --batch_size BATCH_SIZE
                        Batch size. (default: 10)
  --expected_decimal EXPECTED_DECIMAL
                        The expected decimal accuracy. (default: 5)
  --backend {caffe2,tensorrt}
                        The ONNX backend used for validation. (default:
                        caffe2)
 
We tried to validate the onnx models using –backend arg set to tensorrt, e.g., using the onnx representation of the fit_a_line model from the paddle-onnx/extras directory:
 
root@c33e4b787188:~/paddle-onnx# python validate.py --fluid_model extras/fit_a_line.inference.model --onnx_model extras/fit_a_line.onnx.inference.model --backend tensorrt
-----------  Configuration Arguments -----------
a: 0.0
b: 1.0
backend: tensorrt
batch_size: 10
expected_decimal: 5
fluid_model: extras/fit_a_line.inference.model
onnx_model: extras/fit_a_line.onnx.inference.model
------------------------------------------------
Inference results for fluid model:
[array([[15.874767],
       [17.174097],
       [14.951813],
       [14.069194],
       [13.003316],
       [17.782452],
       [16.204231],
       [13.260891],
       [15.537827],
       [13.720056]], dtype=float32)]
 
 
Traceback (most recent call last):
  File "validate.py", line 129, in <module>
    validate(args)
  File "validate.py", line 113, in validate
    rep = backend.prepare(onnx_model, device='CUDA:0')
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 166, in prepare
  File "build/bdist.linux-x86_64/egg/onnx_tensorrt/backend.py", line 71, in __init__
RuntimeError: While parsing node number 1:
/root/onnx-tensorrt/builtin_op_importers.cpp:539 In function importFlatten:
[8] Assertion failed: dims.nbDims == 3
 
The onnx_tensorrt component always fails with the above assertion error.

**Comment by varunarora** [comment]
@baojun-nervana I reproduced your test, and I don't seem to have Issue number 1. I am using the pip package `onnx==1.0.1` and built the package `onnx-tensorrt==0.1.0`. It passes just fine.

Picked paddle from pip today, so `0.12.0`, CUDA 9.0.176 through an nvidia docker image.

**Comment by varunarora** [comment]
As far as nodes with `dim_value` being `0`: That is expected, so no problems there.

**Comment by baojun-nervana** [comment]
@varunarora Thanks for investigating this. Can you help us to understand what the dim_value 0 means? Is it a size 0 tensor?

**Comment by varunarora** [comment]
@kuke can shed some light on that, and meanwhile I will investigate. Thanks!

**Comment by kuke** [comment]
@baojun-nervana problem 1 should result from the ONNX version, as pointed by @varunarora . And in ONNX, **dim_value 0** means that this dimension is unknown, usually used to specify batch size.

**Comment by varunarora** [comment]
To quote the ONNX doc on @kuke's note:

> The empty list of dimension sizes, [], is a valid tensor shape, denoting a zero-dimension (scalar) value. A zero-dimension tensor is distinct from a tensor of unknown dimensionality, which is indicated by an absent 'shape' property in the Tensor record. When the shape property is absent for an input, a tensor value of any shape may be passed from the caller. When the shape property is absent for an output, the caller should expect that the output value may be of any shape.

**Comment by kuke** [comment]
Please try to upgrade tensorrt to 4.0 if you meet the assert error again after resolving the version problem. I remember that some individual op in tensorrt 3.0 has the dimension problem.

**Comment by varunarora** [comment]
FWIW, I was fine with TensorRT 3.0.4.

**Comment by kuke** [comment]
@varunarora I am not that sure now. Anyway, tensorrt 3.0 works fine in most cases.

**Comment by baojun-nervana** [comment]
would the zero dim be a placeholder or unknown dim to be filled later? Should it be dim_param rather than dim_value?

**Comment by kuke** [comment]
This zero dim will be filled in shape inference. `dim_param` seems to be an option, and we haven't tested it yet.

**Comment by baojun-nervana** [comment]
Thanks @kuke Are they placeholders for batch size in our case? I am thinking to manually replace it as 1 (batch size 1) and try it out as a temporary work around.

**Comment by kuke** [comment]
Yes. the actual batch size will be determined by feeding data

https://github.com/PaddlePaddle/paddle-onnx/blob/02a9ffdd07bc5a95a8b17065e7c05a4308842f0f/validate.py#L85-L88

You can use any positive integers as the batch size if you like.

**Comment by raramer01** [comment]
since Varun indicated that he didn't encounter issue 1 above when using onnx 1.01, I uninstalled onnx 1.1.1, and attempted to install onnx 1.0.1 and use it and ran into the following issue:

root@c33e4b787188:~/paddle-onnx# ./setup.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libprotoc-dev is already the newest version (2.6.1-1.3).
protobuf-compiler is already the newest version (2.6.1-1.3).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Requirement already satisfied: protobuf==3.5.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (3.5.1)
Requirement already satisfied: pytest-runner in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (4.2)
Requirement already satisfied: onnx==1.0.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (1.0.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.5/dist-packages (from protobuf==3.5.1->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from protobuf==3.5.1->-r requirements.txt (line 1)) (39.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from onnx==1.0.1->-r requirements.txt (line 3)) (1.14.3)
uff 0.2.0 requires argparse>=1.4.0, which is not installed.
root@c33e4b787188:~/paddle-onnx# set -o vi
root@c33e4b787188:~/paddle-onnx# python fluid_to_onnx.py --fluid_model $tmp/image_classification_resnet.inference.model --onnx_model /root/image_classification_resnet_onnx_101_patched.inference.model --to_print_model > /root/image_classification_resnet_onnx_101_patched.inference.model.out
Traceback (most recent call last):
  File "fluid_to_onnx.py", line 19, in <module>
    from onnx import helper, checker
  File "/usr/local/lib/python2.7/dist-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/usr/local/lib/python2.7/dist-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /usr/local/lib/python2.7/dist-packages/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message13SpaceUsedLongEv

Do you know what causes this?

**Comment by varunarora** [comment]
Becky, what protobuf version do you have installed? @raramer01

Btw, love how both of you make things simple to read by crossing out the setup stdout, while keeping it relevant,

**Comment by raramer01** [comment]
Hi Varun,
@varunarora 

root@c33e4b787188:/usr/local# protoc --version
libprotoc 3.5.0

I could have sworn that it was 2.6.1 before I started twiddling with my setup again...should it be 2.6.1 to be compatible with onnx 1.01 ?  Do you know of a good way to make sure that it doesn't inadvertently get upgraded?

**Comment by varunarora** [comment]
@raramer01 Unfortunately, I don't :( Every package, in an attempt to be config-free, does its own updates without asking any questions. But we have the same problem within the Paddle world - paddlepaddle's package depends on a different version of protobuf than we suggest on the ONNX convertor. So we just obsessively keep checking versions when things don't look right.

**Comment by baojun-nervana** [comment]
opened another thread for solution.
