### ISSUE TITLE
trainable_statistics should be in AttributeMap 

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/Paddle2ONNX#536]
Error: trainable_statistics should be in AttributeMap at (/paddle/paddle/fluid/framework/attribute.h:177)
  [operator < batch_norm > error]
在paddle1.8下执行onnx_model = paddle2onnx.run_convert(inference_program, input_shape_dict = input_shape_dict, opset_version=11)的时候报错如上。
这个要怎么解决

**Comment by yeliang2258** [comment]
你好，请安装最新版本的Paddle 2.2然后再尝试。https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
