### ISSUE TITLE
请求为cpp版本增加两个接口

### ISSUE THREAD

**Issue by heliqi** [PaddlePaddle/Paddle2ONNX#541]
增加两个统一的对外接口：
1. 增加是否能转换的接口
    bool XXXX(std::string model_file, std::string params_file) -> 返回是否能转换成功;
2. 增加转换paddle模型为onnx模型的接口
    std::string XXX(std::string model_file, std::string params_file)) -> 返回转换成功后并序列化为string的onnx模型

**Comment by jiangjiajun** [comment]
已增加接口

```
#include "paddle2onnx/converter.h"
```
```
bool IsExportable(const std::string& model, const std::string& params,
            bool from_memory_buffer = false, int32_t opset_version = 15,
             bool auto_upgrade_opset = true,
            bool verbose = false, bool enable_onnx_checker = true,
            bool enable_experimental_op = false);
```

```
bool Export(const std::string& model, const std::string& params,
            std::string* out, bool from_memory_buffer = false, int32_t opset_version = 15,
             bool auto_upgrade_opset = true,
            bool verbose = false, bool enable_onnx_checker = true,
            bool enable_experimental_op = false);
```
- model: 模型文件路径，如若from_memory_buffer为true，则该参数表示读入的模型二进制字符串流
- params: 参数文件路径，如若from_memory_buffer为true，则该参数表示读入的参数二进制字符串流
- out: 转换后的ONNX模型二进制字符串
- opset_version: 转换时使用的ONNX OP版本
- from_memory_buffer: 模型和参数是否为内存中的二进制字符串流
- auto_upgrade_opset: 是否自动升级opset，当设定的OP版本较低导致无法转换时，自动升级到可支持转换的OP版本
- verbose: 是否输出转换过程中的中间日志
- enable_onnx_checker: 是否使用ONNX库检查生成的ONNX模型合法性
- enable_expeirmental_op：是否启用一些实验性OP，开启后会有部分实验性OP进行转换

此外已支持`make install`
