### ISSUE TITLE
paddle2onnx 模型转换失败

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/Paddle2ONNX#558]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
`paddle2onnx` 转化`PicoDet`轻量级检测模型，`backbone：ESNet_m`，最后转换失败，报错如下：
```bash
NotImplementedError:
There's 7 ops are not supported yet
=========== lod_array_length ===========
=========== conditional_block ===========
=========== tensor_array_to_tensor ===========
=========== meshgrid ===========
=========== select_input ===========
=========== write_to_array ===========
=========== while ===========
```

**更多信息 :**
 - 用于部署的推理引擎:paddledet 官方给出了paddlelite mnn ncnn 等推理框架的demo，自己想手动实现以下，对比一下性能优劣
 - 为什么需要转换为ONNX格式：当前希望测试ncnn推理框架（paddlelite 已经测试通过），对比推理速度。
 - Paddle2ONNX版本:Version: 0.9.0
 - 部分疑问：为什么官方提供了picodet 的onnx中间格式，自己转换缺提示op不支持，官方如何做的，谢谢解答。

**Comment by yeliang2258** [comment]
您好，PaddleDetection中导出为ONNX模型的指南为：https://github.com/PaddlePaddle/PaddleDetection/blob/a6c6dd4665868b148176b9505908297b0c5f725b/deploy/EXPORT_ONNX_MODEL.md
我看里面确实是支持picodet的转换的，你按照指南再试一下。

**Comment by ChaoII** [comment]
> 您好，PaddleDetection中导出为ONNX模型的指南为：https://github.com/PaddlePaddle/PaddleDetection/blob/a6c6dd4665868b148176b9505908297b0c5f725b/deploy/EXPORT_ONNX_MODEL.md

**Comment by ChaoII** [comment]
> 您好，PaddleDetection中导出为ONNX模型的指南为：https://github.com/PaddlePaddle/PaddleDetection/blob/a6c6dd4665868b148176b9505908297b0c5f725b/deploy/EXPORT_ONNX_MODEL.md 我看里面确实是支持picodet的转换的，你按照指南再试一下。

您好，我就是按照教程来的，转换过程中报错缺少op，我更换主干网络为pplcnet 再尝试一下。

**Comment by yeliang2258** [comment]
好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone

**Comment by ChaoII** [comment]
> 好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone

谢谢！还是没法转onnx，我去`PaddleDetection`那边问问，他们怎么导出的。

**Comment by ChaoII** [comment]
> 好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone



> 好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone

您好，到那边发现问题了，是因为我训练采用paddlex训练的，然后paddlex导出的inference_model 就无法转成onnx，paddledet导出的inference_model 就可以转onnx ，请问一下这是子什么原因呢？

**Comment by ChaoII** [comment]
> 好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone

您好，到那边发现问题了，是因为我训练采用paddlex训练的，然后paddlex导出的inference_model 就无法转成onnx，paddledet导出的inference_model 就可以转onnx ，请问一下这是子什么原因呢？

**Comment by jiangjiajun** [comment]
> > 好的，如果还是转换失败，你可以在PaddleDetection下提issue，询问具体是那个backbone
> 
> 您好，到那边发现问题了，是因为我训练采用paddlex训练的，然后paddlex导出的inference_model 就无法转成onnx，paddledet导出的inference_model 就可以转onnx ，请问一下这是子什么原因呢？

因为PaddleX在实现时，后处理里面加了控制流，导致无法转ONNX
