### ISSUE TITLE
picodet lcnet导出为onnx后精度降低很多

### ISSUE THREAD

**Issue by ChungTak** [PaddlePaddle/Paddle2ONNX#588]
**问题描述**
参照 https://aistudio.baidu.com/aistudio/projectdetail/3497217 教程，把epoch修改为300训练了一个picodet_lcnet_1_5x_416_coco模型。
在paddledetection下  tools/infer.py 推理很准确。
通过 Paddle2ONNX 导出 onnx后，摩托车精度下降一点，人体完全识别不出来，精度下降很多。

**更多信息 :**
 - 用于部署的推理引擎:  onnxruntime https://gitee.com/atari/picodet-onnxruntime
 - Paddle2ONNX版本: paddle2onnx-0.9.1 with python>=2.7, paddlepaddle>=1.8.0
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
   paddledetection 下检测结果: moto 0.90   person 0.68
![1595214506200933-1606467984- -motorcycle](https://user-images.githubusercontent.com/778353/156153054-70febe67-10b5-450b-ab0c-b344b97ba158.jpg)

  Paddle2ONNX  转换后onnxruntime的结果:  moto 0.834 人体检测不到
  
![result](https://user-images.githubusercontent.com/778353/156153860-d8ab385b-a54a-4929-a75c-8c1d2b3553a3.jpg)

    

**其他信息**

**Comment by jiangjiajun** [comment]
Hi @ChungTak 
这种情况确实不应该，建议你按如下流程排查原因
- 1. 使用`tool/infer.py`去进行paddle模型推理，并将输入到模型的数据dump到本地，模型输出的数据dump到本地
- 2. 使用onnxruntime去进行onnxruntime模型推理，并将输入到模型的数据dump到本地，模型输出的数据dump到本地
对比上面这两种推理方式，数据的差异，如若输入数据一致，而数出的数据有diff，那说明是模型的原因；否则说明是前后处理带来的差异

**Comment by ChungTak** [comment]
@jiangjiajun 感谢回复·~~ dump到本地 是怎样操作？ picodet 官方的80类onnx在onnxruntime和tool/infer.py,都没有问题，就是自己训练的才出现

**Comment by jiangjiajun** [comment]
你可以找到`tool/infer.py`这个脚本，里面应该有一个地方调用了`copy_from_cpu`的接口，这个接口即是将numpy的数据拷贝给推理引擎。

使用numpy.save('test.npy', data)，可以将np.ndarray的数据保存到本地。 你需要注意下picodet有几个输入，就要dump几个数据。

而输出则是`tool/infer.py`有一个调用`copy_to_cpu`的地方，这就是把结果从推理引擎中拷贝成np.ndarray格式，也就是模型的输出，同样也使用numpy.save保存到本地

**Comment by ChungTak** [comment]
@jiangjiajun  我是新手不太会~~~我按你的方法保存了很多.npy文件后。请问用什么工具或者方法能检测对比dump数据？我用文本编辑器打开npy文件出现一堆乱码~~看不懂

**Comment by jiangjiajun** [comment]
如若对于这些不太了解的话，建议直接使用飞桨官方提供的推理方式
