### ISSUE TITLE
ImportError: cannot import name fetch_var

### ISSUE THREAD

**Issue by liyungithub** [PaddlePaddle/Paddle2ONNX#59]
![_ _20181125113011](https://user-images.githubusercontent.com/22513244/48975195-30470c00-f0a6-11e8-8739-f532f62b7125.png)

**Comment by FrankWork** [comment]
+1

**Comment by liyungithub** [comment]
pip install paddlepaddle==0.14     ok

**Comment by sicarioakki** [comment]
How was this issue solved?
Please can someone post the complete solution for this problem?
Even i am facing the same issue
