### ISSUE TITLE
what's the meaning of  "releated"?

### ISSUE THREAD

**Issue by znsoftm** [PaddlePaddle/Paddle2ONNX#598]
linspace releated pull request https://github.com/PaddlePaddle/Paddle2ONNX/pull/470

like above, what's the meaning  of  releated? related ?

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
sorry for spelling error, it should be related
