### ISSUE TITLE
paddle1.3.0隐藏了fetch_var接口，无法使用paddle-onnx

### ISSUE THREAD

**Issue by daiwk** [PaddlePaddle/Paddle2ONNX#60]
paddle1.3.0隐藏了fetch_var接口，无法使用paddle-onnx。。。

**Comment by daiwk** [comment]
会报错：

>     from paddle.fluid.executor import fetch_var
ImportError: cannot import name fetch_var

**Comment by yxchng** [comment]
Change `fetch_var` to `_fetch_var`
