### ISSUE TITLE
在linux把pdmodel转换成onnx失败

### ISSUE THREAD

**Issue by liutheuniverse** [PaddlePaddle/Paddle2ONNX#606]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
版本信息如下
paddle2onnx 0.9.1
onnx 1.9.0
onnxruntime 1.10.0
paddlepaddle 2.2.2
paddlelite 2.10
请在此处详细的描述报错信息
在kali下运行shell：paddle2onnx --model_dir /home/kali  --model_filename MyCNN.pdmodel --params_filename MyCNN_.pdiparams --save_file onnx_file --opset_version 10 --enable_onnx_checker True
报错
/home/kali/.local/lib/python3.9/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/kali/.local/lib/python3.9/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/kali/.local/lib/python3.9/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/kali/.local/lib/python3.9/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
/home/kali/.local/lib/python3.9/site-packages/onnx/helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  is_iterable = isinstance(value, collections.Iterable)
Killed

**更多信息 :**
 - 用于部署的推理引擎:我不知道是什么，但是我是用这个网站生成的https://aistudio.baidu.com/aistudio/projectdetail/2498526
 生成模型用的是这个指令
from x2paddle.convert import pytorch2paddle
pytorch2paddle(module=torch_module,
               save_dir="./pd_model",
               jit_type="trace",
               input_examples=[torch_input])
我用的数据库是这个https://aistudio.baidu.com/aistudio/datasetdetail/42610
 - 为什么需要转换为ONNX格式：为了安卓开发，需要转换成tensorflow lite
 - Paddle2ONNX版本:paddle2onnx 0.9.1
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

![VirtualBox_kali-linux-2022 1-virtualbox-amd64_05_03_2022_21_27_16](https://user-images.githubusercontent.com/83712510/156885101-85d07f8c-7bd7-46a4-a032-c55d8948397e.png)
![VirtualBox_kali-linux-2022 1-virtualbox-amd64_05_03_2022_21_26_54](https://user-images.githubusercontent.com/83712510/156885113-11b8a13a-6944-485b-b8b9-1913bd9a3fee.png)

**其他信息**

**Comment by jiangjiajun** [comment]
看起来是由于Python版本太高的原因导致的，你试下使用python3.7

**Comment by liutheuniverse** [comment]
安装numpy时显示RuntimeError: Python version >= 3.8 required

**Comment by liutheuniverse** [comment]
> 看起来是由于Python版本太高的原因导致的，你试下使用python3.7

我又在飞桨paddle上输入，结果跳出来这个：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
usage: paddle2onnx [-h] [--model_dir MODEL_DIR]
                   [--model_filename MODEL_FILENAME]
                   [--params_filename PARAMS_FILENAME] [--save_file SAVE_FILE]
                   [--opset_version OPSET_VERSION]
                   [--input_shape_dict INPUT_SHAPE_DICT]
                   [--enable_onnx_checker ENABLE_ONNX_CHECKER]
                   [--enable_paddle_fallback ENABLE_PADDLE_FALLBACK]
                   [--version]
paddle2onnx: error: unrecognized arguments: 10

**Comment by jiangjiajun** [comment]
因为命令没输对，参阅下readme

**Comment by liutheuniverse** [comment]
> 因为命令没输对，参阅下readme

Exception: Error happened when mapping node ['pool2d_0'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['relu_1.tmp_0']} and outputs: {'Out': ['pool2d_0.tmp_0']}, specific error: module 'paddle' has no attribute 'float32'
需不需要把float32转成int8

**Comment by jiangjiajun** [comment]
升级paddlepaddle到最新版本
