### ISSUE TITLE
能不能支持一下paddle的模型转换的tensorflow？

### ISSUE THREAD

**Issue by thomaszheng** [PaddlePaddle/Paddle2ONNX#621]
**问题描述**
请在此处详细的描述报错信息
请问一下，业务中已经使用tensorflow部署了模型，但是新的模型是使用paddlepaddle进行训练的，部署想继续使用tensorflow的部署方案，想问一下有没有计划支持一下paddle模型转换为tensorflow的格式，比如saved_mode之类的

**Comment by jiangjiajun** [comment]
@thomaszheng Hi， 我们没有这个计划。你当前想采用tensorflow的部署方案原因是什么呢？

**Comment by thomaszheng** [comment]
我们项目中以前的模型都是使用tensorflow的部署方案，后续希望新增的模型还是可以复用之前的部署方案，不希望增加部署这块相关的成本。

**Comment by jiangjiajun** [comment]
当前Paddle框架针对CPU/GPU的Paddle Inference，针对移动端的Paddle Lite，针对服务化的Paddle Serving均能对飞桨模型做非常完善的部署。

当前没有转tensorflow的计划，但是我们提供了Paddle2ONNX，支持将模型转换tensorflow格式，你可以使用onnx-tensorflow尝试再将模型转成tensorflow格式（可能存在转换失败，或性能变差的风险）

**Comment by thomaszheng** [comment]
嗯，paddle的部署的方案我们也是有使用的，支持也是非常好的。只是我们在一些业务上需要和之前保持一致的。
我们也是在尝试了onnx-tensorflow转换失败后（paddle->onnx是没有问题），才在你们这提的issue。因为onnx那边沟通和开发效率感觉都不高，而且链路比较长，所以问问看看你们有没有计划。

**Comment by bettergsh** [comment]
paddle->onnx->tensorflow
