### ISSUE TITLE
导出语音合成模型 fastspeech2 存在不支持 op

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle2ONNX#627]
NotImplementedError:
There's 4 ops are not supported yet
=========== conditional_block ===========
=========== set_value ===========
=========== share_data ===========
=========== while ===========

同样调查 issue ，发现导出 speedyspeech 也存在不支持 op
https://github.com/PaddlePaddle/Paddle2ONNX/issues/471

目前已实验可以直接的语音合成模型：
声学模型：
None, 因为 SpeedySpeech 和 Fastspeech2 都不支持，Tacotron2 和 Transformer TTS 的控制流更加显式，肯定不支持
声码器：
HIFIGAN
其余 GAN Vocoder 未测试，但是 WaveRNN 肯定更不支持

面临的困难：
fastspeech2 暂时 TRT 走不通，HIFIGAN TRT 可以走通，但是由于有很多 unsqueeze 算子，导致进 TRT 的算子很少

暂时的解法：
使用朴素 PaddleInference 推理 fastspeech2 + onnx run time 推理 HIFIGAN

需求：
希望可以考虑支持 while 等控制流，因为控制流在语音任务中很常见

相关 issue:
[Paddle2onnx 转化Paddledetection的fasterrcnn模型出现ops不支持错误](https://github.com/PaddlePaddle/Paddle2ONNX/issues/462)

**Comment by yeliang2258** [comment]
用户你好，目前暂时不支持控制流，尽快排期支持

**Comment by yeliang2258** [comment]
用户您好，目前PaddleInference是支持调用TensorRT进行推理的，请问使用PaddleInference调用TRT的方案还不满足你们的使用需求吗？是因为性能原因还是什么原因呢？

**Comment by yt605155624** [comment]
我是 PaddleSpeech 的研发，目前语音合成的很多模型，PaddleInferenceTRT 是跑不通的（正在让推理的同事帮忙解决），能跑通 PaddleInferenceTRT 的模型，因为目前有的算子进不了 trt, PaddleInferenceTRT 并没有真正产生作用（这个也让推理的同事在看了），发现还是直接用 onnx-trt 的速度是最快的（用 onnxruntime trt 由于动态 shape 反而不快。。），语音合成模型转 onnx 控制流相关正在与 jiajun 跟进
而且 cpu 上的推理， PaddleInference 很慢，PaddleInference mkldnn 在很多语音模型上又用不了（某些 shape 不支持，结果对不齐等），但是用 onnxruntime-cpu 速度却很快，所以想把模型转成 onnx 部署~

**Comment by yt605155624** [comment]
fixed in  https://github.com/jiangjiajun/Paddle2ONNX/tree/speech, 支持了 
=========== set_value ===========
=========== share_data ===========
=========== while ===========

通过修改模型代码绕过了 
=========== conditional_block ===========
