### ISSUE TITLE
Whether the PP-LCNET model can be onNX transformed  

### ISSUE THREAD

**Issue by HDU-CarryStar** [PaddlePaddle/Paddle2ONNX#638]
Whether the PP-LCNET model can be ONNX transformed  ?
Could you please tell me how to carry out transformation? I am a newcomer in this field, and I hope you can guide me. Thank you very much !

**Comment by yeliang2258** [comment]
Hello, you can export PP-LCNET model to an inference model first and then convert it with Paddle2ONNX.
1. You can download the model here [Model download link](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/PPLCNet_x0_25_infer.tar), [models list](https://github.com/PaddlePaddle/PaddleClas/blob/1358e3f647e12b9ee6c5d6450291983b2d5ac382/docs/zh_CN/algorithm_introduction/ImageNet_models.md)
3. Refer to this document to export to ONNX. https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by HDU-CarryStar** [comment]
Does Paddle2.0ONNX currently support PP-LCNet conversion to ONNX? Consider that the home page does not see whether the model is supported or not.

**Comment by jiangjiajun** [comment]
There are just  part of models we have tested in home page. And PP-LCNet has been converted to ONNX format successfully by other users
