### ISSUE TITLE
关于paddleOCR转onnx格式后的推理代码

### ISSUE THREAD

**Issue by 471417367** [PaddlePaddle/Paddle2ONNX#640]
在研究PaddleOCR转onnx格式过程中看到以下教程，请问哪里可以找到onnx_inference目录下的代码文件？
https://aistudio.baidu.com/aistudio/projectdetail/1479970

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/model_zoo/model_zoo/ocr 参考下这里吧

**Comment by 471417367** [comment]
@jiangjiajun 
非常感谢，已解决。

**Comment by 471417367** [comment]
@jiangjiajun 
非常感谢，已解决。
