### ISSUE TITLE
如果固定导出onnx时batch大小，目前都是-1

### ISSUE THREAD

**Issue by BackT0TheFuture** [PaddlePaddle/Paddle2ONNX#653]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
导出onnx时如果固定batch大小，目前导出detection那边的模型shape都是 [-1,c,h,w], 如何能固定batch大小，谢谢！
导出时命令行如果指定 input shape 为 {'image':[1,3,256,256]}，此时导出的onnx输入是固定batch了，但输出shape还是[-1,n]

**更多信息 :**
无

**报错截图**
![图片](https://user-images.githubusercontent.com/10088733/160374545-87880266-4a30-4ccd-a5c0-a0255319b3b3.png)

**其他信息**
无

**Comment by yeliang2258** [comment]
可能是某些OP无法推断出shape导致还是存在-1，请问你的部署场景是？这样的模型无法部署吗？

**Comment by jiangjiajun** [comment]
可以试下这个脚本 https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/symbolic_shape_infer.py

```
python symbolic_shape_infer.py --input model.onnx --output new_model.onnx
```

**Comment by BackT0TheFuture** [comment]
@yeliang2258 
在使用opencv dnn模块加载时会报异常，后来发现用固定的shape正常

@jiangjiajun 

谢谢，马上试一下

**Comment by FL77N** [comment]
> 可能是某些OP无法推断出shape导致还是存在-1，请问你的部署场景是？这样的

您好，您解决了这个问题了吗？我也有同样的问题。

**Comment by datalee** [comment]
是啊，怎么指定batch_size

**Comment by jiangjiajun** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/19339784/184626889-7fca6cda-21c3-4c6a-b2e5-abfd0113359e.png">
@datalee  参考README
