### ISSUE TITLE
[Question]什么时候支持OCRV2 转换ONNX?

### ISSUE THREAD

**Issue by shelllet** [PaddlePaddle/Paddle2ONNX#661]
我没有看到官方模型列表中支持ocr-v2 版本

https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/model_zoo.md

![image](https://user-images.githubusercontent.com/16729017/161016342-2f0eca8c-8051-4140-a85e-15ecc8150a98.png)

请问什么时候提供支持？

**Comment by jiangjiajun** [comment]
你可以直接转换，文档列的仅为此前测试的一部分，并不表示只支持文档中列出来的模型

**Comment by shelllet** [comment]
> 你可以直接转换，文档列的仅为此前测试的一部分，并不表示只支持文档中列出来的模型

thks!
