### ISSUE TITLE
Paddle导出onnx时候去掉后处理

### ISSUE THREAD

**Issue by yuexiayiren159aaa** [PaddlePaddle/Paddle2ONNX#664]
使用
python tools/export_model.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml \
                            -o weights=weights/ppyolo_tiny_650e_coco.pdparams \
                            TestReader.inputs_def.image_shape=[3,416,416] \
                            --output_dir inference_model

paddle2onnx --model_dir inference_model/ppyolo_tiny_650e_coco \
 --model_filename inference_model/ppyolo_tiny_650e_coco/model.pdmodel \
--params_filename inference_model/ppyolo_tiny_650e_coco/model.pdiparams \
--save_file inference_model/ppyolo_tiny_650e_coco/ppyolo3.onnx \
--enable_onnx_checker True

![image](https://user-images.githubusercontent.com/102778714/161187109-1b7e3153-4c7c-474b-89a2-4f60aa8cc9b1.png)
# 我想导出成下main的格式onnx
![image](https://user-images.githubusercontent.com/102778714/161187176-86e98dee-d658-4428-b7db-1a6f7ceda9b5.png)

**Comment by jiangjiajun** [comment]
https://github.com/jiangjiajun/PaddleUtils/tree/main/onnx 参考这里的onnx模型裁剪脚本
