### ISSUE TITLE
Worse output in Onnx compared to Predict by Paddle

### ISSUE THREAD

**Issue by thhart** [PaddlePaddle/Paddle2ONNX#666]
I have trained a new model and tested the output with paddles predict scripts as well within Onnx runtime. However I get worse results Onnx, the class prediction is much less precise and looks very bad. This is independent from the model type, ort version or opset version.
The only difference I can imagine is the input step. Maybe the input data is not normalized well enough, however I can not find any documentation how to format the input accordingly can you give an example of an input normalization step of an image? What is the expected band ordering? (RGB vs. BGR)

 - Inference engine for deployment: Onnx runtime for Java 1.10.0 (Opset version 15)
 - Paddle2ONNX Version: 0.9.2

**Comment by thhart** [comment]
I can see the result is getting better by normalization into the range -1,1? Is this correct?
As I already started asking, how come the output is swapped x/y wise, any intention by this?

**Comment by jiangjiajun** [comment]
Hi, @thhart I think the difference may comes from the data preprocessing. Here we have built a model zoo, covering image classification, object detection, ocr and semantic segmentation, and we also provided codes shows how to inference by onnxruntime https://github.com/PaddlePaddle/Paddle2ONNX/tree/model_zoo/model_zoo
