### ISSUE TITLE
得到的onnx是int64的weight

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/Paddle2ONNX#686]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
![image](https://user-images.githubusercontent.com/53338761/163367160-737cd956-0f8b-478b-87f4-4fb5c83f9406.png)
目前转出来的onnx是int64的格式是吗？有接口可以自己定义吗？
**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):
zhaoxin34@baidu.com

**Comment by jiangjiajun** [comment]
没有影响，忽略这个提示即可

**Comment by jiangjiajun** [comment]
@xinliyangguang 方便的话麻烦抽半分钟时间帮忙填下我们的用户问卷，帮忙我们了解大家的需求，改进飞桨模型的部署体验哈 https://iwenjuan.baidu.com/?code=r8hu2s
