### ISSUE TITLE
您好，请教一下panddle2onnx转换出来的onnx文件，int类型是int64位的，这个有方法可以改成int32位的吗？

### ISSUE THREAD

**Issue by liroda** [PaddlePaddle/Paddle2ONNX#705]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by jiangjiajun** [comment]
你好，你的这个提示可能是来自于TensorRT的影响，这个并不会影响TensorRT的部署，忽略即可

**Comment by jiangjiajun** [comment]
@liroda 方便的话麻烦抽半分钟时间帮忙填下我们的用户问卷，帮忙我们了解大家的需求，改进飞桨模型的部署体验哈 https://iwenjuan.baidu.com/?code=r8hu2s
