### ISSUE TITLE
Have it support convert pretrained nlp model from PaddlePaddle to tensorflow ?

### ISSUE THREAD

**Issue by 312shan** [PaddlePaddle/Paddle2ONNX#71]
I want to convert pretrained nlp model from PaddlePaddle to tensorflow ?
like bert or elmo (https://github.com/PaddlePaddle/LARK/tree/develop/BERT).
Is that have been supported and tested?

**Comment by wawltor** [comment]
Sorry, we do not support convert to tensorflow model from paddle model at present.

**Comment by wawltor** [comment]
> I want to convert pretrained nlp model from PaddlePaddle to tensorflow ?
> like bert or elmo (https://github.com/PaddlePaddle/LARK/tree/develop/BERT).
> Is that have been supported and tested?

Sorry, we do not support convert to tensorflow model from paddle model at present.
