### ISSUE TITLE
paddleseg转onnx模型后推理出错

### ISSUE THREAD

**Issue by qypf** [PaddlePaddle/Paddle2ONNX#719]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
paddleseg训练后的模型，使用paddle可以正常推理，但是换成onnx后出错，导出模型时正常无报错

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本: 0.9.0
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
 Traceback (most recent call last):
  File "D:/code/python/PaddleSeg-release-2.5/tt_onnx.py", line 26, in <module>
    onnx_out = check_and_run_onnx(onnx_model_path, input_data)
  File "D:/code/python/PaddleSeg-release-2.5/tt_onnx.py", line 13, in check_and_run_onnx
    ort_outs = ort_sess.run(None, ort_inputs)
  File "D:\ProgramData\Anaconda3\envs\OCR2\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Conv node. Name:'batch_norm_38.tmp_2_nchwc' Status Message: Dilation not supported for AutoPadType::SAME_UPPER or AutoPadType::SAME_LOWER.

**其他信息**

测试代码如下：
import onnx
import onnxruntime
import numpy as np

def check_and_run_onnx(onnx_model_path, input_data):
    onnx_model = onnx.load(onnx_model_path)
    onnx.checker.check_model(onnx_model)
    print('The onnx model has been checked.')

    ort_sess = onnxruntime.InferenceSession(onnx_model_path)
    ort_inputs = {ort_sess.get_inputs()[0].name: input_data}
    ort_outs = ort_sess.run(None, ort_inputs)
    print("The onnx model has been predicted by ONNXRuntime.")

    return ort_outs[0]

if __name__ == '__main__':
    input_shape = [1, 3, 768, 768]
    print("input shape:", input_shape)
    input_data = np.random.random(input_shape).astype('float32')

    # 1. check and run onnx
    onnx_model_path = r"C:\Users\Administrator\Desktop\model.onnx"
    onnx_out = check_and_run_onnx(onnx_model_path, input_data)
    print("output shape:", onnx_out.shape, "\n")

**Comment by qypf** [comment]
模型的地址
链接: https://pan.baidu.com/s/1NvxbIO3WYuDs-fsLzU7NiA 提取码: ja36 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by jiangjiajun** [comment]
由于onnxruntime对于conv OP没有支持`dilation`>1且`padding=SAME`的情况，因此出现了上面的问题

**Comment by qypf** [comment]
> 由于onnxruntime对于conv OP没有支持`dilation`>1且`padding=SAME`的情况，因此出现了上面的问题

如果是onnx的问题，那目前是没法解决了是吧？我对比了不同的模型，同样使用deeplabp算法，output_stride=8和16的时候会出现这个问题，如果output_stride=32就没有问题。

**Comment by jiangjiajun** [comment]
目前没解决方法，或者你可以手动将padding改成指定padding多少个单位

**Comment by qypf** [comment]
> 目前没解决方法，或者你可以手动将padding改成指定padding多少个单位

好的，谢谢

**Comment by jiangjiajun** [comment]
@qypf  不客气，方便的话麻烦抽半分钟时间帮忙填下我们的用户问卷，帮忙我们了解大家的需求，改进飞桨模型的部署体验哈 https://iwenjuan.baidu.com/?code=r8hu2s
