### ISSUE TITLE
使用Paddle2ONNX转换yolo模型出错

### ISSUE THREAD

**Issue by shliar** [PaddlePaddle/Paddle2ONNX#731]
**问题描述**
我在使用最新版本的paddle2ONNX转换在paddlex上训练的模型使出现导出错误，log如下：
[Paddle2ONNX] Model loaded, start to converting...
[Paddle2ONNX][nearest_interp_v2: nearest_interp_v2_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX][nearest_interp_v2: nearest_interp_v2_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX][yolo_box: yolo_box_0.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX][yolo_box: yolo_box_1.tmp_0] Requires the minimal opset version of 11.
[Paddle2ONNX][yolo_box: yolo_box_2.tmp_0] Requires the minimal opset version of 11.
[ERROR][Paddle2ONNX][multiclass_nms3: multiclass_nms3_0.tmp_1] The 2-nd and 3-rd dimension of input bboxes tensor of multiclass_nms should be fixed, but now the shape is [-1, -1, 4].
[Paddle2ONNX] Due to the operator: multiclass_nms3, this model cannot be exported to ONNX.
[Paddle2ONNX] Due to the operator: nearest_interp_v2, requires opset_version >= 11.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.

**更多信息 :**
 - 用于部署的推理引擎:openvino
 - 为什么需要转换为ONNX格式：需要使用openvino来进行cpu上的加速推理
 - Paddle2ONNX版本:0.9.5
 - 你的联系方式(Email/Wechat/Phone):1843134669@qq.com

**报错截图**
![捕获](https://user-images.githubusercontent.com/56796761/168030199-29d5a453-d535-430f-a392-6111fdda352a.JPG)

**其他信息**

**Comment by jiangjiajun** [comment]
提示中已经说明，需要更高的opset版本，将opset_version设为11即可

**Comment by shliar** [comment]
> 提示中已经说明，需要更高的 opset 版本，将 opset_version 设为 11 即可
我刚刚重新设置了一下，但是还是出错了，log与截图如下：

[Paddle2ONNX] Start to parse PaddlePaddle model(model file: D:\Games\sqayolo\work\output\yolov3_darknetsqa\inference_model\inference_model\model.pdmodel, parameters file: D:\Games\sqayolo\work\output\yolov3_darknetsqa\inference_model\inference_model\model.pdiparams
[Paddle2ONNX] Model loaded, start to converting...
[ERROR][Paddle2ONNX][multiclass_nms3: multiclass_nms3_0.tmp_1] The 2-nd and 3-rd dimension of input bboxes tensor of multiclass_nms should be fixed, but now the shape is [-1, -1, 4].
[Paddle2ONNX] Due to the operator: multiclass_nms3, this model cannot be exported to ONNX.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.

![image](https://user-images.githubusercontent.com/56796761/168036048-bbb1cbcf-d2e6-4a40-a14b-c34e03f7a062.png)

**Comment by jiangjiajun** [comment]
你的模型shape是否没有固定，https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/EXPORT_ONNX_MODEL.md#%E6%AD%A5%E9%AA%A4%E4%B8%80%E5%AF%BC%E5%87%BApaddlepaddle%E9%83%A8%E7%BD%B2%E6%A8%A1%E5%9E%8B 参考这里，在导出yolov3模型时，需要将输入shape固定

**Comment by jiangjiajun** [comment]
另外注意到你是想通过openvino部署， 可以参考这篇openvino部署yolov3的文档 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/experimental/openvino_ppdet_cn.md

**Comment by shliar** [comment]
> 另外注意到你是想通过openvino部署， 可以参考这篇openvino部署yolov3的文档 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/experimental/openvino_ppdet_cn.md

谢谢！已经可以正常导出了
