### ISSUE TITLE
转换ch_PP-OCRv2_rec_infer至ONNX模型时出错

### ISSUE THREAD

**Issue by PaulX1029** [PaddlePaddle/Paddle2ONNX#737]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**
转换ch_PP-OCRv2_rec_infer至ONNX模型时出错

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version: onnx-1.9.0 paddle2onnx-0.9.6
 - Email/Wechat/Phone:Wechat:13755845443

**Screenshots**
![image](https://user-images.githubusercontent.com/77143808/168769004-ed494b0f-d9f4-4a30-a806-2ee676bf2338.png)

**Additional context**

**Comment by jiangjiajun** [comment]
这个的原因是因为指定的input_shape_dict中的shape不符合模型的要求。 你可以直接删除input_shape_dict后再进行转换

**Comment by PaulX1029** [comment]
> 

请问一下，这个怎么删除呢？谢谢您！

**Comment by PaulX1029** [comment]
> 这个的原因是因为指定的input_shape_dict中的shape不符合模型的要求。 你可以直接删除input_shape_dict后再进行转换

请问一下，这个怎么删除呢？谢谢您！

**Comment by PaulX1029** [comment]
> 



> 这个的原因是因为指定的input_shape_dict中的shape不符合模型的要求。 你可以直接删除input_shape_dict后再进行转换

请问这个会影响其他地方吗？还是我在使用的时候指定输入的话也可以？

**Comment by PaulX1029** [comment]
![image](https://user-images.githubusercontent.com/77143808/168971944-0160e626-4524-4926-8c58-e0d75a93d0e8.png)
直接删除input_shape_dict后再进行转换的网络输入好像也不太对

> 这个的原因是因为指定的input_shape_dict中的shape不符合模型的要求。 你可以直接删除input_shape_dict后再进行转换
