### ISSUE TITLE
paddle2onnx如何保存onnx.graph.initializer

### ISSUE THREAD

**Issue by BelongAl** [PaddlePaddle/Paddle2ONNX#741]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
我这边有一个需求，需要从onnx.graph.initializer中获取超参数；但是我使用paddle2onnx获取的onnx文件这个参数都为空
```
import onnx
model = onnx.load("./32_onnx_saved.onnx")
print(model.graph.initializer)
```

**更多信息 :**

**报错截图**
![image](https://user-images.githubusercontent.com/49713362/169004354-b4850665-4a5e-4880-b438-b98455f13532.png)

**其他信息**

**Comment by jiangjiajun** [comment]
因为没有initliazer， paddle2onnx在转换时，将所有的权重转成了constant节点

**Comment by huajunyong123** [comment]
那如果希望修改constant为initializer请问有方法嘛

**Comment by jiangjiajun** [comment]
使用onnxsimplifier将模型处理后，会将模型中的constant转成initializer
