### ISSUE TITLE
使用PaddleX中的ResNet50_vd_ssld模型进行图像分类，转换模型出现下列的报错

### ISSUE THREAD

**Issue by leigangblog** [PaddlePaddle/Paddle2ONNX#742]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
使用PaddleX中的ResNet50_vd_ssld模型进行图像分类，出现下列的报错
Due to the operator: pool2d, this model cannot be exported to ONNX.

**更多信息 :**
 - 用于部署的推理引擎:OpenVINO
 - 为什么需要转换为ONNX格式：想转化到openvino模型，然后进行部署
 - Paddle2ONNX版本:0.9.6
 - 你的联系方式(Email/Wechat/Phone):2839953196@qq.com

**报错截图**
![image](https://user-images.githubusercontent.com/63993442/169030397-3bd05f17-21c3-441f-b404-2c88843c1afd.png)

**Comment by jiangjiajun** [comment]
@leigangblog 能提供一下你导出来的paddle模型吗？

**Comment by leigangblog** [comment]
已经解决了，加上了 --fixed_input_shape=[224,224]
```
paddlex --export_inference --model_dir=./output/resnet50/best_model/ --save_dir=./ --fixed_input_shape=[224,224]
```

**Comment by jiangjiajun** [comment]
我不确定这种报错是否是必须的，如果方便的话，麻烦提供下模型给我进行debug @leigangblog

**Comment by leigangblog** [comment]
这是对应的/output/resnet50/best_model/

**Comment by leigangblog** [comment]
发你邮箱啦！

**Comment by jiangjiajun** [comment]
谢谢你的反馈，其实这个模型，不用固定shape也是可以支持导出的。 我已经提PR修复，会随下周0.9.7的版本发布
