### ISSUE TITLE
相同模型算法训练出来的模型转为onnx后输出的shape维度以及数据格式不一致问题

### ISSUE THREAD

**Issue by pythondever** [PaddlePaddle/Paddle2ONNX#747]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
我使用paddleSeg fcn_hrnet18 训练出来的模型,训练后转onnx模型, 第一次的模型预测输出的shape是 （c， h， w） 形式，里面的数据格式都是 0 或者 1，但是后来我隔了一段时间再用相同的训练代码，只是不同的训练图像去训练，转onnx输出的shape是 （c， n， h， w），而且输出的数据格式不再是0和1，而是一堆浮点数, 请问这个是什么原因导致的，我尝试了更换onnx的版本但是还是一样的问题

**更多信息 :**
 - 用于部署的推理引擎:onnxruntime-gpu==1.11.0, onnx=1.9.0
 - 为什么需要转换为ONNX格式：速度更快环境部署更简单
 - Paddle2ONNX版本:0.9.5
 - 你的联系方式(Email/Wechat/Phone):228826582@qq.com

**报错截图**
第一次训练的模型转onnx后运行输出
![image](https://user-images.githubusercontent.com/24561457/169678692-f2dce0a1-db74-4fbd-bf27-56ae9043d8b5.png)
第二次训练的模型转onnx后运行输出
![image](https://user-images.githubusercontent.com/24561457/169678879-feb9605b-abb6-4b34-b239-963408986469.png)
第二次输出的数据
![image](https://user-images.githubusercontent.com/24561457/169678755-ae304c32-5448-4f49-adf6-1d1fe16b9065.png)

**其他信息**

**Comment by jiangjiajun** [comment]
鉴于第一次是正确的，这个问题我猜测跟Paddle2ONNX无关。  建议检查下训练代码

**Comment by pythondever** [comment]
是的,我发现了问题所在原因是我运行export.py时，第二次的导出使用了soft_max参数
