### ISSUE TITLE
使用paddledetection 训练faster_rcnn_r50_fpn_2x  转ONNX报错，提示Exception: ONNX model is not valid

### ISSUE THREAD

**Issue by memoryrobber** [PaddlePaddle/Paddle2ONNX#749]
使用paddledetection 训练faster_rcnn_r50_fpn_2x  转ONNX报错，提示Exception: ONNX model is not valid，是有不支持的OP吗

C:\PaddleDetection\inference_model>paddle2onnx --model_dir haidaipianyi --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx  --enable_dev_version False --opset_version 16
c:\program files\python39\lib\site-packages\onnx\mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:107
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:108
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:109
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:110
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:116
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:116
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:117
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:117
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:120
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:118
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:123
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:121
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:126
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:127
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:128
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:129
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:72
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:73
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\distribute_fpn_proposals.py:38
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\distribute_fpn_proposals.py:39
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py:336: UserWarning: c:\program files\python39\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\distribute_fpn_proposals.py:40
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  warnings.warn(
c:\program files\python39\lib\site-packages\onnx\helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  is_iterable = isinstance(value, collections.Iterable)
2022-05-23 20:36:45 [WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.
2022-05-23 20:36:48 [INFO]      ONNX model generated is valid.
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\paddle2onnx\utils.py", line 43, in check_model
    onnx.checker.check_model(onnx_model)
  File "c:\program files\python39\lib\site-packages\onnx\checker.py", line 104, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'S' of node:
name: NonMaxSuppression_5 OpType: NonMaxSuppression
 is not output of any previous nodes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\paddle2onnx\command.py", line 273, in main
    program2onnx(
  File "c:\program files\python39\lib\site-packages\paddle2onnx\command.py", line 200, in program2onnx
    p2o.program2onnx(
  File "c:\program files\python39\lib\site-packages\paddle2onnx\convert.py", line 95, in program2onnx
    return export_onnx(
  File "c:\program files\python39\lib\site-packages\paddle2onnx\convert.py", line 40, in export_onnx
    onnx_proto = onnx_graph.export_proto(enable_onnx_checker, output_names)
  File "c:\program files\python39\lib\site-packages\paddle2onnx\graph\onnx_graph.py", line 313, in export_proto
    check_model(onnx_proto)
  File "c:\program files\python39\lib\site-packages\paddle2onnx\utils.py", line 45, in check_model
    raise Exception('ONNX model is not valid.')
Exception: ONNX model is not valid.

**Comment by jiangjiajun** [comment]
将你的onnx版本升级至最新试下 
`pip install onnx --upgrade`

**Comment by memoryrobber** [comment]
已经是最新的版本了
![image](https://user-images.githubusercontent.com/21274112/169842179-bee5a748-7e2b-4aee-b94b-a057ed86d2e4.png)

**Comment by jiangjiajun** [comment]
是指升级onnx，而非paddle2onnx

**Comment by memoryrobber** [comment]
确实使用的都是最新版本，并且更换了一台设备之后报同样的错误
![image](https://user-images.githubusercontent.com/21274112/169866156-758d30e5-a2a0-4895-9746-b5b8c2264db4.png)

**Comment by yeliang2258** [comment]
您好，为了快速解决这个问题，麻烦将要转换的Paddle模型上传到网盘，然后给我一个链接吧，谢谢

**Comment by yeliang2258** [comment]
另外请问你转到ONNX的原因是？用什么推理引擎部署呢？

**Comment by memoryrobber** [comment]
> 您好，为了快速解决这个问题，麻烦将要转换的Paddle模型上传到网盘，然后给我一个链接吧，谢谢


模型在这里，希望能够移植到xbox上，使用onnxruntime directML部署
链接：https://pan.baidu.com/s/158Xvm9xkdBAyL0OgVwtUZg
提取码：wzq5
--来自百度网盘超级会员V5的分享

**Comment by yeliang2258** [comment]
你好，请使用这个PR进行测试：https://github.com/PaddlePaddle/Paddle2ONNX/pull/756

**Comment by memoryrobber** [comment]
> 你好，请使用这个PR进行测试：#756

太好了，问题解决了，辛苦
