### ISSUE TITLE
opencv调用转换的onnx文件出错

### ISSUE THREAD

**Issue by pdlzx2018** [PaddlePaddle/Paddle2ONNX#762]
E:\>python test.py
[ERROR:0@0.653] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(Clip_0) from domain='ai.onnx'
Traceback (most recent call last):
  File "E:\test.py", line 23, in <module>
    net = cv2.dnn.readNetFromONNX("e:\\model.onnx")  # 加载训练好的识别模型
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
> Node [Clip@ai.onnx]:(Clip_0) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1613: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20211220::ONNXImporter::parseClip(class cv::dnn::dnn4_v20211220::LayerParams &,const class opencv_onnx::NodeProto &)'
> >  (expected: 'node_proto.input_size() == 1'), where
> >     'node_proto.input_size()' is 3
> > must be equal to
> >     '1' is 1
>

**其他信息**

**Comment by pdlzx2018** [comment]
该怎么办啊，大佬。。。

**Comment by jiangjiajun** [comment]
看起来是opencv对于clip这个OP的要求，限制他的输入只能是1个。 而在你的onnx模型中clip的输入是3个（即input, min和max）。

这个问题的原因是
onnx在opset低于11的时候，clip确实只有input这一个输入，而min和Max是这个op的属性。 但在opset到11的时候，onnx将min和max也变成了输入。

所以当前你可以试下，将opset_version设为10再进行转出

**Comment by pdlzx2018** [comment]
> 看起来是opencv对于clip这个OP的要求，限制他的输入只能是1个。 而在你的onnx模型中clip的输入是3个（即input, min和max）。
> 
> 这个问题的原因是
> onnx在opset低于11的时候，clip确实只有input这一个输入，而min和Max是这个op的属性。 但在opset到11的时候，onnx将min和max也变成了输入。
> 
> 所以当前你可以试下，将opset_version设为10再进行转出

![IMG_20220603_164553.jpg](https://user-images.githubusercontent.com/42494064/171821060-e28500a1-90cc-48e1-b919-b9487bb5bf48.jpg)

然后就变成这个问题了，我不会改。。。能指导下解决流程不。

![IMG_20220603_165748.jpg](https://user-images.githubusercontent.com/42494064/171823018-e4e93790-86fb-4e7a-b1c7-955aa6105ef6.jpg)

**Comment by yeliang2258** [comment]
你可以使用ONNXRuntime验证ONNX模型是否可以正常推理，如果可以正常推理，说明模型是没有问题的，那么您可以去OpenCV下提issue咨询一下。另外请问，为什么需要转出为ONNX用OpenCV推理呢？
