### ISSUE TITLE
GhostNet分类网络，四类和九类的onnx模型速查差别十倍

### ISSUE THREAD

**Issue by Gmgge** [PaddlePaddle/Paddle2ONNX#772]
你好，非常感谢你们的工作，我有一些疑问如下：

1.网络：使用paddle clas 的GhostNet网络，一个九类，一个是四类；
2.原生paddle推理，两个速度近似。
3.同样转换为onnx，则九类的耗时是四类的十倍之久。

我尝试进行onnxsim，但是还是存在差距，不过缩小到两倍，相关文件在该百度云链接
链接：https://pan.baidu.com/s/1178iwPcr0FP1YnplBMGiaQ?pwd=i52t 
提取码：i52t 
--来自百度网盘超级会员V5的分享

**Comment by jiangjiajun** [comment]
这个模型是你自己训练的吗，两个模型都已经收敛了吗？

**Comment by Gmgge** [comment]
是的，模型已经收敛，这个速度和是否收敛也具有如此之强的相关性嘛？
