### ISSUE TITLE
安装paddleonnx出错

### ISSUE THREAD

**Issue by fan-min-97** [PaddlePaddle/Paddle2ONNX#785]
执行!python paddle2onnx/setup.py install

显示：
CMake Error at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.16 or higher is required.  You are running version 3.12.2

**Comment by yeliang2258** [comment]
执行python setup_dev.py install安装，如果还是以上错误，需要升级cmake版本

**Comment by yeliang2258** [comment]
另外今天paddle2onnx发布了新版本，可以使用pip install paddle2onnx直接安装最新版本

**Comment by fan-min-97** [comment]
> 



> 执行python setup_dev.py install安装，如果还是以上错误，需要升级cmake版本

非常感谢您的回复。执行python setup_dev.py install 还是一样的错误。我有尝试升级cmake，但是执行sudo命令，需要aistudio的password，我查了一下，飞浆不提供这个权限哈

**Comment by yeliang2258** [comment]
安装操作可以参考这个文档：https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md
你也可以直接使用pip install paddle2onnx安装最新版本
