### ISSUE TITLE
ppyolo模型转化为onnx后infer_shapes失败

### ISSUE THREAD

**Issue by coffezhou** [PaddlePaddle/Paddle2ONNX#810]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
ppyolo_mbv3_large_coco模型转化为onnx后infer_shapes失败，报如下错误：
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)

同时，使用TVM加载转化后onnx模型，也无法通过，报如下错误：
Check failed: *axis_ptr == 1 (-1 vs. 1) : cannot squeeze axis with dimension not equal to 1

但是，使用onnx的check_model对模型进行验证，一切正常。
所以不知道上述问题是什么原因造成的，还是说转化过程需要什么特别操作。
[转化步骤参考了EXPORT_ONNX_MODEL.md中的步骤。](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.4/deploy/EXPORT_ONNX_MODEL.md)
其余模型如ppyolov2_r50vd_dcn_365e_coco同样存在这个问题。
环境：
OS：ubuntu 18.04
paddle2onnx：0.9.8/1.0.0rc
onnx：1.11/1.12

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by jiangjiajun** [comment]
在使用tvm时，有设定输入的shape吗

**Comment by coffezhou** [comment]
> 

多谢提醒，使用tvm时，之前只设置了image的shape，把im_shape和scale_factor的shape也设定，tvm可加载模型了。但onnx的infer_shape依旧报错，可能也是同样的原因吧。

**Comment by jiangjiajun** [comment]
```
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"
```
可以试下这个命令来进行infer_shape， 推导shape时将shape包括Image和scale_facotr固定一下看看

**Comment by coffezhou** [comment]
> ```
> python -m paddle2onnx.optimize --input_model model.onnx \
>                                --output_model new_model.onnx \
>                                --input_shape_dict "{'x':[1,3,224,224]}"
> ```
> 
> 可以试下这个命令来进行infer_shape， 推导shape时将shape包括Image和scale_facotr固定一下看看

感谢，相关问题已解决。
