### ISSUE TITLE
paddle2onnx转PaddleClas以图搜图主体检测模型onnx中出现"Constant"这个额外输入怎么处理

### ISSUE THREAD

**Issue by lovegit2021** [PaddlePaddle/Paddle2ONNX#812]
我使用paddle2onnx转以图搜图的PaddleClas主体检测模型ppyolov2_r50vd_dcn_mainbody_v1.0_infer时候出现onnx中有一个“Constant”的空白输入，要怎么处理掉啊

**Comment by jiangjiajun** [comment]
有什么影响吗？
