### ISSUE TITLE
onnx转paddle时报错Exception: convert failed node:onnx__Shape_2099, op_type is Conv

### ISSUE THREAD

**Issue by yangshurong** [PaddlePaddle/Paddle2ONNX#815]
onnx转paddle时报错Exception: convert failed node:onnx__Shape_2099, op_type is Conv

**Comment by jiangjiajun** [comment]
onnx转paddle的issue，麻烦在X2Paddle项目下提 https://github.com/PaddlePaddle/X2Paddle
