### ISSUE TITLE
Paddleocr中的方向训练模型转化onnx模型报错

### ISSUE THREAD

**Issue by JackieXuu** [PaddlePaddle/Paddle2ONNX#823]
用PaddleOCR训了一个方向训练器，使用paddle2onnx部署后用起来报错
```
2022-07-26 14:39:11.503010670 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running Add node. Name:'Add_30' Status Message: /onnxruntime_src/onnxruntime/core
/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, pt
rdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension oth$
r than 1. 3 by 4

    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_30' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:505 void onnxruntime::BroadcastIterator::Append(ptrdiff_t, ptrdiff_t) axis == 1 || axis == largest was false. Attempting to broadcast anaxis by a dimension other than 1. 3 by **4**
```

**Comment by yeliang2258** [comment]
麻烦提供一下Paddle的部署模型，我这边来看看是什么问题。

**Comment by JackieXuu** [comment]
> 麻烦提供一下Paddle的部署模型，我这边来看看是什么问题。

@yeliang2258 

https://drive.google.com/file/d/1v1chngk2NZbB05T9F7HyugcVuCqx9WOf/view?usp=sharing

paddle模型和onnx模型，以及convert命令都在里面

**Comment by yeliang2258** [comment]
好的，收到

**Comment by yeliang2258** [comment]
你好，这个地方虽然后面两维是-1和-1，但是并不是所有的输入大小都可以的，你可以尝试一下最后两维度为320或640，比如1 * 3 * 320 * 320，1 * 3 * 640 * 640

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/PaddleOCR/issues/3694

**Comment by JackieXuu** [comment]
> 你好，这个地方虽然后面两维是-1和-1，但是并不是所有的输入大小都可以的，你可以尝试一下最后两维度为320或640，比如1 * 3 * 320 * 320，1 * 3 * 640 * 640

这样是可以的，但类似的det和rec都能转成-1，-1，因为input图片并不是正方形这样的，会对后续的inference造成影响。

**Comment by yeliang2258** [comment]
不一定要正方形的，主要是里面可能是下采样的原因，导致如果H和W不满足一定的条件则concat会报错而已，如果输入不规则，可以padding一下，比如输入1 * 3 * 320 * 640也是可以的

**Comment by JackieXuu** [comment]
> 不一定要正方形的，主要是里面可能是下采样的原因，导致如果H和W不满足一定的条件则concat会报错而已，如果输入不规则，可以padding一下，比如输入1 * 3 * 320 * 640也是可以的

好的，谢谢！
