### ISSUE TITLE
paddle2onnx环境移植问题

### ISSUE THREAD

**Issue by LLsmile** [PaddlePaddle/Paddle2ONNX#837]
我将本地win10下的python环境拷贝到另一台win10上后，paddleocr可以正常使用，包括训练、推理，但是paddle2onnx无法直接使用，网上查了一圈，说原因是paddle2onnx安装的是绝对路径，其他包是相对路径，然后我拷贝到和本机一样的目录下后，的确可以正常运行。但是我想问一下有没有其他的解决方式，有没有用相对路径安装paddle2onnx的方式？

**Comment by LLsmile** [comment]
具体操作步骤：
电脑A操作：
1. 从python官网下载python，然后安装python。
2. 安装paddlepaddle，安装paddleocr依赖
3. 安装pyyaml，paddle2onnx，onnxruntime


电脑B操作：
1. 将电脑A上的python环境拷贝到电脑B；
2. 配置电脑B的python环境；
3. 运行paddleocr训练、测试程序，一切正常；
5. 运行paddle2onnx，报错，Fatal error in launcher: Unable to create process using .... ?????????????????????
6. 将电脑B上的python环境拷贝到和电脑A一样的目录中，一切正常。

**Comment by jiangjiajun** [comment]
你是怎么运行paddle2onnx的

**Comment by LLsmile** [comment]
dos中输入命令: paddle2onnx --help，然后就挂了

**Comment by jiangjiajun** [comment]
直接移过去后，试下不要直接使用`paddle2onnx`这个命令，而是用`python -m paddle2onnx.command`来替代这个命令，例如

```
python -m paddle2onnx.command --help
```
