### ISSUE TITLE
转换后的onnx模型被openvion识别时提示错误

### ISSUE THREAD

**Issue by danve-fan** [PaddlePaddle/Paddle2ONNX#838]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
转换后的onnx模型被openvion2022识别时提示错误：
non_zero.cpp:43 NonZero layer with name 'NonZero_0' has incorrect number of output edges: 2

转换成onnx时启用了检查，提示：ONNX model generated is valid.
说明转换是成功的！

请问是怎么回事？

**Comment by yeliang2258** [comment]
您好，可以使用ONNXRuntime验证模型是否转换成功，如果只是openvino加载报错的话，可以去openvino的repo下提issue

**Comment by danve-fan** [comment]
转换成onnx时启用了检查，提示：ONNX model generated is valid.


> 您好，可以使用ONNXRuntime验证模型是否转换成功，如果只是openvino加载报错的话，可以去openvino的repo下提issue

**Comment by yeliang2258** [comment]
那应该ONNX模型没有问题，有可能是openvino对ONNX模型的支持有问题，建议去openvino的repo下提issue
