### ISSUE TITLE
zsh: command not found: paddle2caffe

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/Paddle2ONNX#841]
$ paddle2caffe --model_dir ./inference/sign2 \
             --model_filename ./inference/sign2/inference.pdmodel \
             --params_filename ./inference/sign2/inference.pdiparams \
             --save_file ./inference/sign2_caffe \
             --enable_caffe_custom False
zsh: command not found: paddle2caffe

paddle2caffe命令无法运行。

**Comment by jiangjiajun** [comment]
@wstchhwp 拉一下这PR https://github.com/PaddlePaddle/Paddle2ONNX/pull/843 进入Contrib后执行python setup.py install即可
