### ISSUE TITLE
离线静态量化后，转为onnx，onnx大小与非量化大小相当

### ISSUE THREAD

**Issue by maximli** [PaddlePaddle/Paddle2ONNX#846]
离线静态量化后，转为onnx，onnx大小与非量化大小相当，理论上是不是应该比非量化的onnx要小？

量化后的参数文件和模型文件比非量化时要小很多，转为onnx后，onnx模型大小与非量化前的onnx大小差不多，还要大一点点，请问是什么原因造成的，谢谢！

**Comment by jiangjiajun** [comment]
@yeliang2258

**Comment by yeliang2258** [comment]
因为我们的量化模型的权重还是以FP32来存储，只是我们在模型中新增了一个量化的OP，因此你看到的量化的ONNX模型和FP32的ONNX模型大小差不多
