### ISSUE TITLE
smkoe 模型转换 onnx失败

### ISSUE THREAD

**Issue by mikasazgx** [PaddlePaddle/Paddle2ONNX#848]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
smoke 模型转换，group_norm 不支持

**更多信息 :**
 - 用于部署的推理引擎:  
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:   0.9.8
 - 你的联系方式(Email/Wechat/Phone):  820801454@qq.com

**报错截图**
![Screenshot from 2022-08-12 15-19-27](https://user-images.githubusercontent.com/26949230/184304637-173162db-865b-43cc-9313-dcbb7927514a.png)

**其他信息**

**Comment by jiangjiajun** [comment]
看起来缺少一个OP，方便的话麻烦附一下你的模型

**Comment by mikasazgx** [comment]
感谢答复
我采用的模型是panddle 3d vision 官方提供的模型
链接如下：
https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/3d_vision/SMOKE

报错的算子应该是group_norm, 具体实现如下
![Screenshot from 2022-08-16 13-23-53](https://user-images.githubusercontent.com/26949230/184803970-7897057e-9612-4b48-b9a5-fd79ef1b13dc.png)

**Comment by yeliang2258** [comment]
另外，请问你导出到ONNX后是使用什么推理引擎部署呢？

**Comment by mikasazgx** [comment]
准备用TensorRT

已经支持了吗?谢谢
paddle2onnx我之前直接pip安装的，我需要卸载掉老版本，直接重新pip install 就可以了吗

**Comment by yeliang2258** [comment]
下周会发新的版本，发版本之后可以使用pip重装
