### ISSUE TITLE
转化出来的onnx结构不是官方通用的，一些算子有没有什么办法解决

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/Paddle2ONNX#849]
转化出来的结构推断好像不是官方通用的输出，如resize算子转化出来不是官方通用的，这个有没有什么办法解决嘛？
![image](https://user-images.githubusercontent.com/58769772/184322691-37f6bb89-4f67-4c3d-ad09-01c3046246fa.png)

再使用onnxsim优化其结构时出现了一些卷积操作推断不出来，这个是不是哪里存在问题，能帮我解答一下疑惑嘛。
![image](https://user-images.githubusercontent.com/58769772/184323083-6c52e458-2489-41db-b88b-a547dfb145d2.png)
我是用于模型推理部署

**Comment by jiangjiajun** [comment]
不是官方通用的是指？

**Comment by chen-del** [comment]
就是onnx通用的resize形式,不是变种的那种形式。或者是自定义的resize11,resize10等等，而且最后使用onnxsim进行优化时，结构推断好像有点问题没有推断出来。

**Comment by chen-del** [comment]
@jiangjiajun

**Comment by chen-del** [comment]
![image](https://user-images.githubusercontent.com/58769772/184500746-5725d356-7e23-4d51-940a-e9edc54b9d46.png)
![1660404621008](https://user-images.githubusercontent.com/58769772/184500759-109a5fea-667a-4dd8-a79f-f124fefc267a.png)
就是类似于这种而不是下面哪一种
![image](https://user-images.githubusercontent.com/58769772/184500813-c14fdeb0-faf5-45b7-bdcc-6ef002bb51c3.png)

roi有8个 ，有用普通resize形式替换的方法吗

**Comment by jiangjiajun** [comment]
你上面的列的那种“官方通用的”模型，含resize的，能发一下吗，我看看

**Comment by chen-del** [comment]
可以，就是普通的上采样结构
![image](https://user-images.githubusercontent.com/58769772/184566176-ca6c5de0-9470-419f-8318-8a723f511aca.png)
模型我邮件发吧

**Comment by jiangjiajun** [comment]
Hi, @chen-del  我已经提了PR修改了resize的导出方式，这里我附上了一个转出来的模型，能帮忙看下是否符合你现在的使用方式了吗？

代码应该会随下个版本进行发版，当前如若你需要使用，可以参考这个PR，拉相应的分支，按照这个文档编译后使用 [Paddle2ONNX编译安装](https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md)
[bilinear_interp_v2_11.onnx.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/9386617/bilinear_interp_v2_11.onnx.zip)

**Comment by chen-del** [comment]
@jiangjiajun 对的Resize就是采用这种align_corners属性，看起来似乎对上了那个结构,具体情况有没有问题我可能需要验证一下。

**Comment by jiangjiajun** [comment]
好的，等你的反馈哈

**Comment by chen-del** [comment]
@jiangjiajun  似乎编译很难通过，出现了报错
/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  SetuptoolsDeprecationWarning,
running install
/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
writing paddle2onnx.egg-info/PKG-INFO
writing dependency_links to paddle2onnx.egg-info/dependency_links.txt
writing entry points to paddle2onnx.egg-info/entry_points.txt
writing requirements to paddle2onnx.egg-info/requires.txt
writing top-level names to paddle2onnx.egg-info/top_level.txt
reading manifest file 'paddle2onnx.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'paddle2onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running create_version
running cmake_build
-- Found PythonInterp: /home/dell/anaconda3/envs/padclass/bin/python (found version "3.6.13") 
Generated: /home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/.setuptools-cmake-build/third/onnx/onnx/onnx_paddle2onnx-ml.proto
Generated: /home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/.setuptools-cmake-build/third/onnx/onnx/onnx-operators_paddle2onnx-ml.proto
Generated: /home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/.setuptools-cmake-build/third/onnx/onnx/onnx-data_paddle2onnx.proto
-- 
-- ******** Summary ********
--   CMake version             : 3.22.5
--   CMake command             : /home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/cmake/data/bin/cmake
--   System                    : Linux
--   C++ compiler              : /usr/bin/c++
--   C++ compiler version      : 7.5.0
--   CXX flags                 :  -Wnon-virtual-dtor
--   Build type                : Release
--   Compile definitions       : MAX_ONNX_OPSET_VERSION=16;PADDLE2ONNX_LIB;ONNX_NAMESPACE=paddle2onnx;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH         : 
--   CMAKE_INSTALL_PREFIX      : /usr/local
--   CMAKE_MODULE_PATH         : 
-- 
--   ONNX version              : 1.11.0
--   ONNX NAMESPACE            : paddle2onnx
--   ONNX_USE_LITE_PROTO       : OFF
--   USE_PROTOBUF_SHARED_LIBS  : OFF
--   Protobuf_USE_STATIC_LIBS  : ON
--   ONNX_DISABLE_EXCEPTIONS   : OFF
--   ONNX_WERROR               : OFF
--   ONNX_BUILD_TESTS          : OFF
--   ONNX_BUILD_BENCHMARKS     : OFF
--   ONNXIFI_DUMMY_BACKEND     : OFF
--   ONNXIFI_ENABLE_EXT        : OFF
-- 
--   Protobuf compiler         : /usr/bin/protoc
--   Protobuf includes         : /usr/include
--   Protobuf libraries        : /usr/lib/x86_64-linux-gnu/libprotobuf.a;-lpthread
--   BUILD_ONNX_PYTHON         : OFF
-- Found pybind11: /home/dell/anaconda3/envs/padclass/include (found version "2.10.0")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/.setuptools-cmake-build
Consolidate compiler generated dependencies of target p2o_paddle_proto
Consolidate compiler generated dependencies of target onnxifi_dummy
Consolidate compiler generated dependencies of target onnxifi_loader
[  1%] Built target onnxifi_dummy
[  2%] Built target p2o_paddle_proto
[  2%] Built target onnxifi_loader
[  3%] Built target gen_onnx_proto
[  4%] Built target gen_onnx_operators_proto
[  4%] Built target gen_onnx_data_proto
Consolidate compiler generated dependencies of target onnxifi_wrapper
[  5%] Built target onnxifi_wrapper
Consolidate compiler generated dependencies of target onnx_proto
[  9%] Built target onnx_proto
Consolidate compiler generated dependencies of target onnx
[  9%] Building CXX object third/onnx/CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o
/home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/third/onnx/onnx/defs/sequence/defs.cc: In function ‘bool paddle2onnx::BuildSequenceMapBodyFunc(const paddle2onnx::FunctionBodyBuildContext&, const paddle2onnx::OpSchema&, paddle2onnx::FunctionProto&)’:
/home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/third/onnx/onnx/defs/sequence/defs.cc:809:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<paddle2onnx::ValueInfoProto>’ and ‘int’)
         seq_at_node.add_output(g_inputs[inputIndex].name());
                                        ^
/home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/third/onnx/onnx/defs/sequence/defs.cc:817:37: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<paddle2onnx::ValueInfoProto>’ and ‘int’)
         identity.add_output(g_inputs[inputIndex].name());
                                     ^
/home/dell/bag-torch/darkpull/Paddle/PaddleUtils/Paddle2ONNX/third/onnx/onnx/defs/sequence/defs.cc:877:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<paddle2onnx::ValueInfoProto>’ and ‘int’)
     int64_t dtype = g_outputs[outputIndex].type().tensor_type().elem_type();
                              ^
third/onnx/CMakeFiles/onnx.dir/build.make:523: recipe for target 'third/onnx/CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o' failed
make[2]: *** [third/onnx/CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o] Error 1
CMakeFiles/Makefile2:310: recipe for target 'third/onnx/CMakeFiles/onnx.dir/all' failed
make[1]: *** [third/onnx/CMakeFiles/onnx.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 320, in <module>
    entry_points={'console_scripts': ['paddle2onnx=paddle2onnx.command:main']})
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.run_command('cmake_build')
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 198, in run
    subprocess.check_call(build_args)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/dell/anaconda3/envs/padclass/bin/cmake', '--build', '.', '--', '-j', '40']' returned non-zero exit status 2.

**Comment by jiangjiajun** [comment]
确认下你本地的protobuf版本是不是过低，如若是，按照文档重新编译安装protobuf

**Comment by chen-del** [comment]
@jiangjiajun 似乎不是这个原因 ，因为我的buaffe版本大于3.16了

**Comment by jiangjiajun** [comment]
你的系统，python版本提供一下，我替你编译一个吧

**Comment by chen-del** [comment]
Python3.6.13



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月12日(周五) 晚上8:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle2ONNX] 转化出来的onnx结构不是官方通用的，一些算子有没有什么办法解决 (Issue #849)




 
不是官方通用的是指？

**Comment by chen-del** [comment]
使用的系统版本是ubantu18.04 python使用的3.6.13 @jiangjiajun

**Comment by jiangjiajun** [comment]
@chen-del 试下安装最新paddle2onnx 1.0.0rc4看下

**Comment by chen-del** [comment]
@jiangjiajun 还是源码构建嘛，有没有方法直接使用pip install 拉取

**Comment by jiangjiajun** [comment]
python -m pip install paddle2onnx==1.0.0rc4 -i https://pypi.org/simple

**Comment by chen-del** [comment]
嗯好的，谢谢

**Comment by chen-del** [comment]
@jiangjiajun 经过测试发现，resize op好像没有问题了，好像他的属性没有变化还是half_pixel  虽然结构是正确的了，有没有办法将half_pixel改成 align_corner，是需要在代码中进行调整嘛
![image](https://user-images.githubusercontent.com/58769772/186833526-5cb440b3-a6bd-473e-8819-21248849fab8.png)

**Comment by jiangjiajun** [comment]
half_pixel和align_corner对应的计算结果不同的哦

https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/mapper/nn/interpolate.cc#L68 可以看下这里的逻辑，会根据实际的模型，修改这个属性

**Comment by chen-del** [comment]
@jiangjiajun 这个好像是根据实际模型修改属性的，但是如果使用这个属性开发板half_pixel是不支持的，得换成align_corner。

**Comment by jiangjiajun** [comment]
嗯。 这里在组网模型调用inteploate这个api时，将align_corners设为True，导出的模型即为align_corners
