### ISSUE TITLE
Due to the operator: pool2d, this model cannot be exported to ONNX.

### ISSUE THREAD

**Issue by ouyangpingbu** [PaddlePaddle/Paddle2ONNX#852]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式： 
 - Paddle2ONNX版本:'1.0.0rc3
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

[ERROR][Paddle2ONNX][pool2d: pool2d_9.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.
[ERROR][Paddle2ONNX][pool2d: pool2d_10.tmp_0] Adaptive only support static input shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX.
[ERROR] Model exporting failed, you can report this problem to https://github.com/PaddlePaddle/Paddle2ONNX.git.
Aborted (core dumped)

**其他信息**

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/issues/813  参考这个issue回复
