### ISSUE TITLE
Oops, there are some operators not supported yet, including temporal_shift

### ISSUE THREAD

**Issue by alice929** [PaddlePaddle/Paddle2ONNX#853]
我想转换ppTSM_fight中的模型为onnx,在转换的过程中遇到Oops, there are some operators not supported yet, including temporal_shift,似乎是不支持temporal_shift，请问该如何进行修改

**Comment by yeliang2258** [comment]
请问你的Paddle2ONNX版本是？

**Comment by alice929** [comment]
paddle2onnx      0.9.8   谢谢

**Comment by yeliang2258** [comment]
python -m pip install paddle2onnx==1.0.0rc3再转换试试

**Comment by alice929** [comment]
好的，谢谢

**Comment by aureosun** [comment]
@alice929 请问问题解决了没
