### ISSUE TITLE
Deepfm 模型转换报错

### ISSUE THREAD

**Issue by RyanRong** [PaddlePaddle/Paddle2ONNX#862]
执行命令：paddle2onnx --model_dir output_model_all_deepfm/0/ --model_filename rec.pdopt --params_filename rec.pdparams --save_file model.onnx --enable_dev_version True

输出如下msg：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: output_model_all_deepfm/0/rec.pdopt
[Paddle2ONNX] Paramters file path: output_model_all_deepfm/0/rec.pdparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Failed to parse paddlepaddle model from read content.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.
2022-08-18 17:22:54 [INFO]      ===============Make PaddlePaddle Better!================
2022-08-18 17:22:54 [INFO]      A little survey: https://iwenjuan.baidu.com/?code=r8hu2s

**Comment by jiangjiajun** [comment]
你需要先将Paddle模型导出成部署模型，再使用Paddle2ONNX转换。 这里你传入的文件是训练过程中保存的check point

**Comment by yuehui49** [comment]
paddle2onnx 
--model_dir models
--model_filename pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml 
--params_filename PP-LiteSeg\model.pdparams  
--opset_version 11  
--save_file modelinfer/model.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: model_1\pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml
[Paddle2ONNX] Paramters file path: model_1\PP-LiteSeg\model.pdparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Failed to parse paddlepaddle model from read content.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.
请问模型转化失败是语法原因吗？还是其他
