### ISSUE TITLE
有没一种设置让导出时不带argmax

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/Paddle2ONNX#866]
有没有一种方法是去掉argmax输出的，然后直接输出reshape op 例如1,3,192,192这种形式

**Comment by jiangjiajun** [comment]
你可以按自己的需求载剪Paddle模型或ONNX模型。 这里有提供Paddle/ONNX模型裁剪工具 https://github.com/jiangjiajun/PaddleUtils

**Comment by chen-del** [comment]
嗯好的，谢谢可以了

**Comment by jiangjiajun** [comment]
@chen-del  也帮忙验证下这个issue https://github.com/PaddlePaddle/Paddle2ONNX/issues/849

另外当前你转出ONNX是想用于什么场景或硬件，什么推理引擎部署啊
