### ISSUE TITLE
转换HumanSeg到onnx后，输出不正确

### ISSUE THREAD

**Issue by enduringstack** [PaddlePaddle/Paddle2ONNX#871]
版本信息：
paddle2onnx          1.0.0rc4

root@kep_common_server:~/project/seg_task# python3
Python 3.6.13 (default, Jun 10 2021, 13:15:56) 

转换HumanSeg模型后，理论上输出是1 2 192 192，但是输出是1 2 -1 -1

**Comment by jiangjiajun** [comment]
你是指最终转出的模型，他的最后输出结点shape不是[1, 2, 192, 192]么， paddle2onnx在转换时，最终的shape是由原paddle模型获取而来，即原paddle模型的输出也是[1, 2, -1, -1]，所以onnx模型也是[1, 2, -1, -1]

你可以参考README使用如下命令，重新计算onnx模型的各个节点shape
<img width="764" alt="image" src="https://user-images.githubusercontent.com/19339784/186154530-80e24d92-673c-4cac-a64d-a8aa9c2b0706.png">
