### ISSUE TITLE
onnx ocr 推理怎么显示多个备选结果？微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [PaddlePaddle/Paddle2ONNX#884]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

onnx ocr 推理怎么显示多个备选结果？微信nlanguage
**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
您好，你可以咨询一下PaddleOCR具体后处理细节，ONNX模型可以和TensorRT或者ONNXRuntime配合做推理，但是具体的后处理需要咨询PaddleOCR

**Comment by nissansz** [comment]
没有得到想要的代码。不知道怎么写
