### ISSUE TITLE
缺少算子grid_sampler和linspace

### ISSUE THREAD

**Issue by geoyee** [PaddlePaddle/Paddle2ONNX#888]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
缺少算子支持：`grid_sampler`和`linspace`

**更多信息 :**
 - Paddle版本：2.3.1
 - Paddle2ONNX版本：0.9.8
 - 操作系统：Win 10

**报错截图**
```
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: *\model.pdmodel
[Paddle2ONNX] Paramters file path: *\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including grid_sampler,linspace,
[ERROR] Due to the unsupported operators, the conversion is aborted.
```

**Comment by yeliang2258** [comment]
请安装1.0.0rc4

**Comment by yeliang2258** [comment]
您好，麻烦提供一下模型，我这边来看看。另外请问一下你的模型是什么使用场景，转换到ONNX之后用什么推理引擎进行部署呢？

**Comment by geoyee** [comment]
> 您好，麻烦提供一下模型，我这边来看看。另外请问一下你的模型是什么使用场景，转换到ONNX之后用什么推理引擎进行部署呢？

场景是想在QGIS中使用ONNX推理，因为在Linux下QGIS使用Paddle会有问题，是用ONNX Runtime。代码功能就类似于这样：
``` python
# 创建一个水平和竖直方向都是-1到1的格网
h, w = img.shape[:2]
h_grid = paddle.linspace(-1.0, 1.0, h).reshape([-1, 1]).tile([w])
w_grid = paddle.linspace(-1.0, 1.0, w).reshape([-1, 1]).tile([h]).transpose((1, 0))
grid = paddle.concat([w_grid.unsqueeze(2), h_grid.unsqueeze(2)], axis=2)[None]
# 对网格进行扰动
grid += paddle.randn((1, h, w, 2), dtype="float32")
# 以网格来扭曲图像进行上采样
half_img = cv2.resize(img, None, None, 0.5, 0.5, cv2.INTER_LINEAR)
new_img = F.grid_sample(to_tensor(half_img), grid)
```

**Comment by yeliang2258** [comment]
您好，麻烦安装最新的1.0.0版本，然后再尝试转换

**Comment by yeliang2258** [comment]
另外，请问一下Linux下QGIS使用Paddle会有问题，请问具体是什么问题啊？

**Comment by geoyee** [comment]
> 您好，麻烦安装最新的1.0.0版本，然后再尝试转换

好滴我试试

**Comment by geoyee** [comment]
> 另外，请问一下Linux下QGIS使用Paddle会有问题，请问具体是什么问题啊？

[https://github.com/PaddlePaddle/Paddle/issues/38268](https://github.com/PaddlePaddle/Paddle/issues/38268)

**Comment by geoyee** [comment]
能够成功导出了，但加载失败。
onnx相关版本：
```
onnx                              1.12.0
onnxruntime                       1.12.1
onnxruntime-gpu                   1.12.1
```
使用
```
predictor = onnxruntime.InferenceSession(
    model_file,
    providers=["CUDAExecutionProvider"]
)
```
报错
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from */model.onnx failed:Node (p2o.Div.19) Op (Div) [ShapeInferenceError] Incompatible dimensions
```

**Comment by yeliang2258** [comment]
麻烦提供一下paddle模型，我看看是什么问题

**Comment by yeliang2258** [comment]
另外你可以尝试一下更新paddle到2.3.2，看看你上面说的问题是否还存在

**Comment by geoyee** [comment]
> 麻烦提供一下paddle模型，我看看是什么问题

不好意思模型暂时不方便上传，不过我检查了一下，发现问题主要在其他地方，那两个算子应该是OK了的，也是更新到了2.3.2试的：
1. `loc = loc[::-1]`这种操作会使形状出问题导致后面的Div算子那个错误，因为loc只是[x, y]，所以用`paddle.flip(loc, axis=0)`代替了
2. 修复上面的问题后又遇到Tile算子报错，发现是`h_grid = h_grid.tile([w])`需要写成`h_grid = h_grid.tile([1, w])`，即需要保持`tile()`中`repeat_times`的长度和执行`tile()`的张量的形状的长度`h_grid.shape`相等

一些写法看来只能在Paddle中没问题，最后模型的结果与paddle的还是有一定差距，不过看起来也还能用。感谢大佬的帮助~我这边没有问题了，需要我关闭这个issue吗 😄

**Comment by yeliang2258** [comment]
好的，问题解决了可以关闭的
