### ISSUE TITLE
Paddle2ONNX：BiseNet转换问题

### ISSUE THREAD

**Issue by zxc14751475** [PaddlePaddle/Paddle2ONNX#890]
PaddleSeg版本：PaddleSeg 2.6     PaddlePaddle版本：PaddlePaddle 2.1.0    操作系统信息：Linux
    Python版本号：Python3.6   CUDA/cuDNN版本：CUDA10.2   Paddle2ONNX版本:0.9.8
    onnxruntime
    其他内容:
    ！使用paddlaseg里bisenetv2训练的模型，paddle2onnx转onnx模型成功了，
paddleseg中的predict.py能正常检测，但用onnxruntime推理没有结果，
（我用同样的流程尝试了DeepLabV3P，onnxruntime能正常出结果），
请问我需要检查哪里来解决这个问题，是因为Bisenet不支持转换吗

**Comment by yeliang2258** [comment]
你好，可以先只对模型的推理做检查，相同的一个随机数据输入，如果paddle模型和onnx模型的输出结果误差小于1e-5则认为ONNX模型准换无误，那么就需要再检查一下送入模型的前后处理是否对齐。

如果检查到模型转换有精度误差的话，麻烦提供一下Paddle的模型，我这边来看看是什么问题。

**Comment by yeliang2258** [comment]
另外请问转到ONNX模型是想用什么推理框架进行部署呢？

**Comment by zxc14751475** [comment]
好的，感谢回复。 我想尝试用paddle训练模型，通过onnx最终部署到Ti中，推理框架使用tidl
