### ISSUE TITLE
pyramidbox_lite_mobile_mask模型导出为ONNX协议失败

### ISSUE THREAD

**Issue by StrongandSurvive** [PaddlePaddle/Paddle2ONNX#891]
**问题描述**
版本、环境信息
1）版本：paddlehub 2.2.0，paddlepaddle-gpu 2.2.2， paddle2onnx  0.9.8
2）系统环境：Windows10，python 3.7.13
模型：
pyramidbox_lite_mobile_mask==1.3.0
pyramidbox_lite_mobile==1.2.0
问题：
已通过save_inference_model将模型从paddleHub导出，尝试使用paddle2onnx将两个模型导出为onnx协议，其中pyramidbox_lite_mobile模型导出成功，但是pyramidbox_lite_mobile_mask导出失败。
命令：
`paddle2onnx --model_dir mask_detector --model_filename __model__ --params_filename __params__  --save_file mask_cls.onnx --enable_onnx_checker True`
报错：
`Exception: Error happened when mapping node ['scale_0'] to onnx, which op_type is 'scale' with inputs: {'X': ['batch_norm_0.tmp_2']} a
nd outputs: {'Out': ['scale_0.tmp_0']}, specific error: object of type 'NoneType' has no len()`

*全部报错信息：*
Traceback (most recent call last):
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 132, in mapping
    mapper_func(graph, node, **kw)
  File "..\pplearn\lib\site-packages\paddle2onnx\legacy\op_mapper\math.py", line 987, in opset_7
    if len(node.input('ScaleTensor')) == 0 and np.fabs(
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\pplearn\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\pplearn\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\pplearn\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "...\pplearn\lib\site-packages\paddle2onnx\command.py", line 224, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "...\pplearn\lib\site-packages\paddle2onnx\command.py", line 148, in program2onnx
    auto_update_opset)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\command.py", line 210, in program2onnx
    output_names=output_names)
  File "...\pplearn\lib\site-packages\paddle2onnx\convert.py", line 80, in program2onnx
    operator_export_type, auto_update_opset, **configs)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\convert.py", line 102, in program2onnx
    output_names=output_names)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\convert.py", line 37, in export_onnx
    auto_update_opset)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 331, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\graph\onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "...\pplearn\lib\site-packages\paddle2onnx\legacy\op_mapper\op_mapper.py", line 137, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['scale_0'] to onnx, which op_type is 'scale' with inputs: {'X': ['batch_norm_0.tmp_2']} a
nd outputs: {'Out': ['scale_0.tmp_0']}, specific error: object of type 'NoneType' has no len()

请问问题是出在模型导出还是模型转化阶段呢？该如何解决？谢谢！

转换为onnx格式的原因：开发需要，统一协议框架；

联系方式：lucky_sorceress@163.com

**Comment by yeliang2258** [comment]
麻烦升级paddle2onnx到1.0.0版本再试一下导出，如果还是转换失败，请提供一下Paddle模型，我这边来看看具体原因。

**Comment by StrongandSurvive** [comment]
> 麻烦升级paddle2onnx到1.0.0版本再试一下导出，如果还是转换失败，请提供一下Paddle模型，我这边来看看具体原因。

您好！这边按您的建议升级到了paddle2onnx-1.0.0，重新尝试命令：`paddle2onnx --model_dir mask_detector --model_filename __model__ --params_filenam
e __params__  --save_file mask_cls.onnx --enable_onnx_checker True`
报错信息发生变化，但仍不能顺利完成转换，报错信息如下:
`[Paddle2ONNX] Start to parse PaddlePaddle model...`
`[Paddle2ONNX] Model file path: mask_detector\__model__`
`[Paddle2ONNX] Paramters file path: mask_detector\__params__`
`[Paddle2ONNX] Start to parsing Paddle model...`
`[ERROR] Cannot found attribute padding_algorithm in op: conv2d`
模型文件请到网盘提取：
链接：https://pan.baidu.com/s/1o-yt4rc0H9zkPMQB1wpqrA 
提取码：0elx
非常感谢！！

**Comment by yeliang2258** [comment]
Paddle2ONNX支持Paddle2.0版本之后导出的模型，你这个模型应该是老版本的Paddle导出的，可以升级一下paddle再导出paddle模型吗？

**Comment by StrongandSurvive** [comment]
> Paddle2ONNX支持Paddle2.0版本之后导出的模型，你这个模型应该是老版本的Paddle导出的，可以升级一下paddle再导出paddle模型吗？

您好，我再次确认了一下，我是在paddlepaddle-gpu 2.2.2，paddlehub  2.2.0的环境下
![env](https://user-images.githubusercontent.com/79584290/188605064-ab0e0aa4-18d8-4976-8e78-d86f3548402d.jpg)导出的模型。
具体操作如下：
`hub install pyramidbox_lite_mobile_mask==1.3.0`
`hub install pyramidbox_lite_mobile==1.2.0`

`import paddlehub as hub`
`module = hub.Module(name="pyramidbox_lite_mobile_mask")`
`module.processor.save_inference_model(dirname="program")`
得到如下文件，然后发给您的。
![models](https://user-images.githubusercontent.com/79584290/188605452-20aecc57-0923-4434-901f-bce75275d13e.jpg)

我对出现上述问题也感到非常奇怪，导出的模型参考[教程](https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/python/mixed/mask_detection/mask_detect.py)也可以正常运行，只是在转换onnx协议时出现问题，o(╥﹏╥)o

**Comment by rainyfly** [comment]
你好，这个模型在hub中是paddle v1.6时期导出来的预训练模型，目前看起来导入这个预训练模型是没问题，但是使用paddle2onnx导出可能不太行了，你要不试试能不能直接去PaddleDetection中找到这个模型的全新版本

**Comment by StrongandSurvive** [comment]
> 你好，这个模型在hub中是paddle v1.6时期导出来的预训练模型，目前看起来导入这个预训练模型是没问题，但是使用paddle2onnx导出可能不太行了，你要不试试能不能直接去PaddleDetection中找到这个模型的全新版本

您好！我认真翻阅了PaddleDetection项目，但是并没有发现这个模型或者说类似功能的模型，您方便的话请给一个链接；此外，难道paddle2onnx只支持paddle2.0以上的模型转换为onnx协议吗？
