### ISSUE TITLE
转换成onnx模型后使用gpu推理速度比cpu还慢

### ISSUE THREAD

**Issue by MgArcher** [PaddlePaddle/Paddle2ONNX#893]
系统环境/System Environment：
onnxruntime-gpu==1.9.0
在使用onnxruntime-gpu进行推理时发现一张图片耗时在3s以上，继续传入相同图片耗时下降到0.5s。更换图片传入耗时又在3s左右,模型是动态模型，为什么不同图片推理速度会变慢？

**Comment by yeliang2258** [comment]
您好，onnxruntime的速度问题，建议直接到onnxruntime的repo下提issue哦

**Comment by xxdm** [comment]
你好， 你这边问题解决了吗
