### ISSUE TITLE
转换时提示unique op不支持

### ISSUE THREAD

**Issue by littletomatodonkey** [PaddlePaddle/Paddle2ONNX#897]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**

拉了develop的paddle2onnx代码编译，导出模型的时候提示unique op不支持，但是看pr记录，是已经支持了来着：https://github.com/PaddlePaddle/Paddle2ONNX/pull/523/files

转换代码如下

```bash
paddle2onnx --model_dir=./model_with_unique/ \
    --model_filename=inference.pdmodel \
    --params_filename=inference.pdiparams \
    --save_file=./model_with_unique/model_unique.onnx \
    --opset_version=13 \
    --enable_onnx_checker=True
```

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

<img width="721" alt="image" src="https://user-images.githubusercontent.com/14270174/190068408-8b1ea3a1-1d2e-4d1e-828f-166112529942.png">

**其他信息**

**Comment by jiangjiajun** [comment]
@littletomatodonkey 你看到的那个是去年提的PR，彼时所有代码是纯Python开发。 在去年年底Paddle2ONNX重构，全部改为C++开发（之前的Python代码已经移到了legacy目录），所以会有少数几个OP可能Python中存在，但C++中暂时没有。


当前可以在转换时，指定参数`--enable_dev_version False`来使用老的代码转换（但可能会存在转换失败风险，目前仅维护最新版本代码）。这个OP我们也会尽快在C++版本中增加

**Comment by littletomatodonkey** [comment]
好的，指定上述flag之后，可以转换成功了~多谢

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/903
