### ISSUE TITLE
使用paddle2onnx转换paddle1.x模型

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle2ONNX#899]
您好，我使用paddle2onnx1.0.0对paddle1.8下环境训练的模型进行转换出现以下错误：
![image](https://user-images.githubusercontent.com/101849755/190304816-54b124a3-8cd5-4e0a-9c40-0429b84847f6.png)
我使用的指令是这样的：
paddle2onnx --model_dir output/det/model/ --model_filename best_accuracy.pdmodel --params_filename best_accuracy.pdparams --save_file output/det/onnx/ocr.onnx --opset_version 9 --enable_onnx_checker True

**Comment by yeliang2258** [comment]
你这个模型是一个训练模型，可以先导出为inference的模型

**Comment by fanxiaochen456** [comment]
您好，我使用的是paddleocr1.1的程序，它存储下来的训练模型是pdmodel,pdopt和pdparams，然后使用转换脚本转为推理模型是
![图片](https://user-images.githubusercontent.com/101849755/190316044-439cd581-1a32-4e5e-90cc-c53f5aadc7ef.png)
这样子的，我使用这样的进行模型转换还是会出现那样子的错误信息。
