### ISSUE TITLE
你们提供的onnx load进来为空，自己导出的也一样

### ISSUE THREAD

**Issue by marsbzp** [PaddlePaddle/Paddle2ONNX#902]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/model_zoo/ocr

![image](https://user-images.githubusercontent.com/20138766/190543711-29ee3c1f-9cf9-44c2-8c47-ff3a79b8f1fe.png)

希望尽快回复

**Comment by yeliang2258** [comment]
我们所有的权重都转换成为constant，存在了node中，initializer里面没有存数据

**Comment by yeliang2258** [comment]
你使用过程中遇到什么问题了吗？

**Comment by marsbzp** [comment]
> 你使用过程中遇到什么问题了吗？

我在用onnx转寒武纪模型里面需要用到x.graph.initializer，我可以怎么等价使用
