### ISSUE TITLE
PaddleX训练的PicoDet模型转ONNX提示少OP

### ISSUE THREAD

**Issue by panp4n** [PaddlePaddle/Paddle2ONNX#914]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
PaddleX训练的PicoDet模型转ONNX提示少OP。

导出模型指令：paddlex --export_inference --model_dir=D:\workspace\projects\P0012\T0016\output\epoch_140 --save_dir=E:\model\onnx --fixed_input_shape=[640,640]。

转换指令已设置--enable_dev_version 为False。
另外paddleX 训练的MaskRCNN模型也报缺少OP的错。

**更多信息 :**
 -PaddleX版本：2.1.0
 -onnx版本：1.12.0
 - 用于部署的推理引擎:Openvino
 - 为什么需要转换为ONNX格式：需要转成IR格式
 - Paddle2ONNX版本:1.0
 - 你的联系方式(Email/Wechat/Phone):928583088@qq.com

**报错截图**
PicoDet：
![image](https://user-images.githubusercontent.com/40445051/192486973-42d16d92-944f-4aa9-a6c5-982241170a8e.png)

MaskRCNN：
![image](https://user-images.githubusercontent.com/40445051/192487351-b0ca269b-eb74-4ed2-a3e1-597fcd9f2169.png)

**其他信息**

**Comment by yeliang2258** [comment]
您好，PaddleX中的picodet应该是包括了控制流，导致无法导出成ONNX，可以去PaddleDetection下找原版的picodet来导出
