### ISSUE TITLE
human_pp_humansegv2_lite_192x192_inference_model_with_softmax导出onnx出错

### ISSUE THREAD

**Issue by zeckireck** [PaddlePaddle/Paddle2ONNX#917]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version:
 - Email/Wechat/Phone:

**Screenshots**
![image](https://user-images.githubusercontent.com/81000191/192922148-29f30783-90ce-4d4e-aefa-cde95cb03d93.png)

**Additional context**

**Comment by yeliang2258** [comment]
You can use the following script to convert your model to static shape model first and then use paddle2onnx to convert to onnx: https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle#2-%E4%BF%AE%E6%94%B9paddle%E6%A8%A1%E5%9E%8B%E8%BE%93%E5%85%A5shape
