### ISSUE TITLE
有while语句的模型，如何转ONNX？

### ISSUE THREAD

**Issue by hitbuyi** [PaddlePaddle/Paddle2ONNX#922]
能否提供一点思路？ 通过下面的方法可行？
1） 用PADDLESLIM修改模型
2） 在python语言层级修改模型
3）自定义插件

如果提供一点例子就好了

**Comment by jiangjiajun** [comment]
支持有while的转换

**Comment by hitbuyi** [comment]
> 支持有while的转换

 我转SMOKE的时候，就是卡在不支持while这个语句上啊

**Comment by jiangjiajun** [comment]
怎么提示

**Comment by hitbuyi** [comment]
> 怎么提示

见#907, 按提示，就是模型中含用控制流语句，导致不能导出

**Comment by jiangjiajun** [comment]
那个是有if导致，现在还没支持if语句

**Comment by hitbuyi** [comment]
> 那个是有if导致，现在还没支持if语句

if语句，提示的却是while?

**Comment by jiangjiajun** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/19339784/196443238-e44b7aa2-ea30-4f5d-8244-a4e645ebd21b.png">
你可以看下是否能去掉代码中的if，也就是上面标红的两个OP， while应该有方式解决

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
