### ISSUE TITLE
目前不支持swin模型的转换吗

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle2ONNX#925]
[Paddle2ONNX] Oops, there are some operators not supported yet, including roll,uniform_random

请问什么时候会支持呢

**Comment by yeliang2258** [comment]
你好，转化的时候可以设置--enable_dev_version False，然后再试试

**Comment by yeliang2258** [comment]
另外，请问你转到onnx之后用什么推理引擎进行部署呢？
