### ISSUE TITLE
动态形状不应该用 -1 表示

### ISSUE THREAD

**Issue by daquexian** [PaddlePaddle/Paddle2ONNX#928]
用 -1 表示动态形状是很早之前 ONNX 没有原生支持动态形状时不得已的一种做法，不是被 ONNX Spec 认可的。现在 ONNX 已经原生支持了动态形状，且用 -1 表示动态形状会导致 ppyolo 在 onnxruntime 中报错：

> onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Transpose, node name: p2o.Transpose.1): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (-300) vs (-1)

**Comment by jiangjiajun** [comment]
@daquexian 是建议用`batch_size`这种字符串来表示动态维度是么？

**Comment by clancylian** [comment]
不用-1表示的话，onnx在转tensorrt出现问题怎么处理呢？

**Comment by daquexian** [comment]
> 不用-1表示的话，onnx在转tensorrt出现问题怎么处理呢？

除了过去的 paddle2onnx 之外没有其他工具把动态形状用 -1 表示，onnx 转 trt 更没有这样的要求😂 可以看看是不是其他原因
