### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/******params/__model__'

### ISSUE THREAD

**Issue by geniusSDNexplorer** [PaddlePaddle/Paddle2ONNX#93]
-----------  Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: /home/work/luqiankun/tools_for_renfeng/qt_batchlist_31w_bak/params/
fluid_model_name:
fluid_params_name:
image_path:
name_prefix:
onnx_model: ERNIE2.0
return_variable: False
to_print_model: False
------------------------------------------------
Traceback (most recent call last):
  File "/ssd1/share/python36/bin/paddle2onnx", line 11, in <module>
    load_entry_point('paddle2onnx==0.1', 'console_scripts', 'paddle2onnx')()
  File "/ssd1/share/python36/lib/python3.6/site-packages/paddle2onnx-0.1-py3.6.egg/fluid_onnx/fluid_to_onnx.py", line 230, in main
  File "/ssd1/share/python36/lib/python3.6/site-packages/paddle2onnx-0.1-py3.6.egg/fluid_onnx/fluid_to_onnx.py", line 99, in convert
  File "/ssd1/share/python36/lib/python3.6/site-packages/paddle/fluid/io.py", line 1199, in load_inference_model
    with open(model_filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/work/******/params/__model__'

运行代码报错 __model__文件是什么？我再paddle里下的ernie模型里也没有这个文件呀

**Comment by guoshengCS** [comment]
__model__是网络配置文件，这个应该是因为放出的ernie模型里只保存了参数值，需要的话可以使用ernie再load下保存的模型然后用save_inference_model重新save下就有这个文件里，不过网络配置不一定能通过ONNX转换。

**Comment by wawltor** [comment]
> ## ----------- Configuration Arguments -----------
> check_task: image_classification
> debug: False
> fluid_model: /home/work/luqiankun/tools_for_renfeng/qt_batchlist_31w_bak/params/
> fluid_model_name:
> fluid_params_name:
> image_path:
> name_prefix:
> onnx_model: ERNIE2.0
> return_variable: False
> to_print_model: False
> Traceback (most recent call last):
> File "/ssd1/share/python36/bin/paddle2onnx", line 11, in
> load_entry_point('paddle2onnx==0.1', 'console_scripts', 'paddle2onnx')()
> File "/ssd1/share/python36/lib/python3.6/site-packages/paddle2onnx-0.1-py3.6.egg/fluid_onnx/fluid_to_onnx.py", line 230, in main
> File "/ssd1/share/python36/lib/python3.6/site-packages/paddle2onnx-0.1-py3.6.egg/fluid_onnx/fluid_to_onnx.py", line 99, in convert
> File "/ssd1/share/python36/lib/python3.6/site-packages/paddle/fluid/io.py", line 1199, in load_inference_model
> with open(model_filename, "rb") as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/work/******/params/**model**'
> 
> 运行代码报错 __model__文件是什么？我再paddle里下的ernie模型里也没有这个文件呀

目前paddle2onnx目前还不支持NLP相关的模型，具体支持模型可以参照文档

**Comment by shoegazerstella** [comment]
I am having the same problem.
I am trying to convert a [DeepSpeech2 model](https://github.com/PaddlePaddle/DeepSpeech) to onnx.
What's in my model dir:
```
mean_std.npz  params.pdparams  vocab.txt
```
The command i am using:

```
paddle2onnx --fluid_model ds2model/  --onnx_model deepspeech2_onnx --fluid_params_name params.pdparams
```
The error:
```
-----------  Configuration Arguments -----------
check_task: image_classification
debug: False
fluid_model: ds2model/
fluid_model_name: 
fluid_params_name: params.pdparams
image_path: 
name_prefix: 
onnx_model: deepspeech2_onnx
return_variable: False
to_print_model: False
------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/usr/local/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 99, in convert
    ] = fluid.io.load_inference_model(args.fluid_model, exe)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/io.py", line 1360, in load_inference_model
    with open(model_filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ds2model/__model__'
```

Any idea on how can I save a DS2 model using paddlepaddle `save_inference_model` ?

**Comment by ghost** [comment]
@shoegazerstella Any luck? I am also working on the same.
