### ISSUE TITLE
Paddle2onnx hardsigmoid  参数错误。

### ISSUE THREAD

**Issue by xiguadong** [PaddlePaddle/Paddle2ONNX#930]
### bug描述 Describe the Bug

onnx的[Hardsigmoid](https://github.com/onnx/onnx/blob/main/docs/Operators.md#HardSigmoid)公式为 y = max(0, min(1, alpha * x + beta))，其中默认值 **alpha = 0.2, beta = 0.5**. Paddle2Onnx在进行转换时，应该使用了该默认值，在推理时精度掉点，望知悉。
![image](https://user-images.githubusercontent.com/55774832/196848876-55a9ccb3-aec7-4a2a-b6ae-ca491a349849.png)

**Comment by zhangbo9674** [comment]
感谢您的反馈，我们会尽快评估及修复该问题！

**Comment by jiangjiajun** [comment]
@xiguadong  Hi, 你用的是Paddle2ONNX版本，以及导出的命令能发一下吗

**Comment by xiguadong** [comment]
> @xiguadong Hi, 你用的是Paddle2ONNX版本，以及导出的命令能发一下吗

# Paddle2onnx 版本
```bash
paddle2onnx -v
2022-10-23 07:01:08 [INFO]      paddle2onnx-1.0.1 with python>=3.6, paddlepaddle>=2.0.0
```
# 快速复现
可以使用PaddleOCR项目，安装好环境后，在下面链接处下载预训练模型 https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/algorithm_rec_crnn.md#1-%E7%AE%97%E6%B3%95%E7%AE%80%E4%BB%8B 
(rec_mv3_none_bilstm_ctc.yml 对应的链接)

然后执行下列命令
```
# 1. 导出pdmodel
python3 tools/export_model.py -c configs/rec/rec_mv3_none_bilstm_ctc.yml -o Global.pretrained_model=./pre_train/best_accuracy  Global.save_inference_dir=./inference/rec_crnn
# 2. 导出onnx
paddle2onnx --model_dir ./inference/rec_crnn --model_filename inference.pdmodel  --params_filename inference.pdiparams --save_file ./inference/rec_rcnn.onnx --opset_version 11  --enable_onnx_checker True
```

**Comment by jiangjiajun** [comment]
@xiguadong Hi， 这个模型中有多个hard_sigmoid，我查看了每一个hardsigmoid，并没看到有slope为0.16的节点。 另外在Paddle2ONNX导出ONNX时，也并没有使用默认值，而是根据slope的值来转换的，以下是我导出的Paddle模型，麻烦检查看下哈
[inference_crcnn.pdmodel.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/9848392/inference_crcnn.pdmodel.zip)

**Comment by xiguadong** [comment]
抱歉，检查了之后应该是我模型弄混了，谢谢。
