### ISSUE TITLE
Input shape detection in combination with PaddleSeg

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/Paddle2ONNX#937]
When exporting PaddleSeg models to ONNX I have to provide --input_shape manually to PaddleSeg's export.py. In combination with the fact that widthxheight or rowsxcolumns might be given and most of the time the value is only hinted at in filenames, this means I have to go through the whole chain of exporting models, converting to ONNX and trying to apply the ONNX at least twice to be sure I get the correct results.

It would be great if that would be detected automatically. I do not know if PaddleSeg's export.py or Paddle2ONNX is the best place to do that. PaddleSeg referred me to you: https://github.com/PaddlePaddle/PaddleSeg/issues/2660

**Comment by jiangjiajun** [comment]
Hi, @ukoehler  There's no need to export a fixed shape again. 

If you have a paddleseg model already, you can modify it's shape manually. 

We provided tools here: https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle

```
python paddle_infer_shape.py --model_dir ch_PP-OCRv2_det_infer/ \
                             --model_filename inference.pdmodel \
                             --params_filename inference.pdiparams \
                             --save_dir new_model \
                             --input_shape_dict="{'x':[1,3,640,640]}"
```

The `x` is the input tensor's name

**Comment by ukoehler** [comment]
Hi @jiangjiajun ,

thanks for the answer. That would add another step in the conversion and I still would have to guess the input shape. Also, since I only convert and not design the models, I would somehow have to get the name of the input tensor.

**Comment by jiangjiajun** [comment]
Use `netron` to visualize the model, it will visualize all the nodes in your model

**Comment by ukoehler** [comment]
Thanks a lot. I have only used Netron for ONNX file so far. When opening a model.hdparams is it normal to only get a list of nodes without connections? The model.pdmodel file gives more info.

**Comment by jiangjiajun** [comment]
yes, model.pdmodel describle the structure information. pdiparams file strores all the weights

**Comment by ukoehler** [comment]
Still, is there no way to detect input shape automatically? From netron, I do not get those values (and have to export from model.hdparams first).

**Comment by jiangjiajun** [comment]
The shape is decided by yourself， it means size of image you will feed into the model. e.g set the input shape as[1，3，640， 1280] means the feeded image height 640， width 1280

**Comment by ukoehler** [comment]
Hi @jiangjiajun ,

in my case, most if not all models require a specific input image size. The problem starts with the input size not being documented in most cases and guessed from filenames. This also means that it is not clear if widthxheight or rowsxcolumns is meant.

Using paddle2onnx without explicitly providing the input size during PaddleSeg export will result in errors:

I follow instructions from the OpevCV GitHub. I have to provide it to export.py or I get an error in paddle2onnx.

```
paddle2onnx --model_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.onnx
```

will result in

```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg\PP-LiteSeg>paddle2onnx --model
_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.p
dmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_lites
eg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_
scale0.5_160k.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160
k\model.pdmodel
[Paddle2ONNX] Paramters file path: pp_liteseg_stdc1_cityscapes_1024x512_scale0.5
_160k\model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR][Paddle2ONNX] [pool2d: pool2d_4.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR][Paddle2ONNX] [pool2d: pool2d_5.tmp_0] Adaptive only support static input
 shape.
[Paddle2ONNX] Due to the operator: pool2d, this model cannot be exported to ONNX
.
[ERROR] Model exporting failed, you can report this problem to https://github.co
m/PaddlePaddle/Paddle2ONNX.git.
```

trying with input shape gives the same result

```
paddle2onnx --model_dir pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 --save_file pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k\pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.onnx --input_shape_dict="{'image':[1, 3, 1024, 512]}"
```

Since you always have to provide the input shape by hand to export.py I guess that should be shown in the example. Actually, since it is not easy to find out the input shape (is PP-LiteSeg really operating in portrait mode?), it would be good if auto-detection would work

**Comment by jiangjiajun** [comment]
@ukoehler After upgrade to version 1.0, Paddle2ONNX has deprecated the flag `--input_shape_dict`. This flag will modify the paddle model's shape,  this function is provided as a single script https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/paddle here
