### ISSUE TITLE
Attribute not found: allowzero

### ISSUE THREAD

**Issue by lyuwenyu** [PaddlePaddle/Paddle2ONNX#939]
请问用TRT跑导出的onnx报这个错  怎么解决
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/17582080/198966545-87cbb698-c1c7-4dec-81be-be4c6a6a1b9e.png">

**Comment by jiangjiajun** [comment]
转换出ONNX时，指定 --opset_version 14
