### ISSUE TITLE
Paddle2onnx支持DeepASRmodel吗

### ISSUE THREAD

**Issue by MornJ** [PaddlePaddle/Paddle2ONNX#94]
你好，Paddle2onnx支持DeepASRmodel吗？或者有没有什么方法可以进行这样的转换？

**Comment by wawltor** [comment]
> 你好，Paddle2onnx支持DeepASRmodel吗？或者有没有什么方法可以进行这样的转换？

paddle中有DeepASRmodel具体实现吗？ 我看模型库中没有该模型的实现，或者看看能不能提供一下模型网络结构，我们这边评估一下。

**Comment by MornJ** [comment]
> > 你好，Paddle2onnx支持DeepASRmodel吗？或者有没有什么方法可以进行这样的转换？
> 
> paddle中有DeepASRmodel具体实现吗？ 我看模型库中没有该模型的实现，或者看看能不能提供一下模型网络结构，我们这边评估一下。

https://github.com/PaddlePaddle/models/tree/release/1.6/PaddleSpeech/DeepASR 这里

**Comment by MornJ** [comment]
我尝试着dump出inference model之后在paddle2onnx中出现了这个错误：
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'lstmp_0.tmp_0' of node:
input: "lstmp_0.tmp_0" input: "lstmp_0.tmp_0@shape_tensor_0" output: "lstmp_0.tmp_0@reshape_0" op_type: "Reshape"
 is not output of any previous nodes.
您知道该如何解决吗

**Comment by cjt222** [comment]
这个是因为paddle2onnx不去支持lstm OP转换，之后会考虑去实现LSTM OP的转换
