### ISSUE TITLE
自定义输出节点名称

### ISSUE THREAD

**Issue by lxgyChen** [PaddlePaddle/Paddle2ONNX#947]
我记得某个版本是支持的，现在反而不支持了（至少不生效了），出于什么方面的考虑呢？？
自定义输入节点形状，--input_shape_dict, 从paddle2onnx移到了paddle.optimize. --output_names没了

**Comment by yeliang2258** [comment]
您好，请先转换模型到ONNX，然后再用这个工具来改名字：https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/onnx
