### ISSUE TITLE
转换yolov3报错的问题

### ISSUE THREAD

**Issue by spiritsky123** [PaddlePaddle/Paddle2ONNX#95]
使用paddlepaddle1.5版本，下载了model_zoo中的yolov3_darknet_voc，使用PaddlePaddle中PaddleDetection中的infer.py生成__model__和参数文件，再使用paddle2onnx进行转换，碰到了leaky_relu层的输入参数不匹配的问题，可能是什么原因？
![image](https://user-images.githubusercontent.com/57127805/67744414-65996e00-fa5c-11e9-8449-c103fe24aadc.png)

**Comment by spiritsky123** [comment]
“目前支持PaddleDetection中的YoloV3，我们提供了PaddleDetection中的yolov3_darknet_voc的下载地址，用户需要使用save_inference_model接口来保存模型和参数，并且yolov3中的multiclass_nms的normalized参数需手动设为True，否则最终结果会存在轻微的差异。“

是否能提供一个YoloV3进行转化的一个可行的示例？

**Comment by cjt222** [comment]
这个是PaddleDetection更新OP的参数导致的参数错误，您可以使用models的release1.5.1去save_inference_model，然后进行转换

**Comment by spiritsky123** [comment]
训练产生的模型也需要用models-1.5.1么？

**Comment by spiritsky123** [comment]
有没有可能把paddle2onnx升级支持新的models？
发现不同版本之间的兼容性现在问题很多

**Comment by cjt222** [comment]
之后会对支持的模型做一次重新整理，兼容最新的models

**Comment by spiritsky123** [comment]
那能不能理解当前的paddle2onnx只支持models1.5.1及以前的版本？

**Comment by spiritsky123** [comment]
@cjt222 我按照你的方法，用models1.5.1训练了个模型，用该版本的save_inference_model，结果还是一样，出错信息跟上面的一致。
我用的paddlepaddle是1.6.0的，python3.7的环境。

**Comment by cjt222** [comment]
之前的测试环境是paddlepaddle1.5，您可以试一下paddlepaddle1.5，看是不是可以

**Comment by spiritsky123** [comment]
@cjt222 paddlepaddle是1.5版本，还是1.5.x版本都可以的？好像1.5.2也不行，老问题。
还有，我看paddlepaddle1.6版本的发布说明，不是说paddle2onnx0.2，已经配套了么，难道没有测过？
