### ISSUE TITLE
paddleseg的rtformer转onnx时报错：Oops, there are some operators not supported yet, including max_pool2d_with_index

### ISSUE THREAD

**Issue by shituo123456** [PaddlePaddle/Paddle2ONNX#960]
**问题描述**
使用PaddleSeg的RTFormer训练，导出的paddle模型转onnx时报错

**更多信息 :**
 - 用于部署的推理引擎:gpu，rknn
 - 为什么需要转换为ONNX格式：需要在gpu及npu部署
 - Paddle2ONNX版本:1.0.0rc4
 - 你的联系方式(Email/Wechat/Phone):微信：ST_YangMu

**报错截图**
![741a1184315722cb3683a11cfb166b3](https://user-images.githubusercontent.com/64970397/202404523-9f656891-9908-4d1f-a3e4-eefa94dbd327.jpg)

**其他信息**

**Comment by yeliang2258** [comment]
麻烦提供一下你的Paddle模型吧，我下周高优支持一下

**Comment by shituo123456** [comment]
> 麻烦提供一下你的Paddle模型吧，我下周高优支持一下

怎么向您发模型呢？我用的就是官方的RTformer模型

**Comment by yeliang2258** [comment]
直接传到百度网盘，给我一个下载链接就行

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/964

**Comment by shituo123456** [comment]
> 直接传到百度网盘，给我一个下载链接就行
![ef818627543e3ad72198c846ad9f8ff](https://user-images.githubusercontent.com/64970397/202987363-84ec6728-b216-4085-99c9-1f086b6f9635.jpg)

链接：https://pan.baidu.com/s/1DN3mDezkXEEiCJxw2L1c9Q 
提取码：o8ya

**Comment by sunmooncode** [comment]
@yeliang2258 没出新版本的话，是需要通过源码编译才能用到这个是么？

**Comment by yeliang2258** [comment]
是的，需要源码编译一下Paddle2ONNX

**Comment by shituo123456** [comment]
> 是的，需要源码编译一下Paddle2ONNX

max_pool2d_with_index目前支持了吗？
还要编译paddle2onnx前需要将环境中旧版本卸载吗
