### ISSUE TITLE
[ERROR] Paddle2ONNX: Only support weight with lod_level = 0.

### ISSUE THREAD

**Issue by hi-zhangjie** [PaddlePaddle/Paddle2ONNX#963]
paddle2onnx --model_dir /XX/det_db \
            --model_filename best_accuracy.pdmodel \
            --params_filename best_accuracy.pdparams \
            --save_file /XX/dbnet.onnx \
            --enable_dev_version True \
            --opset_version 9
[Paddle2ONNX] Start to parsing Paddle model...
[ERROR] Paddle2ONNX: Only support weight with lod_level = 0.
Aborted (core dumped)

导出模型，遇到这种报错，请问有什么解决思路和建议吗

**Comment by jiangjiajun** [comment]
![Screenshot_2022-11-18-16-49-15-820-edit_com.github.android.jpg](https://user-images.githubusercontent.com/19339784/202660504-cc75a59f-25a2-467a-9c4f-e7ad3bfaee62.jpg)
