### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by xuefengA** [PaddlePaddle/Paddle2ONNX#965]
I have a question,Please give me some help,can I use the openvino to inference  .onnx model  by PaddleSlim quantify

**Comment by jiangjiajun** [comment]
> I have a question,Please give me some help,can I use the openvino to inference  .onnx model  by PaddleSlim quantify


PaddleSlim can be exported to ONNX， but only supported inference with ONNX Runtime  or TensorRT now, OpenVINO is not tested.

But we are cooperating with OpenVINO now, the PaddleSlim model will be supported soon.

**Comment by xuefengA** [comment]
thank's ,I will test it now
