### ISSUE TITLE
建议针对全新环境更新一下 requirements.txt 

### ISSUE THREAD

**Issue by Gsonovb** [PaddlePaddle/Paddle2ONNX#968]
你好

我是刚入门的新手，
虽然知道一点点内容， 但在全新环境测试时候，
提示找不到 CV2 ， Paddle ， numpy

我知道这些都是很常见库， 但问题是
他们的安装库名和 代码名称并不一致， 
比如 pip install CV2 ， 就会提示找不到
或者 PIP install Paddle  ，就会提示安装失败

**Comment by yeliang2258** [comment]
您好，现在Paddle2ONNX导出模型并不依赖其他第三方库，如果需要做更多验证才需要安装的

**Comment by Gsonovb** [comment]
@yeliang2258

这倒是没错，但主要是 示例代码需要这些 ，刚开始的时候确实有点头大。

PS，回头研究一下模型结构，看看用其他代码调用。
