### ISSUE TITLE
能支持多分支输出节点裁剪嘛例如像这样的输出

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/Paddle2ONNX#969]
![image](https://user-images.githubusercontent.com/58769772/203744839-deb7db15-a5ff-4bf3-8199-f1be284e9077.png)

**Comment by chen-del** [comment]
@jiangjiajun

**Comment by chen-del** [comment]
![image](https://user-images.githubusercontent.com/58769772/203745306-cd3fe404-becf-4625-a4be-b6c3788e0c09.png)

**Comment by chen-del** [comment]
三个分支的argmax都不要裁剪掉

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/tree/develop/tools/onnx
试一下这个工具
