### ISSUE TITLE
Trainer Api 裁剪量化后的模型用paddle2onnx转换成onnx测试指标全为0

### ISSUE THREAD

**Issue by NewToolAI** [PaddlePaddle/Paddle2ONNX#973]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**

Trainer Api 裁剪量化后的模型用paddle2onnx转换成onnx测试指标全为0

转换报错：

![d3186c1f2a9322a0418aa8f5ffbc710](https://user-images.githubusercontent.com/17463933/204224651-7699ccb6-9f5c-41b5-8d42-58eea58a1de3.jpg)

模型：Ernie-3.0-base，序列标注任务

paddle2onnx版本：1.0.3

模型结构和日志：

[model_log.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/10102564/model_log.zip)

 baseline f1: 0.9147

**Comment by LiuChiachi** [comment]
方便把裁剪量化后的模型发出来吗，我们来定位一下
