### ISSUE TITLE
Onnx的softmax算子支持的opset有1,11,13三个，但是转换代码中只有1和13两类

### ISSUE THREAD

**Issue by Real-Chen** [PaddlePaddle/Paddle2ONNX#983]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**
**问题描述**
请在此处详细的描述报错信息
onnx官方支持的softmax算子有3个版本(1，11，13)
https://github.com/onnx/onnx/blob/main/docs/Operators.md
![image](https://user-images.githubusercontent.com/19891206/205653549-ba13b215-93ac-4f14-8de8-ee6511bcdadc.png)
但是legacy\op_mapper\math.py中的softmax算子只有（1，13）两类。
https://github.com/PaddlePaddle/Paddle2ONNX/blob/d5f88459d00717c8584aae74fddb4251608d7c54/paddle2onnx/legacy/op_mapper/math.py#L1039

这就导致使用opset为11时，转换softmax层，必会在softmax层前后添加transpose算子，由于端侧设备对transpose算子支持不好，会导致性能损失严重

希望softmax能支持opset11的格式

**更多信息 :**
 - 用于部署的推理引擎:移动端设备
 - 为什么需要转换为ONNX格式：需要转onnx再转端侧加速芯片支持的文件
 - Paddle2ONNX版本:1.0.1
 - 你的联系方式(Email/Wechat/Phone):15700079221@163.com

**报错截图**
![image](https://user-images.githubusercontent.com/19891206/205655307-fd7150a3-01fc-4352-96cd-fc55913c34f9.png)

**其他信息**

**Comment by Real-Chen** [comment]
非常感谢！！
![482B455F](https://user-images.githubusercontent.com/19891206/205801148-2f13f196-1e2a-48bc-bb9f-308935c4f08d.jpg)

**Comment by Real-Chen** [comment]
@jiangjiajun 
不好意思，是我搞错了，opset-11版本的softmax算子，是计算指定轴（axis）往后所有轴的softmax
https://github.com/onnx/onnx/blob/main/docs/Changelog.md#softmax-11
![image](https://user-images.githubusercontent.com/19891206/205915417-afef8a08-8615-43df-bdce-4fc7b80d8bc0.png)
确实需要将axis指定的维度transpose到最后一维，再做softmax后，transpose回来。
13版本才转换为我们熟悉的softmax操作。
onnx之前版本对于softmax算子的定义太愚蠢了。
![4A3E037D](https://user-images.githubusercontent.com/19891206/205916255-603debfd-a3aa-42fb-84b5-a8bcca9cb476.gif)

**Comment by jiangjiajun** [comment]
好的，难怪我的PR ci没过
