### ISSUE TITLE
转stnet报错

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle2ONNX#99]
将stnet训练的模型，想转onnx，但是却报错了
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'conv3d_0.tmp_0' of node: 
input: "conv3d_0.tmp_0" input: "conv3d_0.tmp_1@reshape_y" output: "conv3d_0.tmp_1" op_type: "Add"
 is not output of any previous nodes.

环境：ubuntu 16.04
paddle版本： paddlepaddle-gpu       1.6.1.post107
onnx版本:       onnx                   1.5.0

**Comment by thunder95** [comment]
换成paddle1.5.1报同样的错

**Comment by cjt222** [comment]
stnet是视频分类模型，存在一些特定OP不支持转换，目前paddle2onnx目前还不支持视频分类模型

**Comment by amandazw** [comment]
paddleOCR项目里的模型，遇到
  File "D:/work/video/beauty_ocr_sdk/paddle2onnx-develop/paddle2onnx-develop/fluid_onnx/fluid_to_onnx.py", line 198, in convert
    checker.check_model(onnx_model)
  File "D:\setup\Anaconda3\envs\py361\lib\site-packages\onnx\checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'hard_swish_0.tmp_0' of node: 
input: "hard_swish_0.tmp_0" input: "conv2_expand_weights" output: "conv2d_1.tmp_0" op_type: "Conv" attribute { name: "dilations" ints: 1 ints: 1 type: INTS } attribute { name: "group" i: 1 type: INT } attribute { name: "kernel_shape" ints: 1 ints: 1 type: INTS } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "strides" ints: 1 ints: 1 type: INTS }
 is not output of any previous nodes.

paddle2onnx不支持paddleOCR的模型吗
