### ISSUE TITLE
Request for supporting softmax_with_cross_entropy

### ISSUE THREAD

**Issue by LemonNoel** [PaddlePaddle/Paddle2ONNX#991]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

For the latest v1.0.5, it fails to convert the `softmax_with_cross_entropy` op.

**Informations (please complete the following information):**
 - Inference engine for deployment: onnxruntime
 - Why convert to onnx：For deployment
 - Paddle2ONNX Version: 1.0.5 (I have also tested on 1.0.3, 1.0.2 and all of them do not work)

**Screenshots**
<img width="1227" alt="截屏2022-12-12 14 59 02" src="https://user-images.githubusercontent.com/25607475/207004841-5ab4c625-2255-4a68-a65d-a09179f6137a.png">

**Comment by Zheng-Bicheng** [comment]
This operator is already supported in the latest Paddle2ONNX. I will now close this issue.
