### ISSUE TITLE
PaddleOCR文字检测模型det_mv3_pse使用paddle2onnx转为onnx后速度下降

### ISSUE THREAD

**Issue by MianMianMeow** [PaddlePaddle/Paddle2ONNX#993]
**问题描述**
使用了PaddleOCR/configs/det/det_mv3_pse.yml和自己的数据集训练了一个文字检测模型
paddle的每张图推理速度约为：GPU 0.1s, CPU 0.4s
onnx的每张图推理速度约为：GPU 0.4s, CPU 1.6s

**其他信息**
版本： 
onnxruntime==1.11.0
paddle2onnx==1.0.5

转换命令
```
paddle2onnx --model_dir inference/det_mv3_pse \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file onnx_models/det_mv3_pse.onnx \
            --opset_version 11 \
            --enable_dev_version True \
            --enable_onnx_checker True \ 
```

onnx推理和速度计算
```
ort_sess = onnxruntime.InferenceSession("PaddleOCR/onnx_models/det_mv3_pse.onnx")
ort_inputs = {ort_sess.get_inputs()[0].name: x}
start = time.time()
ort_outs = ort_sess.run(None, ort_inputs)
time_used = time.time() - start
```

期待您的回复，谢谢啦。

**Comment by yeliang2258** [comment]
paddle测量时间的方式是？是否将输入输出的时间也统计进去了呢？

**Comment by MianMianMeow** [comment]
paddle是在tools/infer_det.py中的main()的88行处开始测量时间的，包括了前处理后和后处理的时间。上面的onnx测量没有包包括前处理和后处理，但依然比paddle慢。paddle和onnx都是测量了约800张图后算的平均时间

 start = time.time()
            with open(file, 'rb') as f:
                img = f.read()
                data = {'image': img}
            batch = transform(data, ops)
            images = np.expand_dims(batch[0], axis=0)
            shape_list = np.expand_dims(batch[1], axis=0)
            images = paddle.to_tensor(images)
            preds = model(images)
            post_result = post_process_class(preds, shape_list)
            time_used = time.time() - start # 结束时间
