### ISSUE TITLE
可以支持翻译领域 mbart模型吗

### ISSUE THREAD

**Issue by Amy234543** [PaddlePaddle/Paddle2ONNX#996]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
你好，可以试试哦
