### ISSUE TITLE
不支持softmax_with_cross_entropy

### ISSUE THREAD

**Issue by teensilenc** [PaddlePaddle/Paddle2ONNX#998]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息
使用paddleNLP训练的文本层次分类模型，转Onnx格式出现不支持的算子

**更多信息 :**
 - Paddle2ONNX版本: paddle2onnx-1.0.5

**报错截图**
![image](https://user-images.githubusercontent.com/120088435/209309836-82ac7b8d-f9ec-47c6-9dea-004fd6970553.png)

**其他信息**

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/997

**Comment by felixhjh** [comment]
> **请将下面信息填写完整，便于我们快速解决问题，谢谢！**
> 
> **问题描述** 请在此处详细的描述报错信息 使用paddleNLP训练的文本层次分类模型，转Onnx格式出现不支持的算子
> 
> **更多信息 :**
> 
> * Paddle2ONNX版本: paddle2onnx-1.0.5
> 
> **报错截图** ![image](https://user-images.githubusercontent.com/120088435/209309836-82ac7b8d-f9ec-47c6-9dea-004fd6970553.png)
> 
> **其他信息**



> #997

**Comment by felixhjh** [comment]
可以再尝试下softmax_with_cross_entropy是否可以转换成功，有问题可以再反馈

**Comment by yangsuo** [comment]
> 可以再尝试下softmax_with_cross_entropy是否可以转换成功，有问题可以再反馈

貌似还没推到paddle2onnx-1.0.5版本
