### ISSUE TITLE
bert_base_uncased 模型转onnx报错

### ISSUE THREAD

**Issue by chenqion** [PaddlePaddle/Paddle2ONNX#999]
想使用paddle2onnx讲bert_base_uncased模型转换为onnx,  报错信息为：
Exception: Error happened when mapping node ['fill_any_like_0'] to onnx, which op_type is 'fill_any_like' with inputs: {'X': ['input_ids']} and outputs: {'Out': ['full_like_0.tmp_0']}, specific error: array(1) has type numpy.ndarray, but expected one of: int

模型的链接为：https://paddlelite-demo.bj.bcebos.com/NNAdapter/models/PaddleNLP/bert_base_uncased.tgz
请问我需要怎样才能转换成功呢？

**Comment by jiangjiajun** [comment]
安装最新版本的Paddle2ONNX 1.0.5版本
